### ISSUE TITLE
React Dev Tools does not connect the device

### ISSUE THREAD

**Issue by RenanRicoldi** [facebook/flipper#1000]
## 🐛 Bug Report

I click the React DevTools and then the retry button several times, and always get this message.
![image](https://user-images.githubusercontent.com/53321448/78929629-22b2dc00-7a79-11ea-9d62-693f8a95671a.png)

## To Reproduce
Run the flipper app, run the app, click React DevTools

## Environment
React Native 0.62
Linux Mint Cinammon 19.3
Flipper version 0.36.0

**Comment by JohannesKlauss** [comment]
Same here on Android on macOS. Using Flipper 0.37.0 and RN 0.62.2

**Comment by EhsanSarshar** [comment]
same issue

**Comment by dayze** [comment]
Exactly the same on React Native 0.62 and flipper 0.36

**Comment by AndrewMorsillo** [comment]
Same issue, devtools appear completely broken on RN 0.62

**Comment by tapz** [comment]
When I click Retry, my app restarts, but still the error. I don't have any other devtools installed.

**Comment by jk-gan** [comment]
same here with React Native 0.62.2 and Flipper 0.37.0

**Comment by Bohmaster** [comment]
Same error! Latest RN and Flipper versions.

**Comment by mweststrate** [comment]
Could you share the output in the terminal running metro as well? Any errors shown over there?

**Comment by JohannesKlauss** [comment]
No error are shown for me.

**Comment by mweststrate** [comment]
If you press reload / dev menu in the toolbar, does that get picked up by
the device?

**Comment by JohannesKlauss** [comment]
Yes. I can reload and open the dev menu via Flipper. At least for Android, don't know about iOS

**Comment by codecog** [comment]
Opposite happening for me. Brand new RN Project, update Flipper to 37 along with all the required dependencies 37 relies on. Works fine on Android with no issue but there's no feedback from Flipper apart from the RN console logging into it.

**Comment by usrbowe** [comment]
Just some thought, it would be good to also share device/simulator type. (@JohannesKlauss, @RenanRicoldi,..)

For example if using Android device, we need to set port forwarding for React DevTools:
```
adb reverse tcp:8097 tcp:8097
```

Another way to test is to use standalone React DevTools and see if this work.
`npx react-devtools`

**Comment by robbienohra** [comment]
the port forwarding did the trick for me
thanks!

**Comment by Aung-Myint-Thein** [comment]
I have a standalone React Native Debugger and it is connecting fine. My app is running on 8081 port. However, my Flipper is not connecting and it is listening to port 56111 .. Any tips? :D 

![Screenshot 2020-05-02 at 5 53 32 PM](https://user-images.githubusercontent.com/612366/80862834-0ed84f80-8c9e-11ea-9fc1-38c95bfa48c5.png)

**Comment by Bohmaster** [comment]
Port forwarding did not worked for me.

**Comment by mweststrate** [comment]
@Aung-Myint-Thein please note that you can run only one of them at the same time, if RN debugger is already connected, Flipper can't, and vice versa. Please note that Flipper currently only supports devTools if the tools are listening to port `8097`. 

@Bohmaster  please note that we need more info for your issue to make it actionable, flipper version, RN version, OS, the status of port `8097` etc.

**Comment by Bohmaster** [comment]
> @Aung-Myint-Thein please note that you can run only one of them at the same time, if RN debugger is already connected, Flipper can't, and vice versa. Please note that Flipper currently only supports devTools if the tools are listening to port `8097`.
> 
> @Bohmaster please note that we need more info for your issue to make it actionable, flipper version, RN version, OS, the status of port `8097` etc.

Hi @mweststrate, thank you for your response.

This is my environment:

**OS**: MacOS HighSierra 10.136
**Flipper**: 0.37.0 
**RN**: 0.62.2
**Node**: 12.16.1
**Port status**: Flipper   17570 rtrovant   29u  IPv6 0x1b2c81c78ff3e951      0t0  TCP *:8097 (LISTEN)

When I go to react devtools it says: WAITING FOR CONNECTION FROM DEVICE

If I press retry it opens this http://localhost:8081/debugger-ui/.

If I open RN Debugger it works just fine. But I really wanto to give Flipper a try.

**Comment by usrbowe** [comment]
@Bohmaster @Aung-Myint-Thein can refer to **Quick check** section https://github.com/facebook/flipper/issues/1000#issuecomment-617512233
I believe the issue is that you have `Remote debugging` -> ON, which should be turned off for Flipper.

**Comment by tomcastro** [comment]
@usrbowe where do you turn this setting on/off? I can't find it anywhere on Flipper.

**Comment by usrbowe** [comment]
@tomcastro it's in dev menu (iOS example) 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/5339061/81634323-5058bf80-9441-11ea-8299-f224c4d9d186.png">

**Comment by xstable** [comment]
After taking some hurdles, it works for me.

- First you have to deactivate Remote-Debugging in your App
- then do the adb reverse command `adb reverse tcp:8097 tcp:8097`
- then stop Flipper and restart it
- make sure you choose your "usb-device" and not the pre-selected `Running Emulators ⇒ React Native Emulator` in the Dropdown in Flipper

![image](https://user-images.githubusercontent.com/1778068/81673545-1e992600-944c-11ea-8db9-66386795337b.png)

That way it work for me. Thanks a lot for this great Debug-Software!

**Comment by Bohmaster** [comment]
I don't get this error anymore now following these steps in order:

1) Be sure to not be in remote debug mode
2) adb reverse tcp:8097 tcp:8097

But now I'm getting this:

> While Flipper was able to connect to your device, it wasn't able to connect to the app you are running on your device. For this reason, app-specific plugins will not show up...

I can see the logs and and React Dev Tools but I can't use any plugin (I've installed redux debugger)

**Comment by mweststrate** [comment]
@Bohmaster are you running on iOS or Android? (previous post was about iOS but `adb` is for Android). Note that for iOS we only support running on the emulator. If you are running on both, please make sure to have focus on one only first and close the other one. Could you screenshot your current flipper state, metro console and device just to have some more context?

Can you confirm that the reload and dev menu buttons from Flipper do work when selecting the RN device?

**Comment by Bohmaster** [comment]
@mweststrate They are not working. They worked before but I was not able to use React dev tools. Now that React dev tools works I can't use reload and dev menu buttons.

**Comment by mweststrate** [comment]
Can you provide the mentioned screenshots, I'm especially interested in the metro logs. What version of `@react-native-community/cli` do you have installed?

**Comment by Bohmaster** [comment]
I've restarted flipper and re-built my app and now I can use developer tools and I use reload and dev buttons.

> While Flipper was able to connect to your device, it wasn't able to connect to the app you are running on your device. For this reason, app-specific plugins will not show up...

This error keeps showing so I can't use any plugin.

On hermes debugger says:

> Metro is connected but no Hermes apps were found.

METRO LOGS:

> 	12:40:17.300	client_log	Require cycle: src/navigation/AppNavigator.js -> src/navigation/MainPatientTabNavigator.js -> src/screens/HomeScreen.js -> src/components/appointments/appointment.js -> src/navigation/AppNavigator.js

> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> 	12:40:17.303	client_log	DEV!
> 	12:40:17.304	client_log	Running "Umir" with {"rootTag":41}

I don't have `@react-native-community/cli` installed. Is it mandatory?

**Comment by mweststrate** [comment]
cc @passy is there any additional trickery needed to connect to Android physical devices on Linux? It sounds like the SDK doesn't connect. 

@Bohmaster double checking, you are running a debug build on the device? What is your `adb devices` output?

**Comment by Bohmaster** [comment]
ADB output:
> List of devices attached
5200c7ce5a2cc4cb	device

I'm running this on my device:
`npx react-native run-android`

**Comment by spsaucier-bakkt** [comment]
I'm having the same issue as @Bohmaster - newly upgraded to 0.62 and trying to use Flipper instead of react-native-debugger particularly to avoid bugs in inspecting network.

<img width="1144" alt="Screen Shot 2020-06-04 at 12 05 39 PM" src="https://user-images.githubusercontent.com/60393644/83781014-f0c68c00-a65b-11ea-9e2f-f5748c4d8305.png">

It recommends [this connection debug page](https://fbflipper.com/docs/troubleshooting/#connection-issues), but the Android command isn't working (`Error: Activity class {myapp/com.facebook.flipper.android.diagnostics.FlipperDiagnosticActivity} does not exist.`), and the I'm not sure what to do with the iOS instructions.

**Comment by mweststrate** [comment]
@spsaucier-bakkt are you using a debug build of your app?

**Comment by spsaucier-bakkt** [comment]
@mweststrate Yes, it's a debug build.

**Comment by CristianFonseca03** [comment]
This works for me

> After taking some hurdles, it works for me.
> 
> * First you have to deactivate Remote-Debugging in your App
> * then do the adb reverse command `adb reverse tcp:8097 tcp:8097`
> * then stop Flipper and restart it
> * make sure you choose your "usb-device" and not the pre-selected `Running Emulators ⇒ React Native Emulator` in the Dropdown in Flipper
> 
> ![image](https://user-images.githubusercontent.com/1778068/81673545-1e992600-944c-11ea-8db9-66386795337b.png)
> 
> That way it work for me. Thanks a lot for this great Debug-Software!

**Comment by voxspox** [comment]
I've the same problem as show in the reports screenshot. Debugging works with other tools like devtools plugin in chromium or with rn-debugger.

Metro always opens chromium when I tap "Debug" in the app menu. Usually I use rn-debugger instead... but suddenly Flipper could connect...

Is it intended behavior that an instance of chromium+devtools has to be running such that Flipper could connect to the app?? I expected that the devtools are running by or within Flipper.

**Comment by mweststrate** [comment]
@voxspox they should actually not be running :)

**Comment by mweststrate** [comment]
We added a trouble shooting guide here: https://fbflipper.com/docs/troubleshooting#q-the-react-devtools-dont-seem-to-connect

Suggestions to add any other points are welcome!

**Comment by sparcbr** [comment]
The user should be notified to turn off debug mode.

It's very counter-intuitive that you have to turn off debug mode to be able to connect..

I just kept trying to turn off chrome after hitting the retry button, as metro server would open web debugging ui in chrome (or firefox after I uninstalled chrome in desperation lol).

**Comment by nenjamin2405** [comment]
I'm having the same issue as @spsaucier-bakkt on iOS. The Flipper app doesn't show any plugins (network inspector, ....). When I tap on the Manage Plugins, it shows the same popup, but I really don't know how to follow the phrase

```
You'll need to manually add this ViewController to your app to see the in-app diagnostics.
```

**Comment by nenjamin2405** [comment]
I fixed it, it turns out that I added the variable `FB_SONARKIT_ENABLED=1` in the wrong place. @spsaucier-bakkt you can try to follow these steps:
1. Go to the Build Settings of your project
2. Search for preprocessor macros
3. Double click on the right area of Debug section (**don't** tap the + icon with a circle on that line, I misclicked that icon and add the variable in the wrong place)
4. It will show a popup with a list of existing variables: DEBUG=1, $(inherited)
5. Click the small plus icon in the bottom left the popup
6. Add `FB_SONARKIT_ENABLED=1`

Hope that help

**Comment by mweststrate** [comment]
If anybody has good ideas how to make the messaging in the plugin more clear, or some checks that we could execute to be more certain about the state you are currently in, PR's are welcome! 

(for example the reverse port mapping should normally not needed as Flipper does that as well when initializing the device, so it is a bit unclear to me why some still need to do this manually. Might relate to multiple connected device (or debug tools), but not sure). .

**Comment by AlcantaraRW** [comment]
Flipper can connect to my device but cannot connect to my app.
I'm using Windows 10, Flipper 0.46.0, RN 0.62...
![flipper](https://user-images.githubusercontent.com/18700266/85456881-cdfe0800-b575-11ea-839b-087c574f9650.png)

**Comment by mweststrate** [comment]
@AlcantaraRW that is a different issue than discussed here; your React DevTools clearly do connect. Please keep issues a bit focused otherwise it becomes impossible to make any sense of them over time. Please open a new issue after checking, assuming you did follow the trouble shooting guide already: https://fbflipper.com/docs/troubleshooting#q-i-see-my-device--emulator-but-i-cant-see-the-app

**Comment by AlcantaraRW** [comment]
Sorry @mweststrate, I thought it could be treated here as well.

**Comment by leo-nezes** [comment]
> Just some thought, it would be good to also share device/simulator type. (@JohannesKlauss, @RenanRicoldi,..)
> 
> For example if using Android device, we need to set port forwarding for React DevTools:
> 
> ```
> adb reverse tcp:8097 tcp:8097
> ```
> 
> ### Quick check
> * Do not turn ON `Debug / Remote JS Debugging` 🚫
> * Run `npx react-devtools` to verify if React Devtools can connect without Flipper
> * Do not install `React Devtools v3` if you have React Native >= `0.61`
> * Close any other React Devtools (standalone,...)

Port forwarding work for me 👍😁

**Comment by mweststrate** [comment]
Closing since the thread forks in to many directions and is inactive. If you run into this problem in the future, make sure to follow this check list https://github.com/facebook/flipper/issues/1000#issuecomment-617512233, the general RN troubleshooting guide https://fbflipper.com/docs/troubleshooting#react-native, and open a _new_ issue.
