### ISSUE TITLE
Discussion: Choose Flipper React Native port

### ISSUE THREAD

**Issue by wmcbain** [facebook/flipper#1001]
## Problem

- The React Native packager typically runs on port 8081 but this conflicts with McAfee virus software which my organization uses
- The workaround is [documented here](https://reactnative.dev/docs/troubleshooting#using-a-port-other-than-8081) for React Native
- Flipper is currently hardcoded for port 8081 as [seen with this search](https://github.com/facebook/flipper/search?q=8081&unscoped_q=8081) and running the app does not present the React Native menu.

## Current Workaround

- Clone the flipper repo
- Run `grep -rl 8081 . | xargs sed -i '' 's/8081/8090/g'` in the flipper directory
- Create a build with the changes, I'm currently preserving the zip in our repo
- Use the build to debug our React Native apps

## Discussion

It would be handy to be able to change the metro port within the app. The workaround is simple enough to do but to make sure we're using the latest version of Flipper in house would be made easier if we could configure the metro port.

**Comment by ihwf** [comment]
em...I have this problem too, but I have not idea to resolve it

**Comment by priteshrnandgaonkar** [comment]
I think there is way to do it. Let me check it.

**Comment by priteshrnandgaonkar** [comment]
Let me know this approach works. https://github.com/facebook/flipper/blob/master/docs/custom-ports.md

Feel free to open an issue if it doesn't solve the problem.

**Comment by tungduonghgg123** [comment]
> Let me know this approach works. https://github.com/facebook/flipper/blob/master/docs/custom-ports.md
> 
> Feel free to open an issue if it doesn't solve the problem.

The link you provided is not working anymore. I can confirm this issue stills persist on 0.119.0 version. When using other port than 8081, flipper does not work as expected
