### ISSUE TITLE
Docs: how to setup flipper plugin for react native ? there is not such a good explanation in docs

### ISSUE THREAD

**Issue by EhsanSarshar** [facebook/flipper#1004]
I want to have network plugin for flipper but as the doc it just said to import some library and make an instance of it and register it to client. but as a react native developer I don't have that knowledge of native code. and  I don't know where to put the client.
https://fbflipper.com/docs/setup/network-plugin.html

**Comment by passy** [comment]
If you use the standard template or the upgrade helper, you'll already have the network plugin set up. Otherwise, could you please share information about your setup? React Native version, template you've used, Android/iOS, etc.

**Comment by EhsanSarshar** [comment]
so As I notice the network plugin is only enabled in ios 

![Screen Shot 2020-04-16 at 1 27 52 PM](https://user-images.githubusercontent.com/46188784/79436450-2351f200-7fe6-11ea-8c4e-a43857ee9cc1.png)

**Comment by passy** [comment]
Here's the Android integration that should exist: https://github.com/facebook/react-native/blob/ddc33007ad0b4a0a24966b833e797227b9c56cca/template/android/app/src/debug/java/com/helloworld/ReactNativeFlipper.java#L38-L45
