### ISSUE TITLE
Discussion: Android Add support for room with sqlcipher

### ISSUE THREAD

**Issue by yueban** [facebook/flipper#1021]
I use room database library on Android platform and integrate it with [sqlcipher](https://github.com/sqlcipher/android-database-sqlcipher). But the encrypted database dont show in database list when I choose database plugin in Flipper app.

I've found a related [issue](https://github.com/facebook/flipper/issues/284), but it mainly talk about Realm and have not been updated for five months.

Do you plan to make a plugin to deal with this kind of situation?

**Comment by passy** [comment]
Hey @yueban, we don't have any plans for this. Sounds like a good idea for an external plugin, though!

**Comment by yueban** [comment]
@passy Thanks for your replying. I've just implement a `DatabaseDriver` based on flipper database plugin and some source code from stetho and [this](https://github.com/technoir42/stetho-sqlcipher) stetho database plugin, and it seems to work properly now. Actually the implementation is just about handling the sqlcipher database, no matter the database is created by room or original Android sqlite.

![image](https://user-images.githubusercontent.com/5647837/79561442-f2ec7f80-80db-11ea-8d1a-bd0f547c76a2.png)

Maybe I will publish a library in a few days.

**Comment by passy** [comment]
Amazing!

**Comment by vkalmath** [comment]
Added Android and JS plugin for Cipher SQL.
https://github.com/vkalmath/flipper-sql-cipher-android
https://github.com/vkalmath/flipper-sql-cipher-android

**Comment by yueban** [comment]
@vkalmath The plugin is not work in my project. And it dont allow to use different password for different database which the java code shows. You can try my [one](https://github.com/yueban/flipper-sqlcipher-plugin).

**Comment by yueban** [comment]
@passy I have just published my [library](https://github.com/yueban/flipper-sqlcipher-plugin) on jitpack. It works fine with database on sqlcipher and the api is easy to use. You dont need to add any plugins to your flipper desktop app, but just create flipper original DatabasePlugin with a `SqlCipherDatabaseDriver`. Wish you could have a look on  it if you have some time.

**Comment by Ghedeon** [comment]
**Tested on `v.0.58.0`**

Plugin provided by @yueban works, but actually, you don't need a plugin. Cipher's `SQLiteDatabase` extends regular `SupportSQLiteDatabase`, means flipper's built-in `SqliteDatabaseDriver` should be able to handle all the I/O out of the box. The only custom part that is left is to open the DB with your password by providing your own implementation of `SqliteDatabaseConnectionProvider`.

```kotlin
DatabasesFlipperPlugin(
    SqliteDatabaseDriver(
        context,
        DatabaseFileProvider(context),
        DatabaseConnectionProvider { PASSWORD }
    )
)

...

class DatabaseFileProvider(
    private val context: Context
) : SqliteDatabaseProvider {

    override fun getDatabaseFiles(): MutableList<File> =
        context.databaseList()
            .map(context::getDatabasePath)
			.toMutableList() // or, just manually created list of your DB files.
}

class DatabaseConnectionProvider(
    private val passwordProvider: (databaseFile: File) -> String
) : SqliteDatabaseConnectionProvider {

    override fun openDatabase(databaseFile: File): SupportSQLiteDatabase =
        SQLiteDatabase.openDatabase(
            databaseFile.absolutePath,
            passwordProvider(databaseFile),
            null,
            SQLiteDatabase.OPEN_READWRITE
        )
}
```

**P.S.** In case there are multiple databases in your project and you'd want an automated cherry-
picking of encrypted ones only, you can try to filter out everything that is _not_ encrypted. 
(not exactly bulletproof approach, but seems to be working)

Ex:
```kotlin
class DatabaseFileProvider(
    private val context: Context
) : SqliteDatabaseProvider {

    override fun getDatabaseFiles(): MutableList<File> =
        context.databaseList()
            .map(context::getDatabasePath)
            .filterNot { file -> UNINTERESTING_FILENAME_SUFFIXES.any { suffix -> file.path.endsWith(suffix) } }
            .filter { it.isEncrypted }
            .toMutableList()

    private val File.isEncrypted
        get() = inputStream().use { file ->
            val magic = ByteArray(16)
            file.read(magic)
            !magic.contentEquals(SQLITE_MAGIC_BYTES)
        }

    companion object {
        private val SQLITE_MAGIC_BYTES = "SQLite format 3\u0000".toByteArray()
        private val UNINTERESTING_FILENAME_SUFFIXES = arrayOf("-journal", "-shm", "-uid", "-wal")
    }
}
```

Hope it helps!

**Comment by yueban** [comment]
@Ghedeon Like you said, it's not a plugin, but a pure android library. Thanks for giving more details.

**Comment by Ghedeon** [comment]
@yueban To be precise, you and @vkalmath went with a custom driver, like it's a different database. My suggestion is to profit from the fact that SQLCipher is still an SQLite database, means default driver can be reused. Thanks for your code, btw, it helped a lot!

**Comment by yueban** [comment]
@Ghedeon I may update it if I have some time. Btw, feel free to submit some pr, or publish a new one.

**Comment by PandaGeek1024** [comment]
@yueban I have just tried your plugin and it requires min API 21. Is it possible for it to support API 19? Thanks

**Comment by PandaGeek1024** [comment]
@Ghedeon I have also tried your code but flipper still shows myDatabase.db corrupted. Do you what could be the cause? Also are you able to upload a workable sample project so we really know how to do it? Would really like to see your approach works because it looks like the most handy one. Many thanks

**Comment by yueban** [comment]
@PandaGeek1024 A new version 1.0.2 was published that minSdkVersion is 16. You can have a try. The minSdkVersion of flipper library is 15, but the minSdkVersion of android-database-sqlcipher library is 16. So I choose 16 as the minSdkVersion of my library.

**Comment by lukneu** [comment]
> 
> 
> @Ghedeon I have also tried your code but flipper still shows myDatabase.db corrupted. Do you what could be the cause? Also are you able to upload a workable sample project so we really know how to do it? Would really like to see your approach works because it looks like the most handy one. Many thanks

You should be able to use it like this. In this example, only one encrypted database ("my_database" with password "my_password_123") is used.

**Add plugin (here in Java):**

    final FlipperClient client = AndroidFlipperClient.getInstance(context);

    Function1<? super File, String> dbConnection = file -> "my_password_123";

    client.addPlugin(new DatabasesFlipperPlugin(
                       new SqliteDatabaseDriver(
                           context,
                           new DatabaseFileProvider(context),
                           new DatabaseConnectionProvider(dbConnection)
                       )
    ));

    client.start();

**DatabaseConnectionProvider.kt**

    class DatabaseConnectionProvider(

        private val passwordProvider: (databaseFile: File) -> String) : SqliteDatabaseConnectionProvider {

        override fun openDatabase(databaseFile: File): SupportSQLiteDatabase =
                SQLiteDatabase.openDatabase(
                        databaseFile.absolutePath,
                        passwordProvider(databaseFile),
                        null,
                        SQLiteDatabase.OPEN_READWRITE
                )
    }

**DatabaseFileProvider.kt**

    class DatabaseFileProvider(private val context: Context) : SqliteDatabaseProvider {

        override fun getDatabaseFiles(): MutableList<File> {
            SQLiteDatabase.loadLibs(context)

            val fileList: MutableList<File> = ArrayList()
            fileList.add(context.getDatabasePath("my_database"))

            return fileList.toMutableList()
        }
    }
