### ISSUE TITLE
Android: Network Plugin requires Java 8+ or Android 5+, because of OKHttp 3.14.1

### ISSUE THREAD

**Issue by xit0c** [facebook/flipper#1037]
## 🐛 Bug Report
Network Plugin for Android requires OkHttp and the included version is 3.14.1 (see [build.gradle](https://github.com/facebook/flipper/blob/v0.37.0/build.gradle)).

But OkHttp, from version 3.13.0, requires Java 8+ or Android 5+ (see [OkHttp changelog](https://square.github.io/okhttp/changelog_3x/#version-3130)).

I suggest to use the 3.12.x branch for OkHttp, at least until they're supported (December 31, 2021 as explained [here](https://square.github.io/okhttp/#requirements)), since it's the only way to support pre-Lollipop devices.

## Environment
Android, Network Plugin

**Comment by passy** [comment]
We won't do this as part of this repo. We've instead split it off into a separate dependency so it's opt-in to use. That said, if you or somebody else want to create an OkHttp 3.12.x version of the plugin, please do and let us know so we can add it to the docs.
