### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by lucasluca** [facebook/flipper#1040]
🐛 Bug Report
Flipper does not load plugins due to certificates not transferring from desktop. The app works against a different laptop, so the issue seems to only be with this machine.

Troubleshooting Steps Taken
Tried the app against Flipper on another desktop and it works so it seems the issue is with this particular computer
The Flipper diagnostic activity shows X's for Check required certificates are present and Getting cert from desktop Flipper diagnostic activity
The only error in the Flipper dev tools is (anonymous) | @ | bundle.js:208546
Flipper doctor shows all checks
Checked that the desktop and mobile device have the same date and time
Cleared ~/.flipper and restarted both Flipper and uninstall/reinstalled the app
Uninstalled and reinstalled Flipper
Expected Behavior
Flipper should load a network plugin for the app on the connected device

Environment
Desktop: Windows 10
Flipper: 0.30.2
Devices: Android emulator API 29, Physical Pixel 3a Android 10

**Comment by lucasluca** [comment]
![image](https://user-images.githubusercontent.com/16627838/79887335-f5e3ba80-83d0-11ea-89a4-0687f3a752d1.png)

**Comment by lucasluca** [comment]
![image](https://user-images.githubusercontent.com/16627838/79887335-f5e3ba80-83d0-11ea-89a4-0687f3a752d1.png)

**Comment by lucasluca** [comment]
Just solved this issue installing OpenSSL via choco with this comand: choco install openssl

**Comment by passy** [comment]
This should also show up in Doctor in newer versions of Flipper. Glad it worked out!

**Comment by lucasluca** [comment]
> This should also show up in Doctor in newer versions of Flipper. Glad it worked out!

Yeah it showed first time, but i installed OpenSSL from another source and did not work. I just got it working installing via chocolately
