### ISSUE TITLE
Question: How to install Flipper in Ubuntu?

### ISSUE THREAD

**Issue by Maskedman99** [facebook/flipper#1058]
As suggested in https://github.com/facebook/flipper/issues/985 when I click on flipper file, I get error

![Screenshot-20200426180014-784x242](https://user-images.githubusercontent.com/31368194/80307686-36d03a80-87e8-11ea-9e58-4168c0a114e7.png)

Happening in 18.04 and 20.04.

**Comment by blusclips** [comment]
also facing the same issue... downloaded the zip.. extracted it but can not display flipper... Linux

**Comment by passy** [comment]
What happens if you try to open it in the terminal? E.g.

```
cd ~/Downloads/flipper
./flipper
```

**Comment by Maskedman99** [comment]
Thanks @passy that's working :)

**Comment by Biplovkumar** [comment]
> What happens if you try to open it in the terminal? E.g.
> 
> ```
> cd ~/Downloads/flipper
> ./flipper
> ```

thanks.
it working.

**Comment by tavareshenrique** [comment]
Can I create a shortcut instead of always having to go into the folder and type `./flipper`?

**Comment by maurusrv** [comment]
hi, i managed to use flipper using @duarte-evocorp's command here: https://github.com/facebook/flipper/issues/1139 

but it seems the effect was when i boot, after i login, i'm always welcomed by 'System Program Problem Detected'. is this usual? if yes, is there maybe a workaround to ignore such problem? if no, is there another way to install it without that warning message?

I'm using ubuntu 16. Thanks guys!

**Comment by alexandrtovmach** [comment]
@tavareshenrique
1. Move folder with flipper app somewhere, for example to your _/opt_:
    ```sh
    sudo mv ~/Downloads/flipper /opt/flipper
    ```
2. Create desktop file for flipper in your application folder:
    ```sh
    sudo nano /usr/share/applications/flipper.desktop
    ```
3. Put this content inside:
    ```
    [Desktop Entry]
    Name=Flipper
    Comment=Platform for debugging mobile apps on iOS and Android.
    Exec=/opt/flipper/flipper
    Terminal=false
    Type=Application
    Icon=/opt/flipper/resources/app/icon.png
    ```
4. Log out and login again to Ubuntu client, and open your applications

![image](https://user-images.githubusercontent.com/28801003/109341836-a208f400-7873-11eb-8105-824f889c43bb.png)

**Comment by mMarcos208** [comment]
@alexandrtovmach thank you so much!

**Comment by tavareshenrique** [comment]
@alexandrtovmach thank you so much, I'm really appreciate!

**Comment by PathToLife** [comment]
> Icon=/opt/flipper/resources/app/icon.png
If you're looking for the icon for the manual install desktop entry. Here it is, just put it manually in the required directory.

![icon](https://user-images.githubusercontent.com/12622625/135164246-f7ab24d1-dc1c-4cdf-bfca-2563c8b7327f.png)

**Comment by thallysfs** [comment]
> @tavareshenrique
> 
> 1. Move folder with flipper app somewhere, for example to your _/opt_:
>    ```shell
>    sudo mv ~/Downloads/flipper /opt/flipper
>    ```
> 2. Create desktop file for flipper in your application folder:
>    ```shell
>    sudo nano /usr/share/applications/flipper.desktop
>    ```
> 3. Put this content inside:
>    ```
>    [Desktop Entry]
>    Name=Flipper
>    Comment=Platform for debugging mobile apps on iOS and Android.
>    Exec=/opt/flipper/flipper
>    Terminal=false
>    Type=Application
>    Icon=/opt/flipper/resources/app/icon.png
>    ```
> 4. Log out and login again to Ubuntu client, and open your applications
> 
> ![image](https://user-images.githubusercontent.com/28801003/109341836-a208f400-7873-11eb-8105-824f889c43bb.png)

Thank you!

**Comment by kuchaguangjie** [comment]
Where to download flipper ?

**Comment by devfed1** [comment]
> Where to download flipper executable for linux ? The link from doc is broken: https://www.facebook.com/fbflipper/public/linux


I notice that this is the last version with linux version builded as app and not flipper-server. @kuchaguangjie  

https://github.com/facebook/flipper/releases/tag/v0.233.0
