### ISSUE TITLE
Question: No plugins appear due to cert issue

### ISSUE THREAD

**Issue by MaxBuster** [facebook/flipper#1068]
I have Flipper 0.39.0 installed on my Mac with no issues showing in the Flipper Doctor. However when I launch my app Flipper doesn't connect and the diagnostics activity shows that there is a certificate issue. 

Any idea what I need to get the correct certs on my laptop? 

![Screenshot_1588019444](https://user-images.githubusercontent.com/7552954/80418280-06da7300-888c-11ea-9cf7-8d6b9feead3b.png)
<img width="601" alt="Screen Shot 2020-04-27 at 1 34 18 PM" src="https://user-images.githubusercontent.com/7552954/80418302-0fcb4480-888c-11ea-8704-f0e0c5a59f45.png">
<img width="512" alt="Screen Shot 2020-04-27 at 1 34 54 PM" src="https://user-images.githubusercontent.com/7552954/80418320-18237f80-888c-11ea-9cfc-7bf6cf9d039e.png">

**Comment by cryptoPickle** [comment]
Same here.

**Comment by mweststrate** [comment]
0.39 is fairly old, would you mind checking if this is still the case in 0.45?

**Comment by mweststrate** [comment]
cc @jknoxville  ideas?

**Comment by jknoxville** [comment]
Strange, I'd expect to see some related errors in Flipper, as it's failing to deploy the certs, but it doesn't look like there are any.

It might be worth checking that your port forwards are correct:
`adb reverse --list`

You should see two entries for your android device, port 8088 and 8089.
Is that true?

Also, when this is happening, does Flipper show any "connecting..." spinner, or any other indication that it is aware you app is trying to connect?

**Comment by MaxBuster** [comment]
I actually get an empty list when running `adb reverse --list` should I set those two ports?

And no, there isn't any messaging in Flipper to show the app is trying to connect.

**Comment by MaxBuster** [comment]
Nevermind, I do see those ports

```
host-9 tcp:8088 tcp:8088
host-9 tcp:8089 tcp:8089
```

**Comment by thu2004** [comment]
I have same problem with my Huawei phone android v 10.

try run adb command in your computer:
adb shell run-as <your package>

See https://github.com/facebook/flipper/issues/92

**Comment by shashachu** [comment]
@passy do you have any tips on how to debug this?

**Comment by jknoxville** [comment]
> And no, there isn't any messaging in Flipper to show the app is trying to connect.

This suggests that no connection at all is being made between client and flipper.

The problem could be either in your desktop installation, or the mobile app. To narrow it down I'd suggest trying it with the android sample app we provide. You can build it locally or download the apk from the [releases page](https://github.com/facebook/flipper/releases).

**Comment by shashachu** [comment]
I'm having the same issue with the sample app as well (downloaded from latest release). I'm certain it must be something about my laptop, or maybe the config our IT department uses, but I'm unsure where to start for debugging.

![Screenshot_20200915-162405](https://user-images.githubusercontent.com/521778/93274806-0cb7ee80-f770-11ea-9e62-de40bcd650f5.png)

**Comment by shashachu** [comment]
@jknoxville just checking in again to see if there are any tips for debugging the connection issue. Thanks!

**Comment by MaxBuster** [comment]
@jknoxville I can confirm that I get the same issue with the sample app and my app works on other laptops so it's definitely an issue with my laptop config or installation.

**Comment by eliot1019** [comment]
Also having this issue on RN63, Mac, android, and latest flipper ver. It doesn't seem app specific as the sample flipper app also has the same problem on the diagnostics screen.

**Comment by darvelo** [comment]
The solution in [this comment](https://github.com/facebook/flipper/issues/262#issuecomment-673789890) worked for me for an iOS device.
