### ISSUE TITLE
No devices running

### ISSUE THREAD

**Issue by abeemukthees** [facebook/flipper#110]
I installed the latest v0.6.9 Sonar desktop app on my mac.  (Downloaded directly)
1. Launched it
2. Started Android Emulator
3. Able to see Log & Layout
4. Not able to see network activities
5. Still showing "No devices running" at the top

App is written in Kotlin, Networking is handled by Retrofit + okhttp + CoroutineCallAdapterFactory + MoshiConverterFactory

```
override fun onCreate() {
        super.onCreate()
        SoLoader.init(this, false)

        if (BuildConfig.DEBUG && SonarUtils.shouldEnableSonar(this)) {
            val client = AndroidSonarClient.getInstance(this)
            client.addPlugin(NetworkSonarPlugin())
            client.addPlugin(InspectorSonarPlugin(this, DescriptorMapping.withDefaults()))
            client.start()
        } else Log.e(MyApplication::class.simpleName, "Sonar not enabled")
    }
```

Since I had some build issues, I added this in the app build.gradle :

```
packagingOptions {

        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'

        pickFirst 'lib/armeabi-v7a/libassmidi.so'
        pickFirst 'lib/x86/libassmidi.so'

        pickFirst 'lib/armeabi-v7a/libsonarfb.so'
        pickFirst 'lib/x86/libsonarfb.so'
        pickFirst 'lib/arm64-v8a/libsonarfb.so'
    }
```

**Comment by lucaslbs15** [comment]
I'm with the same problem. And my project is written in Kotlin too. Someone have some idea how can be done to fix it?

**Comment by tyronen** [comment]
I am having the same issue. Our app is written mostly in Java though. Also using okhttp3 + retrofit. Neither the network nor layout plugins appear on a physical device, but the Logs view shows fine, despite saying "no devices running".

The Android emulator shows both plugins. However, only the Layout plugin works; the Network plugin shows no network requests, even though they're clearly working in the app.

**Comment by singhalmanav** [comment]
I'm experiencing the same issue. The logs and UI layout inspector is working fine but no network logs are displayed in the Sonar Mac app. Our Android app is mostly in Kotlin and uses OkHttp + Retrofit.

**Comment by amenon** [comment]
You will need to include the OkHttp interceptor in order to intercept and view network requests through the network plugin. Take a look at the docs (https://fbsonar.com/docs/network-plugin.html#okhttp-integration) or the sample project (https://github.com/facebook/Sonar/blob/master/android/sample/src/main/java/com/facebook/sonar/sample/SonarSampleApplication.java#L31-L39) for an example.

**Comment by abeemukthees** [comment]
It's working now.
