### ISSUE TITLE
Flipper won't open, shows blank screen

### ISSUE THREAD

**Issue by leoafarias** [facebook/flipper#1111]
## 🐛 Bug Report
I have been working on using Flipper for React Native development. Everything has been working fine, however now Flipper will not open and shows a blank screen. 

Here is the blank screen that I see.
![Screen Shot 2020-05-04 at 11 34 37 AM](https://user-images.githubusercontent.com/435833/80985018-a489f100-8dfc-11ea-8930-68c9428b8228.png)

I have uninstalled, multiple times. Also have tested with multiple Flipper versions, however I am not able to solve this. I have also followed the steps on **Flipper won't launch on Mac**, and have had no luck.

Every time I open app I get before getting the empty screen `Flipper Helper (Renderer).app`
![Screen Shot 2020-05-04 at 11 41 14 AM](https://user-images.githubusercontent.com/435833/80984817-5d9bfb80-8dfc-11ea-89c7-7cb5983023b1.png)

Also here are the logs when I Toggle Developer Tools.
![Screen Shot 2020-05-04 at 11 43 23 AM](https://user-images.githubusercontent.com/435833/80984950-89b77c80-8dfc-11ea-8d9f-d51a69cc4a1b.png)

## To Reproduce
The last thing I remember doing on Flipper was changing the shortcuts for the reload functionality, and while testing the shortcut the app crashed. Since then I have not been able to open it again even after multiple fresh installs.

## Environment
macOS Catalina - 10.15.4
Flipper 0.40 -> however reverting back to 0.37 -> 0.39 does not resolve the issue.

**Comment by jknoxville** [comment]
Thanks for the report @leoafarias ,

Remarkably, it looks like there may be a bug in electron related to global hotkeys: https://github.com/electron/electron/issues/16206

Could you paste the contents of `~/.config/flipper/settings.json` here so we can see (if it is the shortcuts that did this) what shortcuts are set that causes this problem?

Thanks.

If you manually edit that file, and remove the reactNative section, you'll likely be up and running again, failing that you could try getting rid of the file entirely.

**Comment by leoafarias** [comment]
@jknoxville it worked, thanks for the response.  Here is the config for reference, before removing anything.

```{
  "androidHome": "/opt/android_sdk",
  "enableAndroid": true,
  "enableIOS": true,
  "enablePrefetching": 2,
  "jsApps": {
    "webAppLauncher": {
      "url": "http://localhost:8888",
      "height": 600,
      "width": 800
    }
  },
  "reactNative": {
    "shortcuts": {
      "enabled": true,
      "reload": "Alt+Shift",
      "openDevMenu": "Alt+Shift+D"
    }
  },
  "_persist": {
    "version": -1,
    "rehydrated": true
  }
}```

**Comment by risingus** [comment]
This problema still occur

**Comment by diskriminantWasTaken** [comment]
+1

**Comment by orhangazi** [comment]
+1

**Comment by pedrokarnoski** [comment]
This problema still occur

**Comment by MutableLoss** [comment]
Just had this issue today, and found in the Flipper devtools that there was still a stale server process running in the background, causing Flipper to throw an error when trying to start the server. 

In this case, I just had to kill the server, and start Flipper again.

```
$ pgrep -f /usr/libexec/rapportd | kill -9
```
