### ISSUE TITLE
Flipper Pkg Plugin Generation

### ISSUE THREAD

**Issue by Kranthi94** [facebook/flipper#1112]
## 🐛 Bug Report
Facing problems when generating plugin using Flipper Pkg.
  

## To Reproduce
Installed Flipper Pkg from npm and I want to create a plugin defaults using init method

## Environment
MacOS Version: 10.15.4
NPM Version: 6.14.4
Flipper Pkg Version: [0.40.1]

<img width="1261" alt="Screenshot 2020-05-04 at 10 27 51 PM" src="https://user-images.githubusercontent.com/13165950/80992993-f6139980-8e57-11ea-89c6-29a8da19eb6f.png">
)

**Comment by nikoant** [comment]
@Kranthi94, thank you for the report! Templates files were not published with npm package. I;ve just published version 0.40.2 where this issue is fixed.

**Comment by Kranthi94** [comment]
Thank You
