### ISSUE TITLE
Question: Installing the flipper on ubuntu

### ISSUE THREAD

**Issue by duarte-evocorp** [facebook/flipper#1139]
When I went to install on Ubuntu

[5422:0506/113024.894288:FATAL:electron_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap

**Comment by duarte-evocorp** [comment]
I managed to solve by placing the command: sudo ./flipper --no-sandbox

**Comment by maurusrv** [comment]
hi, i managed to use flipper using @duarte-evocorp's command but it seems the effect was when i boot, after i login, i'm always welcomed by 'System Program Problem Detected'. is this usual? if yes, is there maybe a way to make my system not detect such problem? if no, is there another way to install it without that warning message?

I'm using ubuntu 16. Thanks guys!
