### ISSUE TITLE
iOS Simulator cannot show Logs on Flipper

### ISSUE THREAD

**Issue by baveku** [facebook/flipper#1145]
## 🐛 Bug Report
I use Flipper for my swift app, when I run the app on Simulator, I can't see any Logs although Console log of xCode has value
## To Reproduce
  Click Button
 ```swift
 @IBAction func toggleLogin() {
     print("LOGIN TOGGLE")
     NSLog("LOGIN TOGGLE")
}
 ```

## Environment
xCode: latest 11.4.1
iOS SImulator: 13.4.1
Flipper 0.41.0
FlipperSDK 0.41.0
App: Swift 5.1, Cocoapods 1.9

**Comment by passy** [comment]
Hi @baveku, is anything showing up in the logs at all? Can you share a screenshot?

**Comment by baveku** [comment]
<img width="1285" alt="Screen Shot 2020-05-12 at 01 00 07" src="https://user-images.githubusercontent.com/47909357/81595026-0396c980-93ec-11ea-9b2f-102d4cc33ca6.png">
@passy I config follow by FlipperDocument, but DeviceLogs not working, 
In Console of Flipper App:
```js
Could not connect to METRO Error: connect ECONNREFUSED 127.0.0.1:8081
```

**Comment by passy** [comment]
Thanks for the report! @priteshrnandgaonkar has confirmed that this seems to be affecting Swift apps at the moment. We're looking into it.
