### ISSUE TITLE
Discussion: Application Setup - Why put this file in our namespace?

### ISSUE THREAD

**Issue by etaiklein** [facebook/flipper#1151]
Application setup wants us to create our own ReactNativeFlipper class.

Why is this file in our namespace, rather than inside the Flipper library?

https://fbflipper.com/docs/getting-started/react-native-android#application-setup
https://fbflipper.com/docs/getting-started/react-native-ios

**Comment by passy** [comment]
This is to give you the flexibility to edit it, add and remove plugins. I hope that helps.

**Comment by etaiklein** [comment]
@passy can you confirm this copy for accuracy:

Usually for a new library we have to import the library from a native namespace and register it (for example in java we add it to getPackages()).

Flipper setup asks us to create a new library integration point for its many plugins. Creating this in our namespace lets us maintain control over what flipper plugins we allow in our codebase and how, while also wrapping it in a container (which lets us do things like ensure that we dont ship flipper code to prod).

**Comment by jknoxville** [comment]
I'm just doing an audit of past issues, and have seen this. I can confirm that's accurate.
