### ISSUE TITLE
Issue: Window Client not detecting debug android process

### ISSUE THREAD

**Issue by VarunKarhadkar** [facebook/flipper#1157]
## 🐛 Bug Report

I am using flipper on my Windows laptop and trying to get logs out of my android application. I have installed debug app on my mobile and its connected to my laptop. Windows flipper client is not detecting my android debug process. I can see Device name in the Device Pane on the left of the screen.

![image](https://user-images.githubusercontent.com/63746130/81714483-bde20b80-9494-11ea-8fc5-26bfec5e2282.png)

Same build on same device if connected to MAC client its working as expected, Showing app DB, intercepting network calls, etc.

## To Reproduce

To reproduce just use latest version of Flipper on Windows 10 Home edition and use android debug APK capable of intercepting network requests and app DB.

## Environment

Android APK installed on Android phone and connected to Flipper windows client.

**Comment by DevPlus31** [comment]
Same issue. I am using Win 10 Pro.

**Comment by mweststrate** [comment]
Seems this issue was so far missed by everybody. Is anything reported in the Flipper logs? (View > Toggle Developer Tools)

**Comment by nikoant** [comment]
I'm trying to debug it on Windows machine.

**Comment by nikoant** [comment]
I cannot reproduce this. I checked RN android and native android apps and they both appeared in Flipper on my Win 10 PRO machine. Please provide a repository with a mobile app example where this can be reproduced.

**Comment by nishan-wtv** [comment]
Having the same issue, I can't run it on windows 10

**Comment by mweststrate** [comment]
@nishan-wtv since this issue is stale since there isn't any reproduction information, and you don't provide any either, would you mind opening a fresh issue with some more context?
