### ISSUE TITLE
iOS Xcode not build (Undefined symbol: boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find())

### ISSUE THREAD

**Issue by dunamu-amelia** [facebook/flipper#1159]
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/53553681/81816137-dec66180-9565-11ea-89af-8c3461e05cf4.png">

my cocoa pod use option use_frameworks!
and added pod code 
`$static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
   'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
   'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
   'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']

 pre_install do |installer|
   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
   installer.pod_targets.each do |pod|
       if $static_framework.include?(pod.name)
         def pod.build_type;
           Pod::BuildType.static_library
         end
       end
     end
 end`

**Comment by dunamu-amelia** [comment]
and other linker flag is -all_load

if your sample app change other linker flag -all_load, 
The same issue occurs and cannot be build

**Comment by passy** [comment]
Sorry, could you please follow the issue templates we have? We need more information to repro this, and ideally a test repository for this.
