### ISSUE TITLE
Add changelog to Github releases

### ISSUE THREAD

**Issue by ZacSweers** [facebook/flipper#1160]
Another like #934 but opening a new one for visibility. Automated releases are nice for quicker updates, but these are effectively acting as snapshot dependencies without knowing what's in them. Would the team consider either fixing this or returning to manual uploads until automated ones work correctly?

**Comment by passy** [comment]
@ZacSweers We have moved this to the in-app Changelog which shows up on every new version and is accessible via the help menu. Can you elaborate what's missing from there?

**Comment by ZacSweers** [comment]
Could it be both? Thanks releases are published to github, having to look somewhere else too find release notes seems odd

**Comment by passy** [comment]
@mweststrate (who added the changelog feature) what do you think? Would it be feasible to post the changelog to the release page as well?

**Comment by ZacSweers** [comment]
Also the app just points back to github 
![image](https://user-images.githubusercontent.com/1361086/82093359-f79b5800-96c8-11ea-912b-e76c39182f83.png)

**Comment by ZacSweers** [comment]
The app also doesn't auto-update (anymore?), which also makes changes tricky to track.

**Comment by ZacSweers** [comment]
And the 0.43 mac app's changelog doesn't show 0.43 info 
![image](https://user-images.githubusercontent.com/1361086/82417592-c1076980-9a49-11ea-8872-992215e7094c.png)

**Comment by ZacSweers** [comment]
Sorry to nag about this again - I missed 0.43 through 0.46, and the lack of a means to see changelog history in the app makes this worse as I now can't see what changes were in thos.

![image](https://user-images.githubusercontent.com/1361086/84628619-fff8d580-aeb6-11ea-9097-531d3450b092.png)

**Comment by mweststrate** [comment]
@ZacSweers the changelogs are automatically generated, based on whether changelog meta data has been filled. We release every week but not every release has noteworthy changes (sometimes it is just internal infrastructural changes, or FB only changes). But sometimes the info is simply not failed, I'll make sure to emphasize it again with the team :)

**Comment by ZacSweers** [comment]
They are now also missing from the mac app downloads :/

**Comment by mweststrate** [comment]
Closing as this issue has been inactive for a while for now, looks like the in-app changelog generally suffices. For future readers, they can also be found here: https://github.com/facebook/flipper/blob/master/desktop/static/CHANGELOG.md

**Comment by ZacSweers** [comment]
That changelog is not kept in sync. 0.61 was released 4 days ago but is not mentioned there

**Comment by caycecollins** [comment]
@mweststrate Any chance this can be re-opened or a new issue created to keep the CHANGELOG.md updated with releases?

**Comment by mweststrate** [comment]
@caycecollins the changelog.md is kept up to date automatically, but only if we have landed changes with actual changelog notes, to prevent spamming users with not so relevant information. So if there is no entry for a certain version, it is safe to assume all changes were internal or fixing less prominent bugs.

**Comment by mweststrate** [comment]
If you are looking for an extensive list of changes, github compares functionality works pretty well, since we land only one commit per diff / pr, for example: https://github.com/facebook/flipper/compare/v0.66.0...v0.69.0
