### ISSUE TITLE
Docs: Copy button in code snippet is hard to see

### ISSUE THREAD

**Issue by Izzur** [facebook/flipper#1161]
When you open page containing code snippet like:
- https://fbflipper.com/docs/getting-started/android-native
- https://fbflipper.com/docs/setup/layout-plugin

![image](https://user-images.githubusercontent.com/13365626/82036125-b146f880-96ca-11ea-8677-c8eabc8930af.png)

You can copy code using copy button on top-right side
But the button itself is hard to see because some styling issue

**Comment by passy** [comment]
Oh good spot. Thanks for reporting!

**Comment by passy** [comment]
Fix by @jknoxville is landing. :)
