### ISSUE TITLE
Discussion: [Feature Request] allow to set font size

### ISSUE THREAD

**Issue by lambda0xff** [facebook/flipper#1163]

**Comment by cekkaewnumchai** [comment]
Thank you for the suggestion! 

Can you provide specific use case on this? Do you mean some specific component or whole app?

**Comment by lambda0xff** [comment]
I was thinking about logs and layout inspector mostly but i guess that could be extended to all data.  App chrome (menu, etc) doesn't really matter imo.

**Comment by passy** [comment]
I'd also be quite interested in other apps to allow that level of configuration. Both to better understand the use cases and perhaps have something to get some inspiration for the implementation from. :)

**Comment by lambda0xff** [comment]
Use case is pretty simple: just to have better visual comfort :-) (also, log messages are not wrapped, which requires users to scroll horizontally when trying to read long log messages)

I'm not familiar with how flipper is built nor with how Electron apps work so I may be completely off, but isn't it "just" a matter of changing the font size in the relevant css stylesheet ?

I think VSCode is built using Electron too, and it allows some control over font size with CMD+- and CMD+=

**Comment by nyteshade** [comment]
This feature has not yet been fixed.

**Comment by betoharres** [comment]
if you open developer tools of flipper(yes, you'd have two consoles displaying at the same time) you can just `shit` + `ctrl` + `+` or `-` to change the font size
