### ISSUE TITLE
Discussion: Any plan to make Connection Send API support circular reference JSON structure?

### ISSUE THREAD

**Issue by plwai** [facebook/flipper#1167]
The connection [Send API](https://github.com/facebook/flipper/blob/436159eb2249ab29d54757df6364dd69b323f03e/react-native/react-native-flipper/index.js#L43) is using native `JSON.stringify` which does not support circular structure. 

Tried to remove cyclic reference the object before calling the API. However, that impacts the performance heavily for large data object.

**Comment by cekkaewnumchai** [comment]
cc. @mweststrate

**Comment by mweststrate** [comment]
No, the JSON api very deliberately doesn't support circular graphs indeed, just like it doesn't support classes, maps, sets, etc etc. Serializing these kind of data structures would yield a high performance impact on a very intensively used api, so we don't plan to support this. 

Any specific reason why you would wan't to send cyclic data?

**Comment by plwai** [comment]
Some `redux-debugger` users are using cyclic data in their redux store which makes the plugin not usable.

The related issue: #https://github.com/jk-gan/redux-flipper/issues/14

**Comment by mweststrate** [comment]
IIRC Redux officially doesn't support cyclic data structures (I think it
will render most Redux related dev and serialization tools useless). It is
probably best to error on this on the plugin level?

**Comment by plwai** [comment]
Okay. In this case, I agree that it is better to handle the issue in plugin level. Thanks.
