### ISSUE TITLE
Discussion: Add a function to easily copy the response body

### ISSUE THREAD

**Issue by binaryfork** [facebook/flipper#1179]
To copy the response body I have to do like 5 actions: 

Collapse Headers so I can see the Options settings
Expand Options
Select formatted option for Body
Manually select the whole response body
Copy

Please add a button somewhere to easily copy the response

**Comment by cekkaewnumchai** [comment]
You can also right-click to "copy entire tree" 
![out](https://user-images.githubusercontent.com/18430703/82548073-a40a8d80-9b52-11ea-85c2-cbeae0e935d2.gif)

I'm curious about what you workflow in copying response body. Do you mind record video and share?

**Comment by binaryfork** [comment]
I did not know about this, "copy entire tree" works only in formatted option, thanks, it's good enough.
