### ISSUE TITLE
Discussion: Publish flipper to snapcraft.io

### ISSUE THREAD

**Issue by hamidfzm** [facebook/flipper#1184]
In macOS, there is a homebrew script to install flipper. It would be great to implement a convenient way to download flipper from Linux package managers like apt-get, snap, &...

**Comment by passy** [comment]
Hadn't heard of that service before. That looks pretty cool. Unfortunately, I don't have access to my Linux box right now due to the lockdown. I'm happy to look into this once I have a Linux machine again.

**Comment by hamidfzm** [comment]
@passy  I would be happy to help you. I have access to Linux. I think I can build a snap package but I don't want to publish it as a user-maintained repo in Snapcraft.

**Comment by passy** [comment]
I've just added an option to our build script to produce Snaps. Do you know how the publishing procedure works? Is there a way, for instance, to import this from GitHub release pages?

**Comment by mirland** [comment]
Hi, I think this is something that would be nice to have. Update flipper every time that a new version is released is a headache. As @hamidfzm mentioned, facebook should create an official account https://snapcraft.io/docs/releasing-to-the-snap-store
