### ISSUE TITLE
There's no way to remove expression watchers in Logs using context menu

### ISSUE THREAD

**Issue by v0lume** [facebook/flipper#1185]
## 🐛 Bug Report
There's no way to remove expression watchers in Logs using context menu

## To Reproduce
open expressions watcher
add new expression
open context menu on the new element <-- there is no option to remove selected item
press "clear all" <-- only logs from main window are cleared

## Environment
Flipper 0.42, macos

**Comment by v0lume** [comment]
update - it's possible to delete expressions using keyboard "delete" or "backspace" button, but there should be an option in context menu

**Comment by mweststrate** [comment]
Will be fixed in the next release, thanks for reporting!
