### ISSUE TITLE
Flipper 0.44.0 crashes 

### ISSUE THREAD

**Issue by rafaela-stockx** [facebook/flipper#1204]
## To Reproduce

Flipper 0.44.0 can not be opened after installed it crashes repeteadly
![Screen Shot 2020-05-29 at 1 28 16 PM](https://user-images.githubusercontent.com/55147539/83287795-44def580-a1b0-11ea-8126-0028c2a5ab94.png)

## Environment

Macbook pro macOS Catalina10.15.5
opensslv1.1.1g
Flipper 0.44.0
- Flipper has full disk access under `settings > privacy`

**Comment by mweststrate** [comment]
@rafaela-stockx we released 0.45 yesterday, could you check if it has the same problem? If not, try to run `open -a Flipper` from the command line, to see if there is anything logged. I have Catalina 10.15.4 here, so that is probably not the problem (famous last words)

**Comment by passy** [comment]
The `open` command swallows all debug information (you can still look it up through the Console, though). I would recommend directly opening the binary, i.e. `Flipper.app/Contents/MacOS/Flipper`

**Comment by passy** [comment]
Closing for staleness but let us know if this is still a problem.

**Comment by rafaela-stockx** [comment]
Hi @mweststrate and @passy I am very sorry for the delay in replying. I updated to the `0.45`and it is working fine, thank you for the help

**Comment by passy** [comment]
@rafaela-stockx I'm happy to hear it got solved! Thanks for following up.
