### ISSUE TITLE
Network plugin mock data not maintained after plugin switch.

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#1206]
Hello.
Let me start by thanking @qichuan for this amazing option added to the network plugin. I use and abuse of the mock option.

Don't know if this is a bug or not but after adding mock data and then switching to another plugin or restarting the Android app, the mock data is lost thus I have to insert it again.

As a user, I was expecting the mock data being persisted if I switch plugin or restart my app thus not needing to insert the mock data every time one of the described situations occurs.

## To Reproduce

1. In the network, plugin click the mock button and add mock data.
2. Switch to another plugin (databases for example)
3. Go back to the network plugin and press the mock button.
4. No mock data is available

## Suggestion
Another thing that would be great was the place where we insert the mock data had json code highlighting.
Also, the pre-filled `/` on the URL for me is unnecessary. I always have to delete it or double click it to add my URL.

## Environment
Using Flipper on Android. Flipper client version 0.44 on Mac.

**Comment by qichuan** [comment]
Thanks for the feedback, let me see how I can make this plugin work better

**Comment by mgoyanes** [comment]
Hello.

Another thing. The close button is not fully visible.

![image](https://user-images.githubusercontent.com/5049948/83518078-e6788680-a4d1-11ea-97e9-2f01301421db.png)

**Comment by mgoyanes** [comment]
I know that this comes late, but it would be great if we could toggle on or off the mock for a specific URL.

Currently, if in a session we don't want to mock a response, we have to delete the mock.
