### ISSUE TITLE
UI scale broken after use with a 4K monitor

### ISSUE THREAD

**Issue by Braden1996** [facebook/flipper#1223]
## 🐛 Bug Report
Hello! When opening Flipper on my laptop, the UI scale is zoomed in to an unusable state - my suspicion this is because I usually run Flipper within a desktop on my 4K monitor. Worth noting, this happens even when my monitor is not connected to any external displays.

![image](https://user-images.githubusercontent.com/5165963/83745601-b0fca600-a655-11ea-838b-bffbfe72e379.png)

## To Reproduce

1. Open Flipper within a 4K monitor.
2. Quit Flipper fully.
3. Open Flipper within Macbook display,
4. See UI scale hasn't adjusted, despite Flipper being closed fully.
(Not verified to actually work, as I can't seem to reverse the issue to test).

## Environment
- Flipper version: 0.44.0 (50.0.0)
- Macos Version: 10.15.5

**Comment by mweststrate** [comment]
Sadly I can't try to reproduce the issue locally right now, lacking an external 4K monitor, if others can feel free to add more info. I suspect that this might be an Electron issue (I think I saw similar behavior in the past with VSCode).

**Comment by Braden1996** [comment]
> Sadly I can't try to reproduce the issue locally right now, lacking an external 4K monitor, if others can feel free to add more info. I suspect that this might be an Electron issue (I think I saw similar behavior in the past with VSCode).

I wonder if it can be reproduced by just bumping up your resolution and then bringing it down?

**Comment by mweststrate** [comment]
I don't see how this is really actionable for us,  as this is something between Electron and the OS. Nor seems super urgent (I assume restarting Flipper fixes it?)
