### ISSUE TITLE
`flipper-plugin-lib` required but not published

### ISSUE THREAD

**Issue by jeremy-deutsch** [facebook/flipper#1238]
## 🐛 Bug Report

The `0.46.0` release of the `flipper` package (flipper desktop) adds a dependency on `flipper-plugin-lib` `0.46.0`, but the only version of `flipper-plugin-lib` in the NPM registry is `0.0.0`. It looks like `flipper-plugin-lib` just wasn't published as part of the `0.46.0` release?

**Comment by nikoant** [comment]
Hi @jeremy-deutsch, thanks for notifying us! I've published the missing npm packages now.
