### ISSUE TITLE
Docs: Is React Native Android intentionally still 0.35.0?

### ISSUE THREAD

**Issue by joe-goodall-ticketmaster** [facebook/flipper#1240]
Is there a reason [React Native Android](https://fbflipper.com/docs/getting-started/react-native-android/) is still set to 0.35.0 when [React Native iOS](https://fbflipper.com/docs/getting-started/react-native-ios/), [native iOS](https://fbflipper.com/docs/getting-started/ios-native), [native Android](https://fbflipper.com/docs/getting-started/android-native), Flipper desktop, and react-native-flipper are all set to 0.45.0?

**Comment by nikoant** [comment]
@joe-goodall-ticketmaster, thanks, it seems bump job is missing this doc. I'll update it.

**Comment by joe-goodall-ticketmaster** [comment]
> @joe-goodall-ticketmaster, thanks, it seems bump job is missing this doc. I'll update it.

@nikoant Still stuck at 0.35.0
