### ISSUE TITLE
flipper-noop conflicting classes at release

### ISSUE THREAD

**Issue by Stonelinks** [facebook/flipper#1241]
## 🐛 Bug Report

Both `com.facebook.flipper:flipper` and `com.facebook.flipper:flipper-noop` are both being included in releases when I follow the flipper website's documentation.

## To Reproduce

Per the website's documentation (https://fbflipper.com/docs/getting-started/android-native#dependencies), we're supposed to set up our dependencies like this:

```
dependencies {
  debugImplementation 'com.facebook.flipper:flipper:0.46.0'
  debugImplementation 'com.facebook.soloader:soloader:0.9.0'

  releaseImplementation 'com.facebook.flipper:flipper-noop:0.46.0'
}
```

in my project i'm doing this:

```
  debugImplementation 'com.facebook.soloader:soloader:0.9.0'
  debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.fbjni', module: 'fbjni'
  }
  releaseImplementation "com.facebook.flipper:flipper-noop:${FLIPPER_VERSION}"
  debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}")
  debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
```
my FLIPPER_VERSION is currently 0.46.0

However, when I go to make a release build of my app, the following gradle task fails (Note: my app is called "Driver"):

```
> Task :app:checkDriverReleaseDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDriverReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.facebook.flipper.BuildConfig found in modules flipper-0.46.0-runtime.jar (com.facebook.flipper:flipper:0.46.0) and flipper-noop-0.46.0-runtime.jar (com.facebook.flipper:flipper-noop:0.46.0)
  Duplicate class com.facebook.flipper.android.AndroidFlipperClient found in modules flipper-0.46.0-runtime.jar (com.facebook.flipper:flipper:0.46.0) and flipper-noop-0.46.0-runtime.jar (com.facebook.flipper:flipper-noop:0.46.0)
  Duplicate class com.facebook.flipper.android.diagnostics.FlipperDiagnosticActivity found in modules flipper-0.46.0-runtime.jar (com.facebook.flipper:flipper:0.46.0) and flipper-noop-0.46.0-runtime.jar (com.facebook.flipper:flipper-noop:0.46.0)
  Duplicate class com.facebook.flipper.core.FlipperClient found in modules flipper-0.46.0-runtime.jar (com.facebook.flipper:flipper:0.46.0) and flipper-noop-0.46.0-runtime.jar (com.facebook.flipper:flipper-noop:0.46.0)
  Duplicate class com.facebook.flipper.core.FlipperPlugin found in modules flipper-0.46.0-runtime.jar (com.facebook.flipper:flipper:0.46.0) and flipper-noop-0.46.0-runtime.jar (com.facebook.flipper:flipper-noop:0.46.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

So it would appear that `com.facebook.flipper:flipper` and `com.facebook.flipper:flipper-noop` are both being included somehow.
 
I've attempted to google around and try some different strategies (following that android help link, copying how others are configuring flipper in their RN projects, etc.), but none have been successful.

My workaround has been to install flipper like this:

```
  debugImplementation 'com.facebook.soloader:soloader:0.9.0'
  implementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.fbjni', module: 'fbjni'
  }
//  releaseImplementation "com.facebook.flipper:flipper-noop:${FLIPPER_VERSION}"
  debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}")
  debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
``` 

So `com.facebook.flipper:flipper` is no longer debugImplementation, and `com.facebook.flipper:flipper-noop` is removed entirely.

I'm wondering if its safe to release something like this? Are there performance considerations of including flipper instead of flipper-noop in my release or will the impact purely be my APK being a little bigger than it needs to be?

## Environment

```
ld@monster:~$ uname -a
Linux monster 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I've repro'd this with versions of flipper from 0.44 up to the latest.

Thanks!

**Comment by bizzguy** [comment]
I'm not seeing this problem in my app.  My release builds only include flipper-noop and don't have a compile problem.  I'm using 0.46.0 as well.  I suspect it is something in your gradle setup and not a problem with Flipper.

**Comment by bizzguy** [comment]
@Stonelinks Just wondering if you've had any success is solving the library problem?

**Comment by passy** [comment]
There's already been feedback on this here, but to restate this, the conflicts are *intended*. You must not mix no-op and "op" versions of the app. If you have an overlap here, there's something wrong with the dependency configuration and you need to debug where the release dependency gets pulled in again.

**Comment by niall8z** [comment]
It seems you only ever pass off any issues without offering a reasonable solution on every issue raised? We have multiple build variants, for dev staging and our production variants however we still run into this conflict. We are really struggling to understand what other way there is to configure a project in order to use Flipper?

**Comment by passy** [comment]
@niall8z I'm sorry you're having troubles with the integration. The reason why I can't offer a generic solution is because there is no generic build setup everyone follows. Our needs are different from yours and yours are different from the majority of other Flipper users. We have our sample apps to provide some best practices around debug and release splitting. Ultimately, as your integrations get deeper you will likely have to write your own production facades which is sadly just a reality of writing Java applications.

**Comment by niall8z** [comment]
@passy - which we have done, implementing an "initialiser" containing all Flipper-related dependencies for our dev or staging flavours, which is left completely empty for production or release. If that is the case, and these things are empty for release versions (which also configured for no-op) how can it be that we run into duplicate class issues?
