### ISSUE TITLE
Discussion: Network Plugin Request/Response Select and copy

### ISSUE THREAD

**Issue by karthikeyan1241997** [facebook/flipper#1242]
I am using flipper in windows to debug my android application. NetworkPlugin is very useful for me to intercept request/response body.

But I am unable to select and copy texts in the request/response body. 
It would be great to use flipper network plugin with this feature

**Comment by mweststrate** [comment]
@karthikeyan1241997 IIRC it should be possible to get both by using the right click 'copy row' action.

**Comment by karthikeyan1241997** [comment]
Got it. Instead of selecting in the viewer, we can right click the network entry and select copy row. Thanks @mweststrate
