### ISSUE TITLE
Docs: Unclear which build.gradle to add flipper dependencies to

### ISSUE THREAD

**Issue by joe-goodall-ticketmaster** [facebook/flipper#1243]
in the [Dependencies](https://fbflipper.com/docs/getting-started/react-native-android) section of the docs, when it is suggested to add dependencies to the `build.gradle` it is unclear whether it is to the `app/build.gradle` or the `android/build.gradle`.

Usually, dependencies get added to the `app/build.gradle` and in a newly created React Native project that's where the flipper dependencies are, but in the docs jcenter() is referenced which suggests they should be in `android/build.gradle`?

**Comment by nikoant** [comment]
@passy could you take a look please?

**Comment by passy** [comment]
@joe-goodall-ticketmaster Which part of the docs are you referring to? The generic Android instructions or RN specific ones? You usually set up the repositories in the project-wide config and the dependencies more narrowly where they are needed, i.e. the app.

**Comment by joe-goodall-ticketmaster** [comment]
@passy [This](https://fbflipper.com/docs/getting-started/react-native-android) part of the docs (the RN specific ones).

In a newly created RN project the flipper dependencies are in the `android/app/build.gradle`

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+" 
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
```

jcenter() is referenced in the docs which seems to imply you add the flipper dependencies to the `android/build.gradle`.

**Comment by passy** [comment]
@joe-goodall-ticketmaster There are no hard and fast rules about where to specify your repositories. You can do this on a global level or per-app.

**Comment by joe-goodall-ticketmaster** [comment]
OK, thanks @passy
