### ISSUE TITLE
flipper-plugin-sections disabled

### ISSUE THREAD

**Issue by JanithaR** [facebook/flipper#1249]
## 🐛 Bug Report
I'm trying to use `flipper-plugin-rn-redux-inspector` to view Redux actions but it never appears in the UI as it should https://github.com/zrg-team/flipper-rn-redux-inspector-plugin

## To Reproduce
Install Flipper 0.46.0.
Install `flipper-plugin-rn-redux-inspector`

This is what my plugins section looks like;
https://imgur.com/a/E9WSDfP
I think `flipper-plugin-sections` being disabled is the problem. But how do I enable it or correct what ever that is going wrong?

**Comment by joe-goodall-ticketmaster** [comment]
Have you installed `react-native-flipper`?

**Comment by JanithaR** [comment]
> Have you installed `react-native-flipper` (as per [these](https://github.com/zrg-team/flipper-rn-redux-inspector-plugin#1-install-flipper-redux-middleware-to-your-application) instructions)?

Of course. This works on both of my colleagues' MACs and only not on mine. The difference is that `flipper-plugin-sections` is disabled on mine and not on theirs.

**Comment by jknoxville** [comment]
flipper-plugin-sections is a completely separate plugin, it won't be related to why flipper-plugin-rn-redux-inspector isn't showing up.

According to that screenshot, flipper-plugin-rn-redux-inspector isn't supported by "YAS". This "Supported By" column shows which apps have added which plugins, so the most likely explanation for this is that the plugin hasn't been added to the flipper client in that app. I suggest putting a breakpoint in the code where you add the plugin and seeing why it's not being called, or if it is, what is failing.

**Comment by JanithaR** [comment]
> I suggest putting a breakpoint in the code where you add the plugin and seeing why it's not being called

Do you mean when configuring the store?

**Comment by mweststrate** [comment]
If the difference is between your and your collegues machine, it is not likely that we can be of much assistance. Make sure to check the obvious things, same Flipper version, running a dev mode on emulator, clearing android / ios caches and rebuilding, etc.
