### ISSUE TITLE
Idb flipper error for real device iOS testing

### ISSUE THREAD

**Issue by dayze** [facebook/flipper#1250]
## 🐛 Bug Report
When I want to debug my real iOS device, I got this message

![image](https://user-images.githubusercontent.com/11976270/84505018-48e53a00-acbd-11ea-90b3-94d2522556de.png)

## To Reproduce
```
brew tap facebook/fb
brew install idb-companion
sudo pip3 install fb-idb
```

``which idb`` return ``/usr/local/bin/idb``

![image](https://user-images.githubusercontent.com/11976270/84505253-b4c7a280-acbd-11ea-8745-404210d37312.png)

Finally ``idb list-targets`` find my device

![image](https://user-images.githubusercontent.com/11976270/84505576-41726080-acbe-11ea-914c-fcd782f09aed.png)

## Environment
Mac OS 10.15.4
Flipper 0.46.0
iPhone 11 pro 13.3.1 
React-native 0.62.2

**Comment by tientruongvan1995** [comment]
I cannot use it for real device too, ip6s+

**Comment by jknoxville** [comment]
Please bear with us, we're still ironing out some issues with physical iOS device support at the moment, in particular, today's release contains one fix, and there's another fix in idb on the way that should help.

**Comment by nubpro** [comment]
@jknoxville Quick one, is this fixed yet?
Last time I tried, it's still giving this error and I had to rollback to the older Flipper version which is 0.45.

**Comment by hsavit1** [comment]
any updates on this?

**Comment by teseo** [comment]
Any update on this?

**Comment by gregoryfm** [comment]
I'm facing the same issue, searching I've found that on iOS, only simulators are supported though.

https://fbflipper.com/docs/troubleshooting/#known-incompatibilities

`Physical iOS devices. Currently on iOS, only simulators are supported` ([Tracking Issue](https://github.com/facebook/flipper/issues/262)).

**Comment by nishigandhabhosale** [comment]
I am facing a crash on device but not on simulator,  after couple of seconds when app is executed , following are my crash details:

<img width="766" alt="Crash_ConsoleLogs" src="https://user-images.githubusercontent.com/61224511/101357983-3f313d80-38c0-11eb-9f4e-38da0f60585b.png">


<img width="1516" alt="Crash_location" src="https://user-images.githubusercontent.com/61224511/101358009-45bfb500-38c0-11eb-873f-e2132a950b6d.png">


**Following are my Environment Details:**
1.MAC 10.15.6 (19G73)
2.Device iPhone 8 iOS 13.6
3. React Native Version 0.63.5

**Comment by sypl** [comment]
Same issue. Last comment was two months ago? Any progress on this? A react-native debugger that can't be used on a physical device is not great.

**Comment by hsavit1** [comment]
what is the status of this?

**Comment by mweststrate** [comment]
The info here is outdated, we do support physical iOS devices. I'll go over
the docs and update them somewhere in the coming days.

**Comment by mweststrate** [comment]
Physical ios devices are currently supported if
1. you have installed idb https://fbidb.io/docs/installation
2. the app you have installed is build and installed from source.

Currently device logs aren't supported yet, but we hope to address in the upcoming release.

**Comment by kleavjames** [comment]
followed all the instructions in the docs, device is connected to the flipper, but the app is not selected.

**Comment by FFFang** [comment]
still can not connect

**Comment by mweststrate** [comment]
Hi folks, adding more comments here only adds noise and message like "doesn't work" are completely inactionable for us. I just verified that https://github.com/facebook/flipper/tree/master/react-native/ReactNativeFlipperExample works out of the box, which is the case, so for more issues please file a fresh issue, including device & flipper logs, screenshots and the steps you took. Always make sure you are running a debug build as documented here: https://reactnative.dev/docs/running-on-device
