### ISSUE TITLE
Discussion: Horizontal scroll to view logs

### ISSUE THREAD

**Issue by joe-goodall-ticketmaster** [facebook/flipper#1251]
Is the only way to view logs by scrolling horizontally?

![Screen Recording 2020-06-12 at 17 04 03](https://user-images.githubusercontent.com/65718433/84522872-4b508f80-accf-11ea-966f-ac49df9ec823.gif)

**Comment by bizzguy** [comment]
Short answer: yes.  You could also right click on the item and copy it,  then you could paste it into a text editor to see the entire message, but you would be leaving Flipper for that and would only be working with one line at a time.

Thanks for including the screen video.  It really helped make you question very clear.

**Comment by bizzguy** [comment]
I think this issue could be closed.

**Comment by marqroldan** [comment]
Can I ask why this isn't wrapped?

**Comment by bizzguy** [comment]
There is a trade-off between seeing more lines of output (no wrap) and seeing the full details of a single line (wrapped).  Android Studio "solves" this by providing a control to toggle between the two modes:

![Logcat Tool in Android Studio](https://user-images.githubusercontent.com/337874/85413846-f7487500-b530-11ea-9337-e11223ae4592.png)

Logcat also provides a few other controls not available in Flipper (see doc):

https://developer.android.com/studio/debug/am-logcat?utm_source=android-studio

A case could be made that Flipper should at least provide the as much functionality as Logcat.

**Comment by joe-goodall-ticketmaster** [comment]
IMO, the ideal would be the option to toggle wrap.

I get you can copy the line and open it in a text editor but it would be good to keep it in Flipper.

**Comment by bizzguy** [comment]
What about an additional row of controls (starting with the Wrap/NoWrap toggle):
![image](https://user-images.githubusercontent.com/337874/85416865-94f17380-b534-11ea-8039-ec9c752ac97d.png)

**Comment by AndrewMorsillo** [comment]
Agreed an option to toggle wrap would be great. Flipper is pretty useless for viewing logs right now if your use case requires you to log longer lines. Copying single lines into a separate text editor isn't really an effective solution in most cases. It seems odd to me that the log viewer plugin has advanced functionality like the expression watcher (which is awesome) but is missing the most basic functionality of line wrap.

**Comment by mweststrate** [comment]
I am going to make some changes to the device logs soon, so will look into this one as well.

**Comment by mweststrate** [comment]
Flipper 0.81 uses dynamic line wrapping in logs plugin. So, implemented!

![Screenshot 2021-03-17 at 12 06 21](https://user-images.githubusercontent.com/1820292/111475977-8f246980-8725-11eb-84cd-85aa55b6c35e.png)
