### ISSUE TITLE
Plugins not enabled in iOS simulator

### ISSUE THREAD

**Issue by casconed** [facebook/flipper#1252]
## 🐛 Bug Report
After upgrading to 0.46.0, the Flipper plugins no longer are able to be enabled.
![Flipper_and_New_Issue_·_facebook_flipper](https://user-images.githubusercontent.com/102230/84549159-29014680-acbc-11ea-82d4-61ef7c2f630c.png)

## To Reproduce
Launch Flipper, Launch iOS app in simulator, try to enable plugins.

## Environment
iOS 13.5
Simulator 11.5
React Native 0.62.1
Flipper 0.46.0

Plugins installed and supported:
![Flipper](https://user-images.githubusercontent.com/102230/84549330-96ad7280-acbc-11ea-8a1f-162a2309f436.png)

**Comment by mweststrate** [comment]
@casconed  would you mind opening view > developer tools and report on any errors that are logged there in the console?

**Comment by casconed** [comment]
Oh good call. We recently renamed our app with a `#` in front of it. Seems like Flipper is choking on that: I see a bunch of messages for:
`clientUtils.tsx:80 Attempted to deconstruct invalid clientId: "#appname#iOS#iPhone Simulator#129D393B-BB22-4FAD-8AF3-9AD3F279D334"`

**Comment by casconed** [comment]
quick and dirty local test stripping that character when constructing that client ID doesn't break anything, but the plugins still don't work

**Comment by casconed** [comment]
Changing the clientd encoding/decoding to use JSON.stringify/parse seems to fix, but getting tests to work for that change is another issue - the `#` separator seems pretty deeply wired. Working on a PR now...

**Comment by mweststrate** [comment]
@casconed PR welcome! But be warned that the rabbit might go quite deep😅. Are you sure you need that hash there? I can imagine this will will go awry in random other places of the  RN stack (but maybe it doesn't at all).

**Comment by casconed** [comment]
Well, we are in the app store so hopefully it's not going TOO awry! 

Worth noting that app names can use any ASCII char so string separators are probably doomed to fail, in this scenario.

**Comment by mweststrate** [comment]
😆. Some escaping of special characters might be enough.
