### ISSUE TITLE
Question: idb companion not showing after brew install

### ISSUE THREAD

**Issue by hsavit1** [facebook/flipper#1271]
on macOS catalina, a bug shows saying

```
IDB is required to use Flipper with iOS devices. It can be installed from https://github.com/facebook/idb and configured in Flipper settings. You can also disable physical iOS device support in settings. Current setting: /usr/local/bin/idb-companion isn't a valid IDB installation.
```

even though I installed via the brew instructions

```
brew tap facebook/fb
brew install idb-companion
```

**Comment by jknoxville** [comment]
You need to point flipper to your fb-idb installation, not your idb-companion installation.

This one: https://github.com/facebook/idb#idb-client

**Comment by hsavit1** [comment]
Gotcha, thanks @jknoxville . Installing via pip seemed to help

I am having a tough time linking to flipper. My idb-installation seems to live at `~/usr/local/Cellar/idb-companion`

After sticking that path + the 1.0.14 extention into my Flipper settings, it still reads 

```Current setting: ~/usr/local/Cellar/idb-companion/1.0.14 isn't a valid IDB installation```

I've tried with and without the 1.0.14

**Comment by Cordobo** [comment]
If you have to install the idb-client via pip3 and the `--user` flag like `pip3  install --user fb-idb`, the IDB binary location is as follows:

`/Users/<your_username>/Library/Python/<python_version>/bin/idb`

`/Users/johndoe/Library/Python/3.8/bin/idb`

**Comment by a-eid** [comment]
just do `which idb` and you should find out where it's installed.

**Comment by sLurPPPeRsTaR** [comment]
> If you have to install the idb-client via pip3 and the `--user` flag like `pip3 install --user fb-idb`, the IDB binary location is as follows:
> 
> `/Users/<your_username>/Library/Python/<python_version>/bin/idb`
> 
> `/Users/johndoe/Library/Python/3.8/bin/idb`

you save me =)
