### ISSUE TITLE
React Native client_log messages in a better format ?

### ISSUE THREAD

**Issue by smartcris** [facebook/flipper#1273]
I'm using the desktop Windows version to debug react-native and correct me if I'm wrong but looks like each _client_log_ with blue info circle (generated from console.log();) is readable only in a single line. On developer tools instead for example objects  are grouped and expandable etc, I think this could improve the dev experience.

**Comment by mweststrate** [comment]
Multilines should work (for me they do at least), for expandable objects, see #950

**Comment by mweststrate** [comment]
Closing as duplicate of #950 / #1010
