### ISSUE TITLE
Flipper libraries get included in release builds on Android projects using react-native-flipper

### ISSUE THREAD

**Issue by TPXP** [facebook/flipper#1274]
## 🐛 Bug Report
When adding `react-native-flipper` (required by the [redux plugin](https://www.npmjs.com/package/redux-flipper) for example) to a project, Android release builds get bloated with Flipper binaries.

Impact: bundle size significantly increased (+3MB download, +6MB install size)

## To Reproduce
```sh
npx react-native init MyApp
cd MyApp
yarn add react-native-flipper
cd android
./gradlew bundleRelease # assembleRelease will also work (but you get an APK instead)
```

For example, `libflipper.so` is included (it also comes with unneeded `libevent`):
```sh
$ cd app/build/outputs/bundle/release
$ unzip app-release.aab
$ find . | grep flipper
./base/lib/armeabi-v7a/libflipper.so
./base/lib/x86/libflipper.so
./base/lib/arm64-v8a/libflipper.so
./base/lib/x86_64/libflipper.so
```

## Environment
React-Native 0.62.2
Android app
Looks ok on iOS (same bundle sizes with or without `react-native-flipper` - at least when using 0.47.0)

**Comment by passy** [comment]
Oh, that's interesting. Agreed that it definitely shouldn't be included in release builds. Do you know how this is handled for other debug-only dependencies with native components? I'm not sure how we would declare this as part of the `react-native-flipper` package.

**Comment by TPXP** [comment]
Well, to be honest that's the only debug dependency I have in my project, so I can't really help on this point. Do you know of any other debugging tools for react native?

**Comment by FDiskas** [comment]
Should be reopened

**Comment by mweststrate** [comment]
@FDiskas given #1325, preferably give some details / reproduction on why it should be reopened. Your comment as it stands is inactionable.
