### ISSUE TITLE
Screenshot returns a Broken Image

### ISSUE THREAD

**Issue by b3coded** [facebook/flipper#1276]
## 🐛 Bug Report
I'm trying to take a Screenshot inside Flipper but the saved file is broken.

## To Reproduce
- Run application
- Open Flipper
- Press TakeScreenshot button
- Save the broken file (Expected a valid image)
![Captura de tela de 2020-06-18 11-24-21](https://user-images.githubusercontent.com/38642628/85032523-52a3ed00-b156-11ea-8ec7-fa7352285cc1.png)

![Captura de tela de 2020-06-18 11-24-31](https://user-images.githubusercontent.com/38642628/85032516-50da2980-b156-11ea-8c15-d2613b9529fc.png)

## Environment

Android device: Moto G7 Play | Android 9.0
Flipper version: 0.47

Additional environment info (by envinfo library)
```
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 522.36 MB / 11.58 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Managers:
    Apt: 2.0.2 - /usr/bin/apt
    pip2: 20.1 - ~/.local/bin/pip2
    pip3: 20.0.2 - /home/linuxbrew/.linuxbrew/bin/pip3
  Utilities:
    CMake: 3.16.3 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.3.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Virtualization:
    Docker: 19.03.8 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3, 30.0.0
      System Images: android-23 | Google APIs Intel x86 Atom
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.46.0 - /snap/bin/code
  Languages:
    Bash: 5.0.16 - /usr/bin/bash
    Java: 1.8.0_252 - /usr/bin/javac
    Perl: 5.30.0 - /usr/bin/perl
    Python3: 3.7.7 - /home/linuxbrew/.linuxbrew/bin/python3
  Databases:
    SQLite: 3.31.1 - /home/linuxbrew/.linuxbrew/bin/sqlite3
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 77.0.1


```

**Comment by passy** [comment]
Could you attach an example of the file that is captured for you, please?

**Comment by b3coded** [comment]
@passy I can't , Github says The File is empty

**Comment by b3coded** [comment]
Ubuntu recognize as a Text file

**Comment by passy** [comment]
I don't have a way to try and reproduce this right now. This is probably something specific to Linux. If anyone wants to investigate this, please comment.

**Comment by b3coded** [comment]
@passy I tried with Windows but this bug persists

**Comment by passy** [comment]
> @passy I tried with Windows but this bug persists

Could you share which Android device you see this on?

**Comment by b3coded** [comment]
@passy  Moto G7 Play on Android 9.0

**Comment by mohamedsgap** [comment]
@passy Can i take this one ?

**Comment by b3coded** [comment]
Closing issue, I'm running Flipper Desktop v0.54 and Screenshots works now
