### ISSUE TITLE
Question: How to remove imported device

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#1278]
When I import `FlipperExport.flipper`, I can't find a option to remove imported device. 
Am I missing something obvious to click on? 😄 

<img width="251" alt="image" src="https://user-images.githubusercontent.com/5339061/85096989-a1ba5280-b228-11ea-95e1-c4eba7054879.png">

**Comment by passy** [comment]
I don't think there's an option for this? cc @priteshrnandgaonkar

**Comment by priteshrnandgaonkar** [comment]
No you can't remove. There is no such option yet.

**Comment by FreTimmerman** [comment]
please reopen. this is still not implemented
