### ISSUE TITLE
Client setup error: A problem with idb has ocurred.

### ISSUE THREAD

**Issue by zameerascentic** [facebook/flipper#1279]
## 🐛 Bug Report
Getting this error 'Client setup error: A problem with idb has ocurred. Please run `sudo rm -rf /tmp/idb*` and `sudo yum install -y fb-idb` to update it, if that doesn't fix it, post in Flipper Support.' I had installed the IDB correctly in the /usr/local/bin/idb and there was no issue there.
![Screenshot 2020-06-19 at 10 10 41](https://user-images.githubusercontent.com/31923811/85097501-59456980-b215-11ea-8154-477ab348197c.png)

## To Reproduce
Install IDB with Flipper 0.46.0
Run the App with  Xcode
Run Flipper

## Environment
  iOS 13 Device
  Flipper Desktop 0.46.0

**Comment by dayze** [comment]
https://github.com/facebook/flipper/issues/1250

**Comment by passy** [comment]
Closing in favour of #1250.
