### ISSUE TITLE
Question: LayoutInspector not showing Fragments in app

### ISSUE THREAD

**Issue by laurenyew-nytimes** [facebook/flipper#1290]
Hi, I'm having issues seeing Fragments in the Layout Inspector.
I have Flipper setup in my project with
```
AndroidFlipperClient.getInstance(app).apply {
                addPlugin(InspectorFlipperPlugin(app, DescriptorMapping.withDefaults()))
                addPlugin(SharedPreferencesFlipperPlugin(app))
                addPlugin(DatabasesFlipperPlugin(app))
                start()
            }
```
Looks like DescriptorMapping.withDefaults() should add the Fragments to the Descriptor mapping, but I'm not seeing any Fragments in my Layout inspector for Flipper. Is there more setup required or is this a bug?

**Comment by laurenyew-nytimes** [comment]
We are using androidx fragments. Still not seeing them show up in Flipper.

**Comment by passy** [comment]
So that should work in theory with your setup:

https://github.com/facebook/flipper/blob/54ebb44ddab24a0b157701d7c69af469fd5c4769/android/src/main/java/com/facebook/flipper/plugins/inspector/DescriptorMapping.java#L57

Just to be certain, are you on a recent version of the Flipper SDK? The AndroidX support was added earlier this year.

**Comment by laurenyew-nytimes** [comment]
We are on the latest 0.48.0. Still not seeing any Fragments. I confirmed our DescriptorMapping does include the register code you included above.
For example, in opening two parts of the app where I would expect to see fragments, I still see
<img width="513" alt="Screen Shot 2020-06-26 at 10 02 03 AM" src="https://user-images.githubusercontent.com/65074214/85871674-5ce86b80-b794-11ea-806b-891d23f5545f.png">

**Comment by passy** [comment]
@laurenyew-nytimes Do you know if this ever worked, so if this could be a regression or never worked to begin with?

**Comment by laurenyew-nytimes** [comment]
As far as I'm aware, it never worked in our configuration.

**Comment by passy** [comment]
@laurenyew-nytimes I tried to repro this in our sample app here: https://github.com/facebook/flipper/pull/1328

For me everything appears to be working. Could you maybe take a look and check how this differs from your setup?

**Comment by laurenyew-nytimes** [comment]
Noticed you have
<intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="flipper" android:host="fragment_test_activity" />
      </intent-filter>
on your activity in question. Is that required to make the fragment viewable on Flipper?

**Comment by passy** [comment]
@laurenyew-nytimes No, that should have nothing to do with it. That's just to expose a URL so you can open activities in the sample up directly through our navigation plugin.

**Comment by laurenyew-nytimes** [comment]
Confirmed we are getting the Fragments listed, they're just further down in the layout list than expected. Is there a way to hide the View layout parts in Flipper so I can just see Activities / Fragments?
