### ISSUE TITLE
Question: Android-only error, "The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed"

### ISSUE THREAD

**Issue by TheAlmightyBob** [facebook/flipper#1293]
(spun off of https://github.com/facebook/flipper/issues/1253#issuecomment-648553697, as requested by @mweststrate )

When trying to install any Flipper plugin on Android, I get this error running a debug build:
> The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed

The basic Flipper functionality seems to be working on Android without plugins, and the plugins work fine on iOS.
I've gone through the troubleshooting and other documentation but I have not found any mention of this error, except in the case of iOS pods which of course does not apply.

I attempted to use the diagnostic command here: https://fbflipper.com/docs/troubleshooting/#android

But it crashes with this error (thanks to the Flipper Crash Reporter, which at least still works):
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myApp/com.facebook.flipper.android.diagnostics.FlipperDiagnosticActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.flipper.core.FlipperClient.subscribeForUpdates(com.facebook.flipper.core.FlipperStateUpdateListener)' on a null object reference

I've triple-checked the Android configuration after upgrading to RN62 and verified that `FlipperPackage` is included in the generated `PackageList`.

Snippet from `package.json`:
> "react-native": "0.62.2",
"react-native-flipper": "^0.47.0",

Things that are working:
![image](https://user-images.githubusercontent.com/7707864/85646493-13433800-b651-11ea-9048-432e16179698.png)

Snippet from `android/app/build.gradle`:
```
debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.fbjni'
}
debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.flipper'
}
debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.flipper'
}
```

**Comment by mweststrate** [comment]
cc @Epick362

**Comment by mweststrate** [comment]
@TheAlmightyBob thanks! That is a great find! If this is experienced as well I'll add it to the troubleshooting guide

**Comment by rarenatoe** [comment]
Can confirm that @TheAlmightyBob's answer saved my life
