### ISSUE TITLE
Docs: Links break due to trailing slash

### ISSUE THREAD

**Issue by sonicdoe** [facebook/flipper#1298]
For example, the “See setup instructions for React Native” link on [React Native Support](https://fbflipper.com/docs/features/react-native/) works on `/docs/features/react-native` (without a trailing slash) but does not work on `/docs/features/react-native/` (with a trailing slash).

When opening the page through the sidebar, no trailing slash is added. However, when directly navigating to the URL, the server responds with a permanent redirect, adding a trailing slash.

See also https://github.com/facebook/docusaurus/issues/2394.

**Comment by passy** [comment]
Thanks, I tried to go through all relative links and tried to absolute-ify them. Please let me know if you find another one!

**Comment by sonicdoe** [comment]
Thank you 👍 For future reference, this is the commit: https://github.com/facebook/flipper/commit/b2e8070af2410c8c18666899c50d9b0606d68610.
