### ISSUE TITLE
Discussion: Add NetworkRequestFormatter interface 

### ISSUE THREAD

**Issue by aartcm** [facebook/flipper#1307]
Hello!

I wanted to check if a PR would be welcome that introduces a new `NetworkRequestFormatter` interface that is analogous to the already existing `NetworkResponseFormatter` (https://github.com/facebook/flipper/blob/master/android/plugins/network/src/main/java/com/facebook/flipper/plugins/network/NetworkResponseFormatter.java) and used in the same way but to format request bodies instead of response bodies (https://github.com/facebook/flipper/blob/master/android/plugins/network/src/main/java/com/facebook/flipper/plugins/network/NetworkFlipperPlugin.java).

Background: I've noticed that the Flipper client does not seem to display request/response bodies that are not in a JSON format. To fix this you can use a custom NetworkResponseFormatter to format the response body as JSON and it will be displayed. Unfortunately this same method cannot be used for request bodies as the same formatter pattern is not available there. I would like to contribute a PR that introduces the same formatter mechanism for request bodies as already exists for response bodies.

**Comment by mweststrate** [comment]
Sounds good to me. cc @passy do you foresee any problems with such approach?

**Comment by aartcm** [comment]
Cool! I will be on vacation for the next few weeks but will try to add this when I get back!

**Comment by mweststrate** [comment]
@aartcm did you still intend to look into this? In that case let us know and I'll reopen the issue. Thanks!
