### ISSUE TITLE
Question: show dev menu button doesn't work for iOS

### ISSUE THREAD

**Issue by RedMickey** [facebook/flipper#1309]
Hello, I tried to use the `Show dev menu` button on debugging an iOS app and it seems that it doesn't work correctly.
On the Flipper toolbar there are 2 buttons to show dev menu and reload the application. They work correctly in case of debugging Android applications. But when I try to debug an iOS app only the `Reload` button works. Nothing happens when I click on the `Show dev menu` button. 
It could be that I did something wrong and should have done some additional configurations:
- Ran an iOS app using `npx react-native run-ios`
- Clicked on the `Show dev menu` button

As I understand there could be some problems with handling of the `devMenu` command on the Metro packager side, because the command is sent successfully via events socket. Could you please tell if that is an expected behavior and why this command doesn't work on iOS the same way as on Android?

**Comment by mweststrate** [comment]
It just tried and noticed the same. But triggering it from the terminal (by pressing 'd' in the terminal that runs metro) doesn't seem to open it either for me. Is that the same in your case?

**Comment by RedMickey** [comment]
@mweststrate, I tried to open dev menu from the terminal by pressing "d" and faced the same proplem - dev menu isn't opened. It seems that there could be some issues with React Native CLI or Metro packager in this case. Maybe we should open an issue about this problem in the [react-native-community/cli](https://github.com/react-native-community/cli) repository?

**Comment by mweststrate** [comment]
@RedMickey yes, in that case I suspect it is an issue in RN ios itself and I think the issue can be raised on the react-native repository.

**Comment by RedMickey** [comment]
@mweststrate, I opened [the corresponding issue](https://github.com/react-native-community/cli/issues/1213) in RN CLI repository.

**Comment by mweststrate** [comment]
Closing the issue here for now, since there is at this point nothing we can do from our side
