### ISSUE TITLE
Error installing Flipper

### ISSUE THREAD

**Issue by xgqfrms** [facebook/flipper#1321]
## 🐛 Bug Report

> Error installing Flipper

https://github.com/facebook/Sonar

https://github.com/facebook/flipper

## To Reproduce

1. create app using npx `npx react-native init RN_APP`

2. manually install cocoa pod `cd ./RN_APP/ios && pod install`

```sh
$ cd ./RN_APP/ios && pod install

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.62.2)
Installing FBReactNativeSpec (0.62.2)
Installing Flipper (0.33.1)

[!] Error installing Flipper
[!] /usr/bin/git clone https://github.com/facebook/Sonar.git /var/folders/qm/csrtpvpn62x82v4zykvsrnw80000gn/T/d20200630-26546-1ylsi42 --template= --single-branch --depth 1 --branch v0.33.1

Cloning into '/var/folders/qm/csrtpvpn62x82v4zykvsrnw80000gn/T/d20200630-26546-1ylsi42'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

```

## Environment

```sh
# react-native info
$ npx react-native info

info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 254.59 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

***

https://github.com/facebook/react-native/issues/29251

**Comment by xgqfrms** [comment]
```sh
$ pod install
```

![](https://user-images.githubusercontent.com/7291672/86123502-32880c80-bb0c-11ea-80c3-043901031d02.png)

**Comment by xgqfrms** [comment]
```sh
$ pod install --verbose
```

https://github.com/facebook/react-native/issues/29251

> stop, after installing here

![image](https://user-images.githubusercontent.com/7291672/86138970-bdbfcd00-bb21-11ea-91cb-5c9874777803.png)

**Comment by cekkaewnumchai** [comment]
I can't reproduce this. It seems to redirect to correct git for me. Would you mind take a look @priteshrnandgaonkar?

One this to note is Flipper version is too old now. Could you try changing it to `0.49.0` and try `pod install --repo-update` to see if it solves the problem?

**Comment by cekkaewnumchai** [comment]
This might help https://github.com/CocoaPods/CocoaPods/issues/9564

**Comment by xgqfrms** [comment]
@cekkaewnumchai Anyway, thanks a lot!

I don't know why, but it's OK now.
After I installed `expo-cli`. 
Maybe it's my networks problem, who knows.


https://github.com/xgqfrms/React-Native-Tutorials/issues/16

**Comment by leoyb** [comment]
@xgqfrms I have the same problem with you，do you know how to solve it?

`Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.1)
Installing FBReactNativeSpec (0.63.1)
Installing Flipper (0.41.5)

[!] Error installing Flipper
[!] /usr/bin/git clone https://github.com/facebook/Sonar.git /var/folders/g4/drnv501d1mq8qfv478_355940000gn/T/d20200722-15820-9tf26p --template= --single-branch --depth 1 --branch v0.41.0

Cloning into '/var/folders/g4/drnv501d1mq8qfv478_355940000gn/T/d20200722-15820-9tf26p'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed`

**Comment by showtan001** [comment]
> @xgqfrms I have the same problem with you，do you know how to solve it?
> 
> `Analyzing dependencies Fetching podspec for `DoubleConversion`from`../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`Fetching podspec for`Folly`from`../node_modules/react-native/third-party-podspecs/Folly.podspec`Fetching podspec for`glog`from`../node_modules/react-native/third-party-podspecs/glog.podspec`
> Downloading dependencies
> Installing CocoaAsyncSocket (7.6.4)
> Installing CocoaLibEvent (1.0.0)
> Installing DoubleConversion (1.1.6)
> Installing FBLazyVector (0.63.1)
> Installing FBReactNativeSpec (0.63.1)
> Installing Flipper (0.41.5)
> 
> [!] Error installing Flipper
> [!] /usr/bin/git clone https://github.com/facebook/Sonar.git /var/folders/g4/drnv501d1mq8qfv478_355940000gn/T/d20200722-15820-9tf26p --template= --single-branch --depth 1 --branch v0.41.0
> 
> Cloning into '/var/folders/g4/drnv501d1mq8qfv478_355940000gn/T/d20200722-15820-9tf26p'...
> error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed`

There may be a network problem, try another network!

**Comment by Stephen-L-Wang** [comment]
> @xgqfrms I have the same problem with you，do you know how to solve it?
> 
> `Analyzing dependencies Fetching podspec for `DoubleConversion`from`../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`Fetching podspec for`Folly`from`../node_modules/react-native/third-party-podspecs/Folly.podspec`Fetching podspec for`glog`from`../node_modules/react-native/third-party-podspecs/glog.podspec`
> Downloading dependencies
> Installing CocoaAsyncSocket (7.6.4)
> Installing CocoaLibEvent (1.0.0)
> Installing DoubleConversion (1.1.6)
> Installing FBLazyVector (0.63.1)
> Installing FBReactNativeSpec (0.63.1)
> Installing Flipper (0.41.5)
> 
> [!] Error installing Flipper
> [!] /usr/bin/git clone https://github.com/facebook/Sonar.git /var/folders/g4/drnv501d1mq8qfv478_355940000gn/T/d20200722-15820-9tf26p --template= --single-branch --depth 1 --branch v0.41.0
> 
> Cloning into '/var/folders/g4/drnv501d1mq8qfv478_355940000gn/T/d20200722-15820-9tf26p'...
> error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed`

Hi  Did u solve the issue? I met the same problem.

**Comment by leoyb** [comment]
Is network problem, you need to install repeatedly and wait patiently

**Comment by mattdeann** [comment]
^sadly this seems to be the answer

**Comment by iansamz** [comment]
I changed to my mobile hotspot for the download.

**Comment by huangjihua** [comment]
I have same problem with you,do you konw how to solve it?

` vim
$: pod install 
Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.68.0)
Installing FBReactNativeSpec (0.68.0)
Installing Flipper (0.125.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.2.0)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.10)

[!] Error installing Flipper-Folly
[!] /usr/local/bin/git clone https://github.com/facebook/folly.git /var/folders/qq/s09t3v1d76ngfwl62bbgvbyr0000gq/T/d20220405-52321-ruopk0 --template= --single-branch --depth 1 --branch v2021.06.14.00

Cloning into '/var/folders/qq/s09t3v1d76ngfwl62bbgvbyr0000gq/T/d20220405-52321-ruopk0'...
fatal: unable to access 'https://github.com/facebook/folly.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
`

Env:

`
System:
    OS: macOS 12.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 3.38 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

**Comment by NazarWaliMuhammad7** [comment]
i simply run `pod cache clean --all` then run pod install i will be ok

**Comment by sangayt1997** [comment]
I have mostly face this issue when we had network issues

**Comment by kuldeep-IT** [comment]
> i simply run `pod cache clean --all` then run pod install it will be ok and problem will be solved

Thank you buddy! You saved my time.
