### ISSUE TITLE
No icon displayed on Ubuntu 20.04

### ISSUE THREAD

**Issue by vkotovv** [facebook/flipper#1369]
## 🐛 Bug Report
No icon displayed on my Ubuntu 20.04 panel.

## To Reproduce
- Download v0.49.0 for Linux
- Unzip and run
- No icon is displayed on the panel (see screenshot).

![flipper_no_icon](https://user-images.githubusercontent.com/1636249/87299374-8df6c900-c514-11ea-86d2-a6f969ce22f1.png)

## Environment
Flipper 0.49.0, Ubuntu 20.04 (updated from 18.04 LTS).
Previously I used older version of Flipper (0.28.0), then I've deleted the unzipped folder, downloaded a new release and run it.

**Comment by passy** [comment]
Hi @vkotovv, thanks for the report. Because of the ongoing lockdown, I don't have access to my Linux environment at the moment and can't repro this. Happy to look at any PRs that might resolve this, though.

**Comment by lmj0011** [comment]
as a workaround you should be able to edit that `.desktop` file and add the icon that way

see https://github.com/facebook/flipper/issues/1424

**Comment by mohamedsgap** [comment]
Hi @passy, I have fixed this issue on my own here #1424! Can I fill a PR to try to get done automatically when users install Flipper on Ubuntu ?
