### ISSUE TITLE
Suggestion: API Jar for implementing POJO plugins

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#137]
Ideally a plugin API Jar with central classes like BufferingSonarPlugin etc, for implementing plugin libraries without depending on the Android build infrastructure.

Sonar obviously makes sense to distribute as an AAR and with gradle android build configured.

But for developers of 3rd party libs e.g. Retrofit, OkHttp, RxJava, it would be simpler to have a low complexity option for building against.  Even without any firm Android dependencies.

**Comment by passy** [comment]
Hey everyone, I'm currently cleaning up some longstanding issues and enhancement proposals that have not seen any traction. Please feel free to comment if you still thing there is value in keeping this one on the backlog. :)
