### ISSUE TITLE
Bump LeakCanary to 2.x for AndroidX support

### ISSUE THREAD

**Issue by erikghonyan** [facebook/flipper#1379]
The LeakCanary Flipper Plugin v0.50.0 depends on LeakCanary v1.6.3, which uses support libraries. They've migrated to AndroidX in version 2.0. A workaround is to manually add a dependency on LeakCanary and it seems to work fine with v2.2

**Comment by passy** [comment]
If someone would like to work on a PR for bumping the dependency, I'd be happy to take a look!

**Comment by pyricau** [comment]
Side note:

> They've migrated to AndroidX in version 2.0.

Version 2.0 actually removed the dependency on the support library, and will work with both the support and tthe androidx library depending on what's in the classpath. Your general point still stands though.

**Comment by pyricau** [comment]
> You may also label this issue as a "Discussion" or add it to the "Backlog" and I will leave it open. Thank you for your contributions.

I don't think I can 🤔
