### ISSUE TITLE
[Feature Request] Add button to update Flipper

### ISSUE THREAD

**Issue by adamc01** [facebook/flipper#1393]
Hello,
Thanks for the team's continued work on Flipper.
Many versions ago I remember Flipper would prompt to auto-update (or maybe I clicked an update button somewhere).
Now in preferences/about/settings I don't see any option to update the app.
Can we make it so clicking on the version number prompts the user to update the app? (or put it in About)

Thanks,
Adam

**Comment by mweststrate** [comment]
cc @passy, with the new distribution mechanism I think we could even apply updates in-place?

**Comment by passy** [comment]
You should see a little indicator in the top right-hand corner if a newer version is available. There are a lot of moving parts in play for this. I'll check if something there broke.

**Comment by passy** [comment]
![Screenshot from 2020-07-22 13-44-24](https://user-images.githubusercontent.com/9906/88178437-4c57d380-cc22-11ea-95f7-d5801973f8d8.png)

Just checked and this is working as intended. Is there anything else you had in mind, @adambenami1?

**Comment by adamc01** [comment]
Confirmed the new version indicator shows up.
However clicking the link just opens your browser to manually download the new version.
I thought it used to auto-update (and I would have to restart the app)?

I tested an older version v0.28 and I saw it try to auto-update:
![image](https://user-images.githubusercontent.com/10903648/88235696-449f2b80-cc30-11ea-80e6-f16653de06a5.png)

**Comment by passy** [comment]
@adamc01 For ancient versions like that one we still had Squirrel integrated. However, that mechanism has so many odd restrictions and caused a massive inflow of support requests which is why we ended up disabling it. We also wanted to have a mechanism that works cross-platform which there also doesn't seem to be an off-the-shelf solution for. So far the time being this is probably going to stay like this, I'm afraid.

**Comment by passy** [comment]
> cc @passy, with the new distribution mechanism I think we could even apply updates in-place?

I suppose you mean the launcher? My hope is that this is something we could make use of in open source, too, but it's not on the roadmap right now.

**Comment by adamc01** [comment]
Thanks for the response, I'll use the indicator icon for now then.
