### ISSUE TITLE
Discussion: Allow to mock response status code in request mocking feature

### ISSUE THREAD

**Issue by gildor** [facebook/flipper#1423]
Existing request mocking feature doesn't support providing custom HTTP status code, it always returns 200, which is quite a big limitation, the testing HTTP statuses is one of the most important features of request mocking

**Comment by bizzguy** [comment]
I agree with the request to add return code.  Also, I would also like to see DELETE added as a type.  Mocking is really an AWESOME addition to the plugin!

**Comment by bizzguy** [comment]
One more thing.  If the user has selected (highlighted) a network request when the Mock button is clicked, it would be useful if the current highlighted request was populated in the data section.  Some of our requests are really long and this would save us time rather than having to copy and paste from the original request.

**Comment by bizzguy** [comment]
A few more things.  It appears that "export" does not export the mock definitions to the "FlipperExport.flipper" file.

Also, having a way to temporarily disable the mock without deleting the definition would be useful.

**Comment by bizzguy** [comment]
Just submitted a PR to allow for specifying status code on response.  Would be interested in feedback from anyone on this thread.  Thanks. 

https://github.com/facebook/flipper/pull/1441

**Comment by bizzguy** [comment]
The PR to fix this issue has been merged so this issue can now be closed.

**Comment by bizzguy** [comment]
This issue can be closed.  The functionality to add response status code to mocking was added in PR https://github.com/facebook/flipper/pull/1447
