### ISSUE TITLE
Question:  How to create Flipper shortcut on Ubuntu?

### ISSUE THREAD

**Issue by mohamedsgap** [facebook/flipper#1424]
I've just download Flipper, and I wonder if there is a way to create a shortcut for Flipper, to access it easily!

Ubuntu version: 20.04

**Comment by mohamedsgap** [comment]
![Screenshot from 2020-07-30 07-00-22](https://user-images.githubusercontent.com/30293804/88882541-803e8480-d232-11ea-826f-dfc4e39de1b9.png)

**Comment by lmj0011** [comment]
This is one way [to create a desktop shortcut on Ubuntu](https://askubuntu.com/a/854398)

**Comment by mohamedsgap** [comment]
Update: Solved 

`sudo nano /usr/share/applications/Flipper.desktop`

paste the following:
``
#!/usr/bin/env/ xdg-open
[Desktop Entry]`
Version=0.51
Type=Application
Terminal=false
Exec=/home/USERNAME/Downloads/Flipper-linux/flipper
Name=Flipper
Comment=Extensible mobile app debugger
Icon=/home/USERNAME/Downloads/Flipper-linux/resources/app/icon.png
``

make it executable
`sudo chmod +x  /usr/share/applications/Flipper.desktop`




![Screenshot from 2020-07-30 14-20-16](https://user-images.githubusercontent.com/30293804/88922088-ed243f80-d26f-11ea-9a4b-912f82d63331.png)

**Comment by vkotovv** [comment]
@mohamedsgap Your solution did not work for me.

Instead I've created `/usr/share/applications/Flipper.desktop` with this content, like @lmj0011 mentioned.

```
[Desktop Entry]
Name=Flipper
Comment=Extensible mobile app debugger
Exec=/home/user/path-to/Flipper-linux/flipper
Type=Application
Terminal=false
Icon=/home/user/path-to/Flipper-linux/resources/app/icon.png
NoDisplay=false
```

**Comment by mohamedsgap** [comment]
@vkotovv  it's actually the same, but my solution makes you be able to add it to Favorites

**Comment by Zakini** [comment]
That icon file doesn't exist in 0.73, but you can grab it from https://fbflipper.com/img/icon.png
