### ISSUE TITLE
SQL Table and Column names need to be string literals to prevent failed UPDATE statements

### ISSUE THREAD

**Issue by lmj0011** [facebook/flipper#1426]
## 🐛 Bug Report

Having a column name *order* will cause errors when editing row data in the Flipper desktop app

## To Reproduce

Create a table that has a column named *order* and then edit that field using the desktop app

![Screenshot from 2020-07-31 01-39-53](https://user-images.githubusercontent.com/9396189/89007661-c77a5300-d2ce-11ea-817b-5bb0a6ee6700.png)

it will produce a query similar to this `UPDATE labels_table SET order=0 WHERE id=4`, which will fail to execute

![Screenshot from 2020-07-31 01-41-50](https://user-images.githubusercontent.com/9396189/89007816-17f1b080-d2cf-11ea-9451-bf1911e7f94f.png)

No sure why this is happening or if it's a Flipper or sqlite issue, seems like the program is expecting the ORDER BY clause if *order* is not in quotes.

wrapping *order* in single quotes or grave accents and manually running `UPDATE labels_table SET 'order'=0 WHERE id=4` in the SQL query executor is currently the workaround.

## Environment

using:
Flipper Desktop 0.51.0
Android 0.51.0

**Comment by mweststrate** [comment]
Good catch! Yeah that sounds like an escaping issue. @lmj0011  in testing if adding quotes here around `${key}`: https://github.com/facebook/flipper/blob/master/desktop/plugins/databases/UpdateQueryUtil.tsx#L60-L64

solves the issue and submit a PR if that is the case? Cloning this repo and `yarn && yarn start` in the `desktop` folder should be enough to get started

**Comment by mweststrate** [comment]
Should be fixed in next release
