### ISSUE TITLE
Discussion: Persist the Network data to local storage in Network Plugin

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1443]
The network plugin records network requests for active apps.  However, the network data is not persisted if the app is closed (or crashes) or if Flipper is re-started.

I propose saving the network requests to local storage so they can be reloaded when the app plugin is restarted.

Why would this be useful?  I use the network plugin to test if my app handles the network requests properly.  Sometimes, for a new request (or a change in payload), my app will crash when processing the request.  As soon as the app crashes, the app specific plugins disappear and I can't tell which network request caused the problem.

If the requests were persisted, I would be able to see the problem request once the app was re-started.

I also propose that the "Clear Table" button on the Network plugin, would clear the requests and clear local storage.

**Comment by mweststrate** [comment]
Makes me wonder whether we shouldn't keep the app around after disconnecting, just like is done with entire devices if they disconnect🧐

**Comment by bizzguy** [comment]
This is pretty much the same issue as this: https://github.com/facebook/flipper/issues/812

**Comment by mweststrate** [comment]
This was implemented (in 0.81 from top of my head) so closing.

**Comment by bizzguy** [comment]
@mweststrate   I did verify that the calls stay around after a crash.  However, they do seem to disappear at some point.  But if I can confirm that I'll just create a new ticket.  The basic functionality does seem to be there.

**Comment by mweststrate** [comment]
They will disappear as soon as the app or device reconnects again
