### ISSUE TITLE
Mac Desktop is not able to connect with the android app. Though it's connected with the device. 

### ISSUE THREAD

**Issue by manmishr1** [facebook/flipper#1445]
## 🐛 Bug Report
Mac Desktop app is not able to connect with the android app. There is 3 error showing in desktop app console. (Attaching the screenshot for the reference).
I have tried to run the FlipperDiagnostic activity and it's also failing at **Check required certificates are present** (attaching the screenshot for the same)

## To Reproduce
NA

## Environment
Mac Desktop app
android 
<img width="561" alt="Screenshot 2020-08-07 at 1 21 32 PM" src="https://user-images.githubusercontent.com/62888024/89623537-67794300-d8b2-11ea-9ac9-8155cd3babe2.png">
![Screenshot_1596724294](https://user-images.githubusercontent.com/62888024/89623561-719b4180-d8b2-11ea-9f4b-2bea4e0b5a56.png)

**Comment by passy** [comment]
Something else seems to be running on your port 8089. Can you check with `lsof` what other process is taking up the port?

**Comment by manmishr1** [comment]
> lsof

**Comment by manmishr1** [comment]
Hi by mistake it was closed reopened again

**Comment by passy** [comment]
Can you try this?

```
lsof -nP -i4TCP:8089 | grep LISTEN
```

**Comment by manmishr1** [comment]
> Can you try this?
> 
> ```
> lsof -nP -i4TCP:8089 | grep LISTEN
> ```

Yes
lsof -nP -i4TCP:8089 | grep LISTEN
cirratod 5025 root    7u  IPv4 0xabdb0d767f684779      0t0  TCP 127.0.0.1:8089 (LISTEN)

**Comment by manmishr1** [comment]
I have killed all the processes running on port 8089, still, the desktop app is showing the same issue.

**Comment by manmishr1** [comment]
Hi Passy

I managed to fix the issue, so closing the ticket.

**Comment by spsaucier-bakkt** [comment]
@manmishr1 How did you fix the issue?
