### ISSUE TITLE
UserDefaults editor plugin for iOS?

### ISSUE THREAD

**Issue by noahsark769** [facebook/flipper#145]
A SharedPreferences editor for Android was just open sourced. Are there plans to extend it to work with iOS UserDefaults as well? Or would this be something the community could build?

**Comment by priteshrnandgaonkar** [comment]
There are no plans yet for iOS from us. But we would be happy to have a PR from open source community.

**Comment by hhtopcu** [comment]
I'm planning to work on it. I'll send a PR asap

**Comment by pkrmf** [comment]
@priteshrnandgaonkar I have an [PR open](https://github.com/facebook/flipper/pull/291) 

Want to add a few things to it, but feel free to start reviewing it.

**Comment by priteshrnandgaonkar** [comment]
Thanks for the PR, I will look into it.

**Comment by priteshrnandgaonkar** [comment]
We support it now, check the sample app
