### ISSUE TITLE
In Network Plugin headers in mock requests are not scrolling

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1460]
## 🐛 Bug Report

The Network plugin provides feature to create mock requests containing data and header values.  When multiple header values are entered, they display beyond the end of the enclosing view.  They should become scrollable instead.

Here is a screen shot showing the problem.  The headers extend beyond the end of the enclosing view.  And the "Close" button is also pushed outside the enclosing view.

![image](https://user-images.githubusercontent.com/337874/90058574-84918580-dca7-11ea-8385-446961df57fe.png)

## To Reproduce

Create a mock call and add multiple headers.  Keep adding headers until the header list extends beyond the end of the enclosing view.

## Environment

Flipper Desktop 9.0.2-dev

**Comment by bizzguy** [comment]
I tried fixing this myself.  I thought it would be easy.  The headers are shown in a "ManagedTable" element:

![image](https://user-images.githubusercontent.com/337874/90059838-69277a00-dca9-11ea-9ad6-cd63dabd6403.png)

According to the doc, ManagedTable elements can be made scrollable by just changing the "autoHeight" property:

![image](https://user-images.githubusercontent.com/337874/90059933-89efcf80-dca9-11ea-8045-4fc6c5641d94.png)

But changing the property actually caused all the headers to disappear.

I'd like to continue working on this but don't have much React experience (I'm an Android developer).  Would be interested in any guidance anyone might have.

**Comment by cekkaewnumchai** [comment]
Thank you very much for reporting both the layout of network mock and `ManagedTable`. We appreciate your help. 

@mweststrate might know more about React, but he's off for a week.

**Comment by bizzguy** [comment]
@mweststrate Some additional info:

It appears that the "AutoSizer" which is part of "ManagedTable" is not calculating the height correctly.  It is setting the height to 0 possibly because on of its containers (maybe "Tab") does not specify the height.  This SO issues seems to describe the problem:

    https://stackoverflow.com/questions/38340054/react-virtualized-autosizer-calculates-height-as-0-for-virtualscroll

**Comment by bizzguy** [comment]
This has been fixed with PR https://github.com/facebook/flipper/pull/1855
