### ISSUE TITLE
Integrate Flipper iOS get error Conv.h:114:10: 'double-conversion/double-conversion.h' file not found

### ISSUE THREAD

**Issue by fahmisdk6** [facebook/flipper#1461]
Integration Step :

1. Add flipper to podfile

  ```
$flipperkit_version = '0.51.0'
  # need to declare all transitive dependency to make sure the configuration is debug only
  pod 'FlipperKit', '~>' + $flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', '~>' + $flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + $flipperkit_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + $flipperkit_version, :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', :configuration => 'Debug'
  pod 'Flipper-Folly', :configuration => 'Debug'
  pod 'Flipper-Glog', :configuration => 'Debug'
  pod 'Flipper-PeerTalk', :configuration => 'Debug'
  pod 'CocoaLibEvent', :configuration => 'Debug' 
  pod 'boost-for-react-native', :configuration => 'Debug'
  pod 'OpenSSL-Universal', :configuration => 'Debug'
  pod 'CocoaAsyncSocket', :configuration => 'Debug'
  pod 'ComponentKit', '~> 0.30'
```

2. pod install

3. Then i got problem with Flipper-Folly's Time.h
https://github.com/facebook/flipper/issues/1421

It's because my project set all pod target to 10.0 on post_install
So i ignore these pods from set target script
flipper_pods = ['Flipper', 'CocoaLibEvent', 'boost-for-react-native', 'OpenSSL-Universal', 'CocoaAsyncSocket', 'ComponentKit']

4. Then i got error with double-conversion.h

<img width="1675" alt="Screen Shot 2020-08-13 at 08 58 21" src="https://user-images.githubusercontent.com/10940190/90086621-0be10680-dd45-11ea-869b-13d05726c3e9.png">

In this [issue](https://github.com/facebook/react-native/issues/26405) one of the answer suggest to remove `use_framework!` but i can remove it because our project has several dynamic framework. We declare the dynamic framework in pre_install.

Any help or suggestion to fix this double-conversion.h issue? 
Thanks in advance.

**Comment by cekkaewnumchai** [comment]
@priteshrnandgaonkar would you mind take a look on this?

**Comment by fahmisdk6** [comment]
hi @priteshrnandgaonkar, can you help?

**Comment by priteshrnandgaonkar** [comment]
@fahmisdk6, can you provide me with the reproducible example. Can you create a sample example, which I can pull in and debug ? Or maybe if you can reproduce it in the our repo's sample example, then that would be great ?

**Comment by fahmisdk6** [comment]
hi sorry for late response, i will provide sample soon

**Comment by milsawicki** [comment]
Hi! I am facing the same issue.

**Comment by priteshrnandgaonkar** [comment]
Closing it because the author didn't provide with a reproducible example.
