### ISSUE TITLE
Protbuf convert to JSON response in Flipper tool

### ISSUE THREAD

**Issue by dubeyvivek57** [facebook/flipper#1465]
protobuf response not converted to json in "flipper" tool

**Comment by cekkaewnumchai** [comment]
What plugin do you refer to? Can you provide repro step?

**Comment by dubeyvivek57** [comment]
i using NetworkFlipperPlugin with FlipperOkhttpInterceptor.
But i m getting response in below format.
![image](https://user-images.githubusercontent.com/35092674/90505408-30d3e000-e170-11ea-9d7a-d9581a61bae8.png)

**Comment by mweststrate** [comment]
@dubeyvivek57 responses in Flipper are formatted based on inspecting the network request headers. Feel free to open a PR that adds additional conditions to the JSONFormatter, as long as they are in principle universally correct: https://github.com/facebook/flipper/blob/master/desktop/plugins/network/RequestDetails.tsx#L556

**Comment by nikoant** [comment]
I guess this will be quite hard to implement, because decoding protobuf is impossible without knowing the schema which was used for encoding.

**Comment by nikoant** [comment]
Apparently protobuf logging is possible using interceptors on native side, at least for Android. See this great plugin for logging GRPC calls: https://github.com/AckeeCZ/flipper-grpc-plugin.

**Comment by passy** [comment]
Great find, @nikoant. I think we can close this.
