### ISSUE TITLE
Network Inspection Plugin is not working in Sonar Mac App

### ISSUE THREAD

**Issue by singhalmanav** [facebook/flipper#147]
I added Network plugin in the Android app by following instructions here, 
https://fbsonar.com/docs/network-plugin.html

`client.addPlugin(new NetworkSonarPlugin());`

On the sonar Mac app (downloaded from fbsonar.com), I can't see Network information.

<img width="1182" alt="screen shot 2018-07-10 at 10 17 04 am" src="https://user-images.githubusercontent.com/326722/42526364-7234b740-842a-11e8-84a3-0a0bd6f5bf4d.png">

Am I missing any other configuration setup to enable network logging?

**Comment by priteshrnandgaonkar** [comment]
The documentation seems outdated. Follow the [example](https://github.com/facebook/Sonar/blob/master/android/sample/src/sonar/com/facebook/sonar/sample/SonarSampleApplication.java). We use OKHttpInterceptor to track the network calls, so u will have to add interceptor in `okhttpclient`

**Comment by Almaral-Engineering** [comment]
Same here, I am using Volley for all my app requests, does that okhttpclient method work for that?

**Comment by priteshrnandgaonkar** [comment]
We use okhttp interceptors to track network calls. To support Volley, we would have to add support for it. But currently projects with okhttp in their network stack are supported.

**Comment by Shubhampatni86** [comment]
Hey @priteshrnandgaonkar so for now it's not support for Retrofit-integrated project as well !! Is that correct ? I have raised ticket **[here](https://github.com/facebook/flipper/issues/202)**.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
