### ISSUE TITLE
Json Order Wrong

### ISSUE THREAD

**Issue by PaulWoitaschek** [facebook/flipper#1470]
I'm using Flipper 0.52.2 on Linux.

I have a network request that returns a map:

```json
{
   "Für Anfänger":[

   ],
   "Besondere Tracker":[

   ]
}
```

The default view of the network plugin changes the order of these values:

![grafik](https://user-images.githubusercontent.com/743462/90371496-5b8a3f80-e06f-11ea-9db1-50fa8b9518bd.png)

I expect flipper to maintain the order of the original request.

**Comment by passy** [comment]
The object type in JSON is unordered. Quoting from [RFC 7159](http://www.rfc-editor.org/rfc/rfc7159.txt):

> An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.

If you want to maintain the order of your elements, you'll have to use an array.
