### ISSUE TITLE
Network Plugin does not load mock routes on connection to device

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1476]
## 🐛 Bug Report

Network Plugin does not load mock routes on connection to device.  Since the app does not persist the mocks, they are lost when the app is closed.

## To Reproduce

Start the Android Sample app
Create a mock in the Network plugin
Verify that the mock is working using the Android Sample app
Close the Android Sample Flipper app and verify that it no longer appears in Flipper
Execute a network request that has been mocked
The request is not mocked

Note:  The problem appears to be that the mocks (routes) are only updated in the app when they are created or modified.  The app does not persist the mocks.  A fix would be to load the mock table into the app when the plugin connects.

## Environment

Flipper 0.52.1

**Comment by mweststrate** [comment]
Fix will be part of next release, closing issue.
