### ISSUE TITLE
Mocks should be saved and restored from local storage by app

### ISSUE THREAD

**Issue by shoeguy** [facebook/flipper#1487]
## 🐛 Bug Report

When the Network Plugin loads routes (mocks) from local storage, it loads all routes that have been defined for any app.  It should only load the routes for the app that the plugin is in.

The key to local storage should also contain the application name.  It currently does not:

`    const LOCALSTORAGE_MOCK_ROUTE_LIST_KEY = '__NETWORK_CACHED_MOCK_ROUTE_LIST';`

## To Reproduce
1. Add a mock to the Flipper app
2. Run another app (with the Network Plugin and mocks enabled)
3. Add a mock to the new app
4. Stop the Flipper app and restart it
5. In the Network Plugin for Flipper you will see both mocks defined.

## Environment

Flipper 0.52.1

**Comment by bizzguy** [comment]
This can be closed.  It is implemented in this PR https://github.com/facebook/flipper/pull/1871
