### ISSUE TITLE
Question: Can I use flipper on a release build on Android/iOS?

### ISSUE THREAD

**Issue by alexnaiman** [facebook/flipper#1488]
I have some bugs related to some dependencies that for some reason I can reproduce only on release builds and it would be awesome and helpful if I could use some plugins(especially the Network one) on the app for debugging.

So, can I use flipper on a release build on Android/iOS? 

Thanks a lot

**Comment by d3xt3r2909** [comment]
@alexnaiman did you find maybe this workaround? The thing is that before this plugin we have used Stetho which has this possibility (to track network traffic and I really don't see a reason why is this not enabled for release builds). 

Anyhow did you manage to find solution for this?

**Comment by lannyf77** [comment]
@alexnaiman
I was trying to use flipper with release build, but it does not work with dependency
```
    implementation "com.facebook.flipper:flipper:0.93.0"
    implementation "com.facebook.flipper:flipper-network-plugin:0.93.0"
    implementation "com.facebook.soloader:soloader:0.10.1"

```
the debug and release build are fine, just run release build the flipper does not connect and no log shown.

the work around works for me is to add `debuggable true` in the `release` of buildTypes

```
release {
            debuggable true
            minifyEnabled false
            ...
        }

```
then in the release build it starts to show the log in flipper.
if this is what it supposed to work (@mweststrate any comment?), then it could help in your case.

**Comment by mwshubham** [comment]
I am sure it would be helpful if we can allow in release variant as well. Giving option to user to control the same via build variant or custom implemetation based on their usecase. 

e.g. We have some build variant with release build type where we want to use flipper.
