### ISSUE TITLE
release 0.53.0 not available in Jcenter, but listed in setup instructions

### ISSUE THREAD

**Issue by edwardotis** [facebook/flipper#1489]
## 🐛 Bug Report
Release 0.53.0 is used in the setup instructions:
https://fbflipper.com/docs/getting-started/android-native#dependencies

However it is missing from jcenter, so 0.53.0 won't build:
https://bintray.com/facebook/maven/com.facebook.flipper%3Aflipper

Reverting to 0.52.1 fixes the issue in the meantime.

## To Reproduce
https://fbflipper.com/docs/getting-started/android-native#dependencies

## Environment
Android

**Comment by mweststrate** [comment]
cc @realpassy seems 0.54 hasn't been publish either. Are there any manual steps involved?

**Comment by nikoant** [comment]
Closing this as the issue was fixed and new releases are published now. There are releases 0.54.0 and 0.55.0 already available in jcenter.
