### ISSUE TITLE
android sdk not detected on macOS

### ISSUE THREAD

**Issue by gengjiawen** [facebook/flipper#1512]
## 🐛 Bug Report
My android home is defined in my `bash_profile` as `export ANDROID_HOME=~/Library/Android/sdk`

![image](https://user-images.githubusercontent.com/3759816/92196793-a941dd00-eea2-11ea-9c63-d887fb74ede8.png)

I have not look at the code on flipper detect android sdk code, maybe directly use envinfo to fix this bug ?

## To Reproduce
Run doctor on macOS

## Environment
part of `npx envinfo`
```console
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 5.49 GB / 32.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 26.0.0, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      Android NDK: 21.0.6113669
```
flipper 0.55

**Comment by nikoant** [comment]
Hi @gengjiawen, could you open Flipper settings and specify Android SDK path there as "~/Library/Android/sdk"? I think, depending on how you launching Flipper, it might not use bash env vars.

**Comment by gengjiawen** [comment]
> Hi @gengjiawen, could you open Flipper settings and specify Android SDK path there as "~/Library/Android/sdk"? I think, depending on how you launching Flipper, it might not use bash env vars.

Set the absolute path will work. My fillper is installed by brew if it helps.
