### ISSUE TITLE
iOS simulator network requests are reported twice on RN project

### ISSUE THREAD

**Issue by mikaoelitiana** [facebook/flipper#1513]
## 🐛 Bug Report

When using Flipper 0.55 with iOS simulator, any  single network request is displayed twice. The response body is exactly similar but for POST calls, the request body is not displayed anymore on the second report. 

<img width="1383" alt="Capture d’écran 2020-09-04 à 17 15 07" src="https://user-images.githubusercontent.com/674667/92256680-4d904780-eed4-11ea-8dcf-c258fce45d01.png">

## To Reproduce
- install `react-native-flipper` v.055
- launch react-native app
- laucnh flipper and check network requests

## Environment

- react-native 0.63
- react-native-flipper 0.55
- flipper desktop 0.55

**Comment by nikoant** [comment]
Hi @mikaoelitiana, thanks for the reported issue! Could you check if the same issue is reproducible with Flipper 0.54?

**Comment by mikaoelitiana** [comment]
@nikoant yes I am having same issue on 0.54

**Comment by priteshrnandgaonkar** [comment]
We have changed the swizzling of the network classes and this issue might have gotten fixed, worth checking it with latest release. Feel free to reopen issue if it doesn't work.
