### ISSUE TITLE
UnsatisfiedLinkError with Flipper 0.55.0

### ISSUE THREAD

**Issue by shashachu** [facebook/flipper#1514]
## 🐛 Bug Report
We're trying to upgrade from Stetho to Flipper for the first time as we were previously blocked by https://github.com/facebook/flipper/issues/660

I'm able to build after excluding `fbjni` from `flipper` and `flipper-network-plugin` but I'm getting runtime crashes:

```
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "_ZNSt6__ndk112__next_primeEj" referenced by "/data/data/xxxxxxx/lib-main/libflipper.so"... result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

## To Reproduce
Unfortunately I can't provide a complete sample, but this is how we're adding the Flipper dependencies:

```
    debugImplementation ('com.facebook.flipper:flipper:0.55.0') {
        exclude group: 'com.facebook.fbjni', module: 'fbjni'
    }
    debugImplementation 'com.facebook.soloader:soloader:0.9.0'
    debugImplementation ('com.facebook.flipper:flipper-network-plugin:0.55.0') {
        exclude group: 'com.facebook.fbjni', module: 'fbjni'
    }
```

It looks like the missing symbol should be in `libc++_shared.so` which as far as I can tell is ending up in the final APK properly, so not totally sure what's weird about our setup.

## Environment
* Mac OSX 10.15.6
* AGP 4.0.1
* Flipper 0.55.0
* SoLoader 0.9.0
* React Native 0.63.1
* Android Stock emulator, various API levels (27, 29, 30)

**Comment by shashachu** [comment]
I have tried both solutions in https://github.com/facebook/flipper/issues/824 and have not had success.

**Comment by janweigel** [comment]
Same problem here.
I'm getting the same runtime error as mentioned above.

Flipper 0.55.0
SoLoader 0.9.0
React Native: 0.62.2

**Comment by nikoant** [comment]
@passy do you have any suggestions?

**Comment by spsaucier-bakkt** [comment]
Downgrading to 0.54.0 seems to fix this issue.

**Comment by passy** [comment]
No idea where this is coming from. A sample that reproduces this would be very helpful.

**Comment by shashachu** [comment]
> Downgrading to 0.54.0 seems to fix this issue.

Can confirm we're no longer crashing with `0.54.0`. I'm now getting a cert error, so will look into that.

**Comment by passy** [comment]
It would be very interesting to know if reverting https://github.com/facebook/flipper/commit/97adea5423b5b28b63e43137ba72c1828cbe1dac#diff-7ae5a9093507568eabbf35c3b0665732 would change anything for you. It should be enough to override the dependency and pin `fbjni` to `0.0.2` instead.

**Comment by shashachu** [comment]
@passy I wasn't able to pin it to `0.0.2` just in the gradle files, but I made local builds of flipper and the flipper network plugin with 97adea5 reverted and indeed it doesn't crash, so it does appear to be the `fbjni` `0.0.4` version upgrade.

**Comment by passy** [comment]
I'll revert back for now to ensure compatibility with the current RN release. I've just fixed an issue with the fbjni distribution that was blocking them from updating. I hope that with the updates on their side this should Just Work again.
