### ISSUE TITLE
Hermes Debugger appears to connect but is empty on Flipper 0.55 win in clean RN 0.63.2 project

### ISSUE THREAD

**Issue by AndrewMorsillo** [facebook/flipper#1520]
## 🐛 Bug Report
Hermes Debugger simply does nothing when connected to a clean RN 0.63.2 project with Hermes enabled on windows. Elements, Console, Sources, Network, Application, etc are all empty of normal content.  Doctor passes all tests. Remote debugging is off. No other RN apps running. Verified Hermes running. Android SDK is valid and accessible. All other Flipper functions work fine. There are no problems indicated in the Flipper debug logs.

edit: Sometimes the "Debugging connection was closed" window pops up in the Hermes Debugger. It seems it can be dismissed by clicking outside of it. Pushing "Reconnect DevTools" flashes the window as if refreshing but has no effect.
![image](https://user-images.githubusercontent.com/858965/92425451-4cba1880-f155-11ea-98c2-b9a9dc65b547.png)

![image](https://user-images.githubusercontent.com/858965/92425035-0a440c00-f154-11ea-88cb-adcf15037212.png)
![image](https://user-images.githubusercontent.com/858965/92425043-1334dd80-f154-11ea-92ec-a08bca246030.png)

Debug logs:
```
(electron) crashReporter.start is deprecated in the renderer process. Call it from the main process instead. 
Secure server started on port 8088 server 
Certificate server started on port 8089 server 
Device connected: TestCleanRNAndroidErrors#Android#sdk_gphone_x86_64_arm64 - 11 - API 30#emulator-5554 server 
{id: 0, method: "getPlugins", params: undefined}
"message:call" 
Device client initialised: TestCleanRNAndroidErrors#Android#sdk_gphone_x86_64_arm64 - 11 - API 30#emulator-5554. Supported plugins: CrashReporter, Databases, Fresco, Inspector, Network, Preferences, React server 
```

## To Reproduce
1. npx react-native init TestApp
2. set `enableHermes: true` in build.gradle
3. yarn react-native run-android
4. Observe that there is no content in the hermes debugger tab of Flipper and no relevant content in Flipper debug logs indicating any sort of issue.

## Environment
* Android API 30 on Android Studio emulator x86_64 google_apis
* React Native 0.63.2 (fresh project, only change is `enableHermes: true`)
* Flipper 0.55.0
* Windows 10 insider preview build 20206.rs_prerelease_200828-1431

**Comment by nikoant** [comment]
I've reproduced the same issue on my Windows 10 machine. I'm wondering wether Hermes debugger works for someone on Win 10?

**Comment by cklinx** [comment]
Same problem here

**Comment by petr7555** [comment]
Same problem for me

**Comment by chenop** [comment]
I think Javascript debugging is not quite working with Hermes which make this tool useless for me - I mean: debugging, breakpoints, variables is the basic.
Please correct me if I'm wrong.

**Comment by alexfov** [comment]
Same issue. Are there any solutions?

**Comment by nishan-wtv** [comment]
Having the same issue. I am unable to run on my windows machine. In ios, it works well.

**Comment by batuhansahan** [comment]
Is there a solution yet ?

**Comment by Oraci** [comment]
Same problem for me.

**Comment by mweststrate** [comment]
Would be great if someone with a windows machine at hand would be interested in taking a closer look at this, our wrapper is pretty thin ([plugin source](https://github.com/facebook/flipper/blob/master/desktop/plugins/hermesdebuggerrn/index.tsx)), so it would be great if someone could investigate a bit deeper and check if...

1. Stand alone debugging does work: https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools
2. If there are any errors in the Flipper log / Flipper devtools
3. navigating to http://localhost:8081 lists the correct debugging targets

**Comment by pranaydutta89** [comment]
same problem

**Comment by patrickgalbraith** [comment]
@mweststrate Looks like this is an issue in metro. I've opened https://github.com/facebook/metro/pull/662 which should hopefully fix this by providing a valid IPV6 localhost websocket url. 

I had a look at the chrome developer tools source and how it initialises the connection and it is done by creating a new WebSocket(...) and passing the webSocketDebuggerUrl (which makes sense).

As you can see `ws://[::]` is not a valid url:

![image](https://user-images.githubusercontent.com/811945/114950181-b0e24f00-9e91-11eb-938f-590273b46ccb.png)

**Comment by ghasemikasra39** [comment]
same problem on `0.64.2`

**Comment by eltonea** [comment]
Working in 0.98.0 starting bundle manually with the command bellow:
`react-native start --host localhost`

**Comment by jamesdmurphy51** [comment]
Same issue for me
react native version 0.64.0

**Comment by gloredo** [comment]
Same issue here, for more info see [my post]( https://forums.expo.dev/t/flipper-issues-react-devtools-works-sometimes-hermes-debugger-never-works/62141) on expo forum

**Comment by mweststrate** [comment]
Please open new issue with full details. +1's on closed issues without details are in actionable and are only seen by original convo participants.
