### ISSUE TITLE
Question: SoLoader.init(…) throws NullPointerException trying to run local unit test that uses Robolectric

### ISSUE THREAD

**Issue by tatsuyafujisaki** [facebook/flipper#1531]
# Question 
`SoLoader.init(…)` throws `NullPointerException` trying to run a local unit test that uses Robolectric. Is there any way to avoid it?

# Error
```
java.lang.NullPointerException
  at java.base/java.io.File.<init>(File.java:276)
  at com.facebook.soloader.ApplicationSoSource.<init>(ApplicationSoSource.java:46)
  at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:280)
  at com.facebook.soloader.SoLoader.init(SoLoader.java:200)
  at com.facebook.soloader.SoLoader.init(SoLoader.java:182)
  at com.facebook.soloader.SoLoader.init(SoLoader.java:212)
  at com.example.sample.MyApplication.onCreate(MyApplication.kt:14)
  at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:288)
  at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
  at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:288)
  at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
  at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
  at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
  at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:830)
```

# Environment
* macOS Catalina 10.15.7
* Android Studio 4.0.1
* OpenJDK 13
* Flipper 0.57.0 + SoLoader 0.9.0
* Robolectric 4.4

# My local unit test
```kotlin
import android.content.Context
import androidx.test.core.app.ApplicationProvider
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class RobolectricTest {
    private val context = ApplicationProvider.getApplicationContext<Context>()

    @Test
    fun test() {
        assertEquals(1, 1)
    }
}
```

# My simplified Application class
```kotlin
import android.app.Application
import com.facebook.flipper.android.AndroidFlipperClient
import com.facebook.flipper.android.utils.FlipperUtils
import com.facebook.flipper.plugins.inspector.DescriptorMapping
import com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin
import com.facebook.flipper.plugins.network.BuildConfig
import com.facebook.flipper.plugins.network.NetworkFlipperPlugin
import com.facebook.soloader.SoLoader

class MyApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        SoLoader.init(this, false) // throws NullPointerException trying to run local unit test that uses Robolectric.
        if (BuildConfig.DEBUG && FlipperUtils.shouldEnableFlipper(this)) {
            with(AndroidFlipperClient.getInstance(this)) {
                addPlugin(
                    InspectorFlipperPlugin(
                        this@MyApplication,
                        DescriptorMapping.withDefaults()
                    )
                )
                addPlugin(NetworkFlipperPlugin())
                start()
            }
        }
    }
}
```

# My simplified `app/build.gradle`
```gradle
android {
    testOptions {
        unitTests {
            includeAndroidResources true
        }
    }
}

dependencies {
    testImplementation 'org.robolectric:robolectric:4.4'

    debugImplementation 'com.facebook.flipper:flipper:0.57.0'
    debugImplementation 'com.facebook.flipper:flipper-network-plugin:0.57.0'
    debugImplementation 'com.facebook.soloader:soloader:0.9.0'
    releaseImplementation 'com.facebook.flipper:flipper-noop:0.57.0'
}
```

**Comment by mweststrate** [comment]
Looks like your native library dir couldn't be found, is `LD_LIBRARY_PATH ` set correctly? See [here](https://github.com/facebook/SoLoader/blob/f1fc32b6973ab95110f81e2218923f77b455f30e/java/com/facebook/soloader/ApplicationSoSource.java#L46) and [there](https://github.com/facebook/SoLoader/blob/master/java/com/facebook/soloader/SoLoader.java#L225).

**Comment by tatsuyafujisaki** [comment]
@mweststrate
Thanks for the help.

No, `LD_LIBRARY_PATH` is not defined on my Mac.

What directory should I add to `LD_LIBRARY_PATH` to make SoLoader work?

**Comment by mweststrate** [comment]
@tatsuyafujisaki I have no idea :) I just was trying to deduct from the linked sources what might be the problem as to why a `null` path ends up in the `File` constructor, and it seems that this expression returns `null`: `applicationContext.getApplicationInfo().nativeLibraryDir`, where context is a `import android.content.Context;`. 

1. I can imagine your tests don't count as an Android app environment, so I'd check first if you test Android app code with roboelectric. (Sorry, I'm unfamiliar with the tool)
1. run your code without roboelectric, to make sure some essential system calls for Android context / SoLoader aren't stubbed away. 
2. I'd attach a debugger, and step into that `getApplicationInfo()` call,  to see what call ends up returning a `null` unexpectedly
3. File an issue at SoLoader, they might a have a more specific idea.

**Comment by tatsuyafujisaki** [comment]
@mweststrate
Thanks for the insight! After all, I gave up running unit tests, as is, using Robolectric for Android code that uses Flipper.

> I can imagine your tests don't count as an Android app environment

Yes. Robolectric is an Android testing library that lets you test Android code quickly on a JVM instead of an Android device or emulator. It is a fake Android environment, so to speak.

> I'd attach a debugger, and step into that getApplicationInfo() call, to see what call ends up returning a null unexpectedly

When using Robolectric, [this line](https://github.com/facebook/SoLoader/blob/bf93a1579acb501f105d98ad5ffef1f087f4e515/java/com/facebook/soloader/ApplicationSoSource.java#L46) threw an exception because `applicationContext.getApplicationInfo().nativeLibraryDir` was null. `applicationContext.getApplicationInfo()` itself was not null.

On the other hand, when not using Roboletric, `applicationContext.getApplicationInfo().nativeLibraryDir` returned a temporary directory such as `/data/app/com.example.myapplication-Ya5hsKx2EhAkrI7hhoUd3w==/lib/x86`

**Comment by mweststrate** [comment]
I noticed that we actually us RoboElectric ourselves to test Flipper (not sure why I didn't think about checking that before). So it should work with RoboElectric, and I guess you can analyze our setup to see why it works fine in our case: https://github.com/facebook/flipper/search?q=Robolectric

**Comment by tatsuyafujisaki** [comment]
Thanks for the hint.

I will use the following to avoid `NullPointerException` thrown by `SoLoader.init(…)`.
```kotlin
@Config(application = TestApplication.class)
```
https://github.com/facebook/flipper/blob/master/android/sample/src/test/java/com/facebook/flipper/plugins/example/ExampleFlipperPluginTest.java#L22
