### ISSUE TITLE
Incorrect variable name

### ISSUE THREAD

**Issue by nicoburns** [facebook/flipper#1533]
In `flipper/iOS/Plugins/FlipperKitUserDefaultsPlugin/FKUserDefaultsSwizzleUtility.m` (line 58)

```obj-c
if (blk != nil) {
  NSString* originalStr =
        [@"comfacebookFlipperKit_" stringByAppendingString:selStr];
  [invocation setSelector:NSSelectorFromString(originalStr)];
  if (block != nil) {
    block(invocation);
  }
} else {
  ((void (*)(id, SEL, NSInvocation*))orig)(this, fwdSel, invocation);
}
```

The `if(blk != nil)` should be `if(block != nil)`. If you check the function signature you will see that `blk` is part of the type of the variable named `block`. There is no `blk` variable. This PR (#1401) fixed a crash by adding the inner `if (block != nil) {` check. Which fixes the bug. However the code above is still doing an if-check on a non-existent variable, which seems like a potential source of future bugs. The whole code block above can be simplified to:

```obj-c
if (block != nil) {
  NSString* originalStr =
        [@"comfacebookFlipperKit_" stringByAppendingString:selStr];
  [invocation setSelector:NSSelectorFromString(originalStr)];
  block(invocation);
} else {
  ((void (*)(id, SEL, NSInvocation*))orig)(this, fwdSel, invocation);
}
```

**Comment by passy** [comment]
Thanks for the report and the detailed description. @priteshrnandgaonkar can you take a look, please?

**Comment by priteshrnandgaonkar** [comment]
Current code seems fine to me.

blk is the variable passed into the functon. `block` is the closure(block) stored in `swizzledBlocks` variable.
