### ISSUE TITLE
[ios][RN] Network plugin no request reported on RN 0.63.2 with ios14 simulator

### ISSUE THREAD

**Issue by jayshah123** [facebook/flipper#1534]
## 🐛 Bug Report

How flipper is used in react native app:
```swift
  private func initializeFlipper(with application: UIApplication) {
     #if DEBUG
       print("flipper is enabled!!!!!!!")
       let client = FlipperClient.shared()
       client?.add(FKUserDefaultsPlugin(suiteName: nil))
       client?.add(FlipperKitReactPlugin())
       client?.add(FlipperKitNetworkPlugin(networkAdapter: SKIOSNetworkAdapter()))
       client?.start()
     #endif
   }
```

<img width="1211" alt="Screenshot 2020-09-18 at 4 24 32 PM" src="https://user-images.githubusercontent.com/659202/93590107-93b4d300-f9cb-11ea-8981-2b57a73334c2.png">

## To Reproduce

react-native start --reset-cache
Install ios debug app from xcode

## Environment
Flipper version: Version 0.57.0 (50.0.0)
React Native version: 0.63.2
XCode version: 12.0
Mac OS version: 10.15.6

**Comment by jayshah123** [comment]
I also use newrelic ios sdk in my app, does it have something to do with this?

**Comment by elkinjosetm** [comment]
This issue started happening to me since I updated to XCode 12 and started using iOS 14. Just a few hours earlier with XCode 11.x and iOS 13.x was working perfectly fine. The code and everything with the setup is the same.

**Comment by skyride99** [comment]
having the same issue when using Xcode 12

**Comment by umang-simform** [comment]
Same issue here

**Comment by netmaxt3r** [comment]
I believe this is due to internal changes to iOS 14, i am doing local patch for FLEXNetworkObserver.mm in SKIOSNetworkPlugin pod at line 335
```
    if(className == NULL){
            NSClassFromString([@[ @"__", @"NSC", @"FLocalS", @"ession", @"Task" ]
                componentsJoinedByString:@""]);
    }
``` 
read the comments in start of method to understand the struggle with different ios version, I am sure Flipper devs will comeup with proper impl.

**Comment by mweststrate** [comment]
cc @priteshrnandgaonkar

**Comment by hoquocdat** [comment]
I have a same issue with that on iOS 14 and Xcode 12

**Comment by brandonfancher** [comment]
Same issue here. The temp workaround posted by @netmaxt3r worked for me.

**Comment by elkinjosetm** [comment]
Same here, the temp workaround posted by @netmaxt3r worked for me. Thanks! Hopefully we have an official solution soon.

**Comment by Zestpond** [comment]
Same here,

**Comment by hoquocdat** [comment]
> if(className == NULL){
>             className = NSClassFromString([@[ @"__", @"NSC", @"FLocalS", @"ession", @"Task" ]
>                 componentsJoinedByString:@""]);
>     }

You are awesome !!

**Comment by lucipacurar** [comment]
Downloaded iOS Simulator 13.5, and it works. So I guess it's related to the iOS version not Xcode.

**Comment by mym0404** [comment]
Same here

**Comment by cbotsikas** [comment]
I've made a PR with a tested solution. It's based on the solution from the original project: https://github.com/FLEXTool/FLEX/pull/451

**Comment by Piero87** [comment]
when this fix will be released? I have this problem too

**Comment by dftaher** [comment]
it did not work for me

**Comment by mweststrate** [comment]
@cbotsikas / @Piero87 

Should land in next weeks 0.62 release. Thanks for investigating! In the mean time things can be monkey patched in `ios/Pods/FlipperKit/iOS/Plugins/FlipperKitNetworkPlugin/SKIOSNetworkPlugin/FLEXNetworkLib/FLEXNetworkObserver.mm`

**Comment by Piero87** [comment]
@cbotsikas Thanks! At the moment i'm using iOS 13.7 to get around the problem, as soon as it is released I will be able to use iOS 14

**Comment by Paduado** [comment]
I just updated to Flipper 0.62.0 and I'm still not able to see network requests on iOS 14, am I missing something? 🤔

**Comment by cloudychen** [comment]
> I just updated to Flipper 0.62.0 and I'm still not able to see network requests on iOS 14, am I missing something? 🤔

me too.

**Comment by adrianso** [comment]
@Paduado, @cloudychen I had the same issue, but resolved it by updating the Flipper version in iOS to match the Flipper client.

```ruby
use_flipper!('Flipper' => '0.62.0')
```

After that, do a `pod install`. Re-compile your iOS app. Should work afterwards.

**Comment by cloudychen** [comment]
> @Paduado, @cloudychen I had the same issue, but resolved it by updating the Flipper version in iOS to match the Flipper client.
> 
> In your ios/Podfile,
> 
> ```ruby
> use_flipper!('Flipper' => '0.62.0')
> ```
> 
> After that, do a `pod install`. Re-compile your iOS app. Should work afterwards.

Thanks, I will try right away👍

**Comment by cloudychen** [comment]
use method by @adrianso ,I can see network request but my request not work.` [Error: An SSL error has occurred and a secure connection to the server cannot be made.]` my server use a self-signed SSL cert and i use `rn-fetch-blop` make request, rn0.63.3 use flipper 0.54.0 request is ok just not reported.

**Comment by lucipacurar** [comment]
It works for me now on iOS using: 
`use_flipper!('Flipper' => '0.62.0')`

But I have no clue how to make it work on Android.

**Comment by Paduado** [comment]
> @Paduado, @cloudychen I had the same issue, but resolved it by updating the Flipper version in iOS to match the Flipper client.
> 
> In your ios/Podfile,
> 
> ```ruby
> use_flipper!('Flipper' => '0.62.0')
> ```
> 
> After that, do a `pod install`. Re-compile your iOS app. Should work afterwards.

Thanks, now it works 🎉 !

**Comment by Piero87** [comment]
In my pod file I have this: `use_flipper!` and I edited in this: `use_flipper!('Flipper' => '0.62.0')` as you suggest, but now Pod give me error:

```
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "FlipperKit":
  In Podfile:
    FlipperKit (= 0.62.0)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit (= 0.62.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Aborting run
An unexpected error was encountered. Please report it as a bug:
```

**Comment by mweststrate** [comment]
@Piero87 did you try the suggested `pod install --repo-update`?

**Comment by jayshah123** [comment]
Can confirm it works with 
1. `use_flipper!('Flipper' => '0.62.0')` 
2. `pod install --repo-update` 

Another quick question though,
Is it recommened to also update npm dependency `react-native-flipper`  version to `0.62.0` ?
Is it recommended to update Android `gradle.properties` flipper version i.e. `FLIPPER_VERSION` from `0.37.0` to `0.62.0` ?

**Comment by jrdn91** [comment]
I have updated to Flipper client `0.63.0`, updated the package.json version to `0.63.0` and installed pods with `pod install --repo-update` and still cannot get any network logs with react native. I've even tried to specify the version in the podfile with `use_flipper!('Flipper' => '0.63.0)` but get errors when trying to install pods.

Has anyone had luck getting the network plugin to work with the latest version of flipper / react-native?

**Comment by mweststrate** [comment]
make sure to also update `flipperkit_version` in your podfile. If that
doesn't help, please do provide more info (screenshot of Flipper, and your
podfile at least)

**Comment by mweststrate** [comment]
..and any errors printed to the console ofc

**Comment by jrdn91** [comment]
My project wasn't using flipperkit_version before but here is the Podfile I have now

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AtiApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'AppAuth', :git => 'https://github.com/CODEANDTRUST/AppAuth-iOS.git'

  target 'AtiAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'AtiApp-tvOS' do
  # Pods for AtiApp-tvOS

  target 'AtiApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by blueberry6401** [comment]
Still not seeing anything in network tab with flipper 0.64 and react-native 0.63.3. How should I do?

**Comment by mweststrate** [comment]
We all know that things not working is frustrating, but please remember that GitHub isn't a coping group :). 

For us to respond to reported issues we need actionable information. Please follow troubleshooting guides as can be found here: https://fbflipper.com/docs/troubleshooting#react-native, and after that report back with your Flipper version, RN version, OS, the kind of device you are trying to connect to, and the podspec / gradle files.

**Comment by zaporozhetsAnton** [comment]
> I believe this is due to internal changes to iOS 14, i am doing local patch for FLEXNetworkObserver.mm in SKIOSNetworkPlugin pod at line 335
> 
> ```
>     if(className == NULL){
>             className = NSClassFromString([@[ @"__", @"NSC", @"FLocalS", @"ession", @"Task" ]
>                 componentsJoinedByString:@""]);
>     }
> ```
> 
> read the comments in start of method to understand the struggle with different ios version, I am sure Flipper devs will comeup with proper impl.

It works for me, thank you @netmaxt3r 
For those who will use this approach here is the path to file in which you need to add this patch - Pods/FlipperKit/iOS/Plugins/FlipperKitNetworkPlugin/SKIOSNetworkPlugin/FLEXNetworkLib/FLEXNetworkObserver.mm

**Comment by mweststrate** [comment]
Feel free to PR yet another version special case; it might very well be the case that we didn't run into it internally, as sometimes the versions in the stack we use internally are behind.

**Comment by jayshah123** [comment]
Closing since saw it was working as per my last comment.

**Comment by addingama** [comment]
> Can confirm it works with
> 
> 1. `use_flipper!('Flipper' => '0.62.0')`
> 2. `pod install --repo-update`
> 
> Another quick question though,
> Is it recommened to also update npm dependency `react-native-flipper` version to `0.62.0` ?
> Is it recommended to update Android `gradle.properties` flipper version i.e. `FLIPPER_VERSION` from `0.37.0` to `0.62.0` ?

Following this really working on mine, just use exact `0.62.0`

**Comment by mym0404** [comment]
I don't know Ruby syntax.
```ruby
use_flipper!('Flipper' => '0.62.0')
```
produces a warning like that
```
Podfile:16: warning: Passing the keyword argument as the last hash parameter is deprecated
```

Is there solution to above?

**Comment by jarnove** [comment]
I still have the issue with the latest version? I also tried the 0.62 workarounds but without any result. Any ideas?

**Comment by nicoburns** [comment]
> I don't know Ruby syntax.
> ```ruby
> use_flipper!('Flipper' => '0.62.0')
> ```
> produces a warning like that
> ```
> Podfile:16: warning: Passing the keyword argument as the last hash parameter is deprecated
> ```
> 
> Is there solution to above?

Try

```ruby
use_flipper!({ 'Flipper' => '0.62.0' })
```

**Comment by Jonathan0wh** [comment]
I can confirm that it still didn't work on `"react-native": "0.63.4"` and `Flipper 0.75.0`.

**Comment by FlyOrDie** [comment]
Have this issue one react-native 0.64.

**Comment by ogard** [comment]
Same issue with `react-native 0.67.3` and `Flipper 0.99.0`

**Comment by efstathiosntonas** [comment]
same issue with react-native 0.68.2 and flipper 0.155.0

**Comment by pedpess** [comment]
Same for me, since this issue is already closed, I opened a new one here:
https://github.com/facebook/flipper/issues/3945
