### ISSUE TITLE
Failed to start websocket server Couldn't start websocket server. Looks like you have multiple copies of Flipper running.

### ISSUE THREAD

**Issue by patrickbattisti** [facebook/flipper#1536]
## 🐛 Bug Report

The application does't open after changing the SDK path, updating the shortcuts and installing the idb. Before It worked properly, now just load an empty screen and show the errors below on the console.

I have already installed the current version (0.57) and tried versions 0.46 and 0.56, all are't working.

`Underlying stack: TypeError: Error processing argument at index 0, conversion failure from Command`

`Uncaught Error: Could not call remote method 'register'. Check that the method signature is correct. Underlying error: Error processing argument at index 0, conversion failure from Command
Underlying stack: TypeError: Error processing argument at index 0, conversion failure from Command`

`Failed to start websocket server Couldn't start websocket server. Looks like you have multiple copies of Flipper running.`

`Uncaught (in promise) Error: listen EADDRINUSE: address already in use :::8088`

<img width="841" alt="Screen Shot 2020-09-20 at 17 29 21" src="https://user-images.githubusercontent.com/35247414/93716281-db239680-fb66-11ea-92ba-d91d94f22e19.png">

<img width="957" alt="Screen Shot 2020-09-20 at 17 17 03" src="https://user-images.githubusercontent.com/35247414/93716059-2046c900-fb65-11ea-925b-06b979c059ab.png">

## To Reproduce
I don't know, it worked until I configured the SDK path, updating the shortcuts and installing the idb.

## Environment

Flipper: Version 0.57.0 (50.0.0)
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 6.82 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
    Gradle: 6.5.1 - /usr/local/bin/gradle
    Homebrew: 2.5.1 - /usr/local/bin/brew
    pip3: 20.1.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
    Clang: 1200.0.32.2 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.12 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.49.1 - /usr/local/bin/code
    Vim: 8.1 - /usr/bin/vim
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_262 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Protoc: 3.13.0 - /usr/local/bin/protoc
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.5 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 14.0

**Comment by mweststrate** [comment]
Could you check what is running on port 8088?

**Comment by TRomesh** [comment]
> Could you check what is running on port 8088?

Hi @mweststrate is it possible to change the default 8088 to another one? and how?.  Thanks

**Comment by mweststrate** [comment]
IIRC no, as that is the port the device will be connecting to
