### ISSUE TITLE
Question: Recommended pattern to use FlipperOkHttpInterceptor

### ISSUE THREAD

**Issue by bangarharshit** [facebook/flipper#1545]
For network response mocking, it is recommended to use application interceptor but then we misses redirects in flipper. What is the recommended way to use flipper? Should it be the first network interceptor so that mocking works as expected - https://github.com/facebook/flipper/blob/1a8566c9886fbbacb273ebd0ee3b81f0c4e3716e/android/plugins/network/src/main/java/com/facebook/flipper/plugins/network/FlipperOkhttpInterceptor.java#L96

**Comment by mweststrate** [comment]
I don't know if there is any specific downside to either of those variations. Feel free to play with it. I'd assume intercepting works on the original url, but doesn't kick in anymore if that resulted in a re-direct?
