### ISSUE TITLE
Plugin achilles failed to load TypeError: Cannot read property 'supportsDevice' of undefined

### ISSUE THREAD

**Issue by EmilMakaev** [facebook/flipper#1559]
Hello! I have this problem. I can't use any plugins.

Plugin achilles failed to load TypeError: Cannot read property 'supportsDevice' of undefined at new SandyPluginDefinition

macOS Catalina Version 10.15.4

<img width="870" alt="Screenshot 2020-09-29 at 14 42 03" src="https://user-images.githubusercontent.com/50282812/94554074-31c55a80-0262-11eb-8b00-2b06c547be5b.png">

**Comment by mweststrate** [comment]
@EmilMakaev `achilles` doesn't sound like a build-in plugin of Flipper, is it a manually installed plugin?

**Comment by EmilMakaev** [comment]
> @EmilMakaev `achilles` doesn't sound like a build-in plugin of Flipper, is it a manually installed plugin?

I installed it directly in the SDK.

<img width="762" alt="Screenshot 2020-09-29 at 15 23 08" src="https://user-images.githubusercontent.com/50282812/94557864-d007ef00-0267-11eb-8d44-36d5508a9b6d.png">

**Comment by EmilMakaev** [comment]
Actually I don't see any plugin at all.

<img width="592" alt="Screenshot 2020-09-29 at 15 22 03" src="https://user-images.githubusercontent.com/50282812/94557984-047bab00-0268-11eb-9af5-52b0f1005c83.png">

<img width="762" alt="Screenshot 2020-09-29 at 15 22 34" src="https://user-images.githubusercontent.com/50282812/94558011-11989a00-0268-11eb-8e40-41169a15f1d0.png">

**Comment by mweststrate** [comment]
I assume that removing `achilles` does fix it? Could you share the achilles plugin?

**Comment by EmilMakaev** [comment]
> I assume that removing `achilles` does fix it? Could you share the achilles plugin?

How can I send you this plugin (achilles)? This plugin was in the SDK by default.

**Comment by EmilMakaev** [comment]
Can you tell me why I can't see these plugins in the menu?

<img width="129" alt="Screenshot 2020-09-29 at 15 33 48" src="https://user-images.githubusercontent.com/50282812/94559021-4ce79880-0269-11eb-882b-e30f55e05408.png">

**Comment by EmilMakaev** [comment]
> I assume that removing `achilles` does fix it? Could you share the achilles plugin?

https://classic.yarnpkg.com/en/package/flipper-plugin-achilles

**Comment by mweststrate** [comment]
What do you mean by "This plugin was in the SDK by default."? Which SDK? That plugin is not being maintained by us. Note that the plugins shown in "install plugins" merely shows all plugins available on NPM. So if it the plugin doesn't ring a bell to you I'd recommend to uninstall it :). 

We'll check if we can make plugin loading more resilient, as it at least shouldn't affect other plugins to be loaded. cc @nikoant.

To figure out why other plugins aren't shown; please follow the troubleshooting guide here first: https://staticdocs.thefacebook.com/flipper/docs/troubleshooting#react-native

**Comment by EmilMakaev** [comment]
> What do you mean by "This plugin was in the SDK by default."? Which SDK? That plugin is not being maintained by us. Note that the plugins shown in "install plugins" merely shows all plugins available on NPM. So if it the plugin doesn't ring a bell to you I'd recommend to uninstall it :).
> 
> We'll check if we can make plugin loading more resilient, as it at least shouldn't affect other plugins to be loaded. cc @nikoant.
> 
> To figure out why other plugins aren't shown; please follow the troubleshooting guide here first: https://staticdocs.thefacebook.com/flipper/docs/troubleshooting#react-native

Your link doesn't work. Do you mean this link? https://fbflipper.com/docs/troubleshooting/#connection-issues

**Comment by mweststrate** [comment]
Sorry, yes indeed. Best start with the react-native section if you are
working on a RN app.

**Comment by EmilMakaev** [comment]
Thank you very much!

**Comment by nikoant** [comment]
> We'll check if we can make plugin loading more resilient, as it at least shouldn't affect other plugins to be loaded. cc @nikoant.

I checked - failed loading of a plugin does not affect loading of other plugins. So other plugins are now shown by other reasons.
