### ISSUE TITLE
Question: is generateCertificateSigningRequest leaking memory?

### ISSUE THREAD

**Issue by rdunlop** [facebook/flipper#1561]
I'm trying to troubleshoot a possible memory leak on my application, and I'm getting some indications from that there's a memory leak in generateCertificateSigningRequest.

I've looked, and I can't understand why there isn't a call to `free(pKey, x509_req, bne, privateKey, csrBio); ` before the final return in https://github.com/facebook/flipper/blob/master/xplat/Flipper/CertificateUtils.cpp#L210.

Shouldn't we always free the allocated memory for these variables, even in the case where all of the actions were successful (and we got to line 210)?

Thank you

**Comment by mweststrate** [comment]
cc @jknoxville

**Comment by anieve01** [comment]
@mweststrate @jknoxville the memory leak in iOS clearly visible in Instruments. My react native app crashes every 1 or 2. See screenshot attached. Will this leak happen when running the app production mode?
![Screen Shot 2020-11-08 at 9 47 29 PM](https://user-images.githubusercontent.com/1641831/98504554-27f12880-220c-11eb-8228-a553d00b063a.png)

**Comment by jknoxville** [comment]
Thanks very much for pointing this out @rdunlop I think you're right.

@anieve01 We recommend against initialising Flipper in production, so assuming you're not doing that then this won't affect production apps.

Fix coming up as soon as I verify there aren't any unexpected side effects.
