### ISSUE TITLE
Android log freezes the Flipper

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#1562]
## 🐛 Bug Report
I noticed when opening Flipper with connected Android device, the default pkugin will be `Log`, and this will try to display the logs from device `logcat`, but sometimes there is a lot of messages to process and it take freeze entire UI for one minute or so.
I tried to record the CPU usage of the Flipper process via DevTools (it would drop back to normal after another 30s):
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/5339061/94647580-56353b80-0323-11eb-8207-1fb20c368cd8.png">

## To Reproduce
Connect Android device and open Flipper after. It should try to collect also previous logs and show them in Flipper. Some devices/apps will generate a lot so this will take some time for Flipper to process.

## Environment
Device: Android
System: MacOS
Flipper: `0.52`

**Comment by mweststrate** [comment]
@usrbowe thanks for reporting, for me this is usually instant. Do you know if there is a lot of messages, or very large lines that  might cause this? If you have a saved profiler session that would be really great.

**Comment by usrbowe** [comment]
@mweststrate I can't share the log, but it's just massive amount of logs. Even pure adb logcat will run for few seconds to log the older messages.
If there is a way, I would just limit max number of logs it will log from history.

**Comment by mweststrate** [comment]
In flipper 0.81 we will no longer stream the old messages of the device logs, which should fix this problem. The network plugin will probably be optimised soon as well.
