### ISSUE TITLE
Question: duplicate symbol in Pods (Flipper) and external libraries

### ISSUE THREAD

**Issue by marcorm** [facebook/flipper#1565]
Hi all,
i know it's not strictly related to this lib, but we've got a problem building our app with react-native 0.63.3 and Flipper.
I already asked for help on stackoverflow, here's the [link](https://stackoverflow.com/q/64135172/1094045).

I paste here the same question:

---
I know there are tons of questions regarding this issue, but i didn't come up with solution.
We have in my project (react-native) a static library: let's call it `externalLib_v1.1r.a` that we added manually to my project. It always worked fine. It's a security library and we have no access to the source code.
With the new version of Flipper, that comes with latest versions of react-native, i have the following issue when building with Xcode:
```
duplicate symbol 'fileExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)' in:
    /Users/myuser/project/myproject/ios/externalLib_v1.1r.a(utility.o)
    /Users/myuser/Library/Developer/Xcode/DerivedData/proj-duwrxsmkbkccvdfykaajqslcqijq/Build/Products/Debug-iphonesimulator/Flipper/libFlipper.a(ConnectionContextStore.o)
ld: 1 duplicate symbol for architecture x86_64
```
There are 2 methods (1 inside `externalLib_v1.1r.a` and 1 inside ConnectionContextStore.cpp (Flipper)) with the same name.

If i manually rename the `fileExists` method inside the Flipper Pod it all works...
Is there a way to avoid this workaround?

Note: I have the -ObjC flag in "Other Linker Flags" of my project.

---

I hope someone can help.
Thanks

**Comment by mweststrate** [comment]
@marcorm looks like these utilities should be namespaced indeed in `namespace facebook { namespace flipper` indeed. Feel free to submit a PR if interested. (Probably you want to file the same issue on `externalLib`😅)

Double-check: cc @jknoxville these utilities aren't global on purpose I presume? I noticed that we don't use namespaces in e.g. CertificateUtils as well.

**Comment by marcorm** [comment]
> @marcorm looks like these utilities should be namespaced indeed in `namespace facebook { namespace flipper` indeed. Feel free to submit a PR if interested. (Probably you want to file the same issue on `externalLib`😅)
> 
> Double-check: cc @jknoxville these utilities aren't global on purpose I presume? I noticed that we don't use namespaces in e.g. CertificateUtils as well.

Hi @mweststrate, thanks a lot for the reply.
I don't know anything about cpp... i made some tests and applying this patch it all works well...
Can you confirm it is the right thing to do?

```diff
--- ConnectionContextStore.cpp	2020-10-07 16:34:51.000000000 +0200
+++ ConnectionContextStore_patched.cpp	2020-10-07 16:47:38.000000000 +0200
@@ -14,7 +14,8 @@
 #include "CertificateUtils.h"
 #include "Log.h"
 
-using namespace facebook::flipper;
+namespace facebook {
+namespace flipper {
 
 static constexpr auto CSR_FILE_NAME = "app.csr";
 static constexpr auto FLIPPER_CA_FILE_NAME = "sonarCA.crt";
@@ -164,3 +165,6 @@
   struct stat buffer;
   return stat(fileName.c_str(), &buffer) == 0;
 }
+
+} // namespace flipper
+} // namespace facebook

```

**Comment by priteshrnandgaonkar** [comment]
It looks right to me.

**Comment by mweststrate** [comment]
Fix has landed and will be part of next weeks release. Thanks for the contribution!
