### ISSUE TITLE
Other native JNI libraries (.so files) fail to load when using Sonar

### ISSUE THREAD

**Issue by kypeli** [facebook/flipper#157]
I'm trying to use Sonar 0.6.11. My app relies on other 3rd party JNI .so libraries as well and when I take Sonar into use, those other libraries fail to load. 

I tried to hunt down the reason for this and looks like the `SoLoader` class is doing some magic when loading Sonar's own native libraries, possible messing up the dynamic library paths from where to look for the JNI .so files, so my app won't find my `armeabi-v7a` dependency. I say this, because the stack trace telling me that it can't find the library any longer and which folders it tried to look from, does not contain the armeabi-v7a folder. Probably Sonar has overwritten the folders the app should look for dependencies and not including this one? 

SoLoader class has an interesting method `public static void setSystemLoadLibraryWrapper(SystemLoadLibraryWrapper wrapper)` which might be related, but I couldn't find a place in the code where this is being called. 

Sorry for a bit vague bug report, but this is what I can extract from my experience.

**Comment by passy** [comment]
I'm not an expert on SoLoader internals, but my impression was that it wouldn't touch things like `LD_LIBRARY_PATH`. How does you app load the library? By directly calling `Runtime.nativeLoad()` or one of its variants?

**Comment by kypeli** [comment]
Hrmph, this is a bit embarrassing for me since I cannot provide much information about this. We use a 3rd party SDK that is more or less a black box for us and the .so file that fails to load is part of that SDK. But unfortunately I don't know how the SDK itself load the .so file it is dependant on. 

I can only observe that the native .so file is placed under the armeabi-v7a folder and this folder is not in the list of folders Android runtime used when it tried to look for the native library.

**Comment by passy** [comment]
And I assume that by omitting the `SoLoader.init(...)` line, the old behaviour is restored and loading that library works? Do you see the `armeabi-v7a` folder in the output in that case too, or only when the load fails?

**Comment by kypeli** [comment]
If I remove the `SoLoader.init()` line, then there's an exception saying that Sonar is not initialised, so I cannot really say.

But here's something interesting I noticed:

```
07-16 15:33:38.942 3145-3145/com.myapp D/ApkSoSource: not allowing consideration of lib/arm64-v8a/libc++_shared.so: deferring to libdir
    **allowing considering of lib/armeabi-v7a/libMYLIB.so: libMYLIB.so not in system lib dir**
    not allowing consideration of lib/arm64-v8a/libevent.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libevent_core.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libevent_extra.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libfb.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libfolly.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libglog.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/librsocket.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libsonar.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libsonarcpp.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libsonarfb.so: deferring to libdir
    not allowing consideration of lib/arm64-v8a/libyoga.so: deferring to libdir
**07-16 15:33:38.943 3145-3145/com.myapp I/fb-UnpackingSoSource: extracting DSO libMYLIB.so**
```

From the log above you can see that Sonar is trying to do something my the dependency in question. So the .so file is found in the APK and also in the native library dir. 

However, I am bit worried that Sonar tries to use any random .so file as its plugin. What will Sonar do when it finds out this is not a supported plugin? Delete the file? Or does Sonar lock the file so Android cannot load it anymore?

**Comment by passy** [comment]
Yes, the Sonar error is expected then. I'm just curious if `SoLoader` alone is causing the issue or if it's the combination with Sonar that causes trouble.

**Comment by passy** [comment]
`.so` files aren't used as plugins and not randomly loaded by Sonar. There's just a bunch of C++ code powering the network layer to communicate with the desktop application. There's no custom logic around loading these things in Sonar, in general. All of that logic sits in SoLoader.

I've now seen other applications mixing Sonar with other bundled native libraries, so it doesn't seem like `SoLoader` requires all other native library loading steps to be handled differently, but perhaps the loading code for `libMYLIB` makes some assumptions which are no longer valid.

**Comment by kypeli** [comment]
Thanks for looking into this! If you've seen Sonar work with other apps that ship with native .so libraries bundled, then it seems this is not a generic bug, but something specific to my case. Which of course is a PITA and a shame for me. Unfortunately I am not sure how much more I can give input as I don't know how the library is loaded so really difficult to know my .so file fails to load. The error message I get is simply that DexLoader cannot find the file specified and then lists all the locations it tries to look in. 

So I don't blame you if you are closing this bug as not reproducible or something.

**Comment by passy** [comment]
I'd still be curious which part is responsible for the underlying issue. Have you been able to check if just initializing `SoLoader` on its own, without pulling in any of the other Sonar dependencies causes the the problem?

**Comment by bojankoma** [comment]
Resurrecting this issue because I still have the same issue in my project.
Running Flipper with SoLoader and (in my case) DeepMap SDK crashes the app with exception:
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__trunctfdf2" referenced by "/data/app/co.example.example.test.development-8WGgtCqw_HR03TtKYBabcQ==/lib/arm64/libhdmmapcore.so"...`

Since this is an active project in development, can I somehow assist in resolving this?
Using pickFirst didn't help:
```
packagingOptions {

        exclude 'META-INF/rxjava.properties'

        pickFirst 'lib/armeabi-v7a/libc++_shared.so'

        pickFirst 'lib/arm64-v8a/libc++_shared.so'

        pickFirst 'lib/x86/libc++_shared.so'

        pickFirst 'lib/x86_64/libc++_shared.so'

    } 
```

**Comment by passy** [comment]
@bojankoma Flipper is by default built with the `c++_shared` STL. Can you cehck that your app and DeepMap actually does the same? Otherwise, you'll run into the issues described here: https://developer.android.com/ndk/guides/cpp-support#one_stl_per_app

**Comment by passy** [comment]
As they mention in that paragraph, too, it's possible that different versions of the NDK that the SDK and Flipper are built against cause problems. Perhaps it would be advisable to build Flipper yourself against the version of the NDK and the STL you're using, to ensure that everything is indeed compatible.

**Comment by bojankoma** [comment]
@passy 
I understand but I'm not quite sure if that is the issue at hand. I ran the following for comparison:
```
./readelf -a /Users/bojan/Documents/Workspace/Python/elfnote/libhdmmapcore.so | grep NEEDED | grep _shared
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
```
```
./readelf -a /Users/bojan/Documents/Workspace/Python/elfnote/libflipper.so | grep NEEDED | grep _shared
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
```
Conclusion is (and correct me if I'm wrong please) they are both built with same STL. I guess pickFirst had to resolve my issue. But it doesn't, so I ran another comparison:
```
./readelf -dW /Users/bojan/Documents/Workspace/Python/elfnote/libhdmmapcore.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libandroid.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so]
 0x0000000000000001 (NEEDED)             Shared library: [libGLESv3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libEGL.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
```
```
./readelf -dW /Users/bojan/Documents/Workspace/Python/elfnote/libflipper.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libflipperfb.so]
 0x0000000000000001 (NEEDED)             Shared library: [libandroid.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libevent_extra.so]
 0x0000000000000001 (NEEDED)             Shared library: [libevent_core.so]
 0x0000000000000001 (NEEDED)             Shared library: [libevent.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
```
I can see an extra libstdc++.so in DeepMap SDK library but I don't think its an issue, or is it?

Lastly, I tried to dump notes in order to see any NDK versions or other data:
```
./readelf -n /Users/bojan/Documents/Workspace/Python/elfnote/libhdmmapcore.so

Displaying notes found at file offset 0x000001c8 with length 0x00000024:
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: da9e029bc9b0395d210e695864d5512571dd6ea6
```
```
./readelf -n /Users/bojan/Documents/Workspace/Python/elfnote/libflipper.so

Displaying notes found at file offset 0x00000200 with length 0x00000024:
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 96f247615f0fc320c56f998385a2d4b47e73f77d

Displaying notes found at file offset 0x005af6e0 with length 0x00000098:
  Owner                 Data size	Description
  Android              0x00000084	NT_VERSION (version)
```

Nothing useful there...
My last chance is checking for different versions of libc++_shared.so lacking support for the other SDK, depending which pickFirst picks (I guess it picks Flippers, since DeepMap doesn't work), but I'm not really sure how to do it? Any suggestions?

Is there anything else I can do, besides dropping one of the dependencies from the project?

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
