### ISSUE TITLE
No-op dependency

### ISSUE THREAD

**Issue by ubuntudroid** [facebook/flipper#158]
As the plugin usually is just used in debug build types it would be awesome to have a no-op dependency for non-debug build types to keep the code free from debug switches and not having to write own no-op wrappers for other build types.

**Comment by theGlenn** [comment]
Any news on this ?
Implementing flavor specific application class seems like a hassle atm.

**Comment by theGlenn** [comment]
@ubuntudroid As a temporary solution I've implemented a somewhat simple but helpful no-op library.
https://github.com/theGlenn/flipper-android-no-op

**Comment by lijy91** [comment]
For my [flutter_flipperkit](https://github.com/blankapp/flutter_flipperkit) project, I create a  [flipper-no-op](https://github.com/blankapp/flutter_flipperkit/tree/master/android/flipper-no-op) module for release mode.

I hope this module is provided by the flipper

**Comment by jaychang0917** [comment]
What is the state now? I found the `com.facebook.flipper:flipper-noop:0.21.0` is not working at all.

**Comment by passy** [comment]
@jaychang0917 Can you elaborate?

**Comment by ubuntudroid** [comment]
@passy I've just noticed the same: the flipper plugins (that is, their API) are not covered by the no-op artifact meaning you get compilation errors when using plugins and building build types declaring the no-op dependency.

**Comment by jaychang0917** [comment]
I managed to wrap the setup of flipper to a class (e.g. `FlipperHelper`) and put it in `src/debug/java` and provide a no-op `FlipperHelper` in `src/release/java`, then I don't need the flipper no-op dependency now.

**Comment by passy** [comment]
@jaychang0917 That's what we recommend. We won't be able to maintain a full no-op copy of all the plugins and the code size of the dependency at that point would be non-negligible which kinda defeats the point.

We do the same in our sample app: https://github.com/facebook/flipper/blob/master/android/sample/src/release/java/com/facebook/flipper/sample/FlipperInitializer.java

I'll close this issue here but please let us know if there's a way in which we can make this more useful.

**Comment by e16din** [comment]
The problem still persists on Flipper 0.85.0 with soloader and network plugin

**Comment by podocodenick** [comment]
Any solution?

**Comment by e16din** [comment]
The problem still persists on Flipper 0.126.0

**Comment by gturedi** [comment]
The problem still persists on Flipper 0.140.0
