### ISSUE TITLE
Unexpected token o in JSON at position 0 

### ISSUE THREAD

**Issue by OrLevy23** [facebook/flipper#1598]
## 🐛 Bug Report
Not a lot of data. after i've upgraded to xcode 12 i've started to see this error on flipper (
![image](https://user-images.githubusercontent.com/21291210/96023104-92f04f00-0e5a-11eb-990c-d6a38d193583.png)
and i can't seem to get passed this.
I suspect that this comes from here, as before i had a different issue where iPhone XR was with non-ASCII character (Weird R) :
`~ /Users/orlevy/.pyenv/shims/idb list-targets --json                                                                                                                                                          
opened
<_io.TextIOWrapper name='/tmp/idb_local_targets' mode='r' encoding='UTF-8'>
{"name": "iPad (8th generation)", "udid": "5A47F314-DD73-40B7-93F8-ABE8E36D80C1", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPad (6th generation)", "udid": "23CB5CB6-AAE9-43E4-B44F-C5558628E474", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (12.9-inch)", "udid": "DD4CC3AA-4447-4B7B-857F-1678228BBB33", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPod touch (7th generation)", "udid": "A06A005D-9C73-4B16-810B-79BCD8823B7A", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPad Air (3rd generation)", "udid": "52FFF207-F1D8-4DC7-A730-C500CE6B6B4C", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPhone 8 Plus", "udid": "64AD0305-6E07-4A90-8CD3-B2184BE1604F", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone 8 Plus", "udid": "CC8AEB16-FBC9-4B15-A1E0-93983473D7AA", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "Apple TV 4K", "udid": "4DE6D52F-ECFB-4FA1-8DD5-85A1FFE9BF18", "state": "Shutdown", "type": "simulator", "os_version": "tvOS 14.0", "architecture": "x86_64"}
{"name": "iPad Pro (9.7-inch)", "udid": "7C20F7E3-F650-4478-B0A7-A3E17AE54AC2", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPhone 7", "udid": "9E4A3D96-F4A7-4990-905E-D9BF32D85C42", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone 6 Plus", "udid": "3BEF4CB2-4C5B-42B4-8F50-AEB01D15477D", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone 8 Plus", "udid": "4D84260A-CD02-4F2F-BFC5-8D0D6B7A3FE3", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPad Pro (11-inch) (2nd generation)", "udid": "FE50DB24-95C4-4499-9AA0-D37254E9DCE7", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPhone 6", "udid": "2831A2F5-FF77-42D6-BDEE-A46BAFC4D9D8", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (12.9-inch) (4th generation)", "udid": "BFC1F8DC-92D7-43DB-967B-4E772BAE4118", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPhone SE (2nd generation)", "udid": "1946A03E-7BC0-42BC-9A36-0A9605586B23", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPhone 8", "udid": "9DB1FD9C-434E-40AE-BCD6-E17888CB1D08", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPad Pro (9.7-inch)", "udid": "B9D18DC8-2150-4229-BEAD-26B925AA8A3B", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone XS", "udid": "CB69930C-2CF0-41A9-B7EE-53F4A0AF2DF9", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (10.5-inch)", "udid": "1B94B3E6-4910-452A-A913-5D9ED5950166", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone 5s", "udid": "BBA07387-FC87-4056-A9F2-8F42B5B25EC4", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (12.9-inch) (3rd generation)", "udid": "EB07FF5A-D2CC-4AEF-834C-8F35018B824E", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (12.9-inch) (4th generation)", "udid": "F236BE36-EFD8-4B67-B340-E13A26C210CA", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPhone 11 Pro", "udid": "90A04D72-E458-4ED7-9417-133068E46D8B", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPhone SE (2nd generation)", "udid": "545F386E-768C-486E-9950-68DBFFD4F035", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "Apple Watch Series 6 - 40mm", "udid": "994E2F29-340E-4EE9-B414-046BA672DF26", "state": "Shutdown", "type": "simulator", "os_version": "watchOS 7.0", "architecture": "x86_64"}
{"name": "iPhone 6s Plus", "udid": "CC7944EF-EBFE-410D-826A-D3337325ED39", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (11-inch)", "udid": "EF38535E-DB40-48B9-8713-F1AA6C7A98DC", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone SE", "udid": "7D51D26E-75D0-44CB-9E4C-B9E9AF29BD2A", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad (5th generation)", "udid": "80C00F03-4DD2-468A-8AC0-E89004787510", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone XS Max", "udid": "C47B618C-8FC2-458F-993C-BFEA50566F2F", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad (7th generation)", "udid": "D867B199-CBB1-4715-98C2-3ED69ABDA05B", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "Apple TV 4K (at 1080p)", "udid": "DAB993AD-FE42-4815-9233-C4D6838DFF36", "state": "Shutdown", "type": "simulator", "os_version": "tvOS 14.0", "architecture": "x86_64"}
{"name": "iPhone 11 Pro Max", "udid": "62C15B15-0BF5-41AD-8342-2C22F3115A34", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "Apple Watch Series 5 - 44mm", "udid": "91D215B4-1300-49C7-907E-AA7A204479A1", "state": "Shutdown", "type": "simulator", "os_version": "watchOS 7.0", "architecture": "x86_64"}
{"name": "iPhone 11 Pro", "udid": "A184DC58-42AD-4160-B0F4-B2BD7212D873", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPad Air 2", "udid": "ECB7CFA5-2813-4820-AA86-85C6BF0A529E", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (12.9-inch) (4th generation)", "udid": "6A1F87D1-3CAB-42C6-8889-B3B17233200D", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "Or", "udid": "00008027-000B681C3E87002E", "state": "Booted", "type": "device", "os_version": "iOS 14.0.1", "architecture": "arm64e"}
{"name": "iPad Pro (12.9-inch) (2nd generation)", "udid": "CC3760CD-E297-40C4-AE4B-2118807C4994", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Pro (9.7-inch)", "udid": "78B2F52E-84BD-4E63-B90D-F98A9F4EA9AD", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPad Pro (11-inch) (2nd generation)", "udid": "850EF0A4-C7B1-4BBC-9C1D-165F901C5782", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPhone 6s", "udid": "F05FE72D-D2D8-468F-AEAC-146F7A49F09F", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone X", "udid": "31E49B47-8C88-464F-999A-7FC15CD2A066", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone 11", "udid": "02C780D0-7692-40D4-8F89-C2BFDC9035D2", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "iPhone 8", "udid": "32F1A826-99F2-4EBA-B22A-DFF631CA7DE2", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPhone 8", "udid": "7D09131A-BC7C-4AAC-928A-B2F9D746521B", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "Apple Watch Series 5 - 40mm", "udid": "A6B45CF0-994D-411E-81E6-60AB8C49FED8", "state": "Shutdown", "type": "simulator", "os_version": "watchOS 7.0", "architecture": "x86_64"}
{"name": "iPhone 7 Plus", "udid": "19BD898E-5983-43C3-B14D-7FFB517CDE3F", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Air", "udid": "95775F15-7E90-403F-955E-6C2F5740BFF4", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPhone 11 Pro Max", "udid": "A17E4605-77C1-4BC6-B4B3-6C49779BC144", "state": "Shutdown", "type": "simulator", "os_version": "iOS 13.5", "architecture": "x86_64"}
{"name": "Apple TV", "udid": "9BAA8C2F-3851-4740-AA35-4FD8FA7BD71D", "state": "Shutdown", "type": "simulator", "os_version": "tvOS 14.0", "architecture": "x86_64"}
{"name": "iPhone 11", "udid": "1BDD2049-BA9E-44ED-BA11-E1A16B6D0A4D", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "iPhone XR", "udid": "14220A90-6C2D-446A-BDB2-F89DDC2361F7", "state": "Shutdown", "type": "simulator", "os_version": "iOS 12.1", "architecture": "x86_64"}
{"name": "iPad Air (4th generation)", "udid": "B8DEF250-C2F6-4912-A04F-C296F65A9A71", "state": "Shutdown", "type": "simulator", "os_version": "iOS 14.0", "architecture": "x86_64"}
{"name": "Apple Watch Series 6 - 44mm", "udid": "72DE4D9C-B131-462F-8C2F-8DA940E79B36", "state": "Shutdown", "type": "simulator", "os_version": "watchOS 7.0", "architecture": "x86_64"}`

## To Reproduce
Open Flipper

## Environment
Flipper version 0.62 (also happened on 0.60)
MACOS 10.15.6 (19G2021)
React-Native 0.63.3

**Comment by OrLevy23** [comment]
any help with this? 
now i've returned to get the unicode error:
```Command failed: /Users/orlevy/.pyenv/shims/idb list-targets --json
2020-10-22 15:50:56,794 [ERROR] - root - Exception thrown in main

Traceback (most recent call last):

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/cli/main.py", line 211, in gen_main

    await root_command.run(args)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/cli/commands/base.py", line 94, in run

    return await self._get_subcommand_for_args(args).run(args)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/cli/commands/base.py", line 126, in run

    await self._run_impl(args)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/cli/commands/base.py", line 157, in _run_impl

    await self.run_with_client(args=args, client=client)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/cli/commands/list_targets.py", line 24, in run_with_client

    targets = await client.list_targets()

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/common/logging.py", line 110, in _async_wrapper

    raise self.translate_exception(ex)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/common/logging.py", line 85, in _async_wrapper

    value = await function(*args, **kwargs)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/client/grpc.py", line 151, in func_wrapper

    return await func(*args, **kwargs)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/client/grpc.py", line 831, in list_targets

    local_targets = self.local_targets_manager.get_local_targets()

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/common/local_targets_manager.py", line 27, in get_local_targets

    self.local_targets = self._load()

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/idb/common/local_targets_manager.py", line 36, in _load

    targets_list = json.load(f)

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/json/__init__.py", line 296, in load

    return loads(fp.read(),

  File "/Users/orlevy/.pyenv/versions/3.6.5/lib/python3.6/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 8325: ordinal not in range(128```



and indeed on the file i see this characters ```"name":"iPhone Xʀ"```

**Comment by nikoant** [comment]
Hi @OrLevy23, could you try renaming "iPhone Xʀ" simulator in XCode -> Window -> Devices and Simulators?

![Screenshot 2020-10-22 at 18 30 46](https://user-images.githubusercontent.com/6248652/96908909-29dd8c80-1495-11eb-9a5d-a1a453684710.png)

**Comment by passy** [comment]
This looks like a bug in idb. Would be great to report it there. :)

**Comment by passy** [comment]
I'll close this here but please let us know if something trips up Flipper.

**Comment by OrLevy23** [comment]
issue appeared to be indeed with idb, uninstalled and reinstalled have solved it.
thanks
