### ISSUE TITLE
How to close/hide expression watcher?

### ISSUE THREAD

**Issue by mskri** [facebook/flipper#1611]
After updating flipper to version 0.63.0 (50.0.0) there does not seem to be a way to close the "Expression Watcher"?

Previously you were able to close it by closing the right side panel but now you can only "collapse" it. The collapse action just collapses the content but the height of the panel does not change. When not in use the panel just wastes space at the bottom.

**Comment by mweststrate** [comment]
I noticed the same yesterday and fixed it, so next weeks release should address it :). Thanks for reporting though!
