### ISSUE TITLE
Right Side-panel content displaying in main content space & unscrollable. After Flipper 0.63 upgrade

### ISSUE THREAD

**Issue by tdoran** [facebook/flipper#1613]
## 🐛 Bug Report

Content that usually displays in the right-side panel is now displaying in the main panel, covering the content in the main panel, and is unscrollable (so mostly can't be used). The right-panel button is unresponsive and doesn't open the panel. This is the case for most plugins (e.g. `Network` and `Redux Debugger`)

To workaround this issue, switch to the `Layout` plugin, which has the right-panel open, and then switch back to another plugin. The content should now display in the right panel.

## To Reproduce

Upgrade Flipper to 0.63. Inspect the Network plugin and click a network request, or inspect the redux-debugger plugin and click an action item.

## Environment

Flipper desktop 0.63.0
react-native 0.63.2
react-native-flipper 0.62.0
redux-flipper 1.4.0
MacOS 10.14.6 & 10.15.6

<img width="1680" alt="Screenshot 2020-10-23 at 13 17 59" src="https://user-images.githubusercontent.com/29519739/97002949-9eb2d400-1532-11eb-8ed3-20a33401b0f9.png">

**Comment by mweststrate** [comment]
Yes, apologies for this one! I introduced a subtle race condition when converting from class to hook component :/. A fix landed yesterday, but some infra issues hinders pushing out a new release straight away. So I recommend to stick to 0.62 for now as work around.

**Comment by joe-goodall-ticketmaster** [comment]
@mweststrate How do you get version 0.62.0? When I download from [Flipper](https://fbflipper.com/) there's no option to download a specific version (0.63.0 is downloaded automatically).

**Comment by mweststrate** [comment]
https://github.com/facebook/flipper/releases/tag/v0.62.0

**Comment by passy** [comment]
Closing this as the fix is landed in master and we have a temporary workaround until the 0.64 is out. :)
