### ISSUE TITLE
Network plugin shows non-latin characters incorrectly

### ISSUE THREAD

**Issue by keymusicman** [facebook/flipper#1629]
## 🐛 Bug Report
Network plugin seems to display non-latin characters incorrectly

## To Reproduce
In my case there are Russian characters that are displayed incorrectly when network request is made. On the screenshot below you can compare how Stetho and Flipper display the same response. The example word that is displayed incorrectly: "Москва".
![image](https://user-images.githubusercontent.com/30913903/97111457-f0ed2400-16ef-11eb-86be-915fd452b676.png)

### Flipper Desktop:
0.62

### Android:
any api
flipper library - 0.62.0
network-plugin library - 0.62.0

### OS:
MacOS Cataling 10.15.6

**Comment by mweststrate** [comment]
We fixed some issues in this area recently. Could you confirm this still occurs in Flipper Desktop 0.63? If that is the case, please do share a publicly available idempotent endpoint on which we could verify this issue. Your request is utf8 encoded, which should at this moment work correctly, but the absence of gzip could make a difference.

**Comment by keymusicman** [comment]
Just tried Flipper desktop v0.63 and it works. Thanks and sorry for bothering you.

**Comment by passy** [comment]
@keymusicman No problem at all. I'm glad it works now. :)
