### ISSUE TITLE
OkHttp plugin should report on failed requests

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#163]
i.e. throwing IOException (dns, network connectivity) instead of a 500, 401 etc.

https://github.com/facebook/Sonar/blob/master/android/plugins/network/SonarOkhttpInterceptor.java#L37

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!
