### ISSUE TITLE
Docs: Failed to resolve 0.64.0

### ISSUE THREAD

**Issue by mune0903** [facebook/flipper#1637]
Hi, thanks for amazing library.

I think there's a mistake here. I think the answer should be  0.63.0, not 0.64.0.
https://fbflipper.com/docs/getting-started/android-native
<img width="1044" alt="スクリーンショット 2020-10-29 13 57 00" src="https://user-images.githubusercontent.com/28261278/97527431-a53bc280-19ee-11eb-809f-e106d6b54511.png">

**Comment by aLT22** [comment]
Yes, the correct version is `0.63.0` on the 30.10.2020

**Comment by cekkaewnumchai** [comment]
Sorry for the inconvenience, I'll try to fix this by updating the version to 0.65.0 by tomorrow or the day after tomorrow.

**Comment by nikoant** [comment]
I'm republishing packages for failed 0.64 release.

**Comment by mune0903** [comment]
I am grateful for your quick and deliberate response to my issue.
