### ISSUE TITLE
Question: FlipperKit 0.63.0 not published to CocoaPods?

### ISSUE THREAD

**Issue by lukeramsden** [facebook/flipper#1638]
https://cocoapods.org/pods/FlipperKit

https://github.com/facebook/flipper/runs/1288162036?check_suite_focus=true

Seems like the "retry 20 times" hack to get around the eventual consistency problem from https://github.com/CocoaPods/CocoaPods/issues/9502#issuecomment-579486258 must have failed in this instance.

**Comment by cekkaewnumchai** [comment]
Thank you for notifying this to us. In worst case, I'll try to push version 0.65.0 on tomorrow or the day after tomorrow.

**Comment by caycecollins** [comment]
@cekkaewnumchai it's been a couple weeks since you mentioned a day or two fix... any update? Was there something blocking the cocoapods update?

**Comment by nikoant** [comment]
@caycecollins, thanks for bringing this up. It looks like we've missed that they have not been published because the build workflow was green, but it actually failed. I'm checking this now.

**Comment by oblador** [comment]
@nikoant I can see that you merged a fix https://github.com/facebook/flipper/pull/1696, but AFAICT `0.62` is still the latest version on cocoapods. Would you mind trying to kick off the release automation manually?

**Comment by nikoant** [comment]
I've kicked off the publishing workflow manually. Version 0.66.0 is available now: https://cocoapods.org/pods/FlipperKit
