### ISSUE TITLE
OkHttp plugin doesn't handle duplicate headers

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#164]
https://github.com/facebook/Sonar/blob/master/android/plugins/network/SonarOkhttpInterceptor.java#L96

Keys can have duplicates, but call to get will return the first value only in case of duplicates

alternate processing code https://github.com/square/okhttp/blob/5785e1b4f6fdb782b87ceaa4460bc4fca28d747c/okhttp/src/main/java/okhttp3/Headers.java#L179-L191

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!
