### ISSUE TITLE
Discussion: Create export/import feature in Network Plugin for Routes (Mock API calls)

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1651]
Provide feature to allow developer to export definitions of mock requests so they can be shared with another user.

Provide feature to allow developer to import definitions of mock requests created by another user into the Network Plugin.

Provide feature to allow developer to create Routes (mocks) from network data imported from another user.

Use Case
=======

In large enterprises, a separate QA team may be responsible for testing an app.  App behavior is usually depended on Network API calls.  

When the QA team finds a defect, it would be useful to save the Network calls that are involved in the defective behavior.  (This is already provided by the export/import feature - however, these imported calls can't be turned into mocks)

The developer should be able to import the network requests and convert them to mocks (routes).  This would allow the developer to fix the functionality without having to create test data that might only be available to QA.  QA could also then use the mock data to verify that the defect has been fixed.

Current functionality
=====================

Flipper currently has a method for saving Network calls but definitions of mock requests (routes) are not saved.

When a user imports saved Network calls, a new fake device instance is created in Flipper which allows the user to see network calls. Th However, there is no mechanism for creating mocks from these calls and using them in a "live" Flipper session.

**Comment by cekkaewnumchai** [comment]
These features will be quite useful for people who regularly use mocking functionality on network plugin.

We may not have cycle to do this immediately. However, if you are interested in doing this, you can PR so that we can review it.

**Comment by bizzguy** [comment]
@cekkaewnumchai @mweststrate 

I'm starting to work on this PR.  I'm starting out by adding an "Export" button to the Mock dialog.

![image](https://user-images.githubusercontent.com/337874/103023284-4c326b80-4513-11eb-9a19-ed45bb2c36b3.png)

My plan is to use the "startFileExport" util function as the model:

![image](https://user-images.githubusercontent.com/337874/103023506-b814d400-4513-11eb-97a8-b75e6a3dd941.png)

However, I can't seem to figure out how to get the "store" property from the Network plugin like the MenuBar does. 

I'm hoping you can point me in the right direction.  How do I access the "store" so I can pass it to the export function?

**Comment by bizzguy** [comment]
@mweststrate  I'm attempting to create a PR for saving routes separately from the other data (network, logs, etc).  I'm planning to use the same technique and file format.  The menubar saves all the data and I'm trying to use that technique but getting stuck right away.  Can you offer any help on how to get a "dispatch" object from in a plugin?

**Comment by mweststrate** [comment]
@bizzguy, since this seems to be a feature for this specific plugin only, I'd forego using the central export / import mechanism and takes the routes and makes, serialize them as JSON, and directly write them to / read them from a file. Does that make sense?

**Comment by bizzguy** [comment]
@mweststrate   I think that approach would be simpler in the short term (at least for me coding it).  Although, it does mean that routes would continue to be excluded from the central export/import mechanism.  The primary use case that I envision is someone on the QA team saving the routes on bug reports so that a developer could more easily fix (and confirm) an error.  This would probably only require that the routes be saved and not the other plugin data (logs, etc).  So I'm good with going with a separate plugin specific export/import for now.

**Comment by mweststrate** [comment]
Yeah, I think that'd be the safest route for now, especially since we have
some upcoming refactorings in the persistence API's :) I think we could
actually introduce `toJSON` (and fromJSON) support on the `Atom`s exposed
from createState if that would help!

**Comment by bizzguy** [comment]
@mweststrate Having the JSON methods would be a big help.  It would also be useful to have an argument in the "to" method that would provide pretty-printing (a single name/value pair on each line) - there are a few places where JSON is displayed as a single line which makes it hard to read).

**Comment by mweststrate** [comment]
Note that the standard APIs can already pretty print: `JSON.stringify(someObject, null, 2)`
