### ISSUE TITLE
Discussion: Hard time inspecting RN apps' layout

### ISSUE THREAD

**Issue by Fausto95** [facebook/flipper#1653]
Hi there, first things first, thanks for Flipper.

While Flipper works well for Logs, Crash Reports et al, I have hard times when trying to inspect the layout of React Native apps. Expanding all the elements(yes, I'm aware of the `expand all child elements` option) of the tree-hell until reach the desirable elements takes an amount of time and efforts. 
 

Would be nice if we could somehow improve this experience. What would also be much nicer is to show the actual view names instead of `RTCView`(I'm aware of the constraints imposed by this one).

<img width="313" alt="Capture d’écran 2020-11-04 à 16 35 31" src="https://user-images.githubusercontent.com/23306911/98162035-0678ff80-1ee1-11eb-8052-c4ad9ebc39ae.png">

**Comment by mweststrate** [comment]
We do have optimising the tree expansion speed on our roadmap, but it will probably take a while to get there as we have to refactor some internal APIs
