### ISSUE TITLE
Question: Plugin disabled by macOS Gatekeeper

### ISSUE THREAD

**Issue by morikawa77** [facebook/flipper#1680]
Hi,

I installed Flipper for Mac and I have a lot requests from gatekeeper, I think one is missed and now when I open ‘Manage Plugins’ the plugin status for ‘flipper-plugin-sections’ is ‘GK disabled’.

With this, when I try to inspect, some panels are missing.
I trying to uninstall several times, delete folder ~/.flipper and ~/Library/ApplicationSupport/Flipper and looks like I never uninstall the app.

Can you help me in advance?

**Comment by mweststrate** [comment]
Thanks for noticing! It looks that this plugin was exposed publicly by accident, we'll make it internal in the next release.
