### ISSUE TITLE
Question:  Error: not found: emulator

### ISSUE THREAD

**Issue by Rodrigo001-de** [facebook/flipper#1689]
at getNotFoundError (file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3656:207)

at file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3656:766

at new Promise (<anonymous>)

at step (file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3656:700)

at file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3656:974

at new Promise (<anonymous>)

at subStep (file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3656:929)

at file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3656:1079

at file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3657:358

at file:///C:/Users/Usuario/Flipper/resources/app/bundle.js:3658:520

at FSReqCallback.oncomplete (fs.js:171:21)

**Comment by Rodrigo001-de** [comment]
I find this error when I click on launch emulator and then on the name of my emulator, it says that the emulator was not found but then because the name of my emulator appears

The errors that appear in the doctor are:
OpenSSL Installed (I think this is not quite a mistake)
OpenSSL (https://wiki.openssl.org/index.php/Binaries) is not installed or not added to PATH. Command "openssl version" failed to execute with output: Command failed: openssl version 'openssl' is not recognized as an internal or external command, an operable program or a batch file. .

and Watchman Installed (I think this is not quite a mistake)

Watchman file watching service (https://facebook.github.io/watchman/) is not installed or not added to PATH. Live reloading after changes during Flipper plugin development is disabled.

I am using the v12.16.2 version of the node

**Comment by mweststrate** [comment]
Closing as you already opened #1688
