### ISSUE TITLE
Support for plaintext WebSocket transport

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#169]
Consider optional (disabled by default) support for Websocket transport.  Would allow remote clients without certificate swap via adb etc.  Could advertise (zeroconf?) for clients to find sonar instances in local network.

Also with websocket, then a lightweight (no native dependencies) version of the Android library could be supported.

package.json
```
+    "rsocket-websocket-server": "^0.0.6",
```

src/server.js
```
+import RSocketWebSocketServer from 'rsocket-websocket-server';


+     const transport = new RSocketTCPServer({
+       port: port,
+       serverFactory: serverFactory,
+     });
+
+    // server: ...
+    // https://github.com/websockets/ws
+//     const transport = new RSocketWebSocketServer({
+//       port: port,
+//     });
     const rsServer = new RSocketServer({
       getRequestHandler: sslConfig
         ? this._trustedRequestHandler
         : this._untrustedRequestHandler,
-      transport: new RSocketTCPServer({
-        port: port,
-        serverFactory: serverFactory,
-      }),
+      transport: transport,
     });
```

**Comment by jknoxville** [comment]
I think we should split this into two issues.

1. Add an optional opt-out of the secure protocol.
  I think we should definitely do this. It should be pretty simple and for one thing will unlock iOS support for a lot of users.

2. Lightweight library with no native code.
   I haven't thought about this much. One reason a lot on sonar is written in C++ is to allow for code sharing across platforms (with iOS). It would be a considerable rewrite to port it to java, and then we'd have to maintain more code.
Out of interest, what is your concern with native dependencies? App size? Complexity? Compatibility?

**Comment by yschimke** [comment]
+1 to splitting.

I raised https://github.com/facebook/Sonar/issues/170 for the second. I'm kicking that around, don't expect you to build or support.  To be honest, I think the choices made are only clearcut if you are inside FB.  Outside, I think the simplicity of a pure java mobile library will outweigh the benefits of code sharing.  That shared layer should be very thin on mobile.  My 2c.

**Comment by yschimke** [comment]
Raised https://github.com/facebook/flipper/issues/234 for the first issue

**Comment by yschimke** [comment]
covered in other tasks now
