### ISSUE TITLE
Can't see any plugin on flipper

### ISSUE THREAD

**Issue by iradkot** [facebook/flipper#1697]
## 🐛 Bug Report
  I recently upgraded my react-native version from 0.57 to 0.63
  And wanted to debug my app on flipper - did all necessary setups in flipper guidelines and plugins guidlines 
  I can see my react-native logs and my emulator on flipper but I cant see any plugin I install
  Using flipper 0.61
  Not sure if its related but under Debug Logs section I see the following error:
  Version check failure:  Server responded with . 
![image](https://user-images.githubusercontent.com/20597244/99881773-6cc18a00-2c24-11eb-9ed8-d809b02a9621.png)

## To Reproduce
  Steps to reproduce the behavior.
  Install flipper and try installing plugins as well

## Environment
  Working on windows 10 
  react-native : 0.63.3
  react-native-flipper: 0.66.0

**Comment by nikoant** [comment]
Hi @iradkot, could you click to "Manage plugins" to check status of your installed plugins there?

**Comment by iradkot** [comment]
> Hi @iradkot, could you click to "Manage plugins" to check status of your installed plugins there?

This is what I see
![image](https://user-images.githubusercontent.com/20597244/100537021-959ddc80-322d-11eb-9317-8d86be893b55.png)

So, I see the list, but I don't see the plugins I installed (I see only plugins added by flipper)

**Comment by iradkotton** [comment]
And on android emulator this is what I see:
![image](https://user-images.githubusercontent.com/70887949/100540695-7c098e80-3247-11eb-8d06-46577c0e6527.png)

**Comment by sylvanaar** [comment]
I see the same but I ran the troubleshooter - and it says there are connection problems, so I am looking to troubleshoot those

![image](https://user-images.githubusercontent.com/114616/100734485-9ac16f80-3384-11eb-879c-ad656fb23e5c.png)

**Comment by mweststrate** [comment]
Closing this issue as it looks stale and having several different reports. Preferably open new issues rather than piggy backing on existing ones. Many different causes can lead to the same symptoms without needing the same solution.
