### ISSUE TITLE
Lightweight pure java/kotlin library

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#170]
I was looking at making at a lightweight version of the android plugin just requiring

- kotlin
- okhttp
- rsocket-kotlin
- okhttp

https://github.com/yschimke/kona

Basically a headsup, as I assume the internal FB stuff will stay native for good reason.

If you are already working on something similar, then happy to avoid duplication.

**Comment by jknoxville** [comment]
I think that would be useful, and potentially we might want to move to something like that in future, but at the moment we aren't putting any time into doing it.

One thing to bear in mind is that the sonar "protocol" is still quite immature, for one thing it has no concept of versioning. And I expect we'll be iterating on it as time goes by, improving support for backwards compatibility etc. Having said that, we haven't made many substantial changes other than transport protocol (websocket -> rsocket) for quite some time.

Having multiple implementations in the early stages could be churn-ey, but that's just something to consider.
