### ISSUE TITLE
Document network protocol

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#171]
Could we add this to the Wiki?  Starting here as a draft

insecure connection - tcp://10.0.2.2:8089 

secure connection - tcp://10.0.2.2:8088 (uses certs installed via adb)

setup payload {"app": "$app","os": "$os","device": "$device"}

fireAndForget (desktop -> mobile) {"id": 0, "method": "getPlugins"} 
fireAndForget (mobile -> desktop) {"id": 0, "success": {"plugins": ["Sandbox", "Network"]}}

10.0.2.2 is default android bridge connection

**Comment by yschimke** [comment]
It would be good to consider using more features of RSocket in a V2 of the protocol e.g. keepalives, requestResponse, requestStream, etc.  Could avoid a lot of custom logic for correlating responses, timeouts, registering interest in streams etc.

**Comment by yschimke** [comment]
Just noticed https://fbflipper.com/docs/establishing-a-connection.html

It would be good to expand on this with concrete examples

**Comment by vkotovv** [comment]
@yschimke your link is no longer working.

**Comment by passy** [comment]
This got expanded and now lives here: https://fbflipper.com/docs/extending/establishing-a-connection.html
