### ISSUE TITLE
Question: how to package my custom plugin as a File while using antd?

### ISSUE THREAD

**Issue by galex** [facebook/flipper#1713]
Hello,

I've made a desktop plugin that is almost the same as the `seamammals` plugin. 
I can run flipper and I can use my plugin, all is good.
Now, I would like to package this plugin as a file to distribute it to a few devs in my teams, so I ran the following:
```
flipper-pkg pack plugins/seamammals -o ~/Desktop
```
The result is the following:
```
Compiling... !
    Error: Unable to resolve module antd from /Users/myuser/github/flipper/desktop/plugins/seamammals/src/index.tsx: antd could not be found within 
    the project or in these directories:
      ../../node_modules

    If you are sure the module exists, try these steps:
     1. Clear watchman watches: watchman watch-del-all
     2. Delete node_modules and run yarn install
     3. Reset Metro's cache: yarn start --reset-cache
     4. Remove the cache: rm -rf /tmp/metro-*
       9 | 
      10 | import React, {memo} from 'react';
    > 11 | import {Typography, Card} from 'antd';
         |                                 ^
      12 | import {
      13 |   Layout,
      14 |   PluginClient,
```
By the way, I do see the `antd` module in `../../node_modules`, so I don't understand the issue.
That's what the [documentation](https://fbflipper.com/docs/extending/js-setup#publishing-to-npm) tells us to do, so what am I doing wrong here? 

Thank you in advance!

**Comment by mweststrate** [comment]
Did you specify antd bothbas peer- and dev dependency?

**Comment by galex** [comment]
> Did you specify antd bothbas peer- and dev dependency?

Yes, I've tried that: 

```
{
  "$schema": "https://fbflipper.com/schemas/plugin-package/v2.json",
  "name": "myplugin",
  "id": "myplugin-id",
  "version": "0.0.1",
  "main": "dist/bundle.js",
  "flipperBundlerEntry": "src/index.tsx",
  "license": "MIT",
  "keywords": ["flipper-plugin"],
  "title": "myplugin",
  "icon": "apps",
  "bugs": {
    "email": "you@example.com"
  },
  "scripts": {
    "lint": "flipper-pkg lint",
    "prepack": "flipper-pkg lint && flipper-pkg bundle"
  },
  "peerDependencies": {
    "antd":"latest",
    "flipper": "latest",
    "flipper-plugin": "latest"
  },
  "devDependencies": {
    "antd":"latest",
    "flipper": "latest",
    "flipper-plugin": "latest",
    "flipper-pkg": "latest"
  }
}
```
Same result:
```
Compiling... !
    Error: Unable to resolve module antd from /Users/myuser/github/flipper/desktop/plugins/myplugin/src/index.tsx: antd could not be found within the 
    project or in these directories:
      ../../node_modules

    If you are sure the module exists, try these steps:
     1. Clear watchman watches: watchman watch-del-all
     2. Delete node_modules and run yarn install
     3. Reset Metro's cache: yarn start --reset-cache
     4. Remove the cache: rm -rf /tmp/metro-*
      1 | import React, {memo} from 'react';
    > 2 | import {Typography, Card, Row, Col} from 'antd';
        |                                           ^
      3 | import {
      4 |   Layout,
      5 |   PluginClient,

```
I've also tried every step mentioned in the error without success.

**Comment by mweststrate** [comment]
I just tried quickly myself, for me it seemed to without problem. The only difference I could spot is that I have flipper-pkg (0.66) as dev dep in my plugin. Could you try that, and remove node_modules first just in case? Otherwise feel free to create a zip with your test plugin. I attached mine for reference
[Archive.zip](https://github.com/facebook/flipper/files/5589490/Archive.zip)

**Comment by galex** [comment]
Thanks, that archive totally helped to progress.

I've tried it and something must be wrong in my workspace because I had the same error. Then I realized I had `yarn` at version `1.15.x` so I updated to the latest `1.22.10` and now (even after a clean `git clone`) I get the following error on your plugin:
```
Installing dependencies... done
Reading plugin details... done. Source: src/index.tsx. Main: dist/bundle.js.
Compiling... !
    Error: Unable to resolve module @babel/runtime/helpers/extends from 
    /Users/myuser/github/flipper/desktop/plugins/test3/node_modules/antd/es/back-top/index.js: @babel/runtime/helpers/extends could not be found 
    within the project.

    If you are sure the module exists, try these steps:
     1. Clear watchman watches: watchman watch-del-all
     2. Delete node_modules and run yarn install
     3. Reset Metro's cache: yarn start --reset-cache
     4. Remove the cache: rm -rf /tmp/metro-*
    > 1 | import _extends from "@babel/runtime/helpers/extends";
        |                       ^
      2 | import _defineProperty from "@babel/runtime/helpers/defineProperty";
      3 | import _slicedToArray from "@babel/runtime/helpers/slicedToArray";
      4 | import * as React from 'react';
```
My environment (mac): 
```
node --version = v15.2.1
yarn --version = 1.22.10
```
To clarify what I do (just to check):
```
# in terminal
git clone https://github.com/facebook/flipper.git
cd flipper/desktop
yarn
cd plugins/test3
# tried this
flipper-pkg bundle .
# or this, same result
flipper-pkg pack . -o ~/Desktop
```

**Comment by mweststrate** [comment]
I'm pretty sure dropping your plugin into `flipper/desktop/plugins` works as expected icmw `flipper-pkg`, as this is the source directory of plugins that normally ship inside the flipper build. Rather, you should set up your own plugin directory, as detailed in the tutorial https://fbflipper.com/docs/tutorial/js-setup#dynamic-plugin-loading. 

(That makes it possible to develop plugins both on prebuild Flipper or a source build. Dropping a directory inside flippers `plugins` needs to run some additional scripts to set up workspaces. It looks like your plugin hasn't been added to the yarn workspaces Flipper uses, which might explain the build error.)

cc @nikoant

**Comment by galex** [comment]
Yes, that was it!

Running a new plugin from within the `desktop/plugins/` folder works when running flipper through `yarn start` but confuses the hell of `flipper-pkg`, it seems. 

Setting an external folder for the plugins worked perfectly! 
Plus, as I would like it to have its own git repo, it's much better this way.

Thank you so much @mweststrate 👍
