### ISSUE TITLE
Question: What replaces createTablePlugin in flipper-plugin ?

### ISSUE THREAD

**Issue by galex** [facebook/flipper#1717]
Hello,

As I understood in the documentation `createTablePlugin` seems deprecated, so what replaces `createTablePlugin` that would give us this "professional table look" In `flipper-plugin`? 
I am trying to show a table of events and I'd like to look as much as possible like the `Network` desktop UI plugin.
I tried to do it with `antd` but honestly, my css skills are low, and it doesn't look good.

Thank you in advance!

**Comment by mweststrate** [comment]
For now feel free to keep using createTablePlugin. It is the `flipper`
import itself which is going to be deprecated, so if the same functionality
can be found in `flipper-plugin` or antd, use those instead. But
createTablePlugin, DataInspector and ManagedTable haven't been moved to
flipper-plugin yet, so feel free to continue to use those from the
'flipper' package.

**Comment by galex** [comment]
Got it, thanks for the clarification.
