### ISSUE TITLE
Question: When I finished all the preparation and charge the iPhone device , it doesn't work .And with errors

### ISSUE THREAD

**Issue by HJT916109796** [facebook/flipper#1718]
https://user-images.githubusercontent.com/16949904/100342058-5f3b4400-3018-11eb-98ec-b86114758b9e.png\
When use sudo yum install -y fb-idb , it still doesn't work .

**Comment by mweststrate** [comment]
Did you check the trouble shooting guide? https://fbflipper.com/docs/troubleshooting#ios

Could you include the 'debug logs'? (there should be a button on the bottom left)

**Comment by mweststrate** [comment]
Closing for lack of follow up
