### ISSUE TITLE
Remove Guava dep

### ISSUE THREAD

**Issue by passy** [facebook/flipper#172]
It seems like we're pulling in the full Guava library for just `ImmutableMap`. That's overkill to put it mildly. We should either find a smaller implementation of that somewhere out there or provide one ourselves.

**Comment by rahilvora** [comment]
Hey @passy  I am new to open source contributions and would like to work on this.

**Comment by passy** [comment]
@rahilvora Amazing! Let me know if I can help in any way.

**Comment by hzsweers** [comment]
It's just being used in a test (maybe this issue is a bit old?), so it seems like it's not an issue. Put up a PR to make its dependency test-only in #309
