### ISSUE TITLE
Question:  When I edit view attribute values with layout plugin , How to reset  values

### ISSUE THREAD

**Issue by fubd** [facebook/flipper#1737]
![image](https://user-images.githubusercontent.com/29155847/101118023-3e2fb000-3623-11eb-8988-954109b2d75d.png)

**Comment by passy** [comment]
We don't keep a history of the values at this point, which means once you change an attribute, the previous one is lost.

**Comment by fubd** [comment]
> We don't keep a history of the values at this point, which means once you change an attribute, the previous one is lost.

thx.
