### ISSUE TITLE
wont build with fresco plugin

### ISSUE THREAD

**Issue by farfromrefug** [facebook/flipper#1740]
I am trying to use the fresco plugin in my android app.

I added to my gradle file
```
dependencies {
        def frescoVersion =  project.hasProperty("frescoVersion") ? project.frescoVersion : "2.3.0"
  	debugImplementation 'com.facebook.flipper:flipper-fresco-plugin:0.30.1'

	implementation("com.facebook.fresco:fresco:$frescoVersion") {
        exclude group: 'com.facebook.soloader', module: 'soloader'
		exclude group: 'com.facebook.fresco', module: 'soloader'
		// exclude group: 'com.facebook.fresco', module: 'nativeimagefilters'
		// exclude group: 'com.facebook.fresco', module: 'nativeimagetranscoder'
		// exclude group: 'com.facebook.fresco', module: 'memory-type-native'
		// exclude group: 'com.facebook.fresco', module: 'imagepipeline-native'
	}
	implementation("com.facebook.fresco:imagepipeline-okhttp3:$frescoVersion") {
		exclude group: 'com.facebook.soloader', module: 'soloader'
	}
	implementation ("com.facebook.fresco:animated-gif:$frescoVersion") {
		exclude group: 'com.facebook.soloader', module: 'soloader'
	}
}
```

but on compilation i get this error:
```
Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector found in modules jetified-imagepipeline-base-2.3.0-runtime.jar (com.facebook.fresco:imagepipeline-base:2.3.0) and jetified-stetho-2.0.0-runtime.jar (com.facebook.fresco:stetho:2.0.0)
Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector$DumpInfo found in modules jetified-imagepipeline-base-2.3.0-runtime.jar (com.facebook.fresco:imagepipeline-base:2.3.0) and jetified-stetho-2.0.0-runtime.jar (com.facebook.fresco:stetho:2.0.0)
Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector$DumpInfoEntry found in modules jetified-imagepipeline-base-2.3.0-runtime.jar (com.facebook.fresco:imagepipeline-base:2.3.0) and jetified-stetho-2.0.0-runtime.jar (com.facebook.fresco:stetho:2.0.0)
```

Any idea?

**Comment by passy** [comment]
I've not seen this one before. Do you have an example project I could take a look at?

**Comment by farfromrefug** [comment]
It is part of a plugin for thé cross platform framework Nativescript. So not that easy to test. 
I guess I need to reproduce it in a basic gradle project. 
Question does stetho also contaiins those symbols?

**Comment by passy** [comment]
> Question does stetho also contaiins those symbols?

I don't think it does, but it would be great to have a basic gradle project to get to the bottom of this.

**Comment by farfromrefug** [comment]
@passy i am sorry because i did not have time to reproduce the issue in a native Android project that i can share.
However i looked at the exploded dependencies from my built project and i can see the 2 jar with the issues. And in fact it is correct. The symbols are indeed duplicated.
I cant find the sources of stetho runtime 2.0. Can you point me to where they are? Stetho project seems to be archived
<img width="1224" alt="Screenshot 2021-01-09 at 10 03 46" src="https://user-images.githubusercontent.com/655344/104087769-6cc42a80-5262-11eb-8f9c-106d6bbd26e5.png">
<img width="1209" alt="Screenshot 2021-01-09 at 10 04 53" src="https://user-images.githubusercontent.com/655344/104087771-6e8dee00-5262-11eb-8262-8e31db5f9a7a.png">

**Comment by scottkruse** [comment]
```
Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector found in modules jetified-imagepipeline-base-2.5.0-runtime (com.facebook.fresco:imagepipeline-base:2.5.0) and jetified-stetho-2.0.0-runtime (com.facebook.fresco:stetho:2.0.0)
Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector$DumpInfo found in modules jetified-imagepipeline-base-2.5.0-runtime (com.facebook.fresco:imagepipeline-base:2.5.0) and jetified-stetho-2.0.0-runtime (com.facebook.fresco:stetho:2.0.0)
Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector$DumpInfoEntry found in modules jetified-imagepipeline-base-2.5.0-runtime (com.facebook.fresco:imagepipeline-base:2.5.0) and jetified-stetho-2.0.0-runtime (com.facebook.fresco:stetho:2.0.0)
```

This is with fresco 2.5.0 &  Flipper 0.91.1

**Comment by punndcoder28** [comment]
> ```
> Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector found in modules jetified-imagepipeline-base-2.5.0-runtime (com.facebook.fresco:imagepipeline-base:2.5.0) and jetified-stetho-2.0.0-runtime (com.facebook.fresco:stetho:2.0.0)
> Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector$DumpInfo found in modules jetified-imagepipeline-base-2.5.0-runtime (com.facebook.fresco:imagepipeline-base:2.5.0) and jetified-stetho-2.0.0-runtime (com.facebook.fresco:stetho:2.0.0)
> Duplicate class com.facebook.imagepipeline.cache.CountingMemoryCacheInspector$DumpInfoEntry found in modules jetified-imagepipeline-base-2.5.0-runtime (com.facebook.fresco:imagepipeline-base:2.5.0) and jetified-stetho-2.0.0-runtime (com.facebook.fresco:stetho:2.0.0)
> ```
> 
> 
>      
>   
> 
> This is with latest fresco 2.5.0 &  Flipper 0.102.0

Yup same issue here. Any fixes for this?

**Comment by gongshoudao** [comment]
same issue

**Comment by mweststrate** [comment]
Please note that as Flipper core team we generally don't investigate specific build issues (we simply lack the capacity for that). We do make sure our [example repo](https://github.com/facebook/flipper/tree/main/react-native/ReactNativeFlipperExample) keeps running which can be used as reference point, and generally do accept community investigations and fixes where needed.

**Comment by liyamahendra** [comment]
I had a similar issue after upgrading my React native project version to `0.68.2`. I solved it by updating the `FLIPPER_VERSION` to `0.99.0`

[Credits](https://github.com/facebook/flipper/issues/2683#issuecomment-944085698)
