### ISSUE TITLE
After installation Flipper-Folly, due to dual OpenSSL lib application crash on iOS platform.

### ISSUE THREAD

**Issue by gavaliswapnil** [facebook/flipper#1753]
## 🐛 Bug Report
I have written my own node module. its contain a static library. This static library contains OpenSSL lib. I have installed flipper with my node module in the application. After running the application is crashing in OpenSSL code written in your library.
My OpenSLL lib version is 1.1.0f and yours is 1.0.2u.
Kindly update your OpenSSL version to 1.1.0 series to remove conflicts.

**Comment by mweststrate** [comment]
cc @passy / @priteshrnandgaonkar

**Comment by priteshrnandgaonkar** [comment]
We have now moved away from Open SSL static lib. Try using the latest flipper release and see if it works for you.
