### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by sourabhv** [facebook/flipper#1755]
## 🐛 Bug Report
The *experimental* dark theme doesn't work. The UI remains the same even after a restart.

## To Reproduce
1. Install and setup flipper
2. Click settings gear
3. Enable `Enable dark theme (experimental)` toggle
4. Click `Apply and restart`
5. Flipper is still in light theme mode.

## Environment

Flipper Desktop version: 0.69.0
MacOS version: macOS Mojave 10.14.6 (18G87)

**Comment by mweststrate** [comment]
That's how experimental it is :) We are still developing and testing the feature internally at Facebook first so it isn't part of the public code base yet, I'll hide the toggle for now, but here is a sneak preview:

![Screenshot 2020-12-10 at 11 31 03](https://user-images.githubusercontent.com/1820292/101766875-5304bb80-3adb-11eb-816d-a647a1c3788c.png)

We'll probably release the redesign early January.

Thanks for spotting!
