### ISSUE TITLE
Display AccessibilityNodeInfoCompat.isScreenReaderFocusable() property

### ISSUE THREAD

**Issue by Wrywulf** [facebook/flipper#1756]
## 🐛 Bug Report
The accessibility hierarchy in Flipper displays the various AccessibilityNodeInfo properties. However, it does not show the `isScreenReaderFocusable()` boolean, which is available from `AccessibilityNodeInfoCompat`

## To Reproduce
1. Connect flipper to any app
2. Toggle accessibility hierarchy on
3. Review the "AccessibilityNodeInfo" section in the accessibility pane.

There is no "screenreader-focusable" entry

## Environment
Flipper Android libs 0.69.0
Flipper Desktop 0.69.0

**Comment by kodak** [comment]
Submitted fix in #2925
