### ISSUE TITLE
Question: How do I enable the Diagnostic in-app screen in ios?

### ISSUE THREAD

**Issue by chenop** [facebook/flipper#1757]
I want to enable the diagnostic screen.
Doc says this:
You'll need to manually add this [ViewController](https://github.com/facebook/flipper/blob/master/iOS/FlipperKit/FlipperDiagnosticsViewController.m) to your app to see the in-app diagnostics.

How exactly do I do this in IOS?
Copy this file to where?
How can I view this screen?

**Comment by mweststrate** [comment]
See the `Sample` or `SampleSwitft` examples in https://github.com/facebook/flipper/tree/master/iOS. If you search for `FlipperDiagnosticsViewController` in there it should bring you further

**Comment by chenop** [comment]
Thanks @mweststrate for replying.
I can find FlipperDiagnosticsViewController but what **exactly** should I do with it?
How do I get on my simulator's screen the diagnostics?

**Comment by mweststrate** [comment]
I'm no iOS dev, but I assume attach it to your navigation should do the trick as done in the example: 
https://github.com/facebook/flipper/blob/0b2e5f645467bd0ee886d651ebf9cc7e5752ffbc/iOS/Sample/MainViewController.mm#L26-L30

**Comment by L-Yeiser** [comment]
Any update on this. As a RN dev the docs do not give one much to work with.

**Comment by zeusstl** [comment]
Hello, I feel terrible asking again, bc I am clearly missing some basic IOS knowledge here. I don't understand where to add the FlipperDiagnosticsViewController. I'm using Flipper with React Native. The sample and instructions provided are unfortunately not helpful for React Native developers.

If any IOS developer could help out here that would be amazing. I've spent many hours digging around and I can't find where or how to add the FlipperDiagnosticsViewController.m file.

**Comment by zeusstl** [comment]
After a lot more research and experimentation, it is clear to me that my issue is that my app is not connecting and that this is most likely not the right place for this question. I will create a new ticket.
