### ISSUE TITLE
encounted an error when execute command "yarn" 

### ISSUE THREAD

**Issue by NickHu150** [facebook/flipper#1773]
## 🐛 Bug Report
when i upgrade flipper code from master today , command 'yarn' was failed. the following is the details, and i never encounted before i pull the code today

```
react-smooth > react-transition-group@2.9.0" has unmet peer dependency "react-dom@>=15.0.0".
[4/4] 🔨  Building fresh packages...
[6/8] ⢀ electron
[8/8] ⢀ spectron
[-/8] ⢀ waiting...
[-/8] ⢀ waiting...
error /Users/nickhu/WorkSpace/Other/flipper/desktop/node_modules/spectron: Command failed.
Exit code: 1
Command: node lib/rpath-fix.js
Arguments:
Directory: /Users/nickhu/WorkSpace/Other/flipper/desktop/node_modules/spectron
```

## To Reproduce
executing 'yarn' or 'yarn install'
## Environment
newest code on master branch
yarn version:1.22.5
node version: 14+

**Comment by nikoant** [comment]
Hi @NickHu150, please try to remove node_modules and try again. You cleanup everything using "yarn reset" command.

**Comment by nikoant** [comment]
It seems related to this issue: https://github.com/electron-userland/spectron/issues/622. Please try downgrading node to v13 as suggested there.
