### ISSUE TITLE
Please publish to MavenCentral

### ISSUE THREAD

**Issue by ZacSweers** [facebook/flipper#1775]
Currently, flipper releases appear to only be published to jcenter and [are not present on maven central](https://repo1.maven.org/maven2/com/facebook/flipper). JCenter has a long history of artifact integrity issues and we try to avoid it at all costs. I recognize that maven central's publishing process is sometimes considered more tedious, but this signing/verification process is part of why it's preferred.

https://blog.autsoft.hu/a-confusing-dependency/
https://twitter.com/jakewharton/status/1073102730443526144?lang=en

**Comment by tfcporciuncula** [comment]
This just became even more important since JCenter will shutdown on May 1st 2021.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by wdziemia** [comment]
Looks to be resolved, seeing v0.75+ on mavenCentral 

https://repo1.maven.org/maven2/com/facebook/flipper/flipper/0.75.0/

**Comment by mweststrate** [comment]
That is correct, we publish to mavenCentral now

**Comment by WarrenFaith** [comment]
@mweststrate seems there is something broken. Here you just published 0.88.0 22 hours ago yet MavenCentral only shows 0.87.0 as latest version...

**Comment by mweststrate** [comment]
Yeah we're looking into it. For now just stick to 0.87, as there weren't any actual changes being published afaik :). cc @passy.
