### ISSUE TITLE
Plugin Sensor failed to load TypeError: (0 , _immer.produce) is not a function

### ISSUE THREAD

**Issue by NickHu150** [facebook/flipper#1789]
when i install my flipper plugin pacakge, flipper told me reload my applicaiton, then i encounted the following issue.   Is there something i can do that it can fix this terrible issue??
![image](https://user-images.githubusercontent.com/9206069/102784122-e3de6f80-43d6-11eb-8bfc-d85b1c22625e.png)

**Comment by NickHu150** [comment]
The surface recoverd properly after i uninstall my plugin. But it operate properly on electron

**Comment by NickHu150** [comment]
There is an error msg on Manage plugins 's board. Anyone can help me?
![image](https://user-images.githubusercontent.com/9206069/102966295-9410bd00-452a-11eb-82e8-1f8bc363bfb0.png)

**Comment by NickHu150** [comment]
![image](https://user-images.githubusercontent.com/9206069/102967717-83ae1180-452d-11eb-9f96-ade24705b0a2.png)

i checked on  console log ,it shows "Plugin Sensor failed to load TypeError: (0 , _immer.produce) is not a function",but it occured in flipper package. how can i solve it

**Comment by mweststrate** [comment]
Please that people are generally currently on holiday.  To receive help,
please share your plugin.

**Comment by mweststrate** [comment]
Can you provide a plugin to reproduce this with? (It doesn't have to be
your full plugin, feel free to strip everything out, as long as the error
still occurs). Are you importing `produce from "immer"`? Consider importing
`produce from 'flipper-plugin' (or 'flipper')` instead.

**Comment by NickHu150** [comment]
My fault. even forget it  that is Christmas. Thank you for your  reply,  I solved it by myself. just remove the components  from flipper package and use antd component insead then it works properly @mweststrate
