### ISSUE TITLE
Network plugin not showing any requests on Android (react-native)

### ISSUE THREAD

**Issue by inepineee** [facebook/flipper#1790]
## 🐛 Bug Report
The network plugin works perfect when connected to an iOS Simulator. But when connected to an Android, either real device or emulator, no network requests gets logged expect from "localhost:8081/symbolicate".

Everything is setup accordingly to this guide: https://fbflipper.com/docs/setup/network-plugin/ 

FYI: Every other plugin works perfect when using Android 

## Environment
Flipper: 0.69 
React-native: 0.63.3

**Comment by bizzguy** [comment]
Sounds like the network plugin may not be configured correctly.  Could you post the code that registers the plugin in the app you are testing.

Also, Flipper now has a new feature to monitor the communication between Flipper and the app.  Select "Flipper Messages" from the sidebar.  Would you be able to post the output.  Here's an example of what it should look like:

![image](https://user-images.githubusercontent.com/337874/102909534-bb8a5b80-443e-11eb-98a0-0f3b2628469c.png)

**Comment by inepineee** [comment]
Thanks for the answer @bizzguy ! 

Here is the code: 


`

    public static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
        if (FlipperUtils.shouldEnableFlipper(context)) {
            final FlipperClient client = AndroidFlipperClient.getInstance(context);
            client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
            client.addPlugin(new ReactFlipperPlugin());
            client.addPlugin(new DatabasesFlipperPlugin(context));
            client.addPlugin(new SharedPreferencesFlipperPlugin(context));
            client.addPlugin(CrashReporterPlugin.getInstance());

            NetworkFlipperPlugin networkFlipperPlugin = new NetworkFlipperPlugin();
            NetworkingModule.setCustomClientBuilder(
                    new NetworkingModule.CustomClientBuilder() {
                        @Override
                        public void apply(OkHttpClient.Builder builder) {
                            builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
                        }
                    });
            client.addPlugin(networkFlipperPlugin);
            client.start();

            // Fresco Plugin needs to ensure that ImagePipelineFactory is initialized
            // Hence we run if after all native modules have been initialized
            ReactContext reactContext = reactInstanceManager.getCurrentReactContext();
            if (reactContext == null) {
                reactInstanceManager.addReactInstanceEventListener(
                        new ReactInstanceManager.ReactInstanceEventListener() {
                            @Override
                            public void onReactContextInitialized(ReactContext reactContext) {
                                reactInstanceManager.removeReactInstanceEventListener(this);
                                reactContext.runOnNativeModulesQueueThread(
                                        new Runnable() {
                                            @Override
                                            public void run() {
                                                client.addPlugin(new FrescoFlipperPlugin());
                                            }
                                        });
                            }
                        });
            } else {
                client.addPlugin(new FrescoFlipperPlugin());
            }
        }
    }
`


I don't seem to have the new feature you mention, here is an screenshot of how my Flipper looks like: 


![image](https://user-images.githubusercontent.com/6973113/102913777-85210080-447f-11eb-8cfa-b6206c3f599e.png)

**Comment by bizzguy** [comment]
I don't see anything wrong with the code.  The plugins are all appearing which is a good sign.

I think that the "Flipper Messages" feature is only available in dev builds of Flipper, which means you would have to download the repo and create your own version.  It is fairly easy to do.  Here are the instructions: https://fbflipper.com/docs/extending/dev-setup

That might give you some more insight into what is happening.  Otherwise, you may have to do a debug session on the app to see if the OkHttpInterceptor is actually getting wired correctly.  My apps are all native Kotlin apps so I don't have any experience in React-Native apps.

**Comment by inepineee** [comment]
Ok thank you so much for your reply! Great tips, I will try these asap 🙌

**Comment by mweststrate** [comment]
@inepineee just verified with our reference React Native project, and everything seems to be working correctly (see https://github.com/facebook/flipper/tree/master/react-native/ReactNativeFlipperExample). You might make sure that you are using the latest Android Flipper SDK by setting `FLIPPER_VERSION=0.69.0` in the `android/gradle.properties` file.

**Comment by RohovDmytro** [comment]
@inepineee I have a similar issue and the same config file. 

Did you happen to solve the problem?

**Comment by lucipacurar** [comment]
I have the same problem, same config, cloned the dev build and checked the messages when loading the app:
![Screenshot 2021-02-17 at 13 16 07](https://user-images.githubusercontent.com/198549/108196962-6b6c0480-7122-11eb-832e-f9f7057f7251.png)

Does this help debug the problem?

**Comment by RohovDmytro** [comment]
v.0.76, same issue.

**Comment by ebotsupreme** [comment]
same issue, but on v.080.0. IOS is connected on network, but android shows blank.

**Comment by lucipacurar** [comment]
Anyone found a fix for this? It's months since we can't figure out why it ain't working.
The Flipper Messages shows this
![Screenshot 2021-04-29 at 12 24 56](https://user-images.githubusercontent.com/198549/116529925-1ef13200-a8e6-11eb-8b66-140aabfff8ca.png)

The logcat output is showing that Flipper is loaded
![Screenshot 2021-04-29 at 12 25 22](https://user-images.githubusercontent.com/198549/116529994-329c9880-a8e6-11eb-9477-41fed4a9c8ff.png)

Our Flipper init looks like this:
```
public class ReactNativeFlipper {
    public static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
        if (FlipperUtils.shouldEnableFlipper(context)) {
            final FlipperClient client = AndroidFlipperClient.getInstance(context);

            client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
            client.addPlugin(new ReactFlipperPlugin());
            client.addPlugin(new DatabasesFlipperPlugin(context));
            client.addPlugin(new SharedPreferencesFlipperPlugin(context));
            client.addPlugin(CrashReporterPlugin.getInstance());

            NetworkFlipperPlugin networkFlipperPlugin = new NetworkFlipperPlugin();
            NetworkingModule.setCustomClientBuilder(
                    new NetworkingModule.CustomClientBuilder() {
                        @Override
                        public void apply(OkHttpClient.Builder builder) {
                            builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
                        }
                    });
            client.addPlugin(networkFlipperPlugin);
            client.start();

            // Fresco Plugin needs to ensure that ImagePipelineFactory is initialized
            // Hence we run if after all native modules have been initialized
            ReactContext reactContext = reactInstanceManager.getCurrentReactContext();
            if (reactContext == null) {
                reactInstanceManager.addReactInstanceEventListener(
                        new ReactInstanceManager.ReactInstanceEventListener() {
                            @Override
                            public void onReactContextInitialized(ReactContext reactContext) {
                                reactInstanceManager.removeReactInstanceEventListener(this);
                                reactContext.runOnNativeModulesQueueThread(
                                        new Runnable() {
                                            @Override
                                            public void run() {
                                                client.addPlugin(new FrescoFlipperPlugin());
                                            }
                                        });
                            }
                        });
            } else {
                client.addPlugin(new FrescoFlipperPlugin());
            }
        }
    }
}
```

gradle.properties:
```
```

**Comment by Randyanto** [comment]
I have the same problem. I use Flipper 0.54.0. Using the default setting from react native but I can't even see "Network" tab in the side menu.

**Comment by a-eid** [comment]
> Sounds like the network plugin may not be configured correctly. Could you post the code that registers the plugin in the app you are testing.
> 
> Also, Flipper now has a new feature to monitor the communication between Flipper and the app. Select "Flipper Messages" from the sidebar. Would you be able to post a screenshot of the output. Here's an example of what it should look like:
> 
> ![image](https://user-images.githubusercontent.com/337874/102909534-bb8a5b80-443e-11eb-98a0-0f3b2628469c.png)


the interface I have is quit different from the one you have, I see no messaging sand no flipper section



<img width="1440" alt="Screen Shot 2021-05-25 at 10 34 43" src="https://user-images.githubusercontent.com/19273413/119466364-d3933d80-bd44-11eb-9ae1-535d48036747.png">


<img width="690" alt="Screen Shot 2021-05-25 at 10 35 24" src="https://user-images.githubusercontent.com/19273413/119466451-ead22b00-bd44-11eb-8aa8-31ab1f975d33.png">

**Comment by mweststrate** [comment]
Multiple issues seems to be reported here that are different from OP. Feel free to open new issues if any are still persistent.

**Comment by kopax-polyconseil** [comment]
I got same problem with 0.150.0 and I have configured network interceptor. I only get log of localhost when I activate airplane mode, nothing get logged. Most generally, it doesn't depend on airplane mode, it is just unreliable to debug network.

I am not opening an issue as it seems to be the same issue @inepineee is having here.
