### ISSUE TITLE
Question:  How do I create a distribution for a dev build?

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1791]
My team really likes the new "Flipper Messages" plugin.  I can use it when I create Flipper with "yarn start" but I can't seem to create a distribution that enables it.

I've tried the following but the dist does not enable the plugin:

  yarn build --channel insiders --mac --version $buildNumber

Is there a "yarn build" command with an argument for dev builds?  Or some other way I can create distribution that I can share with the rest of my team.

Thanks

**Comment by nikoant** [comment]
Hi @bizzguy! We're suggesting using dev server (yarn start) for plugin development and debugging. Out of curiosity - why do you need release build with plugin debugging capabilities? 

You can enable "Flipper messages" plugin for production builds by removing "if" check here: https://github.com/facebook/flipper/blob/master/desktop/app/src/server.tsx#L107.

**Comment by bizzguy** [comment]
@nikoant We've developed a bunch of custom plugins and sometimes it is useful to see what happened under the hood just to confirm that our plugin was coded correctly.  (Also, its interesting and helps us understand Flipper better! ;) . Since most of our Flipper users are also developers, that's the kind of detail they like.)

**Comment by passy** [comment]
@bizzguy I'd definitely be open to a PR for another build flag (or env var) to allow the inclusion of the messages plugin in release builds if that would be useful to you. :)

**Comment by mweststrate** [comment]
I think it could be just a setting in the settings dialog :)

**Comment by bizzguy** [comment]
@mweststrate   Are there other dev features that you think should be included in a dev build or is "Flipper Messages" the only one?

**Comment by mweststrate** [comment]
@bizzguy nothing jumps to mind :)

**Comment by mweststrate** [comment]
Messages and logs are now part of normal builds as well, so this issue is no longer applicable.
