### ISSUE TITLE
Docs: Links to download Flipper don't work

### ISSUE THREAD

**Issue by jughosta** [facebook/flipper#1812]
<img width="674" alt="Screenshot 2021-01-06 at 12 31 46" src="https://user-images.githubusercontent.com/1415710/103764113-29c44600-501b-11eb-9016-4e880cfa14cb.png">

URL: https://fbflipper.com
Download link: https://www.facebook.com/fbflipper/public/mac

**Comment by mweststrate** [comment]
Can you access facebook.com at all?

**Comment by jughosta** [comment]
@mweststrate Yes.

Now the links are working fine. Sorry if it was a glitch on my end.
