### ISSUE TITLE
Flipper-PeerTalk pointed at wrong repository on timeout

### ISSUE THREAD

**Issue by Rob117** [facebook/flipper#1815]
## 🐛 Bug Report

When running `pod install` after de-integrating cocoapods for a fresh install, I saw the following error on a random timeout:
```
Installing Flipper-PeerTalk (0.0.4)

[!] Error installing Flipper-PeerTalk
[!] /usr/bin/git clone https://github.com/priteshrnandgaonkar/peertalk.git /var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/d20210106-51128-1ghltr2 --template= --single-branch --depth 1 --branch v0.0.3

Cloning into '/var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/d20210106-51128-1ghltr2'...
fatal: unable to access 'https://github.com/priteshrnandgaonkar/peertalk.git/': Failed to connect to github.com port 443: Operation timed out
```

I understand that @priteshrnandgaonkar is an active maintainer, but I thought it was odd that it was pointed to his repository on a timeout and wanted to make sure that everything was alright.

## To Reproduce

Install React Native dependencies for the first time and induce a timeout when installing PeerTalk (block outgoing network connections to that address, maybe?)

## Environment

This happened in React Native, so:

```
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 408.08 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/yarn--1609979861958-0.40126024730125964/node
    Yarn: 1.22.5 - /var/folders/ky/sfz6fdq90f534vsptlfv0x6m0000gn/T/yarn--1609979861958-0.40126024730125964/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/rob/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_121 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Of course, I hope this isn't a serious issue, but I wanted to bring it to your attention. If there is anything else I can do to help, please let me know.

**Comment by mweststrate** [comment]
> Failed to connect to github.com port 443: Operation timed out

Looks like a timeout to github.com, so pretty sure it is a temporarily glitch on either your or their side. I'd expect retrying will eventually fix it it. Doesn't look as something we have influence on :)

**Comment by passy** [comment]
What Michel said but if the question is whether it's intended that we're pointing to an individual's repository here, then the answer is yes. :)

I'm going to close this but please let us know if there's something else.
