### ISSUE TITLE
"Install Plugins" list is empty both on MacOS and Windows

### ISSUE THREAD

**Issue by alexfov** [facebook/flipper#1818]
## 🐛 Bug Report
"Install Plugins" list is empty both on MacOS and Windows

## To Reproduce
1. Download and open Flipper 0.70.0

## Environment
Windows 10 and Catalina 10.15.7

### Screenshots
![Снимок экрана 2021-01-09 в 19 23 48](https://user-images.githubusercontent.com/39302602/104103087-44175180-52b1-11eb-8823-de34313ebb2b.png)
![Снимок экрана 2021-01-09 в 19 23 35](https://user-images.githubusercontent.com/39302602/104103086-437ebb00-52b1-11eb-9e2c-106a9c077bee.png)
![Снимок экрана 2021-01-09 в 19 21 51](https://user-images.githubusercontent.com/39302602/104103083-4083ca80-52b1-11eb-9d41-70fbe9955744.png)
![Снимок экрана 2021-01-09 в 19 23 01](https://user-images.githubusercontent.com/39302602/104103085-42e62480-52b1-11eb-9459-969d7ade2833.png)

**Comment by passy** [comment]
Thanks for the level of detail. That's very helpful! Looks like a real bug to me. Will dig into it.

**Comment by sshquack** [comment]
Seeing the same issue with the following:
- macOS Catalina 10.15.7
- Flipper 0.70
- React Native 0.63.3
- Vanilla `npx react-native init`
- Flipper doctor is all green but manage plugin list is empty
![Screen Shot 2021-01-09 at 3 18 57 PM](https://user-images.githubusercontent.com/5678459/104110618-3b615400-528e-11eb-98aa-32c6f5b9b019.png)

Console error when starting Flipper
```
> Failed to load dynamic plugins Error: ENOENT: no such file or directory, scandir '/Users/<user>/.flipper/installed-plugins'
> Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '/Users/om/.flipper/installed-plugins'
> Error from getpwuid_r: 102 (Operation not supported on socket)
```

![Screen Shot 2021-01-09 at 3 09 49 PM](https://user-images.githubusercontent.com/5678459/104110566-b4ac7700-528d-11eb-85c6-0388b4718ab7.png)

**Comment by rosnaib11** [comment]
+ 1

**Comment by alexfov** [comment]
Is it only 0.70 version problem? If so whre can I get previous version?

**Comment by QuentinArnault** [comment]
I switched to v0.69 and everything was fine. ok👌

You can find all versions here -> https://github.com/facebook/flipper/releases

**Comment by sshquack** [comment]
Thanks @QuentinArnault 0.69 shows the plugin list, but I had to delete the `~/.flipper` before installing 0.69

It also has this error in the console:
```
> Error from getpwuid_r: 102 (Operation not supported on socket)
Uncaught (in promise) Error: Method not implemented.
    at Function.resolveFullPathsFromMyles (bundle.js:4644)
    at LayoutPlugin.invokeMyles (bundle.js:5137)
...
```

![Screen Shot 2021-01-11 at 9 08 24 AM](https://user-images.githubusercontent.com/5678459/104214978-ff90d080-53ec-11eb-90d6-e66d58693c35.png)

**Comment by nikoant** [comment]
Hi all, thanks for the details. We'll push a new release soon, but for now you can just create empty folder "installed-plugins" in "~./flipper" and everything should work after that on version 0.70.0.

**Comment by alexfov** [comment]
> Hi all, thanks for the details. We'll push a new release soon, but for now you can just create empty folder "installed-plugins" in "~/.flipper" and everything should work after that on version 0.70.0.

Ty! This works!
