### ISSUE TITLE
Question: Rows are empty with Table plugin

### ISSUE THREAD

**Issue by QuentinArnault** [facebook/flipper#1819]
Hi,

I tried to follow the tutorial for building a simple table desktop plugin, but I face some difficulties.

My plugin `index.tsx` is:
```
import {ManagedDataInspector, Panel, Text, createTablePlugin} from 'flipper';

type Id = string;

type Row = {
  id: Id,
  column1: string,
  column2: string,
  column3: string,
};

// string | null | undefined
function buildRow(row: Row) {
  return {
    columns: {
      column1: {
        value: <Text>KAKA</Text>,
        filterValue: row.column1,
      },
      column2: {
        value: <Text>{row.column2}</Text>,
        filterValue: row.column2,
      },
      column3: {
        value: <Text>{row.column3}</Text>,
        filterValue: row.column3,
      },
    },
    key: row.id,
    copyText: JSON.stringify(row),
    filterValue: `${row.column1} ${row.column2} ${row.column3}`,
  };
}

function renderSidebar(row: Row) {
  return (
    <Panel floating={false} heading={'Extras'}>
      <ManagedDataInspector data={row} expandRoot={true} />
    </Panel>
  );
}

const columns = {
  time: {
    value: 'Column1',
  },
  module: {
    value: 'Column2',
  },
  name: {
    value: 'Column3',
  },
};

const columnSizes = {
  time: '15%',
  module: '20%',
  name: 'flex',
};

export default createTablePlugin({
  method: 'newRow', // Method which should be subscribed to to get new rows with share Row (from above),
  columns,
  columnSizes,
  renderSidebar,
  buildRow,
});
```

On my iOS source code I simply send a simple message with
```
connection.send("newRow", withParams: ["id": "Id",
                                           "column1": "string",
                                           "column2": "string",
                                           "column3": "string"])
```

In the Flipper application, I see a new row appearing, but all columns are empty. I know that the message was received  correctly because if I click on the row, the right panel appears with sent values.

<img width="1365" alt="Screenshot_2021-01-11_at_09_13_13" src="https://user-images.githubusercontent.com/1578026/104158276-48488980-53ed-11eb-9837-e7d2ee29e878.png">

Could you help me to find where this problem comes from?
For context, I'm an iOS developer and I do not really know the TypeScript.

Regards,
Quentin

**Comment by mweststrate** [comment]
your columns in `columns` shuld have the same names as used in buildrow and the JSON, so, `column1`,`column2`, `column3` etc. (possible you should rename those indeed to use `time` , `module` and `name` which would be a lot clearer.  

but at least this should work
```
const columns = {
  column1: {
    value: 'Time',
  },
  column2: {
    value: 'Module',
  },
  column3: {
    value: 'Name',
  },
};

```

**Comment by QuentinBM** [comment]
Thanks, it works a lot better. 👍

**Comment by QuentinBM** [comment]
"Issue" can be closed.
