### ISSUE TITLE
Search every input is too slow

### ISSUE THREAD

**Issue by Whoisurdady** [facebook/flipper#182]
I am trying to implement sonar in out project, and i found that it searches so slow.
I think may be it is caused by sonar try to search every input.
In most case, this is Inefficient.
Will Sonar improve this by add a search button or sth to let developer make a full search, and forbid the input search？

**Comment by passy** [comment]
Sorry, which search input are you referring to?

**Comment by jknoxville** [comment]
I think that sounds reasonable to optionally disable the
search-as-you-type. High end phones seem to deal with it well, but perhaps
low end ones will struggle with large apps.

By default, we want to keep the ux similar to the rest of the app, where
this type of search is the norm, like in the logs plugin.

**Comment by passy** [comment]
This should have much improved since the initial version.
