### ISSUE TITLE
Hermes performance, can't start recording (React Native)

### ISSUE THREAD

**Issue by alexfov** [facebook/flipper#1830]
## 🐛 Bug Report
Hello. Can't start Hermes debugger performance recording with react native. Initializing profiler takes forever. There are no debug logs. 
![Снимок экрана 2021-01-13 в 15 35 51](https://user-images.githubusercontent.com/39302602/104454875-8f827600-55b7-11eb-88e8-e68612fa0946.png)

## To Reproduce
Run app -> Go to Hermes Debugger -> Performance -> Record

## Environment
Flipper 0.70
Catalina 10.15.7
Android 10 real device (redmi Note 7)
React Native 0.63.4

**Comment by mvehar** [comment]
Same react version, flipper 0.71, Samsung S9, same issue.

**Comment by mweststrate** [comment]
Afaik the hermes debugger doesn't support using the profiler, the source code pane is the only tool that is supported at the moment. For more debugger features support best file an issue at the Hermes project: https://github.com/facebook/hermes

**Comment by leotm** [comment]
Yh only [recording](https://reactnative.dev/docs/next/profile-hermes#record-a-hermes-sampling-profile) and [loading](https://reactnative.dev/docs/next/profile-hermes#open-the-downloaded-profile-in-chrome-devtools) atm
