### ISSUE TITLE
[Android][ReactNative][Linux] While Flipper was able to connect to your device

### ISSUE THREAD

**Issue by retyui** [facebook/flipper#1832]
## 🐛 Bug Report

```
While Flipper was able to connect to your device, it wasn't able to connect to the app you are running on your device.
For this reason, app-specific plugins will not show up.
To debug why Flipper couldn't establish a connection to the app, check out our documentation about connection issues.
```

![image](https://user-images.githubusercontent.com/4661784/104710672-068b4c00-5729-11eb-8a40-16c2d94c886b.png)

I did a lot:
- [x] Use android debug build
- [x] Use the latest version of flipper SDK
- [x] Use the latest version of the flipper app 
- [x] Install the latest version of react-native-flipper
- [x] Tried [all diagnostic approaches](https://fbflipper.com/docs/troubleshooting/#connection-issues)
- [x] Tried [revert ports](https://github.com/facebook/flipper/issues/1000#issuecomment-617512233) via adb

Doctor **OK:**
![image](https://user-images.githubusercontent.com/4661784/104711338-e5772b00-5729-11eb-9e39-4c7db1d15a70.png)

## To Reproduce

No idea what wrong(

## Environment
- Linux Mint 20
- React Native 0.63.4
- react-native-flipper@0.70.0 (`yarn list react-native-flipper`)
- FLIPPER_VERSION=0.70.0 (`android/gradle.properties`)

**Comment by retyui** [comment]
I found the problem 

```
-Class<?> aClass = Class.forName("com.rndiffapp.ReactNativeFlipper");
+Class<?> aClass = Class.forName("com.my.mobile.ReactNativeFlipper");
```

Need to add this case to documentation ))

**Comment by priteshrnandgaonkar** [comment]
Where is this exact change ? @retyui

**Comment by retyui** [comment]
@priteshrnandgaonkar
 
for ReactNative case : `MainApplication.java`
