### ISSUE TITLE
Question: How can I also detect implicit call made by android like 3rd party api calls ?

### ISSUE THREAD

**Issue by Murtaza-arif** [facebook/flipper#1836]
How can I also detect implicit call made by android like 3rd party api calls?
For example: API call by Instabug or Optimizely ?

**Comment by priteshrnandgaonkar** [comment]
Can you elaborate more ? What do you mean by 3rd party api calls, are these the network calls ? If so, then it should ideally show up in network plugin.

**Comment by bizzguy** [comment]
The network plugin works by using an OkHttpInterceptor.  If the 3rd party library also uses OkHttp AND allows a way to add an interceptor then you can use that to connect the library to the network plugin.  However, for many of the 3rd party libraries that I've worked with, this is not the case.

I did take a quick look at the Instabug docs and there is good news.  It looks like they use OkHttp and have made a way for the interceptor to be accessed - https://docs.instabug.com/docs/android-logging#user-steps

**Comment by passy** [comment]
Thanks for chiming in @bizzguy! I'll close this one but if there are more questions about this, let us know!
