### ISSUE TITLE
The 'Network' plugin on flipper don't show nothing

### ISSUE THREAD

**Issue by Manitta1998** [facebook/flipper#1850]
## 🐛 Bug Report

When i have my app in the xcode simulator on, i can have the layout and the shared preferences viewer, but i don't show nothing in the network tab.. I have tried to install pre versione 0.61 / 0.64 and now the last 0.71 but don't work nothing... Why? I another computer work correctly
I don't have log and nothing... Why?

## To Reproduce

Open Flipper
I have tab Layout and also the redux debugger but the network show all white panel

## Environment

0.71

**Comment by mweststrate** [comment]
Can you make sure you are using the latest SDK in your project? https://fbflipper.com/docs/getting-started/react-native#using-the-latest-flipper-sdk

**Comment by Manitta1998** [comment]
Yes it is, i also add the path   use_flipper!('Flipper' => '0.71.0') # should match the version of your Flipper client app
in the podfile but nothing..

**Comment by mweststrate** [comment]
@Manitta1998 ok. Since it does work on one computer, and not on the other, what is the difference between them? OS, xcode version, project... etc? I assume it is both the same project and same version you are running?

**Comment by Manitta1998** [comment]
Update
After add the path for use_flipper on 0.71, i done pod install on cd ios and have this problem in console

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FlipperKitNetworkPlugin":
  In Podfile:
    FlipperKit/FlipperKitNetworkPlugin (= 0.71.0)

    FlipperKit/FlipperKitNetworkPlugin (~> 0.54.0)

None of your spec sources contain a spec satisfying the dependencies: `FlipperKit/FlipperKitNetworkPlugin (= 0.71.0), FlipperKit/FlipperKitNetworkPlugin (~> 0.54.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

I think this is the problem

**Comment by Manitta1998** [comment]
Same error 

```
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FlipperKitNetworkPlugin":
  In Podfile:
    FlipperKit/FlipperKitNetworkPlugin (= 0.71.0)

    FlipperKit/FlipperKitNetworkPlugin (~> 0.54.0)

None of your spec sources contain a spec satisfying the dependencies: `FlipperKit/FlipperKitNetworkPlugin (= 0.71.0), FlipperKit/FlipperKitNetworkPlugin (~> 0.54.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] There are duplicate dependencies on `FlipperKit` in `Podfile`:

- FlipperKit (= 0.71.0)
- FlipperKit (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitLayoutPlugin` in `Podfile`:

- FlipperKit/FlipperKitLayoutPlugin (= 0.71.0)
- FlipperKit/FlipperKitLayoutPlugin (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/SKIOSNetworkPlugin` in `Podfile`:

- FlipperKit/SKIOSNetworkPlugin (= 0.71.0)
- FlipperKit/SKIOSNetworkPlugin (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitUserDefaultsPlugin` in `Podfile`:

- FlipperKit/FlipperKitUserDefaultsPlugin (= 0.71.0)
- FlipperKit/FlipperKitUserDefaultsPlugin (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitReactPlugin` in `Podfile`:

- FlipperKit/FlipperKitReactPlugin (= 0.71.0)
- FlipperKit/FlipperKitReactPlugin (~> 0.54.0)

[!] There are duplicate dependencies on `Flipper` in `Podfile`:

- Flipper (= 0.71.0)
- Flipper (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/Core` in `Podfile`:

- FlipperKit/Core (= 0.71.0)
- FlipperKit/Core (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/CppBridge` in `Podfile`:

- FlipperKit/CppBridge (= 0.71.0)
- FlipperKit/CppBridge (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FBCxxFollyDynamicConvert` in `Podfile`:

- FlipperKit/FBCxxFollyDynamicConvert (= 0.71.0)
- FlipperKit/FBCxxFollyDynamicConvert (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FBDefines` in `Podfile`:

- FlipperKit/FBDefines (= 0.71.0)
- FlipperKit/FBDefines (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FKPortForwarding` in `Podfile`:

- FlipperKit/FKPortForwarding (= 0.71.0)
- FlipperKit/FKPortForwarding (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitHighlightOverlay` in `Podfile`:

- FlipperKit/FlipperKitHighlightOverlay (= 0.71.0)
- FlipperKit/FlipperKitHighlightOverlay (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitLayoutTextSearchable` in `Podfile`:

- FlipperKit/FlipperKitLayoutTextSearchable (= 0.71.0)
- FlipperKit/FlipperKitLayoutTextSearchable (~> 0.54.0)

[!] There are duplicate dependencies on `FlipperKit/FlipperKitNetworkPlugin` in `Podfile`:

- FlipperKit/FlipperKitNetworkPlugin (= 0.71.0)
- FlipperKit/FlipperKitNetworkPlugin (~> 0.54.0)
```

**Comment by mweststrate** [comment]
Can you share your Podfile and RN version you are using? The duplication warnings look strange.

**Comment by Manitta1998** [comment]
PodFile 
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'APP' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"

  use_react_native!(:path => config["reactNativePath"])

  use_flipper!('Flipper' => '0.71.0') # should match the version of your Flipper client app

  target 'APPTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'APP-tvOS' do
  # Pods for RnDiffApp-tvOS

  target 'APP-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end`

RN version 
"react-native": "0.63.4",

**Comment by mweststrate** [comment]
Looks like you are calling and thus installing `use_flipper!` twice. Remove the first one, and replace the second one with `use_flipper!({ 'Flipper' => '0.71.0' })`.

**Comment by Manitta1998** [comment]
Now i have this error

```
[!] CocoaPods could not find compatible versions for pod "Flipper-Folly":
  In snapshot (Podfile.lock):
    Flipper-Folly (= 2.2.0, ~> 2.2)

  In Podfile:
    Flipper (= 0.71.0) was resolved to 0.71.0, which depends on
      Flipper-Folly (~> 2.3)

    Flipper (= 0.71.0) was resolved to 0.71.0, which depends on
      Flipper-RSocket (~> 1.1) was resolved to 1.1.0, which depends on
        Flipper-Folly (~> 2.2)
```

**Comment by mweststrate** [comment]
I can imagine your Podfile.lock file is messed up now. I'd remove it and
try again? And make sure to not forget the `--repo-update` flag.

**Comment by Manitta1998** [comment]
Now Work! 

Summing up i have: 
- Remove the `use_flipper `string on the Podfile
- Start pod install --repo-update on /ios and remove all Flipper package
- Insert `use_flipper!({ 'Flipper' => '0.71.0' })`
- Start pod install --repo-update on /ios and have install all the package as new
- Re boot computer

Thank you!

**Comment by mweststrate** [comment]
And last but not least...

   * close issue
   
   😆

**Comment by leotm** [comment]
I was looking under my unconfigged _Flipper>Hermes>Network_ not _Flipper>Network_ oops.
