### ISSUE TITLE
When starting Flipper Desktop, a message suggests downloading from Managed Software Center

### ISSUE THREAD

**Issue by jhsware** [facebook/flipper#1853]
What is Managed Software Center?

Can't find Flipper on App Store for macOS. Didn't get much help when asking my Linux friends either. Any advice?

**Comment by warting** [comment]
Wondering the same, where to i find this on ubuntu?

![Screenshot from 2021-01-22 14-41-27](https://user-images.githubusercontent.com/657973/105498098-01497680-5cc0-11eb-8f91-e2fc8fabf963.png)

**Comment by mweststrate** [comment]
That doesn't look right! Unless you are working at Facebook you have exactly the right version, so we probably messed up a boolean check somewhere :)

**Comment by jhsware** [comment]
@mweststrate But I want those plugins you are speaking of! 😄  Failing that, at least you can give us a screenshot of this mysterious Managed Software Center 😄
