### ISSUE TITLE
"Please use Flipper@FB" notification shows on every app start

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#1854]
## 🐛 Bug Report
I assume this is only relevant for FB employees. I'm intentionally using the OSS version and don't want to see this message every time I start the app.
<img width="548" alt="Screen Shot 2021-01-22 at 9 25 50 AM" src="https://user-images.githubusercontent.com/157270/105523919-f9340b80-5cac-11eb-9d80-d4d8add471d1.png">

## To Reproduce
Start Flipper 0.72

## Environment
macOS 10.15.7

**Comment by swrobel** [comment]
Nevermind, I see this is a dupe of #1853 

Sorry about that!

**Comment by mweststrate** [comment]
Yeah sorry about this! Should be fixed next week Wednesday in 0.73
