### ISSUE TITLE
Question: cannot run tests with table plugin tutorial

### ISSUE THREAD

**Issue by QuentinBM** [facebook/flipper#1866]
I have created a new plugin with the command line `npx flipper-pkg init`.

Everything is working, I can use my plugin but I cannot run the unit tests.

When I run the command `npm test` I have this error:

<img width="1185" alt="Screenshot_2021-01-27_at_12_33_50" src="https://user-images.githubusercontent.com/64783278/105985686-18131300-609c-11eb-945f-966f65ab13ab.png">

I see some interesting hints but I'm not in my technical area of expertise so I do not know what to do. Could you help me?

**Comment by QuentinBM** [comment]
I think I have advanced a little by following this guide: https://basarat.gitbook.io/typescript/intro-1/jest.


By installing `ts-jest` and `typescript` with npm, I was able to get rid of the error message relative to the tsx file.
But I have a "new" problem: 
![Screenshot_2021-01-29_at_12_20_07](https://user-images.githubusercontent.com/64783278/106269205-81c22700-622c-11eb-8058-aff330498021.png)

Any help wanted. 🙏

**Comment by mweststrate** [comment]
@QuentinBM quick check, which version of `flipper-pkg` are you using?

**Comment by mweststrate** [comment]
just tried `npx flipper-pkg init` locally, and the transpilation should work out of the box. Are you using `jest` to install dependencies? Please share your package.json, and optionally a zip of the package. 

Thanks!

**Comment by QuentinBM** [comment]
I'm using v0.72.0 of flipper-pkg.
I installed dependencies with this command:

```
npm install --save-dev @babel/core @babel/preset-react @babel/preset-typescript @types/jest @types/react @types/react-dom antd flipper flipper-pkg jest ts-jest typescript
````

And my package.json looks like:

```
{
  "$schema": "https://fbflipper.com/schemas/plugin-package/v2.json",
  "name": "flipper-plugin-com-quentin",
  "id": "com.quentin",
  "version": "0.0.1",
  "main": "dist/bundle.js",
  "flipperBundlerEntry": "src/index.tsx",
  "license": "MIT",
  "keywords": [
    "flipper-plugin"
  ],
  "icon": "apps",
  "title": "Analytics",
  "scripts": {
    "lint": "flipper-pkg lint",
    "prepack": "flipper-pkg lint && flipper-pkg bundle",
    "build": "flipper-pkg bundle",
    "watch": "flipper-pkg bundle --watch",
    "test": "jest"
  },
  "peerDependencies": {
    "flipper": "latest",
    "antd": "latest"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-react": "^7.12.10",
    "@babel/preset-typescript": "^7.12.7",
    "@types/jest": "^26.0.20",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "antd": "^4.11.2",
    "flipper": "^0.72.0",
    "flipper-pkg": "^0.72.0",
    "jest": "^26.6.3",
    "ts-jest": "^26.5.0",
    "typescript": "^4.1.3"
  }
}
```

**Comment by mweststrate** [comment]
Do you have `yarn` (1.x) installed on your system? Normally the wizard should run that to set up the deps for you. `ts-jest` shouldn't be needed, but I guess it can be used. The error in your second screenshot signals that `jsx: "react"` flag is not set in `tsconfig.json`. Did you manually edit it?

**Comment by QuentinBM** [comment]
I do not have yarn installed.

I do not have any `tsconfig.json` but I have added a `jest.config.js` with:

```
module.exports = {
  "roots": [
    "<rootDir>/src"
  ],
  "testMatch": [
    "**/__tests__/**/*.+(ts|tsx|js)",
    "**/?(*.)+(spec|test).+(ts|tsx|js)"
  ],
  "transform": {
    "^.+\\.(ts|tsx)$": "ts-jest"
  },
}
```

I added this file and the explicit installation of `ts-jest` `typescript` to get rid of my first error (describe in this issue).

So you advice to 
1) install yarn
2) run `npx flipper-pkg init` command
3) run `yarn install` command

And then `yarn test` should work?

**Comment by mweststrate** [comment]
@QuentinBM correct. Make sure to install yarn 1, not 2, which is a kinda unrelated project. It is really strange the tsconfig is missing. But here you can find the files that should have been generated: https://github.com/facebook/flipper/tree/master/desktop/pkg/templates/plugin

**Comment by QuentinBM** [comment]
I started from scratch a new project with 

```
npm install --global yarn
npx flipper-pkg init
cd test
yarn install
yarn test
```

I have the following issue
```
yarn run v1.22.10
$ jest
 FAIL  src/__tests__/test.spec.tsx
  ● Test suite failed to run

    Cannot find module '@testing-library/react' from 'node_modules/flipper-plugin/lib/test-utils/test-utils.js'

    Require stack:
      node_modules/flipper-plugin/lib/test-utils/test-utils.js
      node_modules/flipper-plugin/lib/index.js
      src/__tests__/test.spec.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/flipper-plugin/src/test-utils/test-utils.tsx:11:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.159 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The content of the folder 👇
[flipper-plugin-com-test.zip](https://github.com/facebook/flipper/files/5900122/flipper-plugin-com-test.zip)

Tell me if any other information can help.

**Comment by mweststrate** [comment]
Thanks for reporting! We fixed this last week but didn't roll out a new
version yet. `yarn add -D typescript @testing-library/react` should fix the
issue
