### ISSUE TITLE
Support for non-CocoaPods dependency managers for the iOS framework

### ISSUE THREAD

**Issue by ethanjdiamond** [facebook/flipper#187]
CocoaPods is only one of three major dependency managers for iOS projects (the other two being [Carthage](https://github.com/Carthage/Carthage) and Apple's own [Swift Package Manager](https://github.com/apple/swift-package-manager)). In order to get adoption in the iOS community, Sonar's going to need to support them, and requiring CocoaPods to be run to build the SonarKit framework prevents any of the other dependency managers from being used. Are the plans to support other dependency managers?

**Comment by priteshrnandgaonkar** [comment]
There are no plans yet from our side in regards to this. But we would be happy to have a PR from the community.

**Comment by ethanjdiamond** [comment]
@priteshrnandgaonkar Could you break out the iOS project into their own repo? That would allow you to use "Releases" to host a pre-built .framework that Carthage/SwiftPM could consume.

**Comment by LeeWong** [comment]
Any news on this request?

**Comment by pyrou** [comment]
Any news on this request?
