### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by krzemienski** [facebook/flipper#191]
I would love to contribute! 

Can someone point me in the right direction as to why tvOS is not supported out of the box. I’m assuming this will take both core work and SDK work.

**Comment by SirArkimedes** [comment]
While this may be possible... there are a lot SonarKit dependencies that currently don't support tvOS. 😢

**Comment by krzemienski** [comment]
Are they all necessary? Maybe we can loose some and loose some functionality in the tvOS flavor? Which ones in particular do you think would be the biggest blockers? @SirArkimedes

**Comment by passy** [comment]
Adding help wanted here. We don't have the bandwidth to implement this ourselves, but we'd be happy to look at PRs implementing this.
