### ISSUE TITLE
JCenter shuts down on May 1st

### ISSUE THREAD

**Issue by matsujun** [facebook/flipper#1912]
JCenter shuts down on May
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Please transfer flipper android from jcenter to any other hosting service

**Comment by mweststrate** [comment]
We're working on it already :). cc @passy

**Comment by passy** [comment]
Yep, we should have all our stuff over on Maven Central way ahead of the JCenter sunset. :)
