### ISSUE TITLE
React Native Pod conflict with libevent

### ISSUE THREAD

**Issue by janicduplessis** [facebook/flipper#1916]
## 🐛 Bug Report

The libevent pod conflicts with the one used by react-native when Hermes is enabled on iOS. To avoid the conflict cocoapod installs Flipper-Folly@2.5.0 which cause a build error. Forcing it to install 2.5.1 causes a conflict error when running pod install.

https://github.com/facebook/flipper/blob/master/iOS/Podspecs/Flipper-Folly.podspec#L20

https://github.com/facebook/react-native/blob/master/scripts/react_native_pods.rb#L67

## To Reproduce

In a RN app enable hermes in the Podfile (`use_react_native!(:hermes_enabled => true,)`). Update pods and see version 2.5.0 of Flipper-Folly is installed instead of latest 2.5.1. In my case this also cause a build error later.

## Environment

Flipper@0.74.0
react-native@2aab894acf83732591de861ee29f3ddbd25546c4

**Comment by mweststrate** [comment]
Could you try with 0.75? We made some changes to the lib-events
dependencies of Flipper-Folly last week.

**Comment by priteshrnandgaonkar** [comment]
Can RN use the libevent pod from the CocoaPod. Its essentially the same pod which RN uses, but its published on cocoapods.

**Comment by janicduplessis** [comment]
Yea, I think so. I can open a PR to make this change.

**Comment by priteshrnandgaonkar** [comment]
Feel free to reopen an issue, if it doesn't solve the problem

**Comment by janicduplessis** [comment]
👍  PR on RN is live https://github.com/facebook/react-native/pull/31010

**Comment by douglasjunior** [comment]
The problem is that in `scripts/react_native_pods.rb` the `Flipper-Folly` version is setted to `'~> 2.2'`, but I think that is better to set something like `'~> 2.2.0'`.

Today to solve it we are configuring the flipper versions manually `use_flipper!({ 'Flipper-Folly' => '~> 2.2.0' })`, but it would be very good not to have to worry about that.
