### ISSUE TITLE
Discussion:  Network Plugin - Update Routes in Android Client

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1918]
When a mock route is update in Flipper, the entire route table is sent to the device.  This occurs on every change, even just a single character.  Although this works, it seems like it would be more efficient to only send the new route table to the client after all the changes have been made (i.e. when the CLOSE button is selected).

This would make debugging easier, especially on the client since less messages would go back and forth between desktop and client.

Here's a screenshot of the current route screen.

![image](https://user-images.githubusercontent.com/337874/107581029-1ded1600-6bbd-11eb-8195-d03e45ca5c61.png)

**Comment by mgoyanes** [comment]
I actually like the current behavior. 

Most of the times, I keep the route screen open and change the routes. Only if I need to use other plugin or I relaunch the app.
For me, It's preferable to keep the behavior as it his.

**Comment by bizzguy** [comment]
Maybe there is a way to trigger update when cursor leaves field (onBlur?).  That could reduce client calls but still not require user to exit the route screen.

**Comment by mweststrate** [comment]
Maybe an explicit 'Apply' button?

**Comment by mgoyanes** [comment]
> Maybe an explicit 'Apply' button?

Yeh. I also agree with this.

**Comment by bizzguy** [comment]
I've wondering if this is really a problem after all.  I haven't really seen on problem on the desktop side because of all the messages but I'm working with a small number of mocks.  Does this become more of a problem (i.e. slowing down the UI) when there are more mocks.  Maybe @mgoyanes could respond to that.

**Comment by mgoyanes** [comment]
> I'm wondering if this is really a problem after all. I haven't really seen on problem on the desktop side because of all the messages but I'm working with a small number of mocks. Does this become more of a problem (i.e. slowing down the UI) when there are more mocks. Maybe @mgoyanes could respond to that.

Never noticed that so was a bit surprised when saw this PR...

**Comment by bizzguy** [comment]
It seems like sending a full route table update on every character change seems wasteful (all those atoms!) but if it isn't causing a UI response problem then I suppose there is no point in changing it.  I don't want to introduce a button that makes the user wonder if routes have been updated.

So my new opinion is ... never mind.
