### ISSUE TITLE
Discussion: Change bolts applinks 1.4.0 dependency to allow jetifier removal

### ISSUE THREAD

**Issue by tpucci** [facebook/flipper#1919]
Hi!

We are trying to get rid of jetifier on our Android project.
However, it seems flipper 0.74 still uses legacy android support libraries (indirectly).

## bye-bye-jetifier logs
```
=========================================
Project: app
=========================================

Scanning com.parse.bolts:bolts-applinks:1.4.0
 Absoulute path: /....../bolts-applinks-1.4.0.jar
 Graphs to this dependency:
 +---com.facebook.flipper:flipper:0.74.0
     +---com.parse.bolts:bolts-applinks:1.4.0

> Task :canISayByeByeJetifier FAILED
```

Is it possible to replace this library?

**Comment by passy** [comment]
This seems to come from the Fresco plugin. I'm not sure why we have this as a top-level dependency for the entire Flipper SDK. Will check if we can quickly move that.
