### ISSUE TITLE
macOS download contains version 0.75.0 instead of 0.75.1

### ISSUE THREAD

**Issue by suschizu** [facebook/flipper#1924]
## 🐛 Bug Report
I just wanted to report that the latest version download still contains 0.75.0 as short version string.

```
CFBundleShortVersionString:
0.75.0

CFBundleVersion:
50.0.0
```

## Environment
macOS
![image](https://user-images.githubusercontent.com/16004333/107856621-ae2f9300-6e29-11eb-8b5c-804f66d22fb3.png)

**Comment by passy** [comment]
Thanks for the report. Closing in favour of #1926.
