### ISSUE TITLE
Xcode version mismatch

### ISSUE THREAD

**Issue by idkjs** [facebook/flipper#1925]
## 🐛 Bug Report

I am getting an `Xcode version mismatch` error when opening Flipper.app
I have xcode installed on an external ssd as shown below. Is there a way to make Flipper aware of this location?

I have already set the location by running:
```sh
 [I] ➜ sudo xcode-select --switch /Volumes/SSD/Applications/Xcode.app/Contents/Developer
```

## Environment
```
Flipper version 75.0
ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64
family-five-xcode12/app on  master [!?] is 📦 v1.0.0 via ⬢ v14.15.4
 [I] ➜ xcrun --find gcc
/Volumes/SSD/Applications/Xcode.app/Contents/Developer/usr/bin/gcc

family-five-xcode12/app on  master [!?] is 📦 v1.0.0 via ⬢ v14.15.4
 [I] ➜ xcode-select --version
xcode-select version 2384.

family-five-xcode12/app on  master [!?] is 📦 v1.0.0 via ⬢ v14.15.4
 [I] ➜ xcode-select -p
/Volumes/SSD/Applications/Xcode.app/Contents/Developer

```
I have xcode installed on an external ssd as show above. Is there a way to make Flipper aware of this location?

I have already set the location by running:
```sh
 [I] ➜ sudo xcode-select --switch /Volumes/SSD/Applications/Xcode.app/Contents/Developer
```

Thank you.

**Comment by priteshrnandgaonkar** [comment]
Just to confirm. Although the Flipper shows a warning, does the things work, like flipper connecting to iOS apps ?

**Comment by idkjs** [comment]
Its seems to be working though I would not know what it looks if that warning was causing some reduced functionality. New to this tool.

**Comment by priteshrnandgaonkar** [comment]
https://github.com/facebook/flipper/pull/1939

This should solve the problem. It was just that our regex was assuming xcode to be in /Applications folder

**Comment by idkjs** [comment]
Cool. So do you have to build from source to get this behaviour?

**Comment by priteshrnandgaonkar** [comment]
Its already published. Use the latest Flipper release to see if this works. Feel free to reopen the issue, if it doesn't work.

**Comment by cjbarth** [comment]
This still seems to be a problem except this time the assumption is that the path will include `Xcode.app`. Based on the error I'm getting in Flipper, this doesn't seem to be the case:


Xcode version mismatch
Xcode version mismatch: Simulator is running from "286DC512-9354-4D32-A0F3-B354C61BD6B7/Contents/Developer" while Xcode CLI is "/Applications/Xcode.app/Contents/Developer". Running "xcode-select --switch 286DC512-9354-4D32-A0F3-B354C61BD6B7/Contents/Developer" can fix this. For example: "sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"


Trying to run `xcode-select --switch 286DC512-9354-4D32-A0F3-B354C61BD6B7/Contents/Developer` with or without `sudo` yields:

`xcode-select: error: invalid developer directory '286DC512-9354-4D32-A0F3-B354C61BD6B7/Contents/Developer'`

Trying to run `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` yields no change in behavior.

**Comment by shekharpro** [comment]
I am also facing the same issue as @cjbarth , any suggestions ?

**Comment by gustavograupner** [comment]
Same here!

**Comment by gustavograupner** [comment]
To workaround this, I've downgrade my version to [v0.113.0](https://github.com/facebook/flipper/releases/tag/v0.113.0) and it's working fine now.

But I'm still looking for a solution to this on version 0.132.

**Comment by kennethlynne** [comment]
I'm seeing what you mentioned @cjbarth in v0.132.0 now

**Comment by pr1ze** [comment]
I am having this issue in version 0.166.0 - Unable to resolve. 
Problem is that i cannot select an app - so flipper states: "NO APPLICATION SELECTED" and then non of the plugins work
