### ISSUE TITLE
Flipper update popup keeps coming up 

### ISSUE THREAD

**Issue by aliraza-noon** [facebook/flipper#1926]
## 🐛 Bug Report
I had flipper 0.73.0 installed I got alert to update, I did update to 0.75.1 but after installation it still comes up I guess version check is only checking for major and minor not patch.

## To Reproduce
Install version 0.75.1 and popup for update flipper should come up on startup.

## Environment
flipper desktop v0.75.1

**Comment by awinograd** [comment]
I'm downloading 0.75.1 from https://github.com/facebook/flipper/releases/download/v0.75.1/Flipper-mac.dmg and installing. Getting the same update popup asking me to download 0.75.1 again. 

The "About flipper" popup thinks i'm still on 0.75.0

![image](https://user-images.githubusercontent.com/303609/107965222-e4772a80-6f6f-11eb-92c2-752f07c19e6d.png)

**Comment by passy** [comment]
That's a bit odd. Not quite sure what went wrong in the CI. We should have another release today. I hope that'll fix the issue for you all.

**Comment by rufat** [comment]
I still keep getting this popup. The Mac version is not the latest (0.75.1).

**Comment by mweststrate** [comment]
This should have been fixed by 0.76. Will reopen if it didn't

**Comment by aliraza-noon** [comment]
@mweststrate this still exists in 0.79.1

**Comment by ysfzrn** [comment]
like @aliraza-noon  same happens to me. I installed new setup file but version seems 0.79.0, not 0.79.1

**Comment by mweststrate** [comment]
cc @passy seems to have happened for this patch release as well, might be an issue with releasing patches?
