### ISSUE TITLE
[iOS] the dependency `OpenSSL-Static` conflict with other version `openssl` library

### ISSUE THREAD

**Issue by faimin** [facebook/flipper#193]
if the project has include `OpenSSL`, then  excute pod install, will occurred error。

the pod error message is `[!] The 'Pods-XXX' target has libraries with conflicting names: libcrypto.a and libssl.a.`。

**Comment by bolismauro** [comment]
Is there any solution to this problem?

**Comment by bolismauro** [comment]
I also tried https://github.com/react-community/react-native-maps/issues/1923 
The pod phase works, but then of course the project fails to compile

**Comment by techinpark** [comment]
any solutions?

**Comment by passy** [comment]
@priteshrnandgaonkar Have you seen this before?

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by vance-liu** [comment]
any solutions?

**Comment by vance-liu** [comment]
`
pre_install do |installer|
    exclude_files = ['libssl', 'libcrypto']
    Dir.glob(File.join(installer.sandbox.pod_dir('BaiduMapKit'), '**', '*.a')).each do |bundle|
      if (exclude_files.include?(File.basename(bundle, ".a").downcase))
        puts "Removing #{bundle}"
        FileUtils.rm_rf(bundle)
      end
    end
  end
`
