### ISSUE TITLE
Question: Support for Mac/Win devices

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#1945]
For plugins who uses:
```js
static supportsDevice(device) {
      return device.os === 'Mac';
}
```

Was support for Mac or Win devices dropped in most recent Flipper? So far I'm only able to see iOS/Android devices, but no longer Mac device.

**Comment by mweststrate** [comment]
No, but the Mac / Windows (host) device will not show up in the selection
if there is no application connected on those devices, to avoid cluttering
the navigation with inactionable options.

**Comment by mweststrate** [comment]
Fair point, I think we aren't aware of any device plugins for the 'Mac'
device, let us know if that should be supported!

**Comment by usrbowe** [comment]
Yeah, internally we do use. But currently the reason why it uses Mac device is that we want to display this "device independent" plugin to appear only once and not clutter all connected devices.
Would there be a good place for "static" plugins? Which are still handy for developers to be inside Flipper, but doesn't require any device to be used.

**Comment by mweststrate** [comment]
Yeah we thought about that in the past, but we didn't find enough use cases
initially to further invest in it, which is why the host device plugin is
the most logical route now indeed :)  Will look into making sure it shows
up!

**Comment by mweststrate** [comment]
Put up a fix, should land next week Wednesday.
