### ISSUE TITLE
Incompatibility with the Facebook library Conceal

### ISSUE THREAD

**Issue by FBisca** [facebook/flipper#195]
In our project we are using the Facebook encryption library [Conceal](https://github.com/facebook/conceal)

And I noticed that Conceal uses the same classes/jni as Sonar but instead of adding them as a transitive dependency, they are added as `sourceSets`.

[**conceal/build.gradle**](https://github.com/facebook/conceal/blob/master/build.gradle#L37)
```gradle
sourceSets {

      main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = [
            'first-party/fbjni/java',
            'first-party/proguard/annotations',
            'first-party/soloader',
            'java']
        jniLibs.srcDir 'libs'
        jni.srcDirs = []
      }
    }
```

This is what happens when we are using Conceal together with Sonar:

**myProject/build.gradle**
```gradle
implementation "com.facebook.conceal:conceal:2.0.1@aar"
debugImplementation('com.facebook.sonar:sonar:0.6.13')
```

**Compilation Error**
```
AGPBI: {"kind":"error","text":"Program type already present: com.facebook.jni.IteratorHelper","sources":[{}],"tool":"D8"}
```

**Transitive dependencies from Sonar**
```
+--- com.facebook.sonar:sonar:0.6.13
|    +--- com.facebook.sonar:fbjni:0.6.13
|    |    \--- com.facebook.soloader:soloader:0.5.1
|    +--- com.facebook.soloader:soloader:0.5.1
```

I tried to `exclude` the transitive dependencies from **Sonar** but it seems that the Conceal don't have all the `.so` files needed.

**Comment by passy** [comment]
Hmm, that's unfortunate. You tried the right steps there, but I think it'll be up to Conceal to change their repo structure so we can properly deduplicate those libraries.

**Comment by jbarr21** [comment]
I'm also seeing this with ReactNative and Profilio Facebook libs. Is there anything that can be done with this library to enable compatibility rather than waiting for updates from 3 other libraries?

**Comment by passy** [comment]
React Native should not be affected by this. What error do you see there?

This is a packaging issue, so this will require a packaging fix. This stuff is hard to get right because the Android build system provides next to no help with this.

**Comment by jbarr21** [comment]
We build with Buck and see the duplicate class error during the R8 step: `Program type already present: com.facebook.jni.CppException` which is provided from both React and Sonar

**Providers of `CppException`**:
```
/Users/jbarr/android2/buck-out/gen/.okbuck/cache/com.facebook.react--react-native--0.55.3.1-uber.aar#aar_prebuilt_jar.classes.txt:
    6  com/facebook/jni/Countable 0cdaafcbe95f801adda9f3772597171624b946a2
    7: com/facebook/jni/CppException 85777f4f9fdb4ef62c6321bb0822d2ee518a9847
    8  com/facebook/jni/CppSystemErrorException 4103b9de06f8212c36d3439b911a36702e1d2f55

/Users/jbarr/android2/buck-out/gen/.okbuck/cache/com.facebook.sonar--fbjni--0.6.11.aar#aar_prebuilt_jar.classes.txt:
    1: com/facebook/jni/CppException 22efc94a21cd56ea6f59525480d610b124964ab2
    2  com/facebook/jni/CppSystemErrorException b6ae976f43432043550c74c4241032e7c5353571
```

**Full build error**:
```
Processing filesystem changes: finished in 1.7 sec
Parsing buck files: finished in 7.7 sec (100%)
Creating action graph: finished in 1.3 sec (100%)
Building... 23.7 sec (99%) 2797/2800 jobs, 11 updated
 - //apps/sample/app-apk:bin_exo#merge_assets... 3.5 sec (running artifact_compress[0.8 sec])
 - //apps/sample/app-apk:bin_exo#d8,dex_merge... 1.6 sec (running smart_dex[1.4 sec])
Error: Program type already present: com.facebook.jni.CppException
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:69)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:306)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:268)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.android.SmartDexingStep.lambda$null$1(SmartDexingStep.java:236)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.facebook.jni.CppException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)
	... 12 more
```

**Comment by passy** [comment]
Oh, okay, now I see. That's why we made `fbjni` a separate artifact. And what happens if you don't include the Sonar-provided `fbjni` package? Are there incompatibilities?

**Comment by jbarr21** [comment]
But that `fbjni` separate artifact does not get published to maven central or jcenter. If it was, then Gradle (Gradle is our source of truth that generates Buck files) would allow us to exclude the artifact, like we are already doing for SoLoader and Infer annotations. Adding an exclude for `com.facebook.fbjni` does nothing for us as the .AAR downloaded from maven central already contains the `CppException` class.
```
implementation(com.facebook.sonar:sonar:0.6.11) {
  exclude group: "com.facebook.infer.annotation"
  exclude group: "com.facebook.soloader"
}
```

**Comment by passy** [comment]
@jbarr21 With the correct exclusion, are you still seeing those errors?

**Comment by jbarr21** [comment]
Nope, thanks for pointing out the issue!

**Comment by passy** [comment]
@jbarr21 Glad to hear that. :)

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!
