### ISSUE TITLE
[0.73+] - MacOS app has sever rendering issue making it unusable

### ISSUE THREAD

**Issue by todesignandconquer** [facebook/flipper#1963]
## 🐛 Bug Report
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/5931477/109074090-20b33500-76ac-11eb-99d6-6886420bb633.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/5931477/109074241-5f48ef80-76ac-11eb-8cb6-f2055601d254.png">

## To Reproduce
Upgraded from 0.70 to 0.75.1 and 0.76
0.71 still works

## Environment
macOS 11.0.1 Big Sur
XCode 12.3

As the screenshot indicates, I cannot get Flipper to render properly since upgrading from 0.70 with what I assume is a new UI. I managed to open the preferences and disable the Dark Theme but the issue persists.

**Comment by mweststrate** [comment]
This is a bug of MacOS + any chrome based rendering. Restarting your
computer usually fixes it.

**Comment by mweststrate** [comment]
For more details see: https://fbflipper.com/docs/troubleshooting#flipper-shows-weird-render-artifacts
