### ISSUE TITLE
Flipper v0.77.0 Failed to query idb for targets on MacOS Big Sur

### ISSUE THREAD

**Issue by vladamx** [facebook/flipper#1966]
Seems like an environment issue, but when i run the same command from terminal it is working fine, so it is hard to debug.
Any input would be appreciated.

See image below

![image](https://user-images.githubusercontent.com/11381171/109221935-e3d56400-77b9-11eb-97c0-d2a6d950c2ce.png)

**Comment by mweststrate** [comment]
@vladamx  is there by any chance non ascii tokens inside your device name?

@jknoxville looks like a charset issue. Is this a known limitation from idb?

**Comment by vladamx** [comment]
Yes, this was the problem.

**Comment by gyanadeep** [comment]
`brew reinstall grpc` worked for me

**Comment by archcorsair** [comment]
I'm having the same error, I do not have ascii tokens in my device name. Running the above suggested brew command did not fix my problem either.

**Comment by moisesynfam** [comment]
> `brew reinstall grpc` worked for me

This solved it for me.
