### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [facebook/flipper#1971]
## Description 

Hi 👋 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/kiali/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point in time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Found explicit type declarations [here](https://deepsource.io/gh/HarshCasper/flipper/issue/JS-0331/)
- Missing key props [here](https://deepsource.io/gh/HarshCasper/flipper/issue/JS-0414/)
- Rules of hooks violation [here](https://deepsource.io/gh/HarshCasper/flipper/issue/JS-0820/)
- Usage of of findDOMNode [here](https://deepsource.io/gh/HarshCasper/flipper/issue/JS-0445/occurrences)
- Prevent extra closing tags for components without children [here](https://deepsource.io/gh/HarshCasper/flipper/issue/JS-0468/occurrences)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you would like to integrate DeepSource to autofix some of the commonly occurring issues, I can help you set that up :)

**Comment by mweststrate** [comment]
Missing key props is interesting, I'll fix those. Beyond that I does largely seem like things that we can already catch by linting (3,4) or over-opinionated (e.g. 1,5)
