### ISSUE TITLE
'cmath' file not found

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [facebook/flipper#1972]
## 🐛 Bug Report
I'm getting the following error when building my iOS react native app : 

![Screen Shot 2021-03-01 at 12 03 08 PM](https://user-images.githubusercontent.com/65596246/109482169-59755480-7a86-11eb-9cf6-921aea4865c2.png)

## To Reproduce
1- enable flipper 
2- cd ios 
3- pod install
4- build the project from xCode

## Environment
react native version : 0.63.4
Flipper version : 0.78.0 
Xcode version : 12.4

**Comment by mweststrate** [comment]
cc @priteshrnandgaonkar 

Note that the React Native template seems to be currently out of date, so the solution for now might be to downgrade the Flipper binding versions used (somewhere between v 0.60 and 0.70 is probably ok?). Hopefully https://github.com/facebook/react-native/pull/31010 gets released soon

**Comment by ghadeeraqraa1992** [comment]
> cc @priteshrnandgaonkar
> 
> Note that the React Native template seems to be currently out of date, so the solution for now might be to downgrade the Flipper binding versions used (somewhere between v 0.60 and 0.70 is probably ok?). Hopefully [facebook/react-native#31010](https://github.com/facebook/react-native/pull/31010) gets released soon

I tried using using v 0.60.0 and v 0.70.0 and I got the below error : 
ios/Pods/Headers/Public/libevent/event.h:44:10: 'event2/event-config.h' file not found

**Comment by mweststrate** [comment]
Just verified, our [reference project](https://github.com/facebook/flipper/tree/master/react-native/ReactNativeFlipperExample) is up to date and builds correctly with Flipper 0.78 against the latest react native version. I recommend to check if it builds correctly for you, compare it with your project, and if that doesn't result in anything check the trouble shooting guide: https://fbflipper.com/docs/troubleshooting/#ios-build-errors-in-react-native. Feel free to reopen if that doesn't help.
