### ISSUE TITLE
Discussion: Network Plugin - allow mocking for imported devices

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1988]
Recent enhancements to the Network Plugin allow the exporting and importing of mock route.  However, there is no way to create mocks for imported network activity.

This occurs during the following use case:

- A QA engineer or developer creates network activity on a device and exports the network requests (without creating mocks).

- Another developer imports the network activity to use to fix a bug or develop a feature.  When the activity is imported, an "imported" device is created

- The developer would like to create mocks for some of the activity but the "Mock" button is not available for imported devices

The mock feature is only enabled when the device supports it and "imported" devices don't support it.

![image](https://user-images.githubusercontent.com/337874/109572459-d5859180-7ab2-11eb-829f-d151bce4317b.png)

Here's the code that checks for mocking:

https://github.com/facebook/flipper/blob/4d8be35d1a1d816afb5b0f4b6f57fa7f9352dbe2/desktop/plugins/network/index.tsx#L327

*****

Possible solutions.

Is there a way to tell that the device is a fake "imported" device

Can the imported device be configured to support mocks.  What will happen when the routes are written to the device?

**Comment by mweststrate** [comment]
> The developer would like to create mocks for some of the activity but the "Mock" button is not available for imported devices

I'm a little confused by this one, what would be the meaning of creating mocks without having a device? There wouldn't be any way to test / verify them?

**Comment by bizzguy** [comment]
The mocks would then be exported to a file and then imported to a real device where they could be tested.

The problem this solves is that the QA team often doesn't know exactly which API calls should be mocked so they can't create the mocks themselves.  However, then can save all the network activity so a developer could then decide which mocks to make from them (but only if imported devices can create mocks).

**Comment by mweststrate** [comment]
Check, yeah I think you could add a condition to check that `showMockResponseDialog` becomes also true if `client.device` is archived during initialization, and add a condition to make sure that `informClientMockChange` doesn't do anything if the client is archived.

**Comment by bizzguy** [comment]
@mweststrate 

Thanks for the advice.  Your suggestions worked perfectly.  Here's the PR https://github.com/facebook/flipper/pull/2040/files

**Comment by bizzguy** [comment]
Resolved by PR https://github.com/facebook/flipper/pull/2040
