### ISSUE TITLE
Discussion: React native devtools not really understandable

### ISSUE THREAD

**Issue by zRelux** [facebook/flipper#1990]
Now I'm not sure if I am missing something regarding setup but when I try to debug using the devtools. There are so many contexts, providers that I really can't find my stuff... plus if I hover an item it doesn't show it in blue in the app (like the toggle inspector).

I'm opening this discussion 1. to see if there is something I can do to improve 2. to see if the team is already working on something regarding this

![Screenshot 2021-03-02 at 12 11 49](https://user-images.githubusercontent.com/23509971/109646819-7a09e100-7b50-11eb-93f9-f1d4e3d09293.png)

**Comment by mweststrate** [comment]
For highlighting see: https://fbflipper.com/docs/troubleshooting#q-how-to-select-a-specific-element-in-the-react-devtools. For feedback on the devtools themself (e.g. showing Context consumers more smartly) I recommend to file it in the React repository, we merely embed them :).

**Comment by zRelux** [comment]
Ok I guess makes sense, thanks for the update will move on to the right repo!
