### ISSUE TITLE
Crash on Mac with Flipper 0.78.0

### ISSUE THREAD

**Issue by Titoura** [facebook/flipper#1991]
## 🐛 Bug Report

I've downloaded Flipper 0.78.0 for Mac (Runnning on Big Sur) and got a crash at first opening. Hitting the Retry button doesn't help either. Previous Flipper version was working fine.

Stacktrace : 

> TypeError: Cannot read property 'has' of undefined
> 
> Component stack:
> 
>     at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1167)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at Layout.ScrollContainer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1942)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at e.LeftSidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4728:529)
>     at AppInspect (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4727:136)
>     at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1333:1802)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at GutterWrapper (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:3286)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at Interactive (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:2848:752)
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at Sidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:1924)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1836)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
>     at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:67:145)
>     at div
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
>     at ContextMenuProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:62:1195)
>     at PopoverProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4718:132)
>     at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3018:3008)
>     at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:29:917)
>     at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3:941)
> 
> Error stacktrace:
> TypeError: Cannot read property 'has' of undefined
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3388:2342
>     at Array.filter (<anonymous>)
>     at computePluginLists (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3388:2330)
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4722:143
>     at Object.useMemo (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:64997)
>     at e.useMemo (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:7:5780)
>     at useMemoize (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4722:136)
>     at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1636)
>     at Ch (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:59074)
>     at li (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:68595)
>     at ki (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67929)
>     at ii (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67587)
>     at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:114730)
>     at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98507)
>     at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98435)
>     at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98298)
> 

## To Reproduce

Simply open Flipper 0.78.0 

## Environment

MacBook Pro (16 pouces, 2019)
Running on Big Sur

**Comment by mweststrate** [comment]
Should be fixed in tomorrows release (0.79). In the mean time clearing local storage should do the trick.

**Comment by mweststrate** [comment]
Should be fixed by todays release
