### ISSUE TITLE
duplicate symbols when install  FLEX 

### ISSUE THREAD

**Issue by zhy32008** [facebook/flipper#1993]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/1761947/109765067-4e115d00-7c2f-11eb-9e87-b86a9d1e93cb.png)

there are mutiple duplicate symbol bewteen FLEX and flipper , i believe these code are copied and modified from [FLEX](https://github.com/FLEXTool/FLEX), please change file name 

## To Reproduce

pod 'FLEX', '4.3.0'
config = use_native_modules!
  use_react_native!(:path => "./node_modules/react-native")
  use_flipper!({ 'Flipper' => '0.74.0' })

## Environment

xcode 12.4 , ios 12

**Comment by passy** [comment]
Seems stale. Closing.
