### ISSUE TITLE
Download links for the desktop app are broken

### ISSUE THREAD

**Issue by amenon** [facebook/flipper#200]
With the project being rename to Flipper, the links to download the desktop client (https://www.facebook.com/flipper/public/mac) are now broken. The old link https://www.facebook.com/sonar/public/mac redirects to https://www.facebook.com/flipper/public/mac and results in a 404.

This also seems to affect the update checker within the app:
![sonar](https://user-images.githubusercontent.com/1328587/43533639-e74a81de-957a-11e8-94dc-5392399b217e.jpg)

**Comment by danielbuechele** [comment]
Thanks for reporting. This should be fixed now!

**Comment by bangarharshit** [comment]
It is still throwing 404.
