### ISSUE TITLE
Network section not showing any log. #Retrofit integration #Android

### ISSUE THREAD

**Issue by Shubhampatni86** [facebook/flipper#202]
sorry to bother here if it's already done, I have little confusion about to see network inspection using flipper tool(Electron). In my project I'm using Retrofit V2.3.0, after **[suggested](https://fbflipper.com/docs/network-plugin.html)** integration here I'm not seeing any network class description in electron-network section. Anyone can suggest what can be wrong or missing something !! PFA for reference. 

<img width="319" alt="electron_nw" src="https://user-images.githubusercontent.com/825165/43576127-34e39462-9666-11e8-90a5-2dd837ebbf54.png">

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by GurvinderSinghAppinventiv** [comment]
not able to see network section at all .
code used :
this.addNetworkInterceptor(FlipperOkhttpInterceptor(NetworkFlipperPlugin()))
