### ISSUE TITLE
Question: iOS Xcode not build (Undefined symbol: boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find())

### ISSUE THREAD

**Issue by maruihi** [facebook/flipper#2027]
Ld /Users/**/Library/Developer/Xcode/DerivedData/pmcloudsMobil-djvwgpyvslczqugyrigvxynwonov/Build/Products/Debug-iphonesimulator/Flipper-Folly/folly.framework/folly normal x86_64 (in target 'Flipper-Folly' from project 'Pods')

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing All Messages
Undefined symbol: boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find()

Undefined symbol: boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match()

Undefined symbol: _d2i_SSL_SESSION

Undefined symbol: _X509_VERIFY_PARAM_set_flags

Undefined symbol: _SSL_CTX_set_session_id_context

Undefined symbol: _SSL_CTX_set_alpn_protos

Undefined symbol: _SSL_CTX_set_default_passwd_cb

Undefined symbol: _i2d_SSL_SESSION

Undefined symbol: _SSL_CTX_check_private_key

Undefined symbol: _SSL_CTX_use_PrivateKey_file

Undefined symbol: _SSL_CTX_use_certificate

Undefined symbol: _SSL_CTX_set_verify

Undefined symbol: _SSL_CTX_set_cipher_list

Undefined symbol: _SSL_CTX_set1_param

Undefined symbol: _EC_KEY_free

Undefined symbol: _SSL_CTX_callback_ctrl

Undefined symbol: _X509_NAME_get_text_by_NID

Undefined symbol: _BIO_s_socket

Undefined symbol: _SSL_CTX_new

Undefined symbol: _SSL_new

Undefined symbol: _SSL_CIPHER_get_id

Undefined symbol: _CRYPTO_THREADID_set_numeric

Undefined symbol: _CRYPTO_num_locks

Undefined symbol: _CRYPTO_set_locking_callback

Undefined symbol: _CRYPTO_set_dynlock_destroy_callback

Undefined symbol: _ASN1_TIME_free

Undefined symbol: _SSL_select_next_proto

Undefined symbol: _X509_STORE_new

Undefined symbol: _X509_digest

Undefined symbol: _ERR_error_string_n

Undefined symbol: _X509_get_issuer_name

Undefined symbol: _SSL_CTX_set_cert_store

Undefined symbol: _BIO_s_mem

Undefined symbol: _X509_NAME_print_ex

Undefined symbol: _GENERAL_NAME_free

Undefined symbol: _BIO_ctrl

Undefined symbol: _X509_get_ext_d2i

Undefined symbol: _BIO_new_mem_buf

Undefined symbol: _sk_value

Undefined symbol: _SSL_get_ciphers

Undefined symbol: _X509_NAME_get_index_by_NID

Undefined symbol: _ASN1_STRING_length

Undefined symbol: _SSL_SESSION_get_id

Undefined symbol: _X509_check_purpose

Undefined symbol: _EVP_cleanup

Undefined symbol: _SSL_library_init

Undefined symbol: _SSL_CTX_load_verify_locations

Undefined symbol: _OBJ_sn2nid

Undefined symbol: _BIO_get_ex_data

Undefined symbol: _OpenSSL_add_all_ciphers

Undefined symbol: _OPENSSL_add_all_algorithms_noconf

Undefined symbol: _SSL_CTX_set_client_CA_list

Undefined symbol: _SSL_load_error_strings

Undefined symbol: _EVP_MD_CTX_cleanup

Undefined symbol: _BN_clear_free

Undefined symbol: _X509_VERIFY_PARAM_free

Undefined symbol: _X509_STORE_CTX_get_chain

Undefined symbol: _BIO_sock_should_retry

Undefined symbol: _SSL_get_rbio

Undefined symbol: _BN_free

Undefined symbol: _EVP_sha1

Undefined symbol: _ASN1_TIME_print

Undefined symbol: _ASN1_STRING_data

Undefined symbol: _TLSv1_2_server_method

Undefined symbol: _CRYPTO_free

Undefined symbol: _SSL_load_client_CA_file

Undefined symbol: _SSL_CTX_use_certificate_chain_file

Undefined symbol: _d2i_X509

Undefined symbol: _CRYPTO_add_lock

Undefined symbol: _event_base_new

Undefined symbol: _PEM_read_bio_PrivateKey

Undefined symbol: _event_base_free

Undefined symbol: _HMAC_CTX_init

Undefined symbol: _X509_NAME_get_entry

Undefined symbol: _event_del

Undefined symbol: _SSL_CTX_use_PrivateKey

Undefined symbol: _X509_get_subject_name

Undefined symbol: _event_add

Undefined symbol: _RAND_poll

Undefined symbol: _event_base_loopbreak

Undefined symbol: _event_base_loop

Undefined symbol: _event_get_version

Undefined symbol: _ERR_clear_error

Undefined symbol: folly::detail::crc32_combine_hw(unsigned int, unsigned int, unsigned long)

Undefined symbol: _SSL_write

Undefined symbol: folly::detail::crc32c_hw(unsigned char const*, unsigned long, unsigned int)

Undefined symbol: boost::re_detail_106300::get_default_error_string(boost::regex_constants::error_type)

Undefined symbol: _event_base_set

Undefined symbol: _SSL_get_fd

Undefined symbol: _SSL_get0_param

Undefined symbol: boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const

Undefined symbol: _CRYPTO_set_dynlock_lock_callback

Undefined symbol: boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const

Undefined symbol: _X509_NAME_ENTRY_get_data

Undefined symbol: _SSL_CIPHER_get_name

Undefined symbol: boost::re_detail_106300::raise_runtime_error(std::runtime_error const&)

Undefined symbol: _SSL_get_error

Undefined symbol: boost::re_detail_106300::verify_options(unsigned int, boost::regex_constants::_match_flags)

Undefined symbol: _SSL_CTX_ctrl

Undefined symbol: _X509_free

**Comment by mweststrate** [comment]
That's not how one files issues. Please check https://fbflipper.com/docs/troubleshooting#ios-build-errors-in-react-native first and respect the issue template.
