### ISSUE TITLE
Discussion: Flipper Logs not developer friendly.

### ISSUE THREAD

**Issue by myckhel** [facebook/flipper#2029]
Using the flipper to debug logs is not developer friendly at all.

it is so frustrating not being able to see json logs properly but user have to scroll on a single tiny non expandable line while tracing a json prop.

It will be better to have something similar to chrome console debugger.

**Comment by mweststrate** [comment]
We're currently working on an improved logging plugin, should be available in a couple of weeks

**Comment by myckhel** [comment]
That is a good news.

Thanks for your response.
