### ISSUE TITLE
v0.6.15 builds are broken for default project configurations

### ISSUE THREAD

**Issue by noahsark769** [facebook/flipper#203]
You can see examples in Objc and Swift here: [sonar-testing-example-projects)](https://github.com/noahsark769/sonar-testing-example-projects). The error is "FBMacros.h: File not found"

I believe the reason is that Sample and SampleSwift both have `"${PODS_ROOT}/Headers/Public/SonarKit"` as a _recursive_ header search path, which is not out-of-the-box configuration for cocoapods. #192 removed FBMacros.h, but it looks like it has been reintroduced. The original PR moved the FBMacros.h content into SKMacros.h, but seems like that change was not preserved in the actual commit.

We should support out-of-the-box configurations because we don't want to make users manually change their header search paths to integrate Flipper/Sonar.

**Comment by priteshrnandgaonkar** [comment]
Yeah, I moved it back in, as it broke the internal build. I will work on this issue of supporting default configurations.

**Comment by priteshrnandgaonkar** [comment]
Closing the issue as the PR for this is merged
