### ISSUE TITLE
Flipper 0.79.1 Mac release is actually 0.79.0

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#2042]
https://github.com/facebook/flipper/releases/download/v0.79.1/Flipper-mac.dmg

<img width="169" alt="Screen Shot 2021-03-08 at 1 32 50 PM" src="https://user-images.githubusercontent.com/157270/110384658-f22e4600-802b-11eb-9d74-06048e8bba62.png">
<img width="506" alt="Screen Shot 2021-03-08 at 1 32 30 PM" src="https://user-images.githubusercontent.com/157270/110384660-f2c6dc80-802b-11eb-9ff1-a58a82c2938f.png">

**Comment by brianchu** [comment]
Is that why plug in doesn't work? The plugins themselves are 0.79.1 though
<img width="655" alt="Screen Shot 2021-03-09 at 7 24 18 AM" src="https://user-images.githubusercontent.com/620647/110497836-ab803080-80ab-11eb-98ee-dfbfd282305f.png">

**Comment by mweststrate** [comment]
@nikoant I suspect there is a bug in the release infra, the previous patch build (0.75.1 iirc) suffered from the very same issue: #1926

**Comment by dftaher** [comment]
since this update, my network stopped showing up

**Comment by yqlim** [comment]
This is true for windows build also

![image](https://user-images.githubusercontent.com/23203360/110569000-d8594400-818e-11eb-9678-f78d2d2e54d5.png)

**Comment by mweststrate** [comment]
@dftaher please keep the conversation on the subject and open separate issues for separate issues, by following the issue template.

**Comment by nikoant** [comment]
Fixed in https://github.com/facebook/flipper/commit/f508a35ff92b353f316669fbba78b0204dd36329
