### ISSUE TITLE
Docs: 0.80.0 changelog missing

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#2048]
The releases page says "See [master/desktop/static/CHANGELOG.md](https://github.com/facebook/flipper/tree/master/desktop/static/CHANGELOG.md) for full notes." but 0.80.0 isn't mentioned there.

**Comment by jknoxville** [comment]
Releases are published automatically every week. There are almost always some small changes included, but we typically only highlight user-facing features or high-profile bug fixes in the changelog.

When the changelog is blank like this, it just means there were no notable (tagged) feature additions in that release.
