### ISSUE TITLE
Discussion: Deprecated plugins

### ISSUE THREAD

**Issue by oblador** [facebook/flipper#2074]
I’m working on some performance tooling for React Native/Flipper and have done some refactoring to support generic and more advanced use cases. To not break existing users I published this rewrite under a new name, but since they are quite similar in naming (and have identical description) people get confused over which package to install in the Flipper UI. I’ve marked the old one as deprecated on NPM. What’s your recommended approach? Would it be possible to filter out deprecated packages in the Flipper plugin UI?

Old: https://www.npmjs.com/package/flipper-plugin-react-native-performance
New: https://www.npmjs.com/package/flipper-plugin-performance

**Comment by mweststrate** [comment]
cc @nikoant

**Comment by oblador** [comment]
Just closing without replies/reason?

**Comment by mweststrate** [comment]
Stale, so leaving it open and pretending anything will happen soon would be misleading as well :). But a PR that reads the deprecation info and shows it is always welcome! In any case, adding a Readme with the deprecation info should already help a lot here.

**Comment by aigoncharov** [comment]
@oblador it comes down to searching NPM for packages. We use [algolia](https://www.algolia.com/) under hood to the heavy lifting for us. We query [NPM packages by the keyword](https://github.com/facebook/flipper/blob/cc76c437202e26ec78320a103485efd43fba1d03/desktop/plugin-lib/src/getNpmHostedPlugins.tsx#L36). 
First, we would need to confirm algolia returns any info about package deprecation. If it does not, we could add `depreacted` tag to deprecated packages and use it in the UI.
As @mweststrate said, PRs are always welcome!

**Comment by oblador** [comment]
So basically I could publish a new version without the keyword and it should remove it? Or will it simply list the old (also deprecated) version?

**Comment by aigoncharov** [comment]
> So basically I could publish a new version without the keyword and it should remove it? Or will it simply list the old (also deprecated) version?

I wish I knew :) Do we anything to lose if we try?

**Comment by aigoncharov** [comment]
@oblador it should be fixed now.
