### ISSUE TITLE
New Log plugin issues

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#2076]
## 🐛 Bug Report

1. App column always empty
2. No Regex allowed on search
3. Cannot remove previous filtered message

## To Reproduce
1. App column always empty
![image](https://user-images.githubusercontent.com/5049948/111598947-a61b9800-87c7-11eb-9b3e-26cddf5dd9aa.png)

I don't know if here, the package names from the apps, were supposed to appear. If not, I think they should. I currently don't have an easy way to show only the logs from, let's say, my app. I was expecting to have the same behavior as **Show only selected application** as we have in Android Studio Logcat

2. No Regex allowed on search
![image](https://user-images.githubusercontent.com/5049948/111599500-3d80eb00-87c8-11eb-9ff9-1f83be12311e.png)

I was expecting the same behavior as in Android Studio Logcat. It's an easy way to filter entries.
![image](https://user-images.githubusercontent.com/5049948/111599737-83d64a00-87c8-11eb-95d1-a9154237f0ab.png)

3. Cannot remove previous filtered message
Filtered a message using **Filter from selection**. That message is very big and now I cannot remove it unless I use the **Reset View**. I think that the message should have a horizontal scroll and show us the remove button as it shows on smaller messages.

![image](https://user-images.githubusercontent.com/5049948/111599863-ab2d1700-87c8-11eb-983d-6ef2e494a9e7.png)

## Environment
MacOs Desktop Client Version 0.80.0

**Comment by mweststrate** [comment]
Thanks for the report! The following will be addressed in 0.81.0 (next week Wednesday)

1. For empty app column, see #326. On android we will now show the PID column by default, which at least will make filtering for the correct process pretty straight forward
2. Restored regex option
3. Fixed

![Screenshot 2021-03-19 at 13 22 39](https://user-images.githubusercontent.com/1820292/111786885-359f7480-88b6-11eb-9177-1a238901ad0e.png)


![Screenshot 2021-03-19 at 13 09 25](https://user-images.githubusercontent.com/1820292/111786679-fa9d4100-88b5-11eb-95a3-a82069783c8a.png)

**Comment by mgoyanes** [comment]
@mweststrate Thanks.

Tested and it's working as expected
