### ISSUE TITLE
[Android] Can't see Network inspector

### ISSUE THREAD

**Issue by toantk238** [facebook/flipper#209]
I'm trying to use Flipper on Linux Mint 19.
Everything seem run well. But after I try to integrate Flipper in Android app, I can't see the Network Inspector in Flipper. Only can see Logs. You can see some screen shots below.
** Note : I build Flipper from source 
   Branch : master
   Revision : fc7f949dafdb5f853ea979d08d33e5157836ba57

![screenshot from 2018-08-07 16-34-33](https://user-images.githubusercontent.com/5424557/43767995-8a3fa81c-9a60-11e8-8fe0-7135a2b59abf.png)
![screenshot from 2018-08-07 16-34-46](https://user-images.githubusercontent.com/5424557/43767997-8a804f7a-9a60-11e8-9c4c-034b9f49f9f2.png)

Thanks for reading !!

**Comment by passy** [comment]
I'm actually having the same issue on my Linux box. I'll look into that, but don't have a good estimate when that will happen.

**Comment by passy** [comment]
Closing this as we've cleaned up a bunch of Linux errors since then.
