### ISSUE TITLE
idb error

### ISSUE THREAD

**Issue by KingAmo** [facebook/flipper#2094]
## 🐛 Bug Report

A problem with idb has ocurred. Please run `sudo rm -rf /tmp/idb*` and `sudo yum install -y fb-idb` to update it, if that doesn't fix it, post in Flipper Support.

## Environment

```
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 287.82 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
`flipper: 0.81.0`

![image](https://user-images.githubusercontent.com/29938227/112097714-76133100-8bdb-11eb-87c2-78ba00c37b95.png)
![image](https://user-images.githubusercontent.com/29938227/112097746-89260100-8bdb-11eb-945b-72699df1f8a1.png)

**Comment by passy** [comment]
Sorry, there's nothing actionable in your logs. Which version of idb are you on?

**Comment by henrymoulton** [comment]
@passy I'm getting this too

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/30093692/124820393-5410a500-df65-11eb-841d-e861fc3b0c48.png">
