### ISSUE TITLE
Could not download the icon bug

### ISSUE THREAD

**Issue by mrpeski** [facebook/flipper#2096]
## 🐛 Bug Report

 When one tries to build it fails with a runtime error of icon bug not found.

<img width="1346" alt="Screenshot 2021-03-23 at 10 26 31" src="https://user-images.githubusercontent.com/8403268/112125823-1eb59680-8bc4-11eb-9513-8d9cd69d7214.png">

## To Reproduce

1. git clone https://github.com/facebook/flipper.git
2. cd flipper/desktop
3. yarn
4. yarn build --mac --version $buildNumber

## Environment

MacOS Big Sur 11.2.1

**Comment by passy** [comment]
This works fine in our CI, so this was probably just flakiness.

**Comment by mrpeski** [comment]
<img width="1148" alt="Screenshot 2021-03-27 at 14 03 22" src="https://user-images.githubusercontent.com/8403268/112721677-8db52700-8f05-11eb-8f68-0ea791a67c86.png">

**Comment by mrpeski** [comment]
<img width="1148" alt="Screenshot 2021-03-27 at 14 03 22" src="https://user-images.githubusercontent.com/8403268/112721774-1d5ad580-8f06-11eb-9f2d-8d474ee4042c.png">

**Comment by mrpeski** [comment]
Consider visiting that url directly. 
[https://external.xx.fbcdn.net/assets/?name=messages&variant=filled&size=12&set=facebook_icons&density=2x](https://external.xx.fbcdn.net/assets/?name=messages&variant=filled&size=12&set=facebook_icons&density=2x
)

**Comment by mrpeski** [comment]
It appears to be back. And it builds successfully!
