### ISSUE TITLE
What about React Native? 

### ISSUE THREAD

**Issue by ahmedlhanafy** [facebook/flipper#21]
Are there any plans to add support for React Native in the future?

**Comment by Maxence-Machu** [comment]
+ 1, nice projet by the way

**Comment by alioguzhan** [comment]
Since integration is being done at native level, we should be able to use this tool for `React-Native` projects as well. (default react native apps, not expo!)

**Comment by trungtin** [comment]
If trying to add this `pod 'Yoga','~>1.8.1', :modular_headers => true` to the Podfile we stuck on #30. And when trying to install `Yoga` from podspec like this:
```
pod 'Yoga', :podspec => 'https://raw.githubusercontent.com/facebook/yoga/50e3714b21437d244e51874435953a2d011d1618/Yoga.podspec' :modular_headers => true
```
We stumble upon this issue `The 'Pods-xxx' target has libraries with conflicting names: libyoga.a.` as indeed in our Podfile we already have this:
```
pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
```

Any idea :D?

**Comment by carloscuesta** [comment]
React Native support would be awesome!

**Comment by danielbuechele** [comment]
I agree! React Native support is something we should look into. From my understanding the actual views created by React Native should already show up in the layout inspector. What we could offer, is adding React Dev Tools to Sonar as a separate plugin, showing the React components. Linking between the layout inspector with the actual views and a React plugin showing the component tree would be great.

The biggest task I see with this project, is to send the component hierarchy to the desktop. We will need to create a connection from JS to the desktop app.

**Comment by metinsut** [comment]
good job facebook team, we look forward to react-native support.

**Comment by NSExceptional** [comment]
It isn't usually useful to inspect React Native views. There are no unique class names so everything looks the same when it's in a flat list. Not great for debugging.

That's my experience using FLEX on a RN app, anyway...

**Comment by koox00** [comment]
I am having the following error when adding Sonar in react-native app.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```

Adding the following fixes the first one
```
defaultConfig {
    .....
    multiDexEnabled true
}
```

but now I get 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/app/BundleUtil.class
```

PS: even without the React devtools having a network inpector in React native app is a great feat!

**Comment by kashishgrover** [comment]
Looking forward to this! Thanks 😄

**Comment by sregg** [comment]
https://github.com/infinitered/reactotron works very well with React Native.
It offers network inspection, better stack traces and redux actions/state logging and replay.
Checkout this video for more details: https://www.youtube.com/watch?v=UiPo9A9k7xc

**Comment by timsaval** [comment]
Our team would love that as well!

**Comment by kashishgrover** [comment]
@sregg already using it! 😄

**Comment by estevaolucas** [comment]
@axe-fb is working to make it happen 🙌.

RN 0.61.0 will come with default setup on Android. And for iOS, per discussion here https://github.com/facebook/react-native/pull/26053, `Yoga` dependence in Layout plugin clashes with RN one's (causing a `The 'Pods-xxx' target has libraries with conflicting names: libyoga.a`) and it should get fixed with those two commits: https://github.com/facebook/react-native/commit/82a8080f0704e83079d0429e4e367f5131052e64 https://github.com/facebook/react-native/commit/a58dd9683da6135bca119a8b0ae5d0ea5382cf4c. 🤞

Thanks @axe-fb!

**Comment by mateosilguero** [comment]
I made this tutorial https://fbflipper.com/docs/getting-started.html#setup-your-react-native-app for React native integration. Currently there is no full support, but you could use some features

**Comment by alminde** [comment]
Trying to get Flipper to work with RN 0.59 and ExpoKit, I’m getting that `libyoga.a` error. Does anyone know of some kind of Podfile workaround or must I wait until Expo ships with RN 0.61?

**Comment by TommyLeong** [comment]
Somehow the default Flipper setup on Android (RN0.61.0) does not connect my app with flipper. Guessing some dependencies weren't included on Android. 

Anyway, my app has successfully integrated with Flipper following [this guide](https://fbflipper.com/docs/getting-started.html#setup-your-react-native-app). Thanks to guide from @mateosilguero !

**Comment by mweststrate** [comment]
We are working on standardizing this, so ideally in 0.62 Flipper should work out of the box on React Native. In a later version it will also be possible to directly integrate with Flipper from the JavaScript side of things on RN.

**Comment by MakhouT** [comment]
Awesome!
