### ISSUE TITLE
Filter by package support for Android

### ISSUE THREAD

**Issue by riyaz** [facebook/flipper#210]
It would be nice to have filter by package like [Pidcat](https://github.com/JakeWharton/pidcat) else we have to find the process then do a filtering, most of times filter by package is more useful than filter by pid

**Comment by mgoyanes** [comment]
Also, add some of the Android Studio logcat viewer like filter by more than one tag (`ABC` and `DEF`) or exclude multiple tags from filtering and allow regular expressions (filter all tags started by `ABC` would map to something like `ABC.*`)

**Comment by jemshit** [comment]
Is it same as "Show only selected application" ?

**Comment by michaelcarrano** [comment]
This issue seems to be duplicate/related to https://github.com/facebook/flipper/issues/326
