### ISSUE TITLE
I dont see the network inspector anymore

### ISSUE THREAD

**Issue by hsavit1** [facebook/flipper#2102]
## 🐛 Bug Report

What happened to the network inspector plugin? I dont see it at all with flipper v0.81

## Environment

react native v63, flipper v0.81

**Comment by mweststrate** [comment]
Nothing :) So please provide more info like screenshots, any errors logged in the console, the Flipper version you've defined in your Podfile etc etc.

**Comment by hsavit1** [comment]
no logged errors

my podfile looks like

``` 
use_flipper!({ 'Flipper-Folly' => '2.5.1', "Flipper" => "0.81", "Flipper-RSocket" => "1.3" })
```

when i downgrade flipper to 61 i see the network inspector


``` 
use_flipper!({ 'Flipper-Folly' => '2.3.0', "Flipper" => "0.61.0" })
```

**Comment by cloudbank** [comment]
I also suddenly no longer can get the network plugin.  It is being added to my project as a dependency and was working until just a few days ago.  I get the message attached.  I cannot see any other error.  I am using android with an emulator.  I have Android Developer selected and iOS Developer deselected in Settings.  Logs are still coming thru from the app.
Version is 0.82.1

![Screen Shot 2021-03-26 at 8 07 25 PM](https://user-images.githubusercontent.com/2288294/112708472-66137f80-8e6f-11eb-9034-d64e77c12031.png)
![Screen Shot 2021-03-26 at 8 08 23 PM](https://user-images.githubusercontent.com/2288294/112708474-6744ac80-8e6f-11eb-9ee7-7c152c1c96cd.png)

**Comment by hsavit1** [comment]
I think the problem may be that I am trying to run on a device and not a mobile device simulator

**Comment by mweststrate** [comment]
The problem is probably that the client application fails to connect to Flipper. The Flipper Logs pane (exclamation icon on the left sidebar) should reveal more info about this.
