### ISSUE TITLE
Database plugin will not show two databases with same name but different paths

### ISSUE THREAD

**Issue by mrubinsquare** [facebook/flipper#2109]
## 🐛 Bug Report

I have two databases at
`/data/data/com.my.package/files/123456/experiments.db`
`/data/data/com.my.package/files/experiments.db`

If I use code (Kotlin) such as
```
    AndroidFlipperClient.getInstance(application).addPlugin(
      DatabasesFlipperPlugin(SqliteDatabaseDriver(application) {
        listOf(
          File(" /data/data/com.squareup.eng/files/123456/experiments.db"),
          File("/data/data/com.squareup.eng/files/experiments.db")
        )
      })

```
to configure my `DatabaseFlipperPlugin`, only one of the databases appears in the client's dropdown:

<img width="885" alt="Screen Shot 2021-03-27 at 11 09 24 PM" src="https://user-images.githubusercontent.com/72885127/112744068-84ea4280-8f51-11eb-86d2-d43512ccf2ef.png">

## Environment
Android API 29, Flipper Desktop reports Version 0.82.1 (50.0.0). Running on MacBook Pro Big Sur 11.2.3

**Comment by mweststrate** [comment]
This should have been fixed by the new databases plugin UI
