### ISSUE TITLE
Support multiple keys for SharedPreferences

### ISSUE THREAD

**Issue by fraherm** [facebook/flipper#211]
It might be interesting to watch multiple instances of `SharedPreferences` with different keys. Currently flipper only displays the first instance which is added with the `SharedPreferencesSonarPlugin`.

```Java
client.addPlugin(new SharedPreferencesSonarPlugin(context, "key1"));
client.addPlugin(new SharedPreferencesSonarPlugin(context, "key2"));
```

For this example flipper only displays the `SharedPreferences` instance for `key1` and not for both.

**Comment by xiphirx** [comment]
b40810080cd3723d038d287722545bde004f494b
