### ISSUE TITLE
[0.82.1] Visual error with flipper (blurry UI with colors)

### ISSUE THREAD

**Issue by jayshah123** [facebook/flipper#2111]
## 🐛 Bug Report

Visual error with flipper (check screenshot).
## To Reproduce

Open flipper and use it.

## Environment

Flipper 0.82.1
MacOs 10.15.7
<img width="1792" alt="Screenshot 2021-03-28 at 6 05 07 PM" src="https://user-images.githubusercontent.com/659202/112752355-566f7480-8ff0-11eb-9a10-a3a5c7089454.png">

**Comment by mweststrate** [comment]
See https://fbflipper.com/docs/troubleshooting#flipper-shows-weird-render-artifacts
