### ISSUE TITLE
TypeError: Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by luco** [facebook/flipper#212]
Getting this message when trying to debug:

![image](https://user-images.githubusercontent.com/246373/43847684-9311cc7a-9b07-11e8-964f-cb1c7304be72.png)

Thoughts?

**Comment by priteshrnandgaonkar** [comment]
Can you post the repro steps?

**Comment by noahsark769** [comment]
I've also run into this error randomly. Not sure what the cause is. Anecdotally, restarting the app seems to have helped in the past.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
