### ISSUE TITLE
Run Gradle Unit Tests in Travis CI

### ISSUE THREAD

**Issue by passy** [facebook/flipper#213]
We currently don't support using Gradle for running our unit tests, i.e. `./gradlew :android:testDebugUnitTest` will fail with a bunch of unresolved dependencies. I don't think there are any blockers from making this work - someone just needs to check out what the missing dependencies are and add them to our `build.gradle` files.

I would be happy to accept partial Pull Requests here, even if we still have build errors but they get us closer to a working setup we could ultimate run in CI.

If you want to help out, please let me know. :)

**Comment by rahilvora** [comment]
I can try this.

**Comment by rahilvora** [comment]
Hey, @passy for the description I understand that there bunch of missing dependencies which needs to be added. Currently, I have added JUnit dependency and created a pull request. Kindly review it and let me know if I am going in the correct direction. 

Currently, I have created a PR https://github.com/facebook/flipper/pull/229.

**Comment by passy** [comment]
This is done now.
