### ISSUE TITLE
Question: Confusion about connecting app on iOS physical device

### ISSUE THREAD

**Issue by FFFang** [facebook/flipper#2144]
I faced some problem about connecting app on my physical iOS device.The error is `No matching device found for app:`

I am looking at `CertificateProvider.tsx.`[here I have some confusion](https://github.com/facebook/flipper/blob/a2d559c8c0fcef2b6a89a28bd18a7f426130b814/desktop/app/src/utils/CertificateProvider.tsx#L522)

Why a device csr string should be equal to server csr string,which is randomly generated by the server(It seems changes each connection)?

After I hardcode my device udid at method `getTargetiOSDeviceId`,It matches well,but then flipper desktop shows warning:
`Sample with device c47e109191018678403d909c023e5339306f711d took long time to connect back on the trusted channel. Verify if your client is connected to Flipper and verify if there is no error related to idb. `

### Environment
1. flipper:master branch,build by source
1. the idb and idb_companion are the latest version.
1. The python version is 3.9.
1. The idb is good,I can transform,connect and read file by idb properly in terminal.

Thanks very much for any help.

**Comment by mweststrate** [comment]
@FFFang is there a reason you want to discuss this separately from #2113? Otherwise let's tackle one problem at a time.

**Comment by FFFang** [comment]
@mweststrate 
[#2144](https://github.com/facebook/flipper/issues/2144) is a question about code in `CertificateProvider.tsx`.
[#2143](https://github.com/facebook/flipper/issues/2143) is a flipper/idb connection problem.

**Comment by jknoxville** [comment]
> Why a device csr string should be equal to server csr string

I can understand the confusion - the code is quite complicated, but this isn't what its comparing.

Flipper receives a connection request over the network from the mobile app, containing the csr that the mobile app has generated.

In general, mobile apps have no way to find out their own serial number, for privacy purposes, so when this network request comes in, flipper has no way to know which device it has come from. But it still needs to write the cert files into the right app on the right device somehow.

So the purpose of this function is to identify the (device, app) combination that sent the current connection request. It works by looking into the file system of each, and seeing which one has a csr that matches the one received in the current request. 

---

I appreciate you efforts to get to the bottom of this, it's hard to debug remotely.

Your hardcoding step sounds valid to me as a step towards getting it working, so what we need to work out next is what's happening on the device after this i.e. why is it not connecting back on the trusted channel. Thankfully we have a diagnostic screen for this purpose, if you run the sample app, and then click on "Diagnostic Screen", can you paste what you see here? Flipper should be running at the time, so it has had time to connect and fail.

<img width="504" alt="Screenshot 2021-03-31 at 11 55 05" src="https://user-images.githubusercontent.com/692011/113133928-24405b80-9218-11eb-9148-4a5b6645efca.png">

**Comment by nnphong1904** [comment]
I have the same issue, any update to fix that?

**Comment by mweststrate** [comment]
We are still waiting for the new idb version to be released which should unblock this.

**Comment by mweststrate** [comment]
Upgrading to idb 1.2.2 should solve the issue, let us know if it doesn't!

**Comment by kofkgoing** [comment]
> 1.2.2

where is 1.2.2? 
fb-idb-1.1.7 is latest in pip
