### ISSUE TITLE
I see my device / emulator, but I can't see the app

### ISSUE THREAD

**Issue by batuhansahan** [facebook/flipper#2148]
## 🐛 Bug Report
I tried with new react-native projects 0.63.x and 0.64.0 it's responding same, cannot open plugin page also it says NO APPLICATION SELECTED but i see the **pixel 3** and **react-native** titles, and i can use react devtools or open developer menu via flipper.

I did all the things mention here [Doc](https://fbflipper.com/docs/troubleshooting/#q-i-see-my-device--emulator-but-i-cant-see-the-app)

I've enabled/disabled hermes and starting app with npx react-native run-android.

## Environment
Flipper: 0.83.0 Windows
React-native:0.63.x and 0.64.0 Android

**Comment by chakrihacker** [comment]
How did you fix the issue?

**Comment by ghasemikasra39** [comment]
@batuhansahan Any fix?

**Comment by luanfonsecap** [comment]
Waiting for this fix too

**Comment by hu-qi** [comment]
Hello，any fix ?

![image](https://user-images.githubusercontent.com/17986122/127275987-17abe289-d0ed-476e-bb1a-d2525b3e9acd.png)

**Comment by quanghungit** [comment]
same

**Comment by YajanaRao** [comment]
I clicked on setup doctor and updated android path but still I see the same issue
![image](https://user-images.githubusercontent.com/38914337/129077519-97c988ae-f4c9-491f-8e15-cb1cb4b86d03.png)

**Comment by karpyzin** [comment]
Same problem

**Comment by tbveloso** [comment]
would like to know how connect the app and have access the images, database and mainly the network features... 

I can see the device and React Native... and the message "Currently connecting..."... just below the selection menu, "NO APPLICATION SELECTED" (in red)
