### ISSUE TITLE
Plugin "NETWORK" encountered an error during render

### ISSUE THREAD

**Issue by abeemukthees** [facebook/flipper#215]
Flipper v0.6.12
`RangeError: Maximum call stack size exceeded at decompress (/Applications/Flipper.app/Contents/Resources/app.asar/defaultPlugins/sonar-plugin-network@1.0.0.js:765:32) at decodeBody (/Applications/Flipper.app/Contents/Resources/app.asar/defaultPlugins/sonar-plugin-network@1.0.0.js:747:91) at ResponseBodyInspector.render (/Applications/Flipper.app/Contents/Resources/app.asar/defaultPlugins/sonar-plugin-network@1.0.0.js:1018:78) at Gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:8052:26) at Kg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:8233:16) at th (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:8874:13) at uh (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:8889:84) at Rh (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:9147:235) at Uh (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:9106:173) at Sh (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:9100:5) at interactiveUpdates (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:9631:33) at Jd (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:6133:5) `

**Comment by priteshrnandgaonkar** [comment]
Can you give the repro step?

**Comment by abeemukthees** [comment]
I installed the latest Flipper v0.6.12 desktop app on my mac. (Downloaded directly)

Launched it
Started Android Emulator
App is written in Kotlin, Networking is handled by `Retrofit` + `okhttp` + `CoroutineCallAdapterFactory` + `MoshiConverterFactory`

```
class MyApplication : Application() {

    val networkSonarPlugin = NetworkSonarPlugin()

    override fun onCreate() {
        super.onCreate()
        SoLoader.init(this, false)

        if (BuildConfig.DEBUG && SonarUtils.shouldEnableSonar(this)) {
            val client = AndroidSonarClient.getInstance(this)
            client.addPlugin(networkSonarPlugin)
            client.addPlugin(InspectorSonarPlugin(this, DescriptorMapping.withDefaults()))
            client.start()
        } 
    }
}

```
```
object ImgurService {

    private val httpLoggingInterceptor = HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BASIC)

    private val contentType = MediaType.parse("application/json")!!
    private val json = JSON

    private val okHttpClientBuilder = OkHttpClient.Builder()
            .addInterceptor(httpLoggingInterceptor)


    private val retrofitBuilder = Retrofit.Builder()
            .baseUrl("https://api.imgur.com/3/")
            .addCallAdapterFactory(CoroutineCallAdapterFactory())
            .addConverterFactory(MoshiConverterFactory.create())

    fun getImgurService(context: Context? = null): ImgurApi {

        context?.let {
            okHttpClientBuilder.addInterceptor(ChuckInterceptor(context))
            okHttpClientBuilder.addNetworkInterceptor(SonarOkhttpInterceptor((context.applicationContext as? MyApplication)?.networkSonarPlugin))
        }

        retrofitBuilder.client(okHttpClientBuilder.build())

        return retrofitBuilder.build().create(ImgurApi::class.java)

    }
}

```
I also have `willowtreeapps/Hyperion-Android` dependency, which uses the `ChuckInterceptor`
Since I had some build issues, I added this in the app build.gradle :

packagingOptions {

        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'

        pickFirst 'lib/armeabi-v7a/libassmidi.so'
        pickFirst 'lib/x86/libassmidi.so'

        pickFirst 'lib/armeabi-v7a/libsonarfb.so'
        pickFirst 'lib/x86/libsonarfb.so'
        pickFirst 'lib/arm64-v8a/libsonarfb.so'
    }

**Comment by gsanguinetti** [comment]
Same Issue here. Any updates?

**Comment by cristan** [comment]
This happens with me at 1 specific call, and that's one which returns a huge JSON, so it might have something to do with how big the response is.

**Comment by erawhctim** [comment]
Same issue on our end, due to a massive JSON response returned for a particular network call (120kb)

**Comment by erawhctim** [comment]
@abeemukthees I'd suggest updating the name to be a little more descriptive: 
"Network plugin: unexpected render error when loading detail view for a GET request with large response" (or something along those lines)

**Comment by abeemukthees** [comment]
@erawhctim For me, it happens irrespective of the response size.

**Comment by erawhctim** [comment]
Still seeing this issue on my end as well (on v0.19)

**Comment by henryzx** [comment]
Still able to reproduce on v0.20. Found that any request whose size exceeds **~20kB** will fail to display. Is there any way to work around this problem? It keeps happening...

**Comment by jbarr21** [comment]
still exists on v0.21.1 (desktop and library)

**Comment by abeemukthees** [comment]
Two more months for the 1st anniversary on this issue. 😛

**Comment by henryzx** [comment]
still exists on v0.22.0

**Comment by passy** [comment]
If you create a Flipper export and attach that, that would help us a lot to
reproduce that issue.

**Comment by martynhaigh** [comment]
Having the same problem.  Here's an export:
[FlipperExport.flipper.zip](https://github.com/facebook/flipper/files/3333952/FlipperExport.flipper.zip)

**Comment by henryzx** [comment]
Seems this function caused the problem. 
The whole network payload is loaded in stack before return.
any idea?

`src/plugins/network/utils.js`

```
function decompress(body: string): string {
  const charArray = body.split('').map(x => x.charCodeAt(0));

  const byteArray = new Uint8Array(charArray);

  let data;
  try {
    if (body) {
    }
      data = pako.inflate(byteArray);
    } else {
      return body;
    }
  } catch (e) {
    // Sometimes Content-Encoding is 'gzip' but the body is already decompressed.
    // Assume this is the case when decompression fails.
    return body;
  }

  return String.fromCharCode.apply(null, new Uint8Array(data));
}
```

**Comment by henryzx** [comment]
@passy May I ask when will this fix deliver? What is the planning of next release?

**Comment by passy** [comment]
Hey @henryzx! Thanks for the fix. We have one issue we're currently trying to fix blocking releases but that should hopefully happen either today or tomorrow and then we can tag a new release.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by Rubon72** [comment]
yes it still problem
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:114890)
    at k (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:54165)
    at p (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:55172)
    at x (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:55825)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:58125
    at fi (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:69389)
    at li (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:71000)
    at Bl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:110334)
    at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:101446)
    at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:101374)
    at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:101227)
    at Lj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:98001)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:46741
    at _e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:101:3887)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:46516)
    at jg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:90:46686)

**Comment by mweststrate** [comment]
@Rubon72 this issue has been closed for 2 years. Please do open a new issue with reproduction steps, flipper version info, etc :)
