### ISSUE TITLE
Question: I can't see the network tab in flipper, is there something I'm doing wrong?

### ISSUE THREAD

**Issue by kyle-ssg** [facebook/flipper#2150]
Hi, I'm trying to see the network tab so that I can debug network requests however it's not available to me.

![image](https://user-images.githubusercontent.com/8608314/113437931-78496c80-93df-11eb-860e-ed37e238dbec.png)
![image](https://user-images.githubusercontent.com/8608314/113438480-92377f00-93e0-11eb-89f5-a1078534fb1b.png)
![image](https://user-images.githubusercontent.com/8608314/113438555-b4c99800-93e0-11eb-8141-f081ca81149e.png)

![image](https://user-images.githubusercontent.com/8608314/113437963-89927900-93df-11eb-88be-65d8a782ed31.png)

I think this could be due to having to run a custom emulator (Bluestacks) as I don't have an intel processor, however I'm unsure. I'm connected to the emulator fine as I see adb logs and I'm also connected to the Hermes debugger as I can add breakpoints.

Just to rule out, I've already added : 
```

      NetworkFlipperPlugin networkFlipperPlugin = new NetworkFlipperPlugin();
      NetworkingModule.setCustomClientBuilder(
          new NetworkingModule.CustomClientBuilder() {
            @Override
            public void apply(OkHttpClient.Builder builder) {
              builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
            }
          });
      client.addPlugin(networkFlipperPlugin);
      client.start();
```

I've also tried a few versions including 0.83

**Comment by mweststrate** [comment]
From the screenshots it looks like the `adb` can't read the application certificates, for which reason any further connection fails. This is indicated by the warning printed as well `does not support the adb shell run-as command`. So it seems that either your adb installation is out of date, or your emulator doesn't support the required adb commands indeed.

**Comment by kyle-ssg** [comment]
Thanks @mweststrate, that makes sense - should be able to debug it from that and see if Bluestacks can be configured to allow this.
