### ISSUE TITLE
react infinite scroll heap memory overuse??

### ISSUE THREAD

**Issue by hanfeni** [facebook/flipper#216]
Hi I am planner of one company who work for company providing mobile service for Korean physician.

And we are preparing for renovation of our mobile web service with React-redux
Like facebook and linkedin, new UI of our service is ‘Timeline’-style, so performance of infinite scroll including rendering and loading time is very critical. 

And we have difficulty in tuning of it. 
As the number of scrolling increases, some components of contents are delayed to render(android browser), or have to wait for a while, partially rendered(IOS BROWSER).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31125557/43887092-ba609440-9bf8-11e8-903d-b49029fd034c.gif)

We checked performance of it with chrome browser (desktop)

![1234](https://user-images.githubusercontent.com/31125557/43886507-df6ae9cc-9bf6-11e8-921a-b6f8bbd9c72d.png)

I would appreciate your help in advance.

(react 16.3.2 / we use react-waypoint)

**Comment by passy** [comment]
I do not see how this is related to Flipper at all. @hanfeni could it be that you picked the wrong GitHub project to report this too? Closing, but let me know if there's something I'm missing.
