### ISSUE TITLE
`DTServiceHub` and `diagnosticd` causes high CPU usage on Mac

### ISSUE THREAD

**Issue by arnnis** [facebook/flipper#2165]
## 🐛 Bug Report
When I open flipper these two process causes big CPU usage and fan noises. this is what I get in the console app, there are many of this error:

```Failed to bootstrap path: path = /Applications/Xcode.app/Contents/SharedFrameworks/DVTInstrumentsFoundation.framework/Resources/DTServiceHub, error = 2: No such file or directory```

I went to that directory and DTServiceHub was there.

I had similar issue with `instruments` process months ago and opened an issue here but can't find it right now.

related issue: #1992 

## To Reproduce
Just open the flipper app

## Environment
OSX: 10.15.7
Flipper: 0.83.0

Please make this high priority because it's very annoying

**Comment by mweststrate** [comment]
Which XCode version?

**Comment by arnnis** [comment]
XCode version: 12.3

**Comment by mweststrate** [comment]
To be fair I'm not sure what to do with this report, as it seems to do with your specific installation. Did you try another machine / reinstalling XCode to see if the problems persist? We do use `instruments` indeed, but I can't really reproduce your symptoms (XCode 12.4, same OS). Note that you can disable iOS support in settings. It might be interesting to check if disabling physical iOS device support makes a difference.

**Comment by arnnis** [comment]
The issue was from my idb installation. I'm not getting the `diagnosticd` process now.

 `Flipper GPU helper` is using so much cpu on idle too. There are some warning in the Electon console about my adb installation. Will check if those will fix the issue.

**Comment by mweststrate** [comment]
Might be related to https://github.com/facebook/flipper/issues/2173
