### ISSUE TITLE
re-add application icon

### ISSUE THREAD

**Issue by voxspox** [facebook/flipper#2168]
## 🐛 Bug Report
There is no icon in the Linux package.

The icon seems to be removed since 0.73
https://github.com/facebook/flipper/issues/1424#issuecomment-771616149

Please re-add the icon to the Linux package.

## Environment
Linux Flipper 0.83

**Comment by mweststrate** [comment]
Fixed in #2116, so should be fixed in next release

**Comment by voxspox** [comment]
Hi @mweststrate, I still can not find the icon in version 0.95.0 :(

https://github.com/facebook/flipper/releases/download/v0.95.0/Flipper-linux.zip
