### ISSUE TITLE
Question: Any timeline for native apple silicon support ?

### ISSUE THREAD

**Issue by umang-simform** [facebook/flipper#2169]

**Comment by mweststrate** [comment]
cc @passy

**Comment by passy** [comment]
Don't have anything to add to @mweststrate. Some more details would definitely be helpful.

**Comment by mweststrate** [comment]
Closing as answered

**Comment by umang-simform** [comment]
Sorry for the late answer but I was talking about the native arm64 based flipper app, Currently it is running through rossetta2 and it doesn't seems optimised well.
