### ISSUE TITLE
LeakCanarySonarPlugin missing 

### ISSUE THREAD

**Issue by pollux-** [facebook/flipper#217]
**com.facebook.sonar.plugins.leakcanary.LeakCanarySonarPlugin** missing in the dependency  

> com.facebook.flipper:flipper:0.6.16'

**Comment by passy** [comment]
What do you mean by "missing in the dependency"?

**Comment by JuanFCalle** [comment]
Same issue, there is no LeakCanarySonarPlugin in com.facebook.sonar.plugins.leakcanary

**Comment by passy** [comment]
I'm still not quite sure what this was about, but if I understand this right, the `0.6.16` release happened before the plugin was released. There's been a new release since then, so I'll close this, but please comment if you still run into this.
