### ISSUE TITLE
@rpath/glog.framework/glog not found at ExampleSwift 

### ISSUE THREAD

**Issue by rubikva** [facebook/flipper#2174]
Steps:
- Download flipper-master repo
- Go to path: /flipper-master/iOS/SampleSwift
- Run `pod install`
- Open `SampleSwift.xcworkspace`
- Run application (commant+R)
- Crash after openinig 

System: macOS BigSur
Xcode: Version 12.4 (12D4e)
Simulator: iOS 12.4, iOS 13 
Cocoapods: cocoapods-1.10

Console output:
```
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Users/mac/Library/Developer/Xcode/DerivedData/SampleSwift-eeopkljdgpkdpccizcxtzuakpaql/Build/Products/Debug-iphonesimulator
DYLD_FALLBACK_LIBRARY_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_INSERT_LIBRARIES=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateF
dyld: Library not loaded: @rpath/glog.framework/glog
  Referenced from: /Users/mac/Library/Developer/CoreSimulator/Devices/E5DD4803-CFD9-4304-BD0E-5F0916267C2F/data/Containers/Bundle/Application/1B9492F0-0B62-41BD-B08B-C66AFBEE4D2D/SampleSwift.app/SampleSwift
  Reason: image not found
```

**Comment by FFFang** [comment]
@rubikva  I don't know where this bug came from.But you can rename `Pods/Flipper-Glog/Frameworks/glog.xcframework/ios-arm64_i386_x86_64-simulator/Glog.framework` to `Pods/Flipper-Glog/Frameworks/glog.xcframework/ios-arm64_i386_x86_64-simulator/glog.framework` as a workaround.

**Comment by mweststrate** [comment]
cc @priteshrnandgaonkar doesn't look like it to me at first sight, but could this somehow relate to https://github.com/facebook/flipper/commit/6ba5a410a072917e5af23bedf9ba64c5254f9799 ?

**Comment by rubikva** [comment]
@FFFang thanks for the workaround! This fix the issue. 

Also, I found another issue, if Other Linker Flags contains `-all_load` flag - `Flipper-Folly` will fail with a lot of errors like: 
`Undefined symbols for architecture x86_64:
  "boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find()", referenced from:`

**Comment by andrew-nemtsev** [comment]
dyld: Library not loaded: @rpath/glog.framework/glog
this error is observer even if folders path match
Pods/Flipper-Glog/Frameworks/glog.xcframework/ios-arm64_i386_x86_64-simulator/glog.framework

**Comment by leolusoli** [comment]
As a workaround, i manage to make it work renaming **Clog** file inside `Pods/Flipper-Glog/Frameworks/glog.xcframework/ios-arm64_i386_x86_64-simulator/glog.framework` to **clog**.

**Comment by compojoom** [comment]
I ran into the same issue, but not with the example app in this repo, but with a custom app. I've installed `react-native-flipper` 0.86.0 on react-native 0.62.2 and got the exact same error and a crash with `dyld`__abort_with_payload:`

Renaming: `Pods/Flipper-Glog/Frameworks/glog.xcframework/ios-arm64_i386_x86_64-simulator/glog.framework/Glog` to `Pods/Flipper-Glog/Frameworks/glog.xcframework/ios-arm64_i386_x86_64-simulator/glog.framework/glog` solved it.

**Comment by baveku** [comment]
> here it is with uppercase Glog: https://github.com/priteshrnandgaonkar/glog/releases/tag/v0.3.8
😲 so sad for this issue

**Comment by baveku** [comment]
@priteshrnandgaonkar any update on the issue? I use Flipper-Glob: 0.3.8 on xCode 12.5 and Flipper 0.87.0

**Comment by AndriiDidkivsky** [comment]
Waiting for the fix too. 
xCode 12.5 and Flipper 0.86.0

**Comment by AndriiDidkivsky** [comment]
@compojoom but this workaround is not acceptable to production env.
I ran into this issue with custom app too. also on RN 0.62.2

**Comment by compojoom** [comment]
Yes, but I don't know why it happens. 

@AndriiDidkivsky  Actually I experienced this on React-Native 0.62.2 as well, when updating flipper to version 0.86. The funny thing is that when updating to react-native .64 and installing flipper 0.86 - we don't end up with the compiled framework, but with the sources.

**Comment by priteshrnandgaonkar** [comment]
Flipper-Glog 0.3.9 addressses this issue.
