### ISSUE TITLE
Discussion: Hide one section is opened on next network call again

### ISSUE THREAD

**Issue by WarrenFaith** [facebook/flipper#2194]
Sorry, I failed to find a better formed title but I suggest the following improvement:

I have a very long authentication bearer in every request I make to our backend. So when I am investigating a lot of network requests, I always have to scroll down to see the request and the response because the bearer takes close to the complete height of the sidebar.

I have two suggestion which would ease my usage of Flipper a lot:

1. use marquee to "cut" long headers (I can copy the value easily with the already existing context menu)
2. if I collapse the "Request Headers" section, keep it collapsed when I switch to another network request. Currently the section is expanded again making me scroll again and again and again whenever I switch to another network request.

Keep it up!

**Comment by bizzguy** [comment]
@WarrenFaith  I like #2, might be useful to make status (open/closed) of all the sections persist.

**Comment by bizzguy** [comment]
@mweststrate   Could you label this as network plugin

**Comment by mweststrate** [comment]
For remembering the panel state; we plan to address this at the component library level as it applies to many plugins.

**Comment by bizzguy** [comment]
@mweststrate  I was thinking of working on this.  Do you think that the time-frame for the component level change is such that it is not working making a temporary fix?

**Comment by bizzguy** [comment]
@mweststrate   We've already got one fix in which persists the selection of "Body" in the "Options" section, so just expanding that would be a fairly quick fix.

**Comment by mweststrate** [comment]
I think ~2 weeks

**Comment by bizzguy** [comment]
@mweststrate   That's pretty soon - sounds like I should find something else to work on :)

**Comment by mweststrate** [comment]
Implemented, should be part of the next release or the one after that.

**Comment by WarrenFaith** [comment]
Verified that it is working with version 0.88.0
