### ISSUE TITLE
React Native hermes debugger crash my App on Simulator! 

### ISSUE THREAD

**Issue by TheSolly** [facebook/flipper#2196]
## 🐛 Bug Report

Running latest react native and flipper, whenever I build my App on iOS 14.4 simulator and press on the Hermes Debugger under the react-native Tab, my App crashes With an error 
```
signal 11 was raised (null)
```
![Simulator Screen Shot - iPhone 12 - 2021-04-15 at 10 19 59](https://user-images.githubusercontent.com/31882844/114837618-31427a80-9dd4-11eb-910a-fe7074e8b7ee.png)

## Environment

macos bigsur
iOS: 14.4 (simulator) 
react-native: 0.64
flipper: 0.85, 0.84

**Comment by mweststrate** [comment]
Would you mind trying to debug with an unembedded debugger? (see https://reactnative.dev/docs/debugging#chrome-developer-tools). If that doesn't crash, let us know. If that still does crash, it is probably best to file the issue at https://github.com/facebook/hermes instead.

**Comment by TheSolly** [comment]
Yeah, using Chrome developer tools does crash the app as well. Will open an issue on Hermes. Thanks.

**Comment by KamauIan** [comment]
> Yeah, using Chrome developer tools does crash the app as well. Will open an issue on Hermes. Thanks.

Did you find a solution for this?

**Comment by IAmMarcellus** [comment]
@KamauIan Looks like this is still an issue: https://github.com/facebook/hermes/issues/516

**Comment by stmiller-shamrock** [comment]
Does anyone having this issue use react-native-reanimated? I had this same issue until I tracked it down to that package. The 2.2.0 version fixed it for me, even mentions the fix in the release notes: https://github.com/software-mansion/react-native-reanimated/releases/tag/2.2.0

**Comment by mweststrate** [comment]
Closing here as this is an open issue in Hermes https://github.com/facebook/hermes/issues/516
