### ISSUE TITLE
Search with an exclude regular expression not working

### ISSUE THREAD

**Issue by tvc97** [facebook/flipper#2214]
Logs and Network plugin not seem to be working correctly when search with an excludes regex pattern.
E.g. `^((?!localhost).)*$` is still match `localhost:8081/status`

![flipper](https://user-images.githubusercontent.com/6320796/115331089-7cd39a80-a1bf-11eb-85f9-dcc4d20164d4.png)

**Comment by mweststrate** [comment]
Thank for the report, we'll look into it!

**Comment by mweststrate** [comment]
The reason this still shows results is that the search bar searches multiple fields, and some of the other fields (that might not contain a URL at all) will match this regex fine, for which reason the results are shown. In the updated version of the network plugin that will be rolled out next week it is possible to filter per column, although we don't support negative filters yet.
