### ISSUE TITLE
Variant image building-city not found 

### ISSUE THREAD

**Issue by Warmachine13** [facebook/flipper#2217]
On  build show error 

          throw ex;
          ^

RuntimeError: abort(Error: Could not download the icon building-city from https://external.xx.fbcdn.net/assets/?name=building-city&variant=filled&size=16&set=facebook_icons&density=1x: got status 404). Build with -s ASSERTIONS=1 for more info.

**Comment by priteshrnandgaonkar** [comment]
Can you please provide more information of how to reproduce it ?
