### ISSUE TITLE
Flipper + Gradle 7

### ISSUE THREAD

**Issue by lucasapereira** [facebook/flipper#2221]
## 🐛 Bug Report

Flipper is not working with Gradle 7

## To Reproduce

distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-bin.zip

## Environment

Flipper 0.85

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/lucas/pontoaponto/pap-passageiro-mobile/node_modules/react-native-flipper/android/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':react-native-flipper'.
> Plugin with id 'maven' not found.

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-flipper'.
> compileSdkVersion is not specified. Please add it to build.gradle

**Comment by devleonardorabelo** [comment]
Same problem here

**Comment by junioorpl** [comment]
Same problem here man :(

**Comment by passy** [comment]
Probably won't have the bandwidth to look into this in the near future. If someone wants to take a look and work on a PR, I'd be happy to take a look.

**Comment by nikolajskov** [comment]
This issue seems not be solved. Using version 0.92.0 still produces this error with gradle:

Build file '/node_modules/react-native-flipper/android/build.gradle' line: 30

A problem occurred evaluating project ':react-native-flipper'.
Plugin with id 'maven' not found.

See: https://github.com/facebook/flipper/blob/7bd4f80c2570bebb52af3cf49e45fc6130d6a473/react-native/react-native-flipper/android/build.gradle#L30

**Comment by ClementLevesque** [comment]
Same problem with version 0.93.0

**Comment by nikolajskov** [comment]
The error is still in 0.94.1.

@passy: Are we doing something wrong or is the error still unfixed?

**Comment by passy** [comment]
Sorry, I think I missed the RN bit as part of the conversion. Will take a look in the next few days.

**Comment by passy** [comment]
There are still some issues with the RN integration which show up in CI. I won't be able to look into this in the near future so if someone else would like to take a stab at it, please feel free!

**Comment by leotm** [comment]
Got the same couple issues as OP with Flipper 0.99, cheers @lucasapereira for raising 🍻

Uploaded more detailed logs here if useful
https://scans.gradle.com/s/et3ewmveubhae

---

Managed to get it working in a minimal template project in the end
https://github.com/leotm/react-native-template-typescript

Some deets on what needed to be done
https://github.com/leotm/react-native-template-typescript/commit/2fd5737c331f57eecd34d1c7c130070e38570806

And PR here
https://github.com/facebook/flipper/pull/2619
