### ISSUE TITLE
font-family spaces characters in arch linux

### ISSUE THREAD

**Issue by betoharres** [facebook/flipper#2222]
## 🐛 Bug Report

Hello, I'm developing in a minimal environment(Arch linux + xfce4 without the goodies) and I installed Flipper through Yay. I have some of the main fonts installed but Flipper for some reason opens with it's characters spaced out. I've been disabling it every time I open flipper for the past months, and it doesn't seem that this is going to be fixed any time soon, so I'd like to request to remove this feature if possible.
It makes things hard to read across the entire app, for all plugins.
Here's a screenshot of how it looks like:
![image](https://user-images.githubusercontent.com/1681530/115897075-6e40e980-a432-11eb-9acf-76dc61f49b8e.png)
![image](https://user-images.githubusercontent.com/1681530/115897155-8153b980-a432-11eb-83c7-77cc28de83a8.png)

## Environment

Arch linux: 5.10.29-1-lts

![image](https://user-images.githubusercontent.com/1681530/115897860-43a36080-a433-11eb-9fbf-3f519ba79250.png)

**Comment by priteshrnandgaonkar** [comment]
@mweststrate will be able to better address this.

**Comment by mweststrate** [comment]
@betoharres what do you mean with "I've been disabling it every time I open flipper for the past months". What is "it" referring to? What / how do you disable?

**Comment by betoharres** [comment]
@mweststrate hi! I meant that every time I open Flipper, I have to open the Developer tools and then disable the font-family at the root element. By doing this, font revert back to system default(I think) and the text is shown properly. I'm not sure why this happens, I've already made 2 clean installations and the problem persisted.

**Comment by mweststrate** [comment]
Yes that sounds like a minimal available fonts availability issue. It looks like the fallback is now a font with really weird spaces. Feel free to PR and add an additional font to the font-family list that is available on your system, so that that will be used as fallback. I'm afraid that without a means to reproduce it I have no way to personally test what a reasonable fallback would be.
