### ISSUE TITLE
Discussion: Text not visible in Flipper Dark Theme 

### ISSUE THREAD

**Issue by israr-shaikh** [facebook/flipper#2223]
Hi Flipper Team, 
 After getting an update on the dark theme, we have been facing text visibility issues on many modals like plugin manager and network as well.

![Screenshot 2021-04-26 at 3 52 17 PM](https://user-images.githubusercontent.com/16683354/116068149-8a998c00-a6a7-11eb-90b2-2cb1bfb5a39d.png)
![Screenshot 2021-04-26 at 3 52 57 PM](https://user-images.githubusercontent.com/16683354/116068164-8cfbe600-a6a7-11eb-8c1d-e6ad041a089e.png)

Thanks in advance.

**Comment by passy** [comment]
Thanks! There's a revamp of the plugin manager coming. We're probably not gonna make big investments in the current one, which includes updating it to our new UI library which has proper support for dark mode.

**Comment by passy** [comment]
Closing this one for now, but thanks for letting us know!
