### ISSUE TITLE
React Native: Unable to inspect contents in React Dev Tools/Layout Inspector

### ISSUE THREAD

**Issue by micnguyen** [facebook/flipper#2224]
## 🐛 Bug Report
- When I start a bare React Native project and I select the React Dev Tools, whenever I select an element, it stays as `Loading` forever on the side panel:

<img width="1512" alt="Screen Shot 2021-04-26 at 10 00 50 pm" src="https://user-images.githubusercontent.com/919166/116079270-f1846880-a6da-11eb-87e7-fa941a191165.png">

 and in the app I get this error:
<img width="484" alt="Screen Shot 2021-04-26 at 9 32 46 pm" src="https://user-images.githubusercontent.com/919166/116076294-62298600-a6d7-11eb-80a0-f1203f3cb2af.png">

## To Reproduce
- Start brand new React Native Project
- Open Flipper
- Select React Dev Tool and select a Text element to change
- View iPhone Simulator and it has the error

## Environment
iOS: 14.4
macOS: 11.2.3
"react": "17.0.1",
    "react-native": "0.64.0"
Flipper: 0.86.0

**Comment by mweststrate** [comment]
This means the react-devtools-core is out of sync with the DevTools in Flipper. This has recently been addressed in https://github.com/facebook/react/pull/21331

But in the mean time you an address the issue by specifying which version of the devtools are needed in your package.json, for example (the version used in Flipper is shown at the top of the plugin): 

```
"resolutions": {
   "react-devtools-core": "4.10.3"
}
```

**Comment by mweststrate** [comment]
The next version of Flipper will support connecting to the React DevTools of older versions.
