### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by jonathanroze** [facebook/flipper#2247]
Hi,

I'm using the latest version of Flipper (Also tried 0.86 and 0.85) and I've very high CPU usage (diagnosticd) and I rand a cmd to have CPU temperature, when Flipper is close, it's around 60°c and when I open Flipper it's between 90°C and 100°c and after several minutes my Mac just showdown sometimes...

Big Sur: 11.3 (also tried on 11.2.3)
Xcode : 12.5 (tried on 12.4)

MacBook Pro 16 inch, I9, 64go Ram

So if you have any ideas because I can't use flipper more than 5 minutes ...

**Comment by passy** [comment]
Some previous issues around this. Sadly out of our control: https://github.com/facebook/flipper/search?q=diagnosticd&type=issues

**Comment by jonathanroze** [comment]
Hey @passy Thanks for your time.

I figure out why Flipper's CPU usage was too high.

IDB wasn't properly configure in Flipper, since I set the right path everything is working cooler :)
