### ISSUE TITLE
Pods update killed system

### ISSUE THREAD

**Issue by ArturIgnatov** [facebook/flipper#2248]
## 🐛 Bug Report
After the pod update command, the mac heats up, freezes and after a while it turns off. This was reproduced on two different macs. I tried to remove and reinstall. Nothing helps. This bug is in the last update, everything was fine a day ago

**Comment by andreialecu** [comment]
Can also confirm this:

<img width="333" alt="Screenshot 2021-04-30 at 14 46 27" src="https://user-images.githubusercontent.com/697707/116690963-d9566700-a9c2-11eb-9205-de75dbcc773c.png">

Seems the CPU is stuck with a `ruby` process at 100%. I'm on an M1 mac.

**Comment by andreialecu** [comment]
Update since my previous post. After letting it run for a while longer (5+ minutes) it eventually finished:

<img width="717" alt="Screenshot 2021-04-30 at 14 50 47" src="https://user-images.githubusercontent.com/697707/116691415-73b6aa80-a9c3-11eb-9b29-cc93a52d76ca.png">

Not sure why this took so long, it never took so long before.

**Comment by ArturIgnatov** [comment]
> Update since my previous post. After letting it run for a while longer (5+ minutes) it eventually finished:
> 
> <img alt="Screenshot 2021-04-30 at 14 50 47" width="717" src="https://user-images.githubusercontent.com/697707/116691415-73b6aa80-a9c3-11eb-9b29-cc93a52d76ca.png">
> 
> Not sure why this took so long, it never took so long before.
> 
> Additional update: This seems to happen every time `pod install` or `pod update` is ran now, during the `Generating Pods project` step.
> 
> `top` shows `ruby` at 50-100% cpu for the duration. Even the mouse seems laggy at times.

Probably my mac is weaker, so it cannot end and mac reboots. the cursor does not move at all at this moment

**Comment by FloEder** [comment]
Facing exactly the same issue as @andreialecu, tried to run pod install with verbose flag and it seems like the issue as something to do with openssl

pod install blocks at the following output: 

Integrating target `OpenSSL-Universal`
    Adding Build Phase '[CP] Copy XCFrameworks' to project.
  - Generating deterministic UUIDs

**Comment by andreialecu** [comment]
A `pod install` with no changes seems to take 5 minutes on my M1, but it does finish.
```
➜ time pod install
Pod installation complete! There are 79 dependencies from the Podfile and 76 total pods installed.
pod install  150.16s user 40.61s system 61% cpu 5:11.30 total
```

**Comment by andreialecu** [comment]
Reverting the `Podfile.lock` changes and reinstalling the previous version of the Flipper pods fixes the issue. However, I can't seem to run on iOS 14.5 with the older Flipper (without disabling it).

```
➜ time pod install
Auto-linking React Native modules for target ...
Analyzing dependencies
Downloading dependencies
Installing Flipper-Folly 2.5.1 (was 2.6.2)
Installing Flipper-RSocket 1.3.1 (was 1.4.1)
Installing SDWebImage 5.11.0 (was 5.11.1)
Removing Flipper-Boost-iOSX
Removing Flipper-Fmt
Generating Pods project
Integrating client project
Pod installation complete! There are 79 dependencies from the Podfile and 74 total pods installed.
pod install  6.96s user 4.64s system 92% cpu 12.608 total
```
(only 12 seconds)

**Comment by andreialecu** [comment]
@FloEder. I can also confirm that it gets stuck on `Generating deterministic UUIDs` via `pod update --verbose`. In my case it's on a different pod though:

```
Integrating target `react-native-config`
    Adding Build Phase '[CP-User] Config codegen' to project.
  - Generating deterministic UUIDs
```

The flipper update triggers the bug though, not sure how it relates to deterministic UUIDs.

This seems to be related: https://github.com/CocoaPods/CocoaPods/issues/10506

**Comment by alimek** [comment]
same, every thing was fine yesterday, then did OSX update, pod update and its taking ages 👴

**Comment by mrousavy** [comment]
I managed to get it working with Flipper by just deleting the entire project from disk, then cloning it again from git. Not sure what files were problematic here, I tried to find all untracked cache files but couldn't figure out which were causing those problems.
Disabling Flipper seems to be the most convenient workaround if you're not using it, which is a dumb assumption since we're talking in the flipper repo here.

**Comment by alimek** [comment]
@priteshrnandgaonkar which version of Flipper-Folly and Flipper-RSocket  is working fine for you

**Comment by priteshrnandgaonkar** [comment]
@alimek 

Use Flipper-Folly 2.5.1 and Flipper-RSocket 1.3.1 for the time being.

**Comment by FloEder** [comment]
FYI: if it helps @priteshrnandgaonkar i'm facing this on Xcode Version 12.4, with Catalina 10.15.7.

**Comment by alimek** [comment]
FYI, if you face issue with `'atomic_notify_one<unsigned long>' is unavailable` then use `'Flipper-Folly' => '2.5.3'`, this version works well and fixing this issue.

**Comment by priteshrnandgaonkar** [comment]
People who are facing this pod update issue, are you on Big Sur ? Because even with older pods it feels like it gets stuck at "Generating Pods project".

**Comment by alimek** [comment]
yes `Big Sur 11.3`

**Comment by pktippa** [comment]
@alimek https://github.com/facebook/flipper/issues/2248#issuecomment-830060572 worked like charm, thanks a lot!!

**Comment by priteshrnandgaonkar** [comment]
Mac OS updates always has gifts wrapped in it. :(

**Comment by Macrow** [comment]
I have the same issue in Big Sur 11.1

**Comment by priteshrnandgaonkar** [comment]
Closing this as #2245 solves this issue.

**Comment by priteshrnandgaonkar** [comment]
The issue was not with our setup, but the issue was with the cocoapods. Cocoapods apparently hangs up  while creating xcworkspace when one of the pods have many source files. One such pod was the Boost which I updated. To navigate around this I updated the podspec to not mention header files in the podspec but refer it directly by putting its path location in header search path. That solved the issue related to pod install getting stuck at workspace creation.

**Comment by ghasemikasra39** [comment]
I have the same issue on my machine:

```bash
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 35.37 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v14.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
```

```bash
Flipper  0.96.1
Flipper-Folly 2.6.9
Flipper-RSocket 1.4.3
FlipperKit  0.96.1
OpenSSL-Universal 1.1.1100
```

**Comment by ghasemikasra39** [comment]
> @priteshrnandgaonkar which version of Flipper-Folly and Flipper-RSocket is working fine for you
> 
> EDIT:
> `use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })` did trick for me

This works because with these old versions the package `Flipper-Boost-iOSX` is not used. With the latest version of `Flipper-Folly 2.6.9`, the package `Flipper-Boost-iOSX` is being used, and then you get this issue.

**Comment by ArtemKha** [comment]
> @priteshrnandgaonkar which version of Flipper-Folly and Flipper-RSocket is working fine for you
> 
> EDIT: `use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })` did trick for me

It doesn't work with `use_frameworks!` option unfortunately.

**Comment by ahmedtausif** [comment]
git system a restart or kill all ruby processes then do pod install. this fix mine.
