### ISSUE TITLE
Improve Android Travis build cache

### ISSUE THREAD

**Issue by passy** [facebook/flipper#226]
There's a lot of duplicate work every time we run travis leading to pretty intense build times. We should cache things like the NDK and SDK and skip extraction if it's already in place.

This is basically limited to modifying the `.travis.yml`, but if the logic in there becomes too complex, we may want to turn this into a separate script.

This is a great starter task. Please just comment here if you're interested in giving it a try or need a helping hand.

**Comment by AadityaDev** [comment]
@passy I want to fix this issues. Is this issue still open?
