### ISSUE TITLE
Question: persist state during flipper restarts

### ISSUE THREAD

**Issue by maxim-pandra** [facebook/flipper#2266]
Hi, documentation for the persistedState api says:  

> however it is not persisted across restarts of Flipper (by default).

But i didn't find a way to enable saving state during application restarts. 

Is it possible? 
Maybe some plugin handle app restarts?

**Comment by passy** [comment]
I'm not sure if we have a proper cross-restart persistence API yet. @mweststrate can probably correct me here, but for one-off cases we've used localStorage in some places.

**Comment by mweststrate** [comment]
First of all, the `persistedState` API is intended to 'persist' state between the user navigation between the current plugin, another one, and coming back to it. That notion however is deprecated now with the new Sandy plugin architecture. See https://fbflipper.com/docs/tutorial/js-custom.

To safe preferences across restarts localstorage can be used indeed, for which [useLocaStorageState](https://fbflipper.com/docs/extending/flipper-plugin#uselocalstoragestate) can be used. If interested, we could add an option to create state as well in [createState](https://fbflipper.com/docs/extending/flipper-plugin#createstate). But note that this mechanism should only be used to remember things like preferences, not the state of a plugin in general (e.g. don't store network state in local storage, that will blow up quickly). Hope that helps!

**Comment by passy** [comment]
Thanks, @mweststrate. Closing this one but please let us know if there's anything else, @maxim-pandra!
