### ISSUE TITLE
Create Paste feature does not work

### ISSUE THREAD

**Issue by nehalsep7** [facebook/flipper#2267]
## 🐛 Bug Report
Create Paste does not do anything

## To Reproduce
Tap on Network
Select any row and right click
Click option to Create Paste, clicking on it does nothing

## Environment
Mac app used for Android device

Code has no implementation:
export default function createPaste(
  _input: string,
): Promise<string | undefined> {
  return Promise.reject(new Error('Not implemented!'));
}

**Comment by nehalsep7** [comment]
Can someone help understand how to implement this? Is this same as creating the Paste in phabricator? What sort of experience do we want here?

**Comment by passy** [comment]
We should probably hide that in public releases. Yes, we use a Phabricator endpoint for this internally that returns a URL.

**Comment by mweststrate** [comment]
Pretty sure this is already being addressed in the upcoming network plugin release. I'll self assign just to be sure :)

**Comment by mweststrate** [comment]
In the updated version of the Network plugin that will be rolled out next week the createPaste button will no longer be visible in OSS versions of the plugin. Thanks for reporting!

**Comment by nehalsep7** [comment]
ok, thanks! I have always wanted that button to work but do realise that it might not be feasible, is the complexity around the implementation the reason for dropping it?

**Comment by mweststrate** [comment]
Nope, there is simply no public implementation yet. If someone would PR something that uses, for example, Github gists, we'd happily expose the functionality in public builds :) https://github.com/facebook/flipper/blob/master/desktop/app/src/fb-stubs/createPaste.tsx

**Comment by nehalsep7** [comment]
Interesting, thanks for letting me know! Will explore github gists api as well.
