### ISSUE TITLE
FlipperOkhttpInterceptor mock: must call proceed() exactly once

### ISSUE THREAD

**Issue by henryzx** [facebook/flipper#2276]
## 🐛 Bug Report

When a mock response is triggered in network intercept, okhttp 4.9.1 complains (app crashes):

```
FATAL EXCEPTION: OkHttp Dispatcher

java.lang.IllegalStateException: network interceptor com.facebook.flipper.plugins.network.FlipperOkhttpInterceptor@5ab0fcc must call proceed() exactly once

FATAL EXCEPTION: OkHttp Dispatcher
Process: com.airbnb.android.development, PID: 26965
java.lang.IllegalStateException: network interceptor com.facebook.flipper.plugins.network.FlipperOkhttpInterceptor@5ab0fcc must call proceed() exactly once
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:113)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.airbnb.android.base.data.net.RecentRequestTracker.intercept(RecentRequestTracker.kt:29)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at 
```

I believe this is a new check introduced with new okhttp. and the reason is that the interceptor did not trigger other interceptors in this [line](https://github.com/facebook/flipper/blame/7bd4f80c2570bebb52af3cf49e45fc6130d6a473/android/plugins/network/src/main/java/com/facebook/flipper/plugins/network/FlipperOkhttpInterceptor.java#L97).

## To Reproduce

add mock request in network plugin
trigger the mock request

## Environment
okhttp 4.9.1

**Comment by cekkaewnumchai** [comment]
@henryzx are you using `addNetworkInterception`? The feature is supported under `addInterception` because it allows short-circuit (e.g. not calling `chain.proceed`). You can read more from [the commit](https://github.com/facebook/flipper/commit/d27e45d7bb7f12d40c5c80aca1162c78a3d38357)
