### ISSUE TITLE
Android Incremental Build

### ISSUE THREAD

**Issue by jknoxville** [facebook/flipper#230]
Currently when building the android project, all of the C++ code is compiled every time, even if it hasn't been modified, making builds FAR slower than they should be.

This appears to be because our ExternalNativeBuildTask doesn't declare any outputs, as shown by a gradle build scan, but not knowing much about gradle, I don't know how to fix this.

**Comment by passy** [comment]
Exactly. This can also be seen by running `./gradlew :android:assembleDebug --info`:

```
> Task :android:generateJsonModelDebug UP-TO-DATE
Skipping task ':android:generateJsonModelDebug' as it is up-to-date.                                                                                     :android:generateJsonModelDebug (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.011 secs.
:android:externalNativeBuildDebug (Thread[Task worker for ':' Thread 6,5,main]) started.

> Task :android:externalNativeBuildDebug
Task ':android:externalNativeBuildDebug' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
```

I don't know how this is declared internally in the android plugin and how targets are normally determined. It could be that this gets derived from the `CMakeLists.txt` and ours doesn't pass that heuristic or something entirely different.

**Comment by passy** [comment]
Dug into this a bit more, and it seems like `Task has not declared any outputs despite executing actions.` is not actually the reason why this is slow. The `ExternalNativeBuildTask` appears to never declare any outputs no matter what. Instead, it relies on `ninja`/`cmake` being "fast enough" to just skip doing any work. This works for `./gradlew :easywsclient:externalNativeBuildDebug` which takes just 2s on my machine.

The real problem seems to be that the `libfolly` subproject is always marked as out-of-date.

Some interesting information from the terminal:
```
> Task :android:generateJsonModelDebug
External native generate JSON debug: starting JSON generation
External native generate JSON debug: using platform version 15 for ABI ARMEABI_V7A and min SDK version 15
External native generate JSON debug: noticing that build file '/home/realpassy/local/fbsource/xplat/sonar/android/third-party/external/folly/CMakeLists.txt' is out of date with respect to /home/realpassy/local/fbsource/xplat/sonar/android/.externalNativeBuild/cmake/debug/armeabi-v7a/android_gradle_build.json
External native generate JSON debug: rebuilding JSON /home/realpassy/local/fbsource/xplat/sonar/android/.externalNativeBuild/cmake/debug/armeabi-v7a/android_gradle_build.json due to:
External native generate JSON debug: - a dependent build file changed
External native generate JSON debug: keeping json folder '/home/realpassy/local/fbsource/xplat/sonar/android/.externalNativeBuild/cmake/debug/armeabi-v7a' but regenerating project
External native generate JSON debug: executing cmake Executable : /opt/android-sdk/cmake/3.6.4111459/bin/cmake
arguments :
-H/home/realpassy/local/fbsource/xplat/sonar/android
-B/home/realpassy/local/fbsource/xplat/sonar/android/.externalNativeBuild/cmake/debug/armeabi-v7a
-DANDROID_ABI=armeabi-v7a
-DANDROID_PLATFORM=android-15
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/realpassy/local/fbsource/xplat/sonar/android/build/intermediates/cmake/debug/obj/armeabi-v7a
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=/opt/android-sdk/ndk-bundle
-DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake
-DCMAKE_MAKE_PROGRAM=/opt/android-sdk/cmake/3.6.4111459/bin/ninja
-GAndroid Gradle - Ninja
-DANDROID_TOOLCHAIN=clang
-DANDROID_STL=c++_shared
jvmArgs :


fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I guess the next step would be to figure out why the generated `CMakeLists.txt` and `android_gradle_build.json` are non-deterministic.

**Comment by passy** [comment]
Some more investigation results.

- As soon as `./gradlew :android:externalNativeBuildDebug` even *starts* (i.e. even when quickly CTRL+C-ing), `cmake` will rerun all build steps.
- `./gradlew --dry-run  :android:externalNativeBuildDebug` will *not* (as it should) impact the cache. Rerunning `cmake --build ...` still yields ` :android:externalNativeBuildDebug`.
- Individual steps like `./gradlew :third-party:prepareOpenSSL` also leave the cache untouched.
- This can likely be bisected to an individual task. Right now I'm at `./gradlew :third-party:prepare` which is enough to break the cache.
