### ISSUE TITLE
Installing plugin then reloading shows plugin as uninstalled

### ISSUE THREAD

**Issue by kyle-ssg** [facebook/flipper#2303]
## 🐛 Bug Report
Installing a particular plugin seems to install fine without error but reloading flipper seems to show the plugin as not installed. I've raised this [here](https://github.com/jk-gan/redux-flipper/issues/42) but similarly it shouldn't just silently fail in Flipper.

## To Reproduce
Attempt to install redux-flipper 

<img src="https://recordit.co/9FKOYL7dw1.gif"/>.

## Environment
Flipper 0.88

**Comment by cekkaewnumchai** [comment]
Thank you for reporting to us. Unfortunately, I can't repro this locally. @nikoant do you know what can cause this?

**Comment by kyle-ssg** [comment]
To add to this I've deleted the app, reinstalled and it still occurs, I've only seen it happen with "redux-debugger"

**Comment by nikoant** [comment]
It sounds like an issue which was fixed few days ago. We'll soon release a fresh Flipper version.

**Comment by mweststrate** [comment]
We just released 0.89, so should have been fixed. If not, let us know!

**Comment by kyle-ssg** [comment]
Exact same issue in 0.90 I'm afraid, @mweststrate.

**Comment by mweststrate** [comment]
cc @nikoant

**Comment by jacklj** [comment]
I'm getting the same thing; I think I know what caused it, in my case at least.

I installed `flipper-plugin-react-query-native-devtools` and then went to the App Inspect tab to enable the plugin. But I accidentally pressed the Trash icon that appears when you mouseover the plugin item in the list. 
I couldn't find a way to "undelete" the plugin, so uninstalled it (despite it being hidden, it was still installed). 

But now when I try and reinstall it, I get the same problem as OP - on restart, it is immediately uninstalled.

**Comment by jacklj** [comment]
In my case, `File > Preferences > Reset all local storage based state` fixed it 👍
