### ISSUE TITLE
Can not scroll horizontally when using database plugin

### ISSUE THREAD

**Issue by kjetile** [facebook/flipper#2306]
## 🐛 Bug Report
After upgrading to Flipper 0.88 I can no longer scroll horizontally in the database plugin view. There used to be a horizontal scroll bar but not anymore:
![flipper](https://user-images.githubusercontent.com/955984/117935907-835bba80-b304-11eb-9746-41af29aad292.png)

## To Reproduce
Open a database table in the database inspector where all the columns do not fit on screen at the same time. Horizontal scrolling doesn't work.

## Environment
Samsung Galaxy S20 Ultra 5G running Android 11, Flipper OSX desktop client v0.88, macOS Big Sur v11.2.3, Database plugin v.0.88.0.

**Comment by maxim-pandra** [comment]
This worked before the redesign of the plugin. Please fix this.
New design is cool, but not all columns are shown :(
