### ISSUE TITLE
Network Plugin: Flipper hangs when exporting Network calls

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#2308]
## 🐛 Bug Report
During export of Network calls, Flipper hangs.  Export does not complete and Flipper is locked

## To Reproduce
Create a large number of requests (some with large payloads) and export them.  I was not able to duplicate this using the sample app but it occurs using production data for my app.  Same calls were exported properly in earlier versions.

## Discussion
Given that this may be difficult to reproduce in development environment, any suggestions for how to further debug this would be appreciated.

Also, in the screenshot below, the status screen shows 134 of 139.  This is much more than the number of calls.  Not sure what these numbers mean.  I think I was exporting log records at the same time - is it a total of all object exported?

## Environment
Flipper desktop: 0.89.0 (and 0.88.0)

![image](https://user-images.githubusercontent.com/337874/118183460-c189d480-b3ff-11eb-9acb-deb6fe9e7e77.png)

**Comment by bizzguy** [comment]
I'm wondering if this is hanging on a particularly large response.  I'll do more research.

**Comment by mweststrate** [comment]
I suspect this hangs primarily on requests that contain binary data? (e.g. images). Might have missed that in the unit tests.

**Comment by bizzguy** [comment]
Hmmm.  Maybe my requests that are showing "binary data" really are.  I thought they were JSON but I'll have to confirm.

There's an open issue about showing image data - https://github.com/facebook/flipper/issues/1694

**Comment by mweststrate** [comment]
Note that we now respect mime-headers, so if no Content-Type is set on the
response, Flipper will assume that the data is binary, even when your
application might treat it as text still. For the open image issue, I'm not
sure if that is a very important case to support, as it is specifically
about multipart encoded requests (with the new plugin setup it would be
easier to implement though)

**Comment by bizzguy** [comment]
@mweststrate   Thanks for the info on the headers.  I'll check that.  Images is not an important use case for how I use the Network Plugin.  My app uses an image library so they go through a completely different route.

**Comment by bizzguy** [comment]
This has been fixed.
