### ISSUE TITLE
Discussion: [iOS]Is the way we use the FLEX library the right integration way?

### ISSUE THREAD

**Issue by FFFang** [facebook/flipper#2309]
Flipper modify some files of FLEX lib,which will cause dumplicate symbols if we use FLEX and flipper at the same time.

Flipper and FLEX have different focuses.Could we find a better way to integrate FLEX?If I want to work on this,will flipper accept this proposal?

**Comment by mweststrate** [comment]
@FFFang it is hard to give a meaningful response to the question without knowing what the exact current problem or the proposed solution is. But if you feel that the setup could be improved feel free to write a proposal with more details or set up a rough PR and we can review and discuss it further from there.
