### ISSUE TITLE
After restarting Android app new network requests don't show up

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#231]
1) make requests using a test app
2) observe requests showing up
3) restart app
4) make requests
5) observe requests not showing up
6) change tab e.g. to shared preferences and back again
7) observe previous requests now show up

Version App : 0.6.12
Android version: 0.6.16

**Comment by yschimke** [comment]
Video https://vimeo.com/user26402724/review/285148758/a9ad12a301

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
