### ISSUE TITLE
LeakCanary and LeakCanary 2 plugins break the android release build

### ISSUE THREAD

**Issue by jguix** [facebook/flipper#2310]
## 🐛 Bug Report
Following setup instructions for both plugins leads to break the android release build.

https://fbflipper.com/docs/setup/leak-canary-plugin/
https://fbflipper.com/docs/setup/leak-canary-2-plugin/

Plus, the setup is not clear as to whether some parts of code should go to `MainApplication.java` or `ReactNativeFlipper.java`, and some of the imports are missing. I had to figure the whole thing out, to make the plugins work, but still the release build was broken.

## To Reproduce
In a React Native app, configure any of leak-canary or leak-canary-2 plugins following the setup instructions.

```
cd android
./gradlew assembleRelease
```

## Environment
React Native v0.63.3
Flipper Desktop 0.87.0

**Comment by passy** [comment]
Could you please provide the error you're seeing?
