### ISSUE TITLE
Question: Network tab showing only localhost images, can't log anything that's remote.

### ISSUE THREAD

**Issue by Mladen1kus** [facebook/flipper#2315]
**_Network tab showing only localhost images, can't log anything that's remote._**

Does anyone have the same issue, i can't figure out what i am missing, maybe something in the setup or some additional plugin or setting.

So far only on iOS Simulator, haven't tried Android yet.

Any tips are appreciated, 
Thanks in advance

**Comment by mweststrate** [comment]
Could you provide some additional information, like the size of the image, the Content-Type of the response, Flipper and SDK versions, kind of stack (RN / Swift) etc.

**Comment by Mladen1kus** [comment]
Hi @mweststrate, the issue is: i don't see anything but that one image which i don't care about. When i run android, either emulator or real device i can see network correctly. We are using reactotron as a backup until we sort this out.

**Comment by mweststrate** [comment]
Sounds like a setup issue indeed. The two important reference points to check are: 

https://github.com/facebook/flipper/blob/master/react-native/ReactNativeFlipperExample/ios/Podfile
https://github.com/facebook/flipper/blob/master/react-native/ReactNativeFlipperExample/ios/ReactNativeFlipperExample/AppDelegate.m#L31-L32

**Comment by Mladen1kus** [comment]
Thank you @mweststrate, I'll check tomorrow and see if something  is missing.

**Comment by Mladen1kus** [comment]
Hey @mweststrate, I just tried this since i was busy with other stuff, im getting some strange error now in the console.

duplicate symbol 'folly::detail::str_to_bool(folly::Range<char const*>*)' Flipper-Folly/libFlipper-Folly.a(Conv.o)

duplicate symbol 'folly::makeConversionError(folly::ConversionCode, folly::Range<char const*>)' RCT-Folly/libRCT-Folly.a(Conv.o)

ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by a-eid** [comment]
I'm having the same issue on android.

**Comment by MirrorZyb** [comment]
me too RN 0.63 on iOS

**Comment by mweststrate** [comment]
Please provide minimal reproductions if you want anyone to look into it. The information provided so far isn't very actionable.
