### ISSUE TITLE
What value does the certificate exchange add?

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#233]
Reading https://fbflipper.com/docs/establishing-a-connection.html

> To avoid mobile apps from connecting to untrusted ports on localhost, they will only connect to servers that have a valid, trusted TLS certificate. In order for the mobile app to know which certificates it can trust, it conducts a certificate exchange with the desktop app before it can make its first secure connection.

I'm confused about the real value of certificate exchange here.  The mobile apps connect to localhost, so assumes a process or at least a network tunnel on the host computer that can also use `adb`.  At this point any process running on the host computer that could run adb commands could pretend to be the flipper desktop app.

It would make more sense if this exchange then allowed remote connections to work, e.g. to a phone that was previously connected via USB, and is now just on the same Wifi network.  e.g. the exchange could also provide the local network address other than 127.0.0.1, e.g. 192.168.1.44.

**Comment by jknoxville** [comment]
> The mobile apps connect to localhost, so assumes a process or at least a network tunnel on the host computer that can also use adb. At this point any process running on the host computer that could run adb commands could pretend to be the flipper desktop app.

That's right. As you point out, all it's doing is verifying that the "server" has adb access to the mobile device. Examples of what this excludes are:
* Other apps on the mobile device
* Web apps running in the browser of the mobile device

Essentially it protects against malware on the phone, but not the host on which you have connected by USB and granted debug access.

Does that answer your question? Depending threat model, the above may not be a concern, so #234 will be a useful simplification.

I agree, it will also be very useful when we come to add remote connectivity.

**Comment by yschimke** [comment]
So it's a mostly weak form of obfuscation, rather than an strong security measure.  Other apps on the mobile device could do the same insecure handshake to get access to the server.  But likely each app running on the phone won't leak data to other apps if they can snoop traffic.  I say likely, as I'm not sure it would stand up to a determined attacker, but given physical access to the device and ability to install apps, spending time on this seems low-pri.

Thanks

**Comment by jknoxville** [comment]
I would agree that it effectively obfuscates getting access to the server, but this isn't a goal of the system.
The goal is to stop unintended access to the app you are debugging - with the exchange, this is possible only with an adb connection, as opposed to just needing to execute a process on the phone.
