### ISSUE TITLE
Allow non-secured connections

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#234]
Useful for connecting remotely, or as a simple connection mode especially for alternative platforms (not Android/iOS).

Initially off, but settable as a preference in the desktop app.

**Comment by jknoxville** [comment]
We're fully in support of this, provided the security is on by default on an opt-out basis.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
