### ISSUE TITLE
Question: 0.91.0 gives error "FlipperKit/FBDefines" #iOS #ReactNative

### ISSUE THREAD

**Issue by oguzturker8** [facebook/flipper#2343]
Can not install pod with flipper 0.91.0
It gives:
![image](https://user-images.githubusercontent.com/33129613/118847792-cb677800-b8d6-11eb-91e1-f1ff86604620.png)

**Is there any way to fix this instead of downgrading version?**

**Comment by nikoant** [comment]
cc @priteshrnandgaonkar, do you know what changed here?

**Comment by nikoant** [comment]
> Can not install pod with flipper 0.91.0
> It gives:
> ![image](https://user-images.githubusercontent.com/33129613/118847792-cb677800-b8d6-11eb-91e1-f1ff86604620.png)
> 
> **Is there any way to fix this instead of downgrading version?**

Could you try again please? It seems new pods were not published yet at the time you asked.

**Comment by priteshrnandgaonkar** [comment]
try `pod install --repo-update` ?

**Comment by oguzturker8** [comment]
It's working well. Thanks
