### ISSUE TITLE
Discussion: Jetpack Compose & SwiftUI support?

### ISSUE THREAD

**Issue by brianguertin** [facebook/flipper#2366]
Any thoughts on supporting these modern UI toolkits in Flipper?

Compose is supposed to hit 1.0 in July, and SwiftUI has been out for some time already.

I've already started migrating to Jetpack Compose I'd like to keep using Flipper :crossed_fingers:

**Comment by nikoant** [comment]
There are no plans on implementing that internally in FB. If someone in open source would like to work on supporting Jetpack Compose or SwiftUI - contributions are welcome. You can either build a separate plugin for Flipper, or probably extend the existing Layout plugin to support these toolkits.

**Comment by ln-12** [comment]
Hey @nikoant and @mweststrate, are there any plans in the meantime to support Compose on Android? According to Google it is the recommended UI framework now, so it would be  a great pity if we cannot continue to use Flipper.

**Comment by mweststrate** [comment]
cc @lblasa

**Comment by ln-12** [comment]
Hey guys, can you give an update on the current state of this feature? I wanted to look into it to see if I can contribute something myself but discovered that there already is some implementation in https://github.com/facebook/flipper/tree/main/android/plugins/jetpack-compose. Are you already actively working on it?

**Comment by cleaninglab-jaeryo** [comment]
Thank you. However, it seems that some code modification are needed.
like this:
```
...
        UIDebuggerComposeSupport.enable(context)
        client.addPlugin(UIDebuggerFlipperPlugin(context))
...
```

it seems that addPlugin should be called after calling UIDebuggerComposeSupport.enabled

**Comment by jaeryo2357** [comment]
@ln-12  Thank you. However, it seems that addPlugin should be called after calling UIDebuggerComposeSupport.enabled
like this:

...
        UIDebuggerComposeSupport.enable(context)
        client.addPlugin(UIDebuggerFlipperPlugin(context))
...
