### ISSUE TITLE
Dark Mode inconsistencies

### ISSUE THREAD

**Issue by has12zen** [facebook/flipper#2379]
## 🐛 Bug Report
when the database plugin is opened in dark mode the first entry is not visible without focusing on it.
![image](https://user-images.githubusercontent.com/57583693/119966491-fd5c9680-bfc8-11eb-98ed-47557499a6bf.png)
![image](https://user-images.githubusercontent.com/57583693/119966863-5c221000-bfc9-11eb-9e73-d31654cb04e3.png)

## To Reproduce
1. run `yarn` in /desktop folder, run `yarn start`.
2. change to dark mode
3. check the DB plugin entries.

## Environment
Android Sdk Version 30
Linux

**Comment by WarrenFaith** [comment]
I hijack this as this is an issue for the dark mode:
The changelog is white as well (with white text on white background)

![Screenshot 2021-05-30 at 22 51 40](https://user-images.githubusercontent.com/152264/120119756-d0aba900-c199-11eb-8dee-33ea94892ae5.png)

And the "splash" screen or the startup blank screen that is visible for half a second is pure white...

**Comment by WarrenFaith** [comment]
And the Settings screen is odd with "darker" areas sometimes

![Screenshot 2021-05-30 at 22 55 16](https://user-images.githubusercontent.com/152264/120119844-34ce6d00-c19a-11eb-8c10-865f3c56496a.png)

**Comment by passy** [comment]
Thanks! I've updated the title so we can use this for tracking issues with dark mode. This is going to be an ongoing thing as we're still in the process of migrating many parts of Flipper over to our new design library.

**Comment by DracotMolver** [comment]
I know this is an ongoing thing but I'm leaving this pictures just in case. 
versión 0.96.0

![image](https://user-images.githubusercontent.com/13334764/124017717-0ae4b200-d9b5-11eb-9d2d-e2cdb9817ef9.png)

**Comment by mweststrate** [comment]
Thanks for reporting! Most of the above issues (except settings dialog) are addressed now, and should show up in the next release.

**Comment by chrise86** [comment]
This is still an issue for me even with latest release.
