### ISSUE TITLE
Request Body shows binary data for POST network calls

### ISSUE THREAD

**Issue by ritwik-shanker** [facebook/flipper#2406]
## 🐛 Bug Report
All the Request Body in `POST` request shows as (binary data)

<img width="419" alt="Screenshot 2021-06-02 at 12 09 59 PM" src="https://user-images.githubusercontent.com/68220382/120438451-040b5500-c39f-11eb-819f-b736d4c9acc2.png">

The similar request when rolled back to Flipper Desktop version`v0.87.0` shows all the data correctly.

## To Reproduce
Open any `post` request and look for Request Body field

## Environment
Android Version - 0.91.2
Android OS Version - 11
Flipper Desktop version- 0.91.2
Desktop OS -mac OS 11.4

**Comment by mweststrate** [comment]
Make sure to set a content-type header (we're still looking into detecting
utf8 strings automatically but didn't get to that yet, PR welcome).

**Comment by hss01248** [comment]
add as networkInterceptor ,not as application interceptor

**Comment by hbmartin** [comment]
I've been seeing this as well, with missing content-type header in the request.

**Comment by rdsedmundo** [comment]
Also seeing this for requests that go to AWS from the SDK, specifically: `application/x-amz-json-1.1` and `application/xml`.

**Comment by mweststrate** [comment]
We added automatic utf-8 guessing, so this should be fixed in the next release.
