### ISSUE TITLE
D8 multidex. Execution failed for task 'transformDexArchiveWithExternalLibsDexMergerForDebug'.

### ISSUE THREAD

**Issue by maxim-pandra** [facebook/flipper#241]
I have seen similar issues, but all of them were closed as fixed. Unfortunately i am facing this issue again.

`AGPBI: {"kind":"error","text":"Program type already present: okhttp3.internal.ws.WebSocketReader$FrameCallback","sources":[{}],"tool":"D8"}
`

I have a multi module project with several dex files. Support library version is 27.1.1 Android gradle plugin 3.1.4

What can be done with that?

Thank you

**Comment by passy** [comment]
Do you have any repro steps for us?

**Comment by maxim-pandra** [comment]
@passy I was able to locate issue.

Everything fails when i add this dependency:   
  `implementation "com.viewpagerindicator:library:2.4.1"`
https://github.com/JakeWharton/ViewPagerIndicator
This is a legacy library that is unfortunately hard to remove from our project.

**Comment by passy** [comment]
That's surprising. The library itself doesn't seem to have any dependencies on `okhttp`.

**Comment by maxim-pandra** [comment]
Oh, I think I just found another problem. 

This time error is:
`AGPBI: {"kind":"error","text":"Program type already present: android.support.v4.content.Loader","sources":[{}],"tool":"D8"}`

The first problem has probably the same nature, but I wasn't managed to find root cause of it yet.

Any way there is something with Loader here.

**Comment by passy** [comment]
This is likely different transitive dependencies with Sonar depending on newer versions of them. `com.viewpagerindicator:library:2.4.1` depends on `'com.google.android', name: 'support-v4', version: 'r7'`. That'll cause you all sorts of compatibility issues with other libraries. Sorry, but there's nothing we can do about that from our end.
