### ISSUE TITLE
Discussion: Chrome Extensions with Hermes Debugger?

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#2428]
I noticed that the Hermes Debugger seems to be an instance of the Chrome DevTools. Does that mean it would theoretically be possible to install extensions like Apollo or Redux DevTools directly into it, rather than requiring specific Flipper plugins to be written? This would certainly make life a lot easier for a lot of js tools that have their own Chrome devtools extensions already...

**Comment by mweststrate** [comment]
Theoretically yes, no idea how hard it is, but in main.ts you can find at
least some examples on how we load plugins in our "own" devtools, so I
guess it would look very similar.
