### ISSUE TITLE
App cannot be opened in Mac with specific security settings

### ISSUE THREAD

**Issue by clodelgosuico** [facebook/flipper#2436]
## 🐛 Bug Report
App cannot be opened

## To Reproduce

I'm on an OSX system where the security setting is "Allow apps downloaded from App Store and identified developers" and I cannot modify this setting because this is a work laptop.

I get the following message when starting the app regardless if I installed the dmg or installed it via homebrew

![Screen Shot 2021-06-09 at 3 06 23 PM](https://user-images.githubusercontent.com/5972930/121436258-16543880-c935-11eb-9373-72e047c8947f.png)

## Environment
Mac OS Catalina

**Comment by nikoant** [comment]
Can you try to open Settings -> Security and Privacy and check if its possible to unblock Flipper there?

**Comment by nikoant** [comment]
Ah, sorry I missed it disabled by system admin

**Comment by nikoant** [comment]
There is already an issue tracking that: https://github.com/facebook/flipper/issues/1457. Please follow it for details.

**Comment by micnguyen-wesdigital** [comment]
You could also try running this command `xattr -d com.apple.quarantine /Applications/Flipper.app` which worked for me. It's not recommended and might ding you with security of your organisation.
