### ISSUE TITLE
List AVD failed - Warning

### ISSUE THREAD

**Issue by matheusfcorocher** [facebook/flipper#2438]
## 🐛 Bug Report

  I'm trying to use Flipper for the first time and gives this warning message in my Flipper's log about listing AVD in my environment.

![image](https://user-images.githubusercontent.com/56937223/121524357-9cbc5900-c9cd-11eb-88aa-ce70a932c9a0.png)

By the image, the error is apparently about my username has white space character and then he can't execute the batch file.

## To Reproduce

1 - Has a username with white space character
2 - Execute Flipper app
3 - Go to Flipper Logs and find some warning with message List AVD failed

## Environment

OS : Windows 10
Flipper Desktop Version: Flipper(0.93.0) - Windows Version
Android Version: API 29(Q)

**Comment by passy** [comment]
That looks like the path you've set for your SDK isn't correctly escaped. Could you check in the settings if it's pointing to a valid path?

**Comment by matheusfcorocher** [comment]
Sure, i copied the value of Android SDK location field and paste on my File Explorer search bar and it's working.

![image](https://user-images.githubusercontent.com/56937223/121577341-cd1ceb00-c9ff-11eb-94c8-4d53cff05986.png)

Is this type of validation path that you have asked?

**Comment by passy** [comment]
Could you post a picture of the settings panel? That would help a lot, thanks!

**Comment by passy** [comment]
No need to. I managed to reproduce it. We're not doing well with spaces in paths ... 😬

I'll try and get that fixed. In the meantime, if you could move this to a space-less folder, that should unblock you in the meantime.
