### ISSUE TITLE
0.93.0 CHANGELOG is blank

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#2445]
## 🐛 Bug Report
I just launched 0.93.0 and the changelog dialog that came up was blank. I looked at the repo and you can see it reflected here as well:
<img width="1262" alt="Screen Shot 2021-06-10 at 2 56 51 PM" src="https://user-images.githubusercontent.com/157270/121602511-3e5a9f00-c9fc-11eb-9b26-c086ecdf1a1a.png">

**Comment by passy** [comment]
Sometimes we don't have any changes that are highlighted in the changelog. That's expected. :)
