### ISSUE TITLE
The binary is missing for v0.94.0

### ISSUE THREAD

**Issue by jsamr** [facebook/flipper#2473]
Hi, I'm a maintainer for the AUR `flipper-bin` repository and the binary is missing for this version. See https://github.com/facebook/flipper/releases/tag/v0.94.0

**Comment by mweststrate** [comment]
cc @passy

**Comment by passy** [comment]
Thanks for flagging. Looks like our release job failed: https://github.com/facebook/flipper/runs/2839520818?check_suite_focus=true

**Comment by passy** [comment]
The build job seems to be succeeding otherwise. I'll just kick off another release and hope for the best.

**Comment by passy** [comment]
https://github.com/facebook/flipper/actions/runs/943818898 is running now. The culprit seems to be some problems with Yarn. Even with pretty aggressive retries this seems to be killing our CI.

**Comment by passy** [comment]
Yarn seems to have recovered. Reran the release and 0.94.1 is out now.

**Comment by jsamr** [comment]
@passy Looks like the issue resurfaced in v0.96.0 https://github.com/facebook/flipper/releases/tag/v0.96.0
