### ISSUE TITLE
"Execute" button in Database Plugin SQL tab is only clickable in the top half.

### ISSUE THREAD

**Issue by alemnunez** [facebook/flipper#2476]
## 🐛 Bug Report
In the database plugin, if you try to run a custom SQL query and click Execute, only the top half of the "Execute" button will take clicks. Clicking on the bottom half of it won't do anything.

## To Reproduce
Open Flipper, enable the Database plugin for an app, click on the SQL tab. Type a valid query, click the bottom part of the "Execute" button. The query won't get executed.

## Environment
OS: MacOS Big Sur 11.4
Connected to Android app.
Flipper 0.31.2
Database plugin 1.0.4

**Comment by alemnunez** [comment]
Same problem with the button "Choose from previous queries" or "Favorite/Star" on the left side of the same tab

**Comment by alemnunez** [comment]
<img width="626" alt="Screen Shot 2021-06-19 at 6 40 34 PM" src="https://user-images.githubusercontent.com/1771915/122659574-5cc44700-d12e-11eb-82ed-2ac639971543.png">

**Comment by mweststrate** [comment]
Please update flipper before reporting bugs, you're currently 60 versions
behind.
