### ISSUE TITLE
React Native 0.64-65 with XCode 13 - could not find or use auto-linked library 'swift_Concurrency' or 'swiftFileProvider'

### ISSUE THREAD

**Issue by leotm** [facebook/flipper#2477]
## 🐛 Bug Report

React Native no longer builds with Flipper enabled with XCode 13 on macOS 12 (Monterey) Beta.

## To Reproduce

- Upgrade to macOS 12 (Monterey) Beta
- Download XCode 13 Beta 1
- Clone: https://github.com/leotm/react-native-template-typescript
- Revert commit: https://github.com/leotm/react-native-template-typescript/commit/02eb9cd641df02b5c64a6fef62b3ebeae38a2961 (or manually re-enable Flipper)
- `yarn`
- `cd ios && pod install`
- `yarn clean` (all iOS options)
- XCode 13 > Build

## Environment

- macOS 12 (Monterey) Beta
- https://github.com/leotm/react-native-template-typescript

**Comment by mweststrate** [comment]
Currently we don't support macOS 12 / XCode 13 yet, nor have a way to test / verify them. Feel free to either dive into the issue further, or report back once they are out of beta.

**Comment by peterkuiper** [comment]
@leotm You might want to checkout this comment: zalando/SwiftMonkey#80 (comment)

All this does is add `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;` to your build settings.

**Comment by gwmccull** [comment]
For the sake of posterity...I had the same issue on the release version of Xcode 13 and the `Void.swift` solution that @peterkuiper linked to fixed it

**Comment by thepirateboy** [comment]
Had this problem with React-Native 0.66.0 + Xcode 13 before, gave me headache, the only way to solve mine was that void.swift solution and update the command line tool of Xcode.
