### ISSUE TITLE
0.94.1 - Crash reporter shows crashes but no details when selecting

### ISSUE THREAD

**Issue by WarrenFaith** [facebook/flipper#2479]
## 🐛 Bug Report
I just updated to 0.94.1 and now the crash reporter lists crashes but what ever crash I am selecting (selection state works), the main window still tells me "no crash selected".

![Screenshot 2021-06-21 at 14 15 31](https://user-images.githubusercontent.com/152264/122760841-db8ac280-d29b-11eb-9aca-6b62dac582fb.png)

## To Reproduce
Run 0.94.1, cause a crash

## Environment
Android API 30, Pixel 4 emulator
Flipper desktop: 0.94.1
Running on latest OSX 11.4

Side note:
I would love to try to run the same with a 0.94.0 version (as far as I remember it was working) but you provide no version history of binaries and your release files are always name without a version, so I always override previously downloaded ones... Maybe you could add a version name to the release file too? :)

**Comment by mweststrate** [comment]
Thanks for reporting!

Old releases can be downloaded from https://github.com/facebook/flipper/releases. 0.93 isn't affected by the issue as far as we're aware. A fix has landed already, so 0.95 (next release) should address it.
