### ISSUE TITLE
https://fbflipper.com is unavailable

### ISSUE THREAD

**Issue by rob2468** [facebook/flipper#249]
```
chenjundeMacBook-Pro:~ chenjun$ ping fbflipper.com
ping: cannot resolve fbflipper.com: Unknown host
```

**Comment by passy** [comment]
@rob2468 Where are you accessing it from? Any chance your accessing it from China? We're using the same IP address space as the rest of Facebook.

**Comment by rob2468** [comment]
```
chenjundeMacBook-Pro:~ chenjun$ ping fbsonar.com
PING fbsonar.com (104.31.83.148): 56 data bytes
64 bytes from 104.31.83.148: icmp_seq=0 ttl=44 time=43.736 ms
64 bytes from 104.31.83.148: icmp_seq=1 ttl=44 time=43.997 ms
^C
--- fbsonar.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 43.736/43.867/43.997/0.130 ms
chenjundeMacBook-Pro:~ chenjun$ ping fbflipper.com
ping: cannot resolve fbflipper.com: Unknown host
```

YES, I'm accessing it from China through VPN. But I can access https://fbsonar.com in the past.

For now, fbsonar.com redirects to fbflipper.com, but not available anymore.

**Comment by passy** [comment]
@rob2468 That's probably because the old domain was set up using Cloudflare, and we use GitHub pages directly now. Sorry, but there's nothing we can do about this. :(
