### ISSUE TITLE
Flipper heats m1 macbook

### ISSUE THREAD

**Issue by zinoviev** [facebook/flipper#2494]
Hey, everyone. I'm not sure if it's considered a bug or not, but I decide to create an issue anyway, maybe someone from the flipper team will be interested.

Here is the backstory: I'm working on react native app and we avoid the flipper in the past, mostly because of our outdated RN version and no visible benefits to plug it on. But lately, we upgrade RN to the latest and start to use Reanimated 2 for animations(it's JSI module) and well - we lose chrome dev tools access and flipper now is the only option to debug the app.

I work on m1 mac pro and normally it's super cool all day even if I run CPU-heavy stuff like huge C/C++ codebase compilation. As we started to use flipper I notice mac is becoming hot and I even spot coolers working. I believe flipper is the second app(first was CS:GO), that was able to launch coolers and this does not look ok for me.

I don't know if it flipper issues, our app issue, or some combination. I will be happy to assist if any additional info needed.

Current installed flipper version 0.92.0

![image](https://user-images.githubusercontent.com/848985/122798374-32f35780-d2c9-11eb-98f8-dee5eafda704.png)

**Comment by mweststrate** [comment]
Please try search before posting. Did the existing solutions work?

**Comment by mweststrate** [comment]
See https://github.com/facebook/flipper/issues/2173#issuecomment-833445728

**Comment by zinoviev** [comment]
@mweststrate wow, yeah I didn't check existing issues, my bad. Compilation of idb packages fails for me, my I guess it's another story and I can just shutdown this setting and suffer no more. 

Thanks!
