### ISSUE TITLE
Failed to connect to metro

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#2503]
## 🐛 Bug Report
Flipper notification says:

> Flipper did find a running Metro instance, but couldn't connect to the logs. Probably your React Native version is too old to support Flipper. Cause: Failed to get a connection to ws://localhost:8081/events in a timely fashion

I'm confused why it would say my RN version is too old, as it's the latest available. Metro is running and communicating with the Simulator just fine (hot reloads are working). React Native devtools within Flipper don't work.

## To Reproduce
Run Flipper 0.95 with a running React Native app in a simulator

## Environment
React Native 0.64.2 (latest available)
Flipper 0.95
macOS 11.4

**Comment by mweststrate** [comment]
What response do you get from `http://localhost:8081/json`?

**Comment by swrobel** [comment]
## Headers
```
Cache-Control | no-cache
Connection | close
Content-Length | 2
Content-Type | application/json; charset=UTF-8
Date | Thu, 24 Jun 2021 19:58:36 GMT
Expires | 0
Pragma | no-cache
Surrogate-Control | no-store
Vary | Accept-Encoding
X-Content-Type-Options | nosniff
```

## Content
`[]`

**Comment by mweststrate** [comment]
Ok that is (probably) the correct endpoint. Do you see any related (security) errors in the Flipper devtools? (View > developer tools). Either in the console or in the network tab?

**Comment by swrobel** [comment]
`WebSocket connection to 'ws://localhost:8081/events' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

**Comment by swrobel** [comment]
This is still happening in 0.96, but oddly, I get the same error even going back as far as 0.88. I know it was working for with that version and later ... I'm honestly not sure what could've changed. Let me know if there's anything else I can do to help troubleshoot.

**Comment by mweststrate** [comment]
Could you share your package.json? I experienced a similar crash in metro whenever trying to connect, which turned out to be solved by this https://github.com/facebook/metro/issues/678#issuecomment-865835602

**Comment by swrobel** [comment]
> Could you share your package.json? I experienced a similar crash in metro whenever trying to connect, which turned out to be solved by this [facebook/metro#678 (comment)](https://github.com/facebook/metro/issues/678#issuecomment-865835602)

I don't have a resolution for `ws`, but here you go, hopefully this helps:

```json
  "dependencies": {
    "@apollo/client": "^3.3.4",
    "@bugsnag/js": "^7.1.1",
    "@bugsnag/plugin-react": "^7.1.1",
    "@bugsnag/plugin-react-navigation": "^7.9.2",
    "@bugsnag/react-native": "^7.9.6",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/pro-light-svg-icons": "^5.13.0",
    "@fortawesome/pro-regular-svg-icons": "^5.13.0",
    "@fortawesome/pro-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "@fortawesome/react-native-fontawesome": "^0.2.3",
    "@invertase/react-native-apple-authentication": "^2.1.0",
    "@rails/activestorage": "6.1.x",
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-community/cookies": "^5.0.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/push-notification-ios": "^1.2.0",
    "@react-native-firebase/analytics": "^12.1.0",
    "@react-native-firebase/app": "^12.0.0",
    "@react-native-firebase/messaging": "^12.0.0",
    "@react-native-picker/picker": "^1.9.8",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/devtools": "^5.1.20",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.2.3",
    "@reduxjs/toolkit": "^1.3.4",
    "@stripe/react-stripe-js": "^1.1.2",
    "@stripe/stripe-js": "^1.5.0",
    "ably": "^1.2.7",
    "babel-plugin-module-resolver": "^4.0.0",
    "big.js": "^6.0.3",
    "buffer": "^6.0.3",
    "cleave.js": "^1.6.0",
    "date-fns": "^2.12.0",
    "formik": "^2.1.4",
    "graphql": "^15.4.0",
    "humps": "^2.0.1",
    "libphonenumber-js": "^1.7.54",
    "lodash": "^4.17.15",
    "normalize.css": "^8.0.1",
    "numeral": "^2.0.6",
    "pluralize": "^8.0.0",
    "prettier": "^2.0.2",
    "qs": "^6.9.3",
    "react": "^17.0.1",
    "react-aria-modal": "^4.0.0",
    "react-autosize-textarea": "^7.0.0",
    "react-calendar": "^3.0.1",
    "react-dom": "^17.0.1",
    "react-dropzone": "^11.2.4",
    "react-helmet": "^6.1.0",
    "react-image-file-resizer": "^0.4.0",
    "react-image-lightbox": "^5.1.1",
    "react-native": "^0.64.2",
    "react-native-app-auth": "^6.0.1",
    "react-native-blob-util": "^0.13.7",
    "react-native-calendars": "^1.265.0",
    "react-native-code-push": "^7.0.0",
    "react-native-contacts": "^7.0.0",
    "react-native-device-info": "^8.0.0",
    "react-native-fbsdk-next": "^4.3.0",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-get-random-values": "^1.3.1",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-masked-text": "^1.13.0",
    "react-native-platform-searchbar": "^1.0.2",
    "react-native-rate": "^1.2.4",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^3.1.1",
    "react-native-svg": "^12.0.3",
    "react-native-webview": "^11.0.2",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^4.0.1",
    "redux-flipper": "^1.4.2",
    "redux-logger": "^3.0.6",
    "reselect": "^4.0.0",
    "rn-async-storage-flipper": "^0.0.10",
    "styled-components": "^5.0.1",
    "uuid": "^8.3.2",
    "visibilityjs": "^2.0.2",
    "yup": "^0.32.6"
  },
  "devDependencies": {
    "@bugsnag/source-maps": "^2.0.0",
    "@louislombardo/babel-plugin-fix-font-awesome": "^1.0.2",
    "@react-native-community/eslint-config": "^3.0.0",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-sort-imports-es6-autofix": "^0.6.0",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-native-clean-project": "^3.6.4",
    "react-native-flipper": ">= 0.75.1",
    "react-test-renderer": "^17.0.1"
  },
```

**Comment by mweststrate** [comment]
Can you connect to a freshly inited project?

**Comment by swrobel** [comment]
> Can you connect to a freshly inited project?

No, I can't. I get the same error:

<img width="554" alt="Screen Shot 2021-07-01 at 11 51 12 AM" src="https://user-images.githubusercontent.com/157270/124175597-a54eff00-da62-11eb-846a-da03bcd800a3.png">

**Comment by mweststrate** [comment]
It's a really weird error. We don't use SSL :-/. Maybe a firewall issue?
Any way you could try this on a different machine?

**Comment by swrobel** [comment]
It's so bizarre because I can connect to the server just fine using Chrome devtools, and I believe this is effectively what Flipper is doing:
```
let ws = new WebSocket('ws://localhost:8081/events')
ws.send("test")
```

And I can see in the Metro console:
```
error Failed to parse the message as JSON:
test
```

**Comment by swrobel** [comment]
This was an interesting one. At one point, I was testing local SSL for my api at `localhost:3000`, so it redirected `http://localhost:3000 -> https://localhost:3000` which apparently made Electron (probably via Chrome's underlying code) cache the redirect and apply it to all calls to localhost. Hence, it auto-redirected `http://localhost:8081 -> https://localhost:8081` as well, even after I removed the redirect from `localhost:3000`

Anyway, the fix was simply `rm -rf ~/Library/Application\ Support/Flipper`
