### ISSUE TITLE
Question: How to integrate flipper-plugin-reactotron

### ISSUE THREAD

**Issue by reeinohio** [facebook/flipper#2504]
I  have a react native app  using RN 63 and i have successfully integrated  flipper 0.94.1 on both iOS and android. Flipper  can connect to device, react native and  app.  The next thing I  want to do is integrate flipper-plugin-reactotron. I am having  no luck doing so.  I followed the instruction recommended here: https://shift.infinite.red/better-react-native-debugging-with-reactotron-in-flipper-6b823af29220 however, i  don't see the mentioned plug-in when i go to
(Flipper -> Manage Plugins -> Install Plugins -> flipper-plugin-reactotron)
1. How does Flipper recognize plugins?  
2. Do i need  to  download  the plugin source to a specific  location and point flipper to it?

Thanks! And I appreciate any  suggestions to help me move forward.

**Comment by mweststrate** [comment]
Flipper plugins are found by searching for a tag on NPM. You don't have to a specific point after download, Flipper will automaticallly install it at the correct location. After install and restart the plugin will show up as 'unavailable' until the Reactotron is configured in the mobile application as well, as per reactotron instructions. 

![Screenshot 2021-07-06 at 11 51 03](https://user-images.githubusercontent.com/1820292/124588978-5e417f00-de51-11eb-93c3-93b3488ace27.png)
![Screenshot 2021-07-06 at 11 57 25](https://user-images.githubusercontent.com/1820292/124588997-64376000-de51-11eb-94e3-7ee56c5168d3.png)
