### ISSUE TITLE
Typo on Setup Doctor Modal

### ISSUE THREAD

**Issue by dwwr** [facebook/flipper#2505]
## What this is: 
* typo in warning text on Setup Doctor modal:
<img width="566" alt="Screen Shot 2021-06-24 at 10 59 14 AM" src="https://user-images.githubusercontent.com/68758506/123311112-a2409580-d4db-11eb-94ec-7f8de981fed6.png">

## To Reproduce
* Navigate to setup doctor when there is an active warning

**Comment by mweststrate** [comment]
Feel free to PR a fix!

**Comment by dwwr** [comment]
On it!

**Comment by dwwr** [comment]
PR: https://github.com/facebook/flipper/pull/2506
(please let me know if I've provided insufficient information)
