### ISSUE TITLE
[iOS] Flipper crashes on AVAggregateAssetDownloadTask using

### ISSUE THREAD

**Issue by OSkliarenko** [facebook/flipper#2507]
## 🐛 Bug Report

Flipper crashes on AVAggregateAssetDownloadTask using due `currentRequest` property is not available for AVAggregateAssetDownloadTask object

From AVKit SDK
```
@interface AVAggregateAssetDownloadTask : NSURLSessionTask
...
@property (readonly, copy) NSURLRequest *currentRequest NS_UNAVAILABLE;
```
>*** Terminating app due to uncaught exception 'NSGenericException', reason: 'AVAggregateAssetDownloadTask does not support currentRequest property'

## To Reproduce
Try to download AVURLAsset with `- (nullable AVAggregateAssetDownloadTask *)aggregateAssetDownloadTaskWithURLAsset:(AVURLAsset *)URLAsset mediaSelections:(NSArray <AVMediaSelection *> *)mediaSelections assetTitle:(NSString *)title assetArtworkData:(nullable NSData *)artworkData options:(nullable NSDictionary<NSString *, id> *)options`

## Environment
iOS 14.5
RN 0.63.4
Flipper 0.87.0

**Comment by alexejh** [comment]
The issue still exists with the error 'AVAggregateAssetDownloadTask does not support currentRequest property'
Tested on:
iOS 16
RN 0.62.2
Flipper 0.182.0

**Comment by yavor87** [comment]
I run into this issue too. I am able to reproduce it every time I try to start a aggregateAssetDownloadTask. Same code works just fine in standalone ios app.

```
let _asset = AVURLAsset(url: URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8")!)
let preferredMediaSelection = _asset.preferredMediaSelection
guard let task =
   assetDownloadURLSession.aggregateAssetDownloadTask(with: _asset,
                                                      mediaSelections: [preferredMediaSelection],
                                                      assetTitle: "my asset",
                                                      assetArtworkData: nil,
                                                      options:
       [AVAssetDownloadTaskMinimumRequiredMediaBitrateKey: 265_000]) else { return }

task.taskDescription = "1"

task.resume()
```

@mweststrate , please reopen this issue. It is a real showstopper for us.

**Comment by rahulnainwal107** [comment]
I am having same issue. @yavor87 DO you have any solution?
