### ISSUE TITLE
Unable to see network logs

### ISSUE THREAD

**Issue by amphora001** [facebook/flipper#253]
I have a Pixel XL. It appears to connect okay. I can see logs but nothing from the network plugin.

![flipper_diag](https://user-images.githubusercontent.com/5721748/44555717-63ff4800-a6eb-11e8-855b-e32a828c5e4c.png)
<img width="1114" alt="screen shot 2018-08-23 at 3 34 31 pm" src="https://user-images.githubusercontent.com/5721748/44555754-90b35f80-a6eb-11e8-9216-3c13ac639514.png">

**Comment by priteshrnandgaonkar** [comment]
Are you using OkHttp as your network stack. Currently we just intercept network requests made through OkHttp.

**Comment by amphora001** [comment]
Yes I am using OkHttp 

```
public class EnableFlipperSupport implements IFlipperSupport {

    private final NetworkSonarPlugin plugin;

    public EnableFlipperSupport() {
        this.plugin = new NetworkSonarPlugin();
    }

    @Override
    public void initFlipper(Application application) {
        SoLoader.init(application, false);

        final SonarClient client = AndroidSonarClient.getInstance(application);
        client.addPlugin(plugin);
        client.start();
    }

    @Override
    public void initFlipperInterceptor(OkHttpClient.Builder okHttpClient) {
        okHttpClient.addNetworkInterceptor(new SonarOkhttpInterceptor(plugin));
    }
}
```

**Comment by amphora001** [comment]
btw, I'm able to build the app locally, but when I try to build it our build machine, I get some error

```
* What went wrong:
Execution failed for task ':driver-app:transformNativeLibsWithMergeJniLibsForDevDebug'.
> More than one file was found with OS independent path 'lib/x86/libc++_shared.so'
```

**Comment by amphora001** [comment]
Any update @passy @priteshrnandgaonkar? Especially about the duplicate file lib/x86/libc++_shared.so ?

**Comment by passy** [comment]
@amphora001 Can you expand on the duplicate library? Is that a separate issue?

**Comment by passy** [comment]
Saw the comment now. But we will need some repro steps for that.

**Comment by amphora001** [comment]
It's pretty hard to give you repo steps. The app is pretty big and writing a prototype as described in Get Started works just fine.

Here are some more clues:

EnableFlipperSupport	adding sonar network interceptor
SoLoader	About to load: libsonarfb.so
SoLoader	libsonarfb.so not found on /data/data/com.lyft.android.driver.dev/lib-main
SoLoader	libsonarfb.so found on /data/app/com.lyft.android.driver.dev-bY93oisT4a10HdFKHgp8Yw==/lib/arm64
SoLoader	Not resolving dependencies for libsonarfb.so
SoLoader	Loaded: libsonarfb.so
SoLoader	About to load: libsonar.so
SoLoader	libsonar.so not found on /data/data/com.lyft.android.driver.dev/lib-main
SoLoader	libsonar.so found on /data/app/com.lyft.android.driver.dev-bY93oisT4a10HdFKHgp8Yw==/lib/arm64
SoLoader	Not resolving dependencies for libsonar.so
SoLoader	Loaded: libsonar.so
sonar	sonar: SonarClient::addPlugin Inspector
sonar	sonar: SonarClient::addPlugin Network
EnableFlipperSupport	starting SonarClient
sonar	sonar: SonarClient::onConnected

**Comment by amphora001** [comment]
Another clue

breakpoint into NetworkSonarPlugin reportRequest(RequestInfo requestInfo) method, where send(String method, SonarObject sonarObject) is called, BufferingSonarPlugin.mConnection is null

**Comment by passy** [comment]
Sorry, I was replying from my phone there. The duplicate `libc++_shared.so` issue, especially when only happening in one build environment, would be where I'm not sure how to tackle this from our end. I would guess that one of your build configurations includes one too and the deduplication there is off. 

The breakpoint seems handy. Maybe @jknoxville could see if there's a missing check somewhere?

**Comment by amphora001** [comment]
@jknoxville any update?

**Comment by amphora001** [comment]
It's not compiling after I added the following

```
    packagingOptions {
         pickFirst 'lib/armeabi-v7a/libc++_shared.so'
         pickFirst 'lib/armeabi/libc++_shared.so'
         pickFirst 'lib/arm64-v8a/libc++_shared.so'
         pickFirst 'lib/x86/libc++_shared.so'
         pickFirst 'lib/x86_64/libc++_shared.so'
         pickFirst 'lib/mips/libc++_shared.so'
         pickFirst 'lib/mips64/libc++_shared.so'
     }
```

but this is not ideal because I have no idea if the first appearance of the native file is the right version or not.

**Comment by amphora001** [comment]
I'm still not seeing anything in Networking. In the same app, I also have stetho integrated and that is showing me all the network traffic.

**Comment by jiantao88** [comment]
Has this problem been resolved?
I also encountered the same problem

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!
