### ISSUE TITLE
Plugin redux-debugger fails to install repeatedly

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [facebook/flipper#2537]
## 🐛 Bug Report

I'm trying to install the plugin `redux-debugger` - https://www.npmjs.com/package/redux-flipper - but it always fails. After installing it and reloading Flipper, it appears on the list as uninstalled again.

## To Reproduce

1. Open the Plugin Manager
2. Select the 2nd tab, Install Plugins
3. Install the plugin redux-debugger by clicking on it's purple button 'Install'
4. Click the red reload banner that appears at the top. The app reloads
6. Open the Plugin Manager again. On the first tab (Plugin Status) you'll see that redux-flipper does not appear. It's not installed
7. Select the 2nd tab in the Plugin Manager (Install Plugins). You'll see that redux-flipper allows you to install it again with the same purple button 'Install'

On the Flipper Logs I can see this message:

> ✅  Loaded 3 installed plugins: ADB Plugin, Async Storage, Redux Debugger. 

I've tried like 10 times, it's always the same result.

## Environment

- Fliper desktop Version 0.95.0 (50.0.0).
- macOS Catalina 10.15.7

**Comment by mweststrate** [comment]
cc @nikoant?

**Comment by vlanemcev** [comment]
the same issue

**Comment by vlanemcev** [comment]
but with reselect-debugger plugin

**Comment by mweststrate** [comment]
Did you follow the necessary steps to configure your app as well, and did you connect the app? The plugin status shows the plugins connected for the currently selected app.

**Comment by nikoant** [comment]
Hey folks, as this plugins are open-sourced, it's hard for me to reproduce this as I have no apps compatible with it. Please share a repo with a sample mobile app which I can build/install to device and connect to Flipper to reproduce this issue. Then I can help to debug what is going on.

**Comment by vlanemcev** [comment]
Hey, work solution for me is clearing Local State via Flipper settings
Try it, @AlbertVilaCalvo !

**Comment by nikoant** [comment]
@vlanemcev  thanks for the hint, I'll check that. One qiestion - did you clicked "uninstall" in the plugin list for this plugin before?

**Comment by vlanemcev** [comment]
@nikoant yeah, you are right about it. Yes, I clicked to uninstall before I cleared my Local State. 
And after I clicked to "Reset all Local State" -> Reload Flipper -> tried to re-install the plugin -> reload flipper -> everything should be fine

**Comment by AlbertVilaCalvo** [comment]
Clicking the 'Reset all state' button on the Flipper Settings modal fixed the issue.

After the reset I installed the plugin redux-debugger..

Now if I go to the Plugin Manager, the 'Install Plugins' tab shows the 'Remove' gray button instead of the 'Install' purple button on the plugin. In the past I always had the purple 'Install' button, even after installing it repeatedly.

Thanks @vlanemcev!
