### ISSUE TITLE
Hermes Debugger does not load in 0.96.0

### ISSUE THREAD

**Issue by archcorsair** [facebook/flipper#2545]
## 🐛 Bug Report
After updating to 0.96.0 the hermes debugger doesn't load. The tab is empty.

## To Reproduce
Attempt to open Hermes Debugger (RN) tab

## Environment
MacOS 11.4
Node 15.4.0
RN 0.64.1

![image](https://user-images.githubusercontent.com/1036921/124037529-8eea6a00-d9b4-11eb-929d-393a112cd0ac.png)

**Comment by archcorsair** [comment]
For now I have rolled back to 0.95.0 where the hermes debugger still works/loads.

**Comment by mweststrate** [comment]
Confirmed, looking into it!

**Comment by nikoant** [comment]
That's probably related to my changes in active device/app selection computation. I'll check that.

**Comment by nikoant** [comment]
We just released 0.96.1 with the fix.

**Comment by Pyroboomka** [comment]
Not @0.96.1 app instantly closes when I select Hermes Debugger in plugins tabs. Devtools seems to be working now though.

**Comment by mweststrate** [comment]
@Pyroboomka  probably a duplicate of https://github.com/facebook/hermes/issues/516, best follow along at the Hermes repo.

**Comment by stmiller-shamrock** [comment]
Does anyone having this issue use react-native-reanimated? I had this same issue until I tracked it down to that package. The 2.2.0 version fixed it for me, even mentions the fix in the release notes: https://github.com/software-mansion/react-native-reanimated/releases/tag/2.2.0
