### ISSUE TITLE
Network Plugin - Mock Network Responses - Copy Selected Calls broken

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#2549]
## 🐛 Bug Report
The Copy Selected Calls button, after the first mock created, always creates a duplicate of the first mock and not a mock from the selected network request.

## To Reproduce

1. Select a network request and use **Copy Selected Calls** button
2. Select another network request and use **Copy Selected Calls** button 

A second mock is created but is the same as the first one. You can repeat step 2 as many times you like and the result will be the same. A copy of the first mock is created.

## Environment
Flipper 0.96.1

## NOTE
Working properly on version 0.93.0. After that stopped working.

**Comment by bizzguy** [comment]
Thanks for reporting this. 

I'm trying to reproduce error but getting a different result.

The 2nd mock call is created (and shown in the list on the left).  But it is not shown in the detail section on the right.

![2021-07-06_11-38-11](https://user-images.githubusercontent.com/337874/124637328-38b37600-de4f-11eb-9015-551c9e502d14.jpg)


This appears to be a problem with the "selection" feature.

Is this what you are seeing?

**Comment by bizzguy** [comment]
This should now be fixed in PR https://github.com/facebook/flipper/pull/2574

**Comment by mgoyanes** [comment]
@bizzguy 
Thanks once again for your support on this plugin.

I'm unable to test this right now but as soon I have the time I will make a test run.

**Comment by mgoyanes** [comment]
I can confirm that the issue is solved in the latest release.
Thanks @bizzguy

**Comment by bizzguy** [comment]
@mgoyanes   Thanks for testing!
