### ISSUE TITLE
Add an option to change units used in Layout Inspector

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#255]
The units used are pixels. We should have an option to toggle between px and dp.

Also, it would be great to:

1. Show the distance from one component to another (another view or the phone margins)
2. Add guidelines to the screen.

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@passy Can I work on this?

**Comment by passy** [comment]
@MONIKA-KUMAR-JETHANI Absolutely! :)

**Comment by mweststrate** [comment]
Closing as it doesn't seem anybody is going to pick this up soon.
