### ISSUE TITLE
Request Body not showing (Binary data)

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#2550]
## 🐛 Bug Report
In the Network Plugin, the request body shows binary data and not the json.
Here is an example from version 0.93.0 (version 0.96.1 behaves the same) on macos:
<img width="322" alt="Screenshot 2021-07-04 at 10 40 43" src="https://user-images.githubusercontent.com/5049948/124380454-8e075000-dcb4-11eb-82ad-9a33560965b6.png">

And this is how it shows on version 0.85.0
<img width="180" alt="Screenshot 2021-07-04 at 10 39 12" src="https://user-images.githubusercontent.com/5049948/124380473-a0818980-dcb4-11eb-8189-c5e5f8d0698e.png">

It's the exact same request. The only change is the Flipper version I'm running it.

Don't know what have changed but would like to have the same behavior as we had in version 0.85.0

**Comment by mweststrate** [comment]
The body formatting depends on your content-type headers. Probably best
check if the content-type header is set and what it is. Without a header,
Flipper will take a best guess to see if it finds a valid utf8 body, but
that is just a heuristic.

**Comment by mgoyanes** [comment]
Thanks.

I will check that but probably this behavior changed with a newer version of Flipper since it was working on a previous one.

Will post here the result after more testing.
