### ISSUE TITLE
Network requests aren't showing details

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#256]
Build the latest version of Flipper (`yarn build --mac --version 0.6.17`) and network plugin is not showing network request data, that is, the right panel is greyed out and clicking it does not open the panel.

Downloading the version available on the site (i think it is 0.6.12) shows the request details.

**Comment by passy** [comment]
@danielbuechele Is that the issue you were working on or is this something else?

**Comment by danielbuechele** [comment]
Yes, this should be fixed as per 2c905646eccf964cd31b5da9a54163314fe00bcd
