### ISSUE TITLE
Random crashes on Flipper-Folly iOS 

### ISSUE THREAD

**Issue by arnauddorgans** [facebook/flipper#2577]
## 🐛 Bug Report

Since Xcode 12.5 we have a lot of crashes on our iOS app due to Flipper-Folly. 
It happens randomly but a lot of times (every 4 runs) 

<img width="1475" alt="Capture d’écran 2021-07-08 à 13 07 05" src="https://user-images.githubusercontent.com/10015557/124912161-e8264f00-dfed-11eb-9992-bbb0bb8e3bc5.png">
<img width="1182" alt="Capture d’écran 2021-07-08 à 13 07 14" src="https://user-images.githubusercontent.com/10015557/124912169-ea88a900-dfed-11eb-81d2-c7f7862ba2db.png">

```
Assertion failed: (mutex_++ == -Assertion failed: (--mutex_ == -1), function Unlock, file ../src/base/mutex.h, line 219.
1), function Lock, file ../src/base/mutex.h, line 218.
Assertion failed: (--mutex_ == -1), function Lock, file ../src/base/mutex.h, line 218.
CoreSimulator 772.1 - Device: iPhone 12 (64A365D7-0182-4AAB-9E74-FE2890839DB2) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 12
```

## Environment

Any iOS versions
Flipper version: 0.94.1 (still crash I 0.96.1)

Podfile:

```
    $flipperkit_version = '0.94.1'
    pod 'FlipperKit', '~>' + $flipperkit_version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', '~>' + $flipperkit_version, :configuration => 'Debug'
    pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + $flipperkit_version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + $flipperkit_version, :configuration => 'Debug'
    pod 'Flipper-DoubleConversion', :configuration => 'Debug'
    pod 'Flipper-Folly', :configuration => 'Debug'
    pod 'Flipper-Glog', :configuration => 'Debug'
    pod 'Flipper-PeerTalk', :configuration => 'Debug'
    pod 'Flipper-RSocket', :configuration => 'Debug'
    pod 'CocoaLibEvent', :configuration => 'Debug'
    pod 'boost-for-react-native', :configuration => 'Debug'
    pod 'OpenSSL-Universal', :configuration => 'Debug'
    pod 'CocoaAsyncSocket', :configuration => 'Debug'
    pod 'ComponentKit', :configuration => 'Debug'
    pod 'Yoga', :configuration => 'Debug'
    pod 'YogaKit', :configuration => 'Debug'
    pod 'RenderCore', :configuration => 'Debug'
    pod 'Flipper-Boost-iOSX', :configuration => 'Debug'
    pod 'Flipper-Fmt', :configuration => 'Debug'
```

**Comment by bill350** [comment]
Same issue here and another colleague too 😕

**Comment by mweststrate** [comment]
Does the same thing happens if you run the `iOS/Sample` project in this repo?

**Comment by regularberry** [comment]
I'm seeing this on Flipper 0.133.1 - @arnauddorgans did you find a solution?

**Comment by lblasa** [comment]
I’ve found this issue is very intermittent at launch, is this the same case for you @regularberry ?

**Comment by regularberry** [comment]
Yep, not consistent @lblasa

**Comment by arnauddorgans** [comment]
> I'm seeing this on Flipper 0.133.1 - @arnauddorgans did you find a solution?

No, we don't use flipper anymore due to this issue

**Comment by lblasa** [comment]
I think the issue itself comes from Glog. The version used for Flipper seems to be quite behind. I'm in the process of updating it so maybe that will finally fix this issue.

**Comment by lblasa** [comment]
A new version of Flipper-Glog has just been released:
https://cocoapods.org/pods/Flipper-Glog

It is based off from v0.5.0 which is the latest. I believe it may solve the issue.

**Comment by regularberry** [comment]
I've updated DoubleConversion to 3.2.0 and Glog to 0.5.0.3 and haven't seen this issue pop up yet 🙌  - thanks @lblasa !

**Comment by regularberry** [comment]
Nevermind, spoke too soon. We see it happen during UI test runs.

**Comment by lblasa** [comment]
@regularberry I think this may have been properly fixed now. Could you please try the newer Flipper-Glog version?

Flipper-Glog v0.5.0.4

Multi-threading config settings were not properly set.

**Comment by regularberry** [comment]
@lblasa I'll check it out, thanks for the update!

**Comment by regularberry** [comment]
@lblasa We haven't seen this issue in a while with the latest Glog :+1: Thanks for fixing this!
