### ISSUE TITLE
Question: Does the Flipper Network plugin support Brotli encoding?

### ISSUE THREAD

**Issue by abouda** [facebook/flipper#2578]
I have integrated the Flipper Network plugin in my Android app.
With gzip it works fine.
With Brotli encoded responses, the Body is not decoded. It is displayed as binary text.

**Comment by jknoxville** [comment]
It does not currently.
However, here's the code for decoding responses, it expect it shouldn't be too involved to add brotli support, in a similar way to how gzip is handled, if you'd like to submit a PR: https://github.com/facebook/flipper/blob/master/desktop/plugins/public/network/utils.tsx#L93

**Comment by bizzguy** [comment]
@abouda  Could you provide a smallish sample file of something in Brotli encoding along with the decoding.  I've done some work with the Network plugin and would be interested in working on this feature.

**Comment by martymiller** [comment]
Did this ever happen?

**Comment by dallasgutauckis** [comment]
I don't think so. We're also seeing Brotli-compressed bodies show up like so:
![image](https://user-images.githubusercontent.com/117083/196549255-ec2ea7d1-de46-4ab9-ab5b-41f56e36c73c.png)

**Comment by dallasgutauckis** [comment]
I opened an MR at https://github.com/facebook/flipper/pull/4288 if someone could review it, that'd be awesome 👍🏻
