### ISSUE TITLE
[iOS][Folly]Build error:Thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by v73alice** [facebook/flipper#258]
when i want to run iOS/Sample project with Xcode, first i select Generic iOS Device, and then build.Then the error came out. But when i build the project with simulator, everything is ok.
So, does flipper only support ios simulator, not ios device ?

**Comment by v73alice** [comment]
@passy

**Comment by jknoxville** [comment]
That's right, unfortunately flipper doesn't support physical iOS devices
yet. However we do plan to enable this in the future.

**Comment by v73alice** [comment]
error msg: Thread-local storage is not supported for the current target

**Comment by v73alice** [comment]
@jknoxville   thanks for reply, and when will you support physical iOS devices?

**Comment by priteshrnandgaonkar** [comment]
Currently there are no plans around this. Closing this issue in the favour of #262
