### ISSUE TITLE
Question: Network tab in Hermes Debugger is empty. Can i make it work?

### ISSUE THREAD

**Issue by zombie6888** [facebook/flipper#2581]
Flipper network section is working, and i can see network logs there, but i don't see any logs in hermes debugger(RN) network tab. Console logs and other tabs  are working in hermes.  Is it possible to make it work? I prefer chrome devtools format for network query response, because it's more readable. 

![image](https://user-images.githubusercontent.com/7497489/125208577-ff8a6400-e29b-11eb-8bf9-684a00ee4266.png)

**Comment by mweststrate** [comment]
No that is not supported. You'll have to use the Flipper network plugin
