### ISSUE TITLE
Upgrade to RN 0.64.2 and Flipper-Folly 2.6.9  cause our dev build to break

### ISSUE THREAD

**Issue by kopax-polyconseil** [facebook/flipper#2597]
## 🐛 Bug Report

After performing an upgrade of Flipper and React Native from 0.63.3 to 0.64.2, Fkipper to 0.92.0, Flipper-Folyy to 2.6.7 ([PR](https://github.com/pass-culture/pass-culture-app-native/pull/1327/files)) we where unable to run and dev build on iOS

This is our configuration after the upgrade: https://github.com/pass-culture/pass-culture-app-native/blob/master/ios/Podfile#L19 

## Reproduction

https://github.com/pass-culture/pass-culture-app-native

## How we fixed

On our attempt on fix on `wip-rn-upgrade` branch:

- It build and install the application with : https://github.com/pass-culture/pass-culture-app-native/blob/wip-rn-upgrade/ios/Podfile
- we had to comment a whole file in `react-native`: https://github.com/facebook/react-native/issues/31249#issuecomment-811715288
- 
## Environment

iOS

## Related issues

- https://developer.apple.com/forums/thread/684441
- #2268 
- https://github.com/facebook/react-native/issues/31249

**Comment by mweststrate** [comment]
Could you update to RN 0.45 or 46 at least? The newer Flipper versions aren't tested against old React Native versions. What made you conclude it is a Flipper issue? Is the issue resolved if you disable Flipper and run pod install again? For reference you could check first if picking the same versions as we do in our [Podfile](https://github.com/facebook/flipper/blob/master/react-native/ReactNativeFlipperExample/ios/Podfile) works (or picking no versions at all)

**Comment by mweststrate** [comment]
The combination of specifying the full list as done in the Podfile is what we test automatically (that is how we can detect build issues with new versions), the combo of not specifying anything (just `use_flipper!())`) is what is verified by [RN repo](https://github.com/facebook/react-native/blob/0.64-stable/packages/rn-tester/Podfile) and the default, and should hence work as well. For any other combination we don't have any automation in place so hard to give any guarantees.

**Comment by kopax-polyconseil** [comment]
Hi @mweststrate, we managed to build our app with this PR : https://github.com/pass-culture/pass-culture-app-native/pull/1350

**Comment by faiz-netlinks** [comment]
I am using React Native 64.2, I switch to multiple versions of the flipper, still getting the same error.
