### ISSUE TITLE
UI Improvements on tables (for example Network Inspector and Database Inspector)

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#2608]
## 🐛 Bug Report
If the table has more columns than it can visually show (for example on smaller monitors or if the Flipper window size is smaller) since we cannot horizontally scroll on the table, we cannot see the data.

Example from the Network Plugin:

<img width="511" alt="np_1" src="https://user-images.githubusercontent.com/5049948/126312199-8f0e4243-a010-4bf2-bb0c-34ea988dbe84.png">

All the other columns (Method, Status, Size, ...) cannot be visible.
Since I have very long Domains and the only different part is the end of the domain I had to increase the column size to see the full domain. Doing this, I was unable to see the other columns. In fact, on a smaller monitor, I was even unable to see the full domain.

It would also be good if double click the handle of the column would increase the column until all the content in that column is shown (just like excel).

## Environment
Flipper 0.98.0 on MacOs

**Comment by hamzaawais96** [comment]
It only shows 50 rows. We can't change the page as well in the new design. Buttons are disabled which can allow us to change the page.

<img width="461" alt="Screen Shot 2021-11-09 at 6 22 22 PM" src="https://user-images.githubusercontent.com/85561593/140931662-8daa5cea-3aac-4caf-b8a3-091fd9505857.png">
e
