### ISSUE TITLE
flipper crashed on opening 

### ISSUE THREAD

**Issue by gnanasurya2** [facebook/flipper#2632]
## 🐛 Bug Report

flipper app crashed when opened.
![image](https://user-images.githubusercontent.com/44925005/127028767-77795729-a54f-428d-844b-34156ad0d451.png)

## To Reproduce

Downloaded the lastest version from the website and opened it

## Environment

windows 10

**Comment by passy** [comment]
Sorry, I can't reproduce this. Is it possible that there's a trailing space in the folder you extracted it into? While we should handle this better, I wouldn't be surprised if this caused more issues down the line.
