### ISSUE TITLE
Flipper 0.7.0 not available in jcenter

### ISSUE THREAD

**Issue by carlonzo** [facebook/flipper#264]
I've just tried to pull 0.7.0 from jcenter but its not found. jcenter problem or it is not deployed yet?
[http://jcenter.bintray.com/com/facebook/flipper/flipper/](http://jcenter.bintray.com/com/facebook/flipper/flipper/) as you can see is not present.

**Comment by carlonzo** [comment]
same for 0.7.1.
I have looked for it in the snapshots repo, but I cant find it :( https://oss.sonatype.org/content/repositories/snapshots/com/facebook/flipper/flipper/

**Comment by priteshrnandgaonkar** [comment]
We will release it soon on jcenter, till then pls use 1.6.8

**Comment by passy** [comment]
Publishing `0.7.1` right now. We'll close that gap in the release process next week.

**Comment by carlonzo** [comment]
Thanks! :)

**Comment by passy** [comment]
Sorry, my first attempt failed but `0.7.1` is on JCenter now.
