### ISSUE TITLE
Desktop app appear bug.

### ISSUE THREAD

**Issue by zhonghanwen** [facebook/flipper#267]
I download the latest build desktop app and open it appear this bug.
![default](https://user-images.githubusercontent.com/12220537/45607823-803f9c00-ba81-11e8-8d34-0b5d1041a5f1.png)

**Comment by jbarr21** [comment]
i went back to 0.7.0 of the desktop version, but sadly i get auto upgraded to the broken version when the flipper app is restarted. might be nice to have an option for disabling auto updates

**Comment by eveliotc** [comment]
```
index.dev.html:89 Uncaught TypeError: Cannot read property 'init' of undefined
    at HTMLScriptElement.script.onload (index.dev.html:89)
script.onload @ index.dev.html:89
load (async)
init @ index.dev.html:88
(anonymous) @ index.dev.html:95
(anonymous) @ index.dev.html:96
```

**Comment by Daavidaviid** [comment]
How can we proceed to have is working again ?

**Comment by passy** [comment]
@eveliotc Do you get this from the release build or from using `yarn start`?

**Comment by passy** [comment]
@danielbuechele Is it possible the global got renamed from `Sonar` to `Flipper` without changing the HTML invocation?

**Comment by passy** [comment]
Verified that this is the case. PR coming.

**Comment by rohandhruva** [comment]
@danielbuechele / @passy, any idea when we can get a new release of the desktop app with this fix applied? :) Alternatively, any other workarounds in the meantime?
