### ISSUE TITLE
Hermes Debugger (RN) - it seems impossible to set a startup breakpoint

### ISSUE THREAD

**Issue by aforty** [facebook/flipper#2705]
## 🐛 Bug Report
It seems impossible to set a breakpoint to trace startup problems such as in the root index.js (or even deeper) because it appears that the Hermes Debugger (RN) doesn't seem to attach until the app has already fully started. This makes debugging certain issues almost impossible and you have to resort of console.log() statements and other nonsense.

## To Reproduce
1. Open Flipper with a React Native app running in an iOS simulator (probably Android too)
2. Set a breakpoint in the root `index.js`
3. Press R in the simulator or terminal to reload the application
4. Notice that your breakpoint never hits

## Environment
iOS 14.5, Flipper 0.102.0, RN 0.64.2

**Comment by mweststrate** [comment]
Would you mind reporting this in the Hermes project instead?

**Comment by trcoffman** [comment]
you can put a `debugger;` statement in your code in order to debug your app's startup code. It works fine with flipper and hermes, I just tested it.
