### ISSUE TITLE
RN 0.65.0 require some listener methods on the NativeModule. It warns when call the NativeEventEmmiter with the NativeModule attached.

### ISSUE THREAD

**Issue by wfern** [facebook/flipper#2707]
## 🐛 Bug Report

Hello, the react-native 0.65.0 is showing a warning with the message: "new NativeEventEmitter() was called with a non-null argument without the required addListener/removeListeners method." Like the image below:
![image](https://user-images.githubusercontent.com/4096003/130073960-5f1b5ce3-f629-4472-a3ee-3dbff1ca7557.png)

This warning is shown because of the commit [114be1d](https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2), which checks if the native module `FlipperModule` has the methods: `addListener` and `removeListeners`. These checks are necessary because of this commit [f5502fb](https://github.com/facebook/react-native/commit/f5502fbda9fe271ff6e1d0da773a3a8ee206a453), which tries to use the native module to notify subscriptions on Android. So I think this issue is only related to Android.

Doing some tests I was able to fix it adding those methods in the Native Module:
```
@ReactMethod
public void addListener(String eventName) {
  // Keep: Required for RN built in Event Emitter Calls.
}

@ReactMethod
public void removeListeners(Integer count) {
  // Keep: Required for RN built in Event Emitter Calls.
}
```

## To Reproduce

On Android just use the react-native 0.65.0 and install the react-native-flipper with some plugin that depends on it, like redux-flipper. 

## Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz    
    Memory: 55.46 GB / 63.93 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\Watchman\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.0 => 0.65.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by dylmye** [comment]
Can confirm I'm getting this trying to use redux-flipper and react-native-flipper. The stacktrace leads to [line 165](https://github.com/facebook/flipper/blob/c0cd32564ad4b07a42365af886045095877a6a6b/react-native/react-native-flipper/index.js#L165).

**Comment by mweststrate** [comment]
Will be fixed in the next release! (ETA 11/11/21). Thanks @arch10 for the PR
