### ISSUE TITLE
Discussion: Automatic Dark Theme

### ISSUE THREAD

**Issue by swrobel** [facebook/flipper#2708]
Now that the dark theme is as usable as the light one (thanks!) it would be nice to have the theme automatically switch based on the system theme. In the previous dark theme discussion, someone [pointed out the Electron API](https://github.com/facebook/flipper/issues/552#issuecomment-533111444) for this.

**Comment by jknoxville** [comment]
Makes sense to me, I guess we want to change the settings from:

`Enable dark theme: Yes | No`

to some 3 way switch:

`Enable dark theme: Yes | No | Use system setting`

With "Use system setting" being the new default.

**Comment by qichuan** [comment]
@passy https://github.com/facebook/flipper/pull/2759 Here is the PR :)

**Comment by mweststrate** [comment]
Implemented, so closing. Thanks for the PR @qichuan!
