### ISSUE TITLE
Not to run flipper-pkg init

### ISSUE THREAD

**Issue by pranshuchittora** [facebook/flipper#2739]
## 🐛 Bug Report

`flipper-pkg init` is not working 

## To Reproduce

1. `npx flipper-pkg init`

## Environment

- Mac
- Linux

![Screenshot 2021-08-29 at 11 29 27 PM](https://user-images.githubusercontent.com/32242596/131260638-76eea79e-c171-4c08-920d-1e6f1ae7fb59.png)

**Comment by passy** [comment]
Dupe: https://github.com/facebook/flipper/issues/2710
