### ISSUE TITLE
Discussion: Display JavaScript Objects as Expandable/Collapsable

### ISSUE THREAD

**Issue by TheWirv** [facebook/flipper#2760]
Coming from a React Native context, every major browser today displays JavaScript objects in a collapsable/expandable form in its console. Flipper on the other hand only prints out the unformatted text version of the objects, with merely a "Show more/less" button. Unless I am missing something there is no way to change that behavior?

This would be an incredibly convenient feature to have, and is currently one of the reasons for me why it is not "on par" mit "Chrome Debugging" in any other browser. I debug my RN apps mainly via console.logging objects, and looking at and deciphering the plain text objects is really tedious and kind of a deal breaker for me right now. :/

**Comment by mweststrate** [comment]
See also https://github.com/facebook/flipper/issues/1010. Normally objects should be JSON formatted if you don't prepend it with other strings. However, the richest interaction with objects is by attaching the Hermes debugger.
