### ISSUE TITLE
cannot spawn openssl

### ISSUE THREAD

**Issue by JulianKingman** [facebook/flipper#2766]
## 🐛 Bug Report
Installed flipper, it doesn't connect to my app/simulator, I assume it's because of this error:

<img width="545" alt="Screen Shot 2021-09-02 at 7 40 03 PM" src="https://user-images.githubusercontent.com/1566400/131898786-d9f1def2-f489-47cb-91fc-9ed7a027156c.png">

I tried installing Watchman fresh from brew
`which watchman` returns `/usr/local/bin/watchman`

## To Reproduce
Install flipper
Try to use it?

## Environment
macOS 11.5.2
Flipper 0.105.0 (on desktop and in react native app)

Sorry if I missed something obvious 😬

**Comment by mweststrate** [comment]
I suspect it is because of the ssl error 😊. Seems your system is lacking
openssl

**Comment by JulianKingman** [comment]
`which openssl` returns `/usr/bin/openssl`
It seems like somehow the system PATH is not available to Flipper, is that possible? I'm not sure how to debug this. Thanks for your  help!

**Comment by JulianKingman** [comment]
Since my android sdk path and iOS idb paths were wrong, I fixed those. Still no luck :(

**Comment by JulianKingman** [comment]
Ah-hah, a suspect! Here's a package that fixes this issue in Electron: https://www.npmjs.com/package/fix-path, from the package description:
>  GUI apps on macOS and Linux do not inherit the $PATH defined in your dotfiles (.bashrc/.bash_profile/.zshrc/etc)

**Comment by JulianKingman** [comment]
Should I make a PR?

**Comment by JulianKingman** [comment]
Problem solved!

Steps:
1. launch app with sudo:
```
sudo /Applications/Flipper.app
```
2. Flipper asks for disk access to finder, is this an undocumented requirement?
3. In the error console, Flipper asks for some permissions changes

I'll leave this open at the moment, as it seems like there should maybe be a documentation change

**Comment by mweststrate** [comment]
`/usr/bin` should be always on the PATH already afaik, despite any local config. This really looks like a local setup issue. If sudo helps, it might be the case that maybe openssl is only installed for the su user and not visible to normal users? I'd try to check openssl installation instructions.

**Comment by Moises-dev08** [comment]
My problem resolved with this command in powershell:

choco install openssl

**Comment by mweststrate** [comment]
I'll add an error to make sure the absence of openSSL during startup is more clearly communicated

**Comment by iswarya2110** [comment]
@Moises-dev08 Thankyou
