### ISSUE TITLE
Question:  app apprears when using iOS simulators, but it doesn't work on my iOS physical device

### ISSUE THREAD

**Issue by luvwylla09** [facebook/flipper#2771]
### Description 
When I run a iOS simulator and open flipper, I can see app and use plugins. 

But when I select my iOS physical device in flipper, I got error tips like ' NO APPLICATION SELECTED'.

### Setup Doctor
![image](https://user-images.githubusercontent.com/55542399/132177343-89aeec27-fa33-47c3-9014-38b3278dd9f6.png)

**Comment by mweststrate** [comment]
Could you try on version 108, and share the logs at loglevel info? (either from the flipper logs or via the devtools)

**Comment by luvwylla09** [comment]
> version 108, and share the logs at loglevel info? (either from the flipper logs or via the devtools)

The problem has been solved in version 108. Thank you very much,
