### ISSUE TITLE
Multiple commands produce OpenSSL.xcframework

### ISSUE THREAD

**Issue by sapramit** [facebook/flipper#2788]
## 🐛 Bug Report
I already have an OpenSSL framework added to the workspace.

When I add Flipper, I get the below error as Flipper-Folly is creating an Opensssl framework

Multiple commands produce '/Users/amit/Library/Developer/Xcode/DerivedData/build/Build/Products/Debug-iphonesimulator/MyMobileApp-Dev.app/Frameworks/OpenSSL.framework':
1) Target 'MyMobileApp' has copy command from '/Users/amit/Desktop/MQ/Src/ios/OpenSSL.xcframework/ios-arm64_i386_x86_64-simulator/OpenSSL.framework' to '/Users/amit/Library/Developer/Xcode/DerivedData/build/Build/Products/Debug-iphonesimulator/MyMobileApp-Dev.app/Frameworks/OpenSSL.framework'
2) That command depends on the command in Target 'MyMobileApp': script phase “[CP] Embed Pods Frameworks”

Is there a way to remove OpenSSL from flipper

## To Reproduce
Add flipper to project which already has an Openssl Framework

## Environment
Xcode 12.5, React native version 0.65.1, Flipper 0.93.0

**Comment by mweststrate** [comment]
OpenSSL is an essential part of Flipper, as without it we cannot secure the device communication. 

Please note that as Flipper core team we generally don't investigate specific build issues (we simply lack the capacity for that). We do make sure our [example repo](https://github.com/facebook/flipper/tree/main/react-native/ReactNativeFlipperExample) keeps running which can be used as reference point, and generally do accept community investigations and fixes where needed.

**Comment by AdilAmanat** [comment]
@sapramit were you able to resolve that? I'm facing the same problem and scratching my head since few days but didn't find any solution yet.
