### ISSUE TITLE
Flipper Desktop app don't load

### ISSUE THREAD

**Issue by EstebanC02** [facebook/flipper#279]
Hi guys, I download the last versión of Flipper, actually the own app download it and the app don't run... So I uninstalled and downloaded from the web page (https://fbflipper.com) but happens again, and I can't used it.

![screen shot 2018-09-24 at 11 19 19 am](https://user-images.githubusercontent.com/11792308/45964534-b3d37680-bfeb-11e8-8492-a466a1e3f59c.png)

![screen shot 2018-09-24 at 11 19 44 am](https://user-images.githubusercontent.com/11792308/45964659-090f8800-bfec-11e8-8697-ff2aef609c86.jpg)

**Comment by duranmla** [comment]
Same here with Sierra:

![image](https://user-images.githubusercontent.com/1425162/45975705-daf16e80-c012-11e8-9389-d4fa7a2bcbc1.png)

**Comment by littlefoxtail** [comment]
may fix at [267](https://github.com/facebook/flipper/issues/267)， but how to get a new release

**Comment by michaelcarrano** [comment]
Seeing the same issue myself, I followed the trouble shooting steps here - https://fbflipper.com/docs/troubleshooting.html

I am using High Sierra 10.13.6

<img width="1440" alt="screen shot 2018-09-25 at 4 36 39 pm" src="https://user-images.githubusercontent.com/301400/46041667-56b9ec80-c0e1-11e8-992d-eb8d2c36a8f6.png">

**Comment by EstebanC02** [comment]
Solved with v0.8.0
