### ISSUE TITLE
Gradle sync fails on 0.8.0

### ISSUE THREAD

**Issue by johnheroy** [facebook/flipper#283]
Following the ["getting started" guide for Android](https://fbflipper.com/docs/getting-started.html), I added this line to my projects build.gradle:

```
debugImplementation 'com.facebook.flipper:flipper:0.8.0'
```

We are including jcenter() in our repositories and I get a failure with this message in Android Studio when trying to sync Gradle deps:

```
Failed to resolve: com.facebook.flipper:fbjni:0.8.0
```

Sure enough, 0.8.0 isn't uploaded to jcenter for `com.facebook.flipper:fbjni`:

https://bintray.com/facebook/maven/com.facebook.flipper%3Afbjni

**Comment by passy** [comment]
Sorry, you must have hit just the time slot during which one was uploaded but not the other. This has been fixed since then.
