### ISSUE TITLE
version 0.104.0 and above on Android cannot connect to our app

### ISSUE THREAD

**Issue by lgleasain** [facebook/flipper#2837]
## 🐛 Bug Report
We have a fairly large Android app that is using Flipper. Before version 0.104.0 we could connect to our app, but after the changes that appeared to come in in https://github.com/facebook/flipper/commit/1db39b8171f7c0c584fd35898f3fd9dfa2c69eca#diff-f60ed56a9c8275894022fe5a7a1625c33bdb55b729bb4e38962af4d1613eda25 Flipper is not able to connect to our see our app.

## To Reproduce
Initialize flipper using the new version

## Environment
Android version 0.104.0 and above and 0.105.0 of the Mac application to view the data.

**Comment by mweststrate** [comment]
We're currently investigating this issue. It seems to happen for quite some people, but not on all machines. We'll post as soon as we know more. Feel free to share any details about consistent reproducible cases! (device type, NDK version, etc)

**Comment by mweststrate** [comment]
Should be fixed in 108 which will release in a bit. Let us know if that doesn't solve the issue!
