### ISSUE TITLE
Question: What is the expected behavior for persisting network requests in Network Plugin

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#2839]
I'm trying to understand the expected behavior of the Network plugin.  It appears that network requests are lost when the app terminates.  The requests also get cleared if Flipper is reloaded.  At some point in the past it seemed like network requests were persisted across app crashes and even device restarts but that may be my imagination.

So I'm trying to understand what the expected behavior is.

**Comment by mweststrate** [comment]
The device & app, and by extension the network requests should remain available, until the app reconnects
