### ISSUE TITLE
Android Add support for Realm

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#284]
If possible, since Realm is widely used, add a plugin that we can check our databases.

**Comment by passy** [comment]
That's a feature that won't come out of our team, but it would definitely be great to have support for it. Happy to review any pull requests for it. :)

**Comment by erawhctim** [comment]
@mgoyanes I'm working on that exact thing as we speak :)

**Comment by mgoyanes** [comment]
@erawhctim great ;)

**Comment by erawhctim** [comment]
For anyone curious, I have basic realm data displaying in a plugin:
<img width="1557" alt="screen shot 2019-02-21 at 12 36 50 am" src="https://user-images.githubusercontent.com/6600919/53146130-0d2adc00-3571-11e9-9786-248e2f55292e.png">

Given a realm class declared in Kotlin like this:
<img width="391" alt="screen shot 2019-02-21 at 12 37 21 am" src="https://user-images.githubusercontent.com/6600919/53146143-17e57100-3571-11e9-9537-01f96ce6a91e.png">

And test/sample data setup like this:
<img width="641" alt="screen shot 2019-02-21 at 12 42 29 am" src="https://user-images.githubusercontent.com/6600919/53146284-9e9a4e00-3571-11e9-999e-b15b9d189b23.png">


I'm actively working on this at the moment. It's obviously _far_, far from complete and nowhere near ready, but I'll post a link to a repo/PR/etc here once the plugin is stable enough for an alpha release - subscribe to notifications on this issue if you're interested in following!

**Comment by passy** [comment]
That's amazing! Looking forward to seeing more about this, @erawhctim!

**Comment by mgoyanes** [comment]
Great @erawhctim. If you need testers count me in :)

**Comment by felislynx-silae** [comment]
@erawhctim are you going to add support to Room too?

**Comment by erawhctim** [comment]
@felislynx-silae Yep - the current plan is to make this plugin as database-agnostic as possible and support multiple different implementations. Realm on Android/iOS and Room at first, with SQLDelight and Core Data as later options. (I _think_ those are possible, but just haven't had time to fully explore/validate them yet since Realm was first-priority)

**Comment by kitttn** [comment]
@erawhctim 
Hi Mitch!
How is it going with SQLite? I was thinking about doing plugin, maybe you need help?

**Comment by BoD** [comment]
A generic db plugin has been merged ( https://github.com/facebook/flipper/issues/33 ).  Since it's generic, it looks like it could be extended to support Realm.

**Comment by tommybuonomo** [comment]
Hi @erawhctim,
Do you have any update on this ? Something we can explore, maybe an implementation of a custom `DatabasesFlipperPlugin` for Realm ?
Thanks :)

**Comment by kamgurgul** [comment]
If anyone need it I extracted driver which I'm using for Realm: https://github.com/kamgurgul/Flipper-Realm 
Maybe in the feature I will add iOS support and merge it here.
