### ISSUE TITLE
Flipper v0.108.0 A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by maystrenkoYurii** [facebook/flipper#2842]
<img width="1102" alt="Снимок экрана 2021-09-12 в 13 25 12" src="https://user-images.githubusercontent.com/23016311/132984044-878397ed-71b7-4d77-a71c-4f96a906f215.png">

**Comment by mweststrate** [comment]
can you share the contents of `~/.flipper/config.json`?

**Comment by maystrenkoYurii** [comment]
@mweststrate yes after change to dark theme and back to light this problem is resolved

**Comment by mweststrate** [comment]
Found the culprit, similar but different issue from the previous one. Will put up a diff but in the mean time changing the theme once should solve it!

**Comment by mweststrate** [comment]
Closing as it will ship in the next release
