### ISSUE TITLE
PortForwardingMacApp - request for documentation and/or source code

### ISSUE THREAD

**Issue by OleksiyA** [facebook/flipper#286]
Hi,

I met with condition when I can't start Flipper by running "yarn start". Issue seems to be that I have 20 or more instances of PortForwardingMacApp running.
This bring related question: PortForwardingMacApp is a binary checked in to this repo. What this binary does and do you intend to open the source of this binary?

Thanks.

**Comment by passy** [comment]
Thanks for flagging this. We'll try to either get rid of this or make sure the source is included here too.

**Comment by passy** [comment]
This is gone now.
