### ISSUE TITLE
ADB notice cannot be dismissed

### ISSUE THREAD

**Issue by kidroca** [facebook/flipper#2873]
## 🐛 Bug Report

I get a "Failed to initialise ADB..." notice docked at the top of the app window. It's preventing me to use the Hermes debugger as it blocks the different tabs available in dev tools. I couldn't find a way to dismiss it.
I didn't expect to see such an error in the first place, as I've switched "Android Developer" to **off** 
![image](https://user-images.githubusercontent.com/12156624/133786830-28148c87-3d24-4e25-a7f4-f52b03cd18c9.png)

## To Reproduce

1. On a mac
2. Have only xCode, don't have Android Studio or adb installed
3. Start flipper (v0.109)

## Environment

macOS Big Sur 11.5.2
Flipper v 0.109.0
Android Studio: not installed

**Comment by mweststrate** [comment]
Thanks for reporting! A fix is on the way. Note that the message should disappear after 10 seconds😅

**Comment by kidroca** [comment]
> Note that the message should disappear after 10 seconds😅

From the diff I see `duration` was set to `10` even before, but the notification never went away

**Comment by mweststrate** [comment]
Fix has been released as Flipper 0.110
