### ISSUE TITLE
Timed out establishing connection with "APPLICATION_NAME" on "Android SDK built for x86 - 10 - API 29". Verify that your client is connected to Flipper and that there is no error related to idb.  undefined

### ISSUE THREAD

**Issue by MohammadAzimi** [facebook/flipper#2874]
## 🐛 Bug Report
**Timed out establishing connection with "lunaapp" on "Android SDK built for x86 - 10 - API 29". Verify that your client is connected to Flipper and that there is no error related to idb. undefined** 

I'm getting this error when I'm trying to connect the android version of my application to Flipper. I've tried flipper 104 and updated it to 109 but no difference.
I also tried another emulator API 30
## To Reproduce
Download Flipper Desktop (windows). Extract the zip file. open the flipper desktop. Run your react native app.

## Environment
Windows10
Andorid Emulator API 29
react native 0.63.4
flipper desktop 104 (also tried 109)
![image](https://user-images.githubusercontent.com/26303194/133797833-3bbdb422-39e2-4ae4-8316-5e5d844f0db5.png)

**Comment by imort** [comment]
Same issue on Mac OS Client 0.109

**Comment by mweststrate** [comment]
A fix is on the way, should be fixed in 110 which should be public in ~2 hours or so, note that the SDK needs to be updated for that: https://fbflipper.com/docs/getting-started/react-native#using-the-latest-flipper-sdk

**Comment by mweststrate** [comment]
We're having some problem getting the build artifacts published. Something Murphy and Fridays. So, it's fixed, but not yet available. Might become Monday

**Comment by jonkun** [comment]
Same issue on Mac OS Client 0.110.0

**Comment by mweststrate** [comment]
`0.110.0` artefacts for Android are now published as well. Please upgrade with above instructions to fix the timeout issues.

**Comment by imort** [comment]
Tried `0.110.0`
```
A/libc: /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::__ndk1::system_error: setFromSocket() failed: Bad file descriptor" failed
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 9798 (FlipperConnecti), pid 9640
```
For a split second Mac client was connected to android application

**Comment by mweststrate** [comment]
@imort please report new issues as new issues.
