### ISSUE TITLE
Question: Cannot get the latest version from mavenCentral

### ISSUE THREAD

**Issue by fattomhk** [facebook/flipper#2876]
Seems the latest one on mavenCentral is 0.105.0 which is not aligning with the release note(0.110.0).

![image](https://user-images.githubusercontent.com/1083049/133966972-0f1a77a4-67a2-4d50-9b40-8ab07b89ef4d.png)

https://search.maven.org/artifact/com.facebook.flipper/flipper

**Comment by mweststrate** [comment]
We are currently looking into it. Between 105 and 109 nothing really changed, but 110 has a critical bug fix, so we'll try to land asap.

**Comment by mweststrate** [comment]
We clogged the build pipeline and the artifact should now be available!
