### ISSUE TITLE
Flipper Hermes Debugger doesn't connect on custom metro port

### ISSUE THREAD

**Issue by sauravk6** [facebook/flipper#2893]
## 🐛 Bug Report
I am trying to connect flipper with a metro server running on 8085. I am able to see the react-native logs and the react devtools but when I open Hermes debugger it shows me "Metro is connected but no Hermes apps were found". This however works completely fine if I am using default metro port (8081)

## To Reproduce
1. Enable hermes in a react native project
2. npx react-native start --port=8085
3. npx react-native run-android
4. Open Flipper via terminal: env METRO_SERVER_PORT=8085 open /Applications/Flipper.app

## Environment
React Native Version: 0.65.1
React Version: 17.0.2
Version of flipper SDK to use with React Native: 0.93.0

**Comment by mweststrate** [comment]
Are the targets listed if you manually go to `http://localhost:8085/json` ?

**Comment by sauravk6** [comment]
I get empty array in 8085, but if i run in default port I get targeted lists (http://localhost:8081/json)

**Comment by mweststrate** [comment]
Ok, that sounds like an issue with either Hermes or Metro itself. Would you mind reporting this in the react-native project instead (and linking it here for future readers)?

**Comment by sauravk6** [comment]
React Native Issue Link: https://github.com/facebook/react-native/issues/32307

**Comment by gentlee** [comment]
Still actual, why not to add setting with port in flipper?

**Comment by stvkoch** [comment]
check if you have enabled Hermes

![image](https://user-images.githubusercontent.com/14454/205904366-496874ab-3af5-48e0-bdfa-b40873d51ffb.png)

if you change the value, you will need install the pods for IOS

`cd ios && pod install`
