### ISSUE TITLE
High CPU/Battery usage

### ISSUE THREAD

**Issue by kidroca** [facebook/flipper#2894]
## 🐛 Bug Report

My laptop was running hot. I went to check battery usage, and found Flipper high battery usage:
<img width="743" alt="Screenshot 2021-09-20 at 21 05 39" src="https://user-images.githubusercontent.com/12156624/134070533-0f800e51-9dc5-42e3-bddd-639a4701f21e.png">
I've quit `Flipper` just before making the screenshot
I haven't noticed this happening before, though I was primarily using v0.100 and not for very long sessions
After quitting Flipper the computer managed to cool down

## To Reproduce

Leave Flipper for an extended period of time. It doesn't have to be on the foreground - I just forgot to close it.

## Environment

Flipper v0.110
M1 MacBook Pro, macOS 11.5.2
Used to debug an app on iPhone 12 iOS 14.5 simulator and react-native 0.64.1

**Comment by mweststrate** [comment]
You might want to check this comment: https://github.com/facebook/flipper/issues/2173#issuecomment-833445728. 

Note that there is still an open Electron bug on M1, that causes really high CPU usage on process spawning, which we really can't do much about at the moment: https://github.com/electron/electron/issues/26143

**Comment by gabrielmoncea** [comment]
Would rewriting the desktop application in react-native make it more efficient?

**Comment by kidroca** [comment]
I haven’t experienced the issue again

If the root problem is coming from Electron we can just close this one

**Comment by stryaponoff** [comment]
Same here in GNOME. I can hear noticeable laptop fan noise during running Flipper. Also system interface is quite laggy. It always back to normal just after I close Flipper.

![Screenshot from 2022-02-16 08-57-18](https://user-images.githubusercontent.com/3353718/154187699-4e399b15-fb96-4630-b36d-791406fc603d.png)
