### ISSUE TITLE
Permanent message about installing software (The "instruments" command requires the command line developer tools.)

### ISSUE THREAD

**Issue by digitalapplebee** [facebook/flipper#2905]
## 🐛 Bug Report
When flipper is running, I constantly see this message, after click installation, installation is in progress
<img width="573" alt="After install" src="https://user-images.githubusercontent.com/16328819/134814916-f9394d4b-1847-4a8a-a672-3ebdcde3c97d.png">

> The "instruments" command requires the command line developer tools. Would you like to install the tools now?
> Choose install to download and install the command line developer tools now.

<img width="610" alt="progress" src="https://user-images.githubusercontent.com/16328819/134814406-0ec82814-2de2-4250-b558-d95145260777.png">

But after successful installation, this message appears again
<img width="610" alt="successful" src="https://user-images.githubusercontent.com/16328819/134814847-978f7927-dfe0-43c6-ad79-9f1400306ec5.png">

When I click cancel, the notification disappears and appears immediately

<img width="573" alt="Screenshot 2021-09-26 at 6 27 52 PM" src="https://user-images.githubusercontent.com/16328819/134814303-9793f5fa-a242-47c7-95a4-136388050dee.png">

Setup Doctor
<img width="1257" alt="setup doctor" src="https://user-images.githubusercontent.com/16328819/134814248-11aaded6-7894-4009-bf31-9f154d8c5a8a.png">

How to solve the problem of the constant message about the need to install software? What is the problem?

## Environment
after update to Flipper 0.112.0 (probably with 0.111.0)
Xcode Version 13.0 (13A233)
MacOS BigSur 11.6 (20G165)

**Comment by BryanCrow** [comment]
This is caused by Apple deprecating the `instruments` command-line tool in Xcode 13. Apple [recommends](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes) using `xctrace` instead.

**Comment by BryanCrow** [comment]
Looks like this is a duplicate of #2896 where a fix has already been suggested.

**Comment by digitalapplebee** [comment]
@BryanCrow Well. Thanks
