### ISSUE TITLE
React Native 66 - Folly Duplicate Symbol compilation error on iOS

### ISSUE THREAD

**Issue by diego-paired** [facebook/flipper#2931]
I am trying to compile my React Native app for iOS after upgrading to RN 0.66 and getting compilation errors originating in Folly:

```
❌  duplicate symbol 'folly::detail::str_to_bool(folly::Range<char const*>*)' in
> libFlipper-Folly.a(Conv.o)
> libRCT-Folly.a(Conv.o)


❌  duplicate symbol 'folly::makeConversionError(folly::ConversionCode, folly::Range<char const*>)' in
> libFlipper-Folly.a(Conv.o)
> libRCT-Folly.a(Conv.o)


❌  duplicate symbol 'folly::exception_wrapper::from_exception_ptr(std::exception_ptr&&)' in
> libFlipper-Folly.a(ExceptionWrapper.o)
> libRCT-Folly.a(ExceptionWrapper.o)


❌  duplicate symbol 'folly::exception_wrapper::from_exception_ptr(std::exception_ptr const&)' in
> libFlipper-Folly.a(ExceptionWrapper.o)
> libRCT-Folly.a(ExceptionWrapper.o)


❌  duplicate symbol 'folly::exception_wrapper::onNoExceptionError(char const*)' in
> libFlipper-Folly.a(ExceptionWrapper.o)
> libRCT-Folly.a(ExceptionWrapper.o)


❌  duplicate symbol 'folly::exceptionStr(folly::exception_wrapper const&)' in
> libFlipper-Folly.a(ExceptionWrapper.o)
> libRCT-Folly.a(ExceptionWrapper.o)


❌  duplicate symbol 'folly::exception_wrapper::uninit_' in
> libFlipper-Folly.a(ExceptionWrapper.o)
> libRCT-Folly.a(ExceptionWrapper.o)


❌  duplicate symbol 'folly::exception_wrapper::ExceptionPtr::ops_' in
> libFlipper-Folly.a(ExceptionWrapper.o)
> libRCT-Folly.a(ExceptionWrapper.o)


❌  duplicate symbol 'folly::exception_wrapper::SharedPtr::ops_' in
> libFlipper-Folly.a(ExceptionWrapper.o)
> libRCT-Folly.a(ExceptionWrapper.o)


❌  ld: 9 duplicate symbols for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have tried multiple versions of Flipper:
```
use_flipper!({ "Flipper" => "0.111.0",  "Flipper-DoubleConversion" => "3.1.7",  "Flipper-Folly" => "2.6.9",  "Flipper-Glog" => "0.3.9",  "FlipperKit" => "0.111.0",  "fmt" => "7.1.3" })
```
The config that worked for RN 0.65:
```
  use_flipper!("Flipper" => "0.93.0", "Flipper-DoubleConversion" => "1.1.7")
```
and the default configuration which uses Flipper 0.99.

My system info:
```
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 307.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
    Watchman: 2021.09.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 30.0.2, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Patch 1 Arctic Fox 2020.3.1 Patch 1
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.4 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1 => 5.0.1
    react: ^17.0.2 => 17.0.2
    react-native: ^0.66.0 => 0.66.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
From Podfile.lock:
`RCT-Folly (2021.06.28.00-v2)`
```  - Flipper-Folly (2.6.9):
    - Flipper-Boost-iOSX
    - Flipper-DoubleConversion
    - Flipper-Fmt (= 7.1.7)
    - Flipper-Glog
    - libevent (~> 2.1.12)
    - OpenSSL-Universal (= 1.1.1100) 
  ```

Other:
Targetting iOS `12.3`
`"react-native-reanimated": "^2.3.0-beta.2"`

Thanks.

**Comment by TheFe91** [comment]
Same problem here

**Comment by storm2513** [comment]
+1

**Comment by storm2513** [comment]
Same issue for 0.65.1. But it's fixed there if I add `use_flipper!('Flipper-DoubleConversion' => '1.1.7')`

**Comment by rahulsolanki1818** [comment]
@TheFe91 How did you solve it?

I tried to comment out `use_flipper!()` & it worked. But without commenting it doesn't work for me.

**Comment by rahulsolanki1818** [comment]
> @rahulsolanki1818 This is my Podfile, hope that helps
> 
> ```
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> platform :ios, '11.0'
> 
> target 'XXX' do
>   config = use_native_modules!
> 
>   use_react_native!(
>     :path => config[:reactNativePath],
>     :hermes_enabled => false
>   )
> 
>   permissions_path = '../node_modules/react-native-permissions/ios'
> 
>   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
>   pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
> 
>   target 'XXXTests' do
>     inherit! :complete
>     # Pods for testing
>   end
>   
>   use_flipper!()
> 
>   post_install do |installer|
>     react_native_post_install(installer)
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end
> end
> ```

I have tried this already. Not working for me.

**Comment by whhotw** [comment]
> @TheFe91
> 
> I have tried this already. Not working for me.

I have deleted `podfile.lock` and `pod install`

**Comment by umang-simform** [comment]
Seems similar to this : https://github.com/facebook/react-native/issues/32333#issuecomment-939799341

**Comment by rahulsolanki1818** [comment]
@beetlebum Thanks this is the perfect solution. I was able to upgrade from React Native 0.61.0 to 0.66.0.
