### ISSUE TITLE
Question: Is fbflipper.com going be be back up soon?

### ISSUE THREAD

**Issue by stmiller-shamrock** [facebook/flipper#2945]
I wrote an article that will be published soon and link to a few places on the fbflipper.com documentation site. But today it is not loading. Is this going to be fixed? Just want to know so I know whether to leave those links in or rewrite around them.

**Comment by mweststrate** [comment]
No ETA yet (afaik), when facebook.com is up probably😅. There seem to be
DNS issues.

**Comment by stmiller-shamrock** [comment]
Didn't realize facebook.com was down. Thanks for the update!

**Comment by jknoxville** [comment]
Site is now back up. Closing this issue.
