### ISSUE TITLE
iOS Demo can not be linked with an iPhone device

### ISSUE THREAD

**Issue by yishuiliunian** [facebook/flipper#2958]
## 🐛 Bug Report

iOS Demo can not be linked.

![image](https://user-images.githubusercontent.com/846525/136639995-71b81675-4b8d-4f3f-9ff8-1248832ac75c.png)

## To Reproduce

follow the started guide

* git clone the repo
* run the ios demo with an iPhone device.

## Environment

Device:
* iPhone:  iPhone 8
* OS Version: 14.3

Mac:
* MacOS: 11.4

**Comment by aigoncharov** [comment]
Closed by https://github.com/facebook/flipper/commit/db59652d0ef2244228db4634c0b2cf9cf55239d4
