### ISSUE TITLE
Question: Can i integrate Flipper Network and Layout plugins in Swift5

### ISSUE THREAD

**Issue by usman643** [facebook/flipper#2992]
I have a project in swift 5 and i got requirement to integrate flipper for easy debugging. I'm adding pods in pods file and getting issues after run project 

i have seen one comment in IOS tutorials on your git repo "# Layout and network plugins are not yet supported for swift projects" [link](https://github.com/facebook/flipper/blob/main/iOS/Tutorial/Podfile) 

Is that true? if No please guide me to integration with swift 5

right now i'm getting error **"Undefined symbol: CKAnalyticsListenerHelpers::GetReusedNodes(NSObject*)"**
<img width="1436" alt="Screenshot 2021-10-21 at 1 30 30 AM" src="https://user-images.githubusercontent.com/59338952/138167935-d78924f2-f326-40d8-809c-37433071baf6.png">

My pod file attached as .txt
[podfile.txt](https://github.com/facebook/flipper/files/7384198/podfile.txt)

**Comment by nikoant** [comment]
Hey @usman643, that is still true.

**Comment by leo150** [comment]
Having same error in the mixed Swift/Obj-C project. Swift example has both plugins in the [Podfile](https://github.com/facebook/flipper/blob/main/iOS/SampleSwift/Podfile):
```
pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', :path => '../../FlipperKit.podspec', :configuration => 'Debug'
pod 'FlipperKit/SKIOSNetworkPlugin', :path => '../../FlipperKit.podspec', :configuration => 'Debug'
```
The only difference I see is that we're trying to build Flipper dependencies as static libs.
So both plugins can work for Swift, but only as dynamic libs?
