### ISSUE TITLE
UI glitch

### ISSUE THREAD

**Issue by kamal-j** [facebook/flipper#3010]
## Environment
Flipper Desktop version : 0.117.0
<img width="1792" alt="Screenshot 2021-10-29 at 12 09 22 PM" src="https://user-images.githubusercontent.com/41279891/139387836-fc9bcba9-11d2-4093-b765-11d4f0e7c2eb.png">

**Comment by mweststrate** [comment]
This is a common Chrome+MacOS bug, restarting your computer fixes it.
