### ISSUE TITLE
Question: Semantic Colors Dark Theme Support

### ISSUE THREAD

**Issue by plwai** [facebook/flipper#3011]
Currently, semantic colors in theme do not support dark theme which causing flipper-plugin `DataInspector` component `diff` content content barely readable. Is there any plan to support the theme color for dark mode?

![image](https://user-images.githubusercontent.com/9108726/139400170-ca6d8378-7f85-4b31-8701-2e8a3e58712f.png)

#https://github.com/jk-gan/redux-flipper/issues/57
#https://github.com/jk-gan/flipper-plugin-redux-debugger/issues/46

**Comment by mweststrate** [comment]
For anyone wanting to look into this: the colors are defined here, so should be var based: https://github.com/facebook/flipper/blob/main/desktop/flipper-plugin/src/ui/theme.tsx#L60-L61

**Comment by jasonakon** [comment]
I would like to look into this issue

**Comment by mweststrate** [comment]
@jasonakon that'd be greatly appreciated!

**Comment by 3rdp** [comment]
Just submitted a PR, I used the same colors, but from the reversed palette. I want to suggest using a darker color though e.g. lime-1 vs lime-2 (current color). Seems like it has better contrast with boolean color and grey text color

![lime-1-lime-2-comparison](https://user-images.githubusercontent.com/8898635/141802733-bc2ea72c-9858-4608-9441-749d900ba9e6.png)
