### ISSUE TITLE
Startup Issues on M1 Mac

### ISSUE THREAD

**Issue by jwaldrip** [facebook/flipper#3037]
I did a fresh install of flipper on an m1 mac. I am not seeing any apps or devices show up and I have an errors saying that the server cert cannot be found.

```
Failed to start FlipperServer Error: ENOENT: no such file or directory, open '/Users/jwaldrip/.flipper/certs/server.key'
Failed to read settings file: "/Users/jwaldrip/Library/Preferences/rs.flipper-launcher/flipper-launcher.toml". TomlError: Unexpected character, expected whitespace, . or ] at row 1, col 10, pos 9:
1> [object Promise]
            ^

. Replacing file with default settings. 
7 plugin(s) were loaded in legacy mode. Please visit https://fbflipper.com/docs/extending/sandy-migration to learn how to migrate these plugins to the new Sandy architecture: 
Hermes Debugger (RN) (id: Hermesdebuggerrn)
KaiOS RAM graph (id: kaios-graphs)
KaiOS: big allocations (id: kaios-big-allocations)
Layout (id: Inspector)
LeakCanary (id: LeakCanary)
React Native Tic Tac Toe (id: ReactNativeTicTacToe)
Sandbox (id: Sandbox) 
```

**Comment by mweststrate** [comment]
Can you make sure you use 0.118.1 which was released last Friday?

**Comment by jwaldrip** [comment]
@mweststrate there is not a DMG download for that version yet.

**Comment by mweststrate** [comment]
Oops! We'll release 0.119 today or tomorrow anyway so probably best to wait for that one. In the mean time sticking to 0.116 should work as well.

**Comment by marcoRS** [comment]
@mweststrate `Version 0.127.0` seems to have this same error. I can no longer see a connected emulator / device on this version.

**Comment by mweststrate** [comment]
@marcoRS there can be many reasons why devices don't show, which might or might not relate to this issue, so please open a fresh one and provide logs, context on the kind of app, device, etc etc
