### ISSUE TITLE
Pod install blocked on 0.118.1 because FlipperKitUserDefaultsPlugin never had a 0.118.1 release 

### ISSUE THREAD

**Issue by shamilovtim** [facebook/flipper#3040]
In Podfile I have:
`use_flipper!({ 'Flipper' => '0.118.1' })`

Afterwards I pod install:
`bundle exec pod install --repo-update`

I expect this is enough to compile but receive the error:
```
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FlipperKitUserDefaultsPlugin":
  In Podfile:
    FlipperKit/FlipperKitUserDefaultsPlugin (= 0.118.1)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit/FlipperKitUserDefaultsPlugin (= 0.118.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by mweststrate** [comment]
Could you retry with 0.119 in a couple of hours? (I takes a while before all artefacts are published)

**Comment by shamilovtim** [comment]
@mweststrate still the same issue. There doesn't seem to be a version over 0.111.0 that works correctly. Are you guys making releases of this dependency?

```
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FlipperKitNetworkPlugin":
  In Podfile:
    FlipperKit/FlipperKitNetworkPlugin (= 0.119.0)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit/FlipperKitNetworkPlugin (= 0.119.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by aigoncharov** [comment]
Flipper and FlipperKit 0.119.0 are released. Please, try with 0.119.0. It should fix the issue. @shamilovtim thank you for reporting the issue! Many thanks to @lblasa for fixing it!
