### ISSUE TITLE
Cmd + B shortcut global on macOS

### ISSUE THREAD

**Issue by mattmcdonald-uk** [facebook/flipper#3090]
## 🐛 Bug Report
On macOS, with an application being inspected the Cmd + B shortcut (and possibly others?) seems to be registered globally and doesn't work in other applications.

This was introduced in 0.120.0 and is not present in 0.119.0

## To Reproduce
- Open Flipper, select a target to inspect. 
- Open another application that uses the Cmd + B shortcut (e.g. VS Code). 
- Press Cmd + B with the other application focused.
- Observe the shortcut is ignored.
- Close Flipper.
- Press Cmd + B with the other application focused.
- Observe the shortcut works.

## Environment
macOS 12.0.1
Flipper 0.120.0

**Comment by zhirzh** [comment]
same issue with Cmd + K shortcut. in network panel, flipper uses this shortcut to clear logs

**Comment by rohandhruva** [comment]
I'm still seeing this in 0.122.

**Comment by seato** [comment]
I'm able to reproduce in 0.123 for `CMD + K`

**Comment by stdavis** [comment]
I'm able to reproduce this with `cmd + k` in `v0.124.0`.

**Comment by SergeiZavialov** [comment]
Still same problem with `cmd + K` in `0.125.0`

**Comment by mweststrate** [comment]
Should be fixed in next release
