### ISSUE TITLE
No release notes for the last 3 releases?

### ISSUE THREAD

**Issue by ColtonIdle** [facebook/flipper#3103]
Were the release notes intentionally left blank or was that a mistake? Thanks

**Comment by passy** [comment]
Sorry, this was to address some build and release issues. Sadly we can only really test this end-to-end by making new releases.

**Comment by lblasa** [comment]
Just to add that you can use the compare tool to find out what changes were included in each release.
For example: https://github.com/facebook/flipper/compare/v0.122.0...v0.123.0

More information here: https://docs.github.com/en/repositories/releasing-projects-on-github/comparing-releases

Sorry about this.
