### ISSUE TITLE
NO APPLICATION SELECTED for React Native iOS app after following troubleshooting guide

### ISSUE THREAD

**Issue by zeusstl** [facebook/flipper#3104]
## 🐛 Bug Report

NO APPLICATION SELECTED after following the [RN setup guide](https://fbflipper.com/docs/getting-started/react-native/) and then the [Troubleshooting Issues](https://fbflipper.com/docs/troubleshooting/)

(I've spent a few days attempting to fix this including upgrading macOS, Xcode and React Native following the React Native Upgrade Helper.)

Everything seems to be working besides the app itself connecting.

<img width="1272" alt="Main View" src="https://user-images.githubusercontent.com/5577624/143763442-6f13f5b3-603d-4759-ac2d-30a95d17454c.png">
 use_flipper!({'Flipper' => '0.122.0'})

<img width="418" alt="Settings" src="https://user-images.githubusercontent.com/5577624/143763668-532a0c5d-f957-4187-a9e1-8913b1d2a4c1.png">

<img width="600" alt="Plugin Statuses" src="https://user-images.githubusercontent.com/5577624/143763443-3a48327a-0712-4cda-a649-e8fb717c7003.png">
<img width="727" alt="Implemented Redux Flipper Middleware code" src="https://user-images.githubusercontent.com/5577624/143763518-77469885-65cb-422e-9171-119dea25cf2a.png">

<img width="419" alt="Setup Doctor" src="https://user-images.githubusercontent.com/5577624/143763444-968220e5-0e31-4e03-8ec4-afb4a976f960.png">
<img width="1230" alt="Flipper Console" src="https://user-images.githubusercontent.com/5577624/143763446-02b94910-1699-415a-b574-90be1025c045.png">

## To Reproduce

Follow setup and troubleshooting guide.
Run the app on an ios simulator via Xcode using a scheme with `Run` set to a Build Configuration of `Debug`.

## Environment

macOS: 12.0.1
Xcode: 13.1
Flipper: 0.122.0

Some relevant packages:
"react": "17.0.2",
"react-native": "0.65.1",
"react-native-flipper": "^0.122.0",
"redux": "^4.1.0",
"redux-flipper": "^2.0.1",
"redux-persist": "^6.0.0",

**Comment by Xmaxer** [comment]
I am having the same issue here.

Ubuntu: 21.10
React Native version: 0.66.3
Flipper version: 0.122.0

All debugging on Hermes, React DevTools, and logs for both device & JS work just fine, including breakpoints. Only problem is, I can't enable any of the other plugins (Such as the network plugin) because I still see "NO APPLICATION SELECTED"

My AndroidManifest.xml in both debug and main contains 'android:name="com.xxxx.mobile.MainApplication"' and the app itself works fine.

ADB devices lists the device correctly, and this project has been working fine for over a year with React Native Debugger so we know most if not all of the setup is correct (We just now added Flipper)

Really, everything is the same as in the original issue posted above for me other than my React version is newer.

**Comment by mweststrate** [comment]
@Xmaxer could you open a separate issue, since the OP is about iOS, not Android, and make sure to run the diagnostics first?  https://fbflipper.com/docs/troubleshooting/#android.

**Comment by mweststrate** [comment]
@zeusstl could you check if the reference project connects correctly for you? https://github.com/facebook/flipper/tree/main/react-native/ReactNativeFlipperExample

**Comment by zeusstl** [comment]
@mweststrate Thanks.

1) Can you please define what you mean by debug build? I've read it a lot throughout the Flipper docs and I want to make sure that it means what I expect it means. 

React Native __DEV__ is true. I have testing/setup code that relies heavily on it.

And in iOS, the scheme is using `Debug` for the `Run`.

<img width="912" alt="Scheme Debug" src="https://user-images.githubusercontent.com/5577624/144081194-ddbaf81f-929c-45f3-852a-cc1b6b3cd9ca.png">

**Is there something else that defines a build as debug?**

2) Have this in the Podfile: (tld.domain.appname is replaced by my actual app)
```
platform :ios, '11.0'
...
target 'tld.domain.appname' do
...
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )
...
  use_flipper!({'Flipper' => '0.122.0'})
...
end
```

All the Flipper packages and pods install successfully. There is one issue that I will try to fix in my pod install, but it is surprisingly difficult to get it right:

`Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
`
**Is this related to Flipper?**


3) I will test the example you sent.

**Comment by zeusstl** [comment]
Hi @mweststrate. I tested the React Native example project and that app does connect to Flipper correctly. I'm a bit baffled as to why my app doesn't connect to Flipper. (The `ffi` issue exists in the React Native example and doesn't prevent Flipper from working properly so that doesn't seem be the cause of the issue.)

**Any chance you can clarify what you mean by debug build?** Apologies if that seems silly, but as you can see in my note above it does seem to me like I'm working on a debug build.

If there is something else I can paste here that would be more informative, please let me know.

**Comment by zeusstl** [comment]
@mweststrate Have solved this. I had never done the Manual iOS setup. I guess it never seemed clear that it was necessary since practically everything worked correctly with the Automatic Setup.

Manual Setup
https://fbflipper.com/docs/getting-started/react-native-ios/

I used the Flipper code from React Native Hello World AppDelegate.m example:
https://github.com/facebook/react-native/blob/main/template/ios/HelloWorld/AppDelegate.m

**Two takeaways**
1. Perhaps add to the Troubleshooting doc to make sure that Manual iOS Setup was completed.
2. In the Manual iOS Setup manual mentioned above, perhaps clarify the language to make that installation more necessary. The title and description at the bottom of the Automatic Setup, make it seem like something that you would do if you weren't doing the automatic setup.

Very excited to get some debugging with my shiny new Flipper debugger.

Thanks for all the great work you do!

**Comment by mweststrate** [comment]
Manually iOS setup should normally not needed. But things can get out of sync when bumping just the react-native version without using React Native's upgrade tool

**Comment by Myahr208** [comment]
at 7:40, Nov 12:

<A.i><permission.granted/><open.source><help/>
