### ISSUE TITLE
Android emulator stderr: PANIC: Broken AVD system path

### ISSUE THREAD

**Issue by kaueDM** [facebook/flipper#3119]
I'm trying to add Flipper to an Expo project (custom development client) but I'm not able to start an emulator from Flipper.

I'm able to start an emulator from AVD manager and run my app without any issues, but it doesn't show up on Flipper.

Doctor:
![image](https://user-images.githubusercontent.com/20171863/144240557-f81a3a0c-1a25-4679-8762-54464574858c.png)

Android Studio:
![image](https://user-images.githubusercontent.com/20171863/144240719-998d28fd-698f-46bb-bfe4-b28e8f877c28.png)

Path:
![image](https://user-images.githubusercontent.com/20171863/144240785-f9feb912-5797-4e4c-9ae4-628c0314bbaf.png)

`envinfo`:
![image](https://user-images.githubusercontent.com/20171863/144240950-d4f90012-23e4-41d3-8dc8-63c338d0c612.png)

`adb --version`:
![image](https://user-images.githubusercontent.com/20171863/144241032-6b993613-d85a-422d-bb19-345846ec8bb1.png)

**Comment by lblasa** [comment]
Hi @kaueDM, thanks for reporting this. Could you please share Flipper logs? Or at least see if there's an error in them?

**Comment by kaueDM** [comment]
> Hi @kaueDM, thanks for reporting this. Could you please share Flipper logs? Or at least see if there's an error in them?

I got this on startup
![image](https://user-images.githubusercontent.com/20171863/144245565-6950eb5e-85f8-47e2-97e1-b89b8b2b24df.png)

And this one when trying to start an emulator from Flipper
![image](https://user-images.githubusercontent.com/20171863/144245629-b3693b71-2a6c-414c-bee6-cdb46abeeb1c.png)

**Comment by mweststrate** [comment]
I created a PR, should e solved in the next version
