### ISSUE TITLE
Docs: Please Update CHANGELOG.md

### ISSUE THREAD

**Issue by Nstd** [facebook/flipper#3123]

**Comment by lblasa** [comment]
We are very sorry about this!

In the meanwhile, you can use the compare tool to find out what changes were included in each release.
For example: https://github.com/facebook/flipper/compare/v0.122.0...v0.123.0

More information here: https://docs.github.com/en/repositories/releasing-projects-on-github/comparing-releases

**Comment by Nstd** [comment]
Thanks~
