### ISSUE TITLE
Header with object value does not show values

### ISSUE THREAD

**Issue by safaiyeh** [facebook/flipper#3145]
## 🐛 Bug Report

Headers that take an object show up as `[object Object]` in the network view.
![Screen Shot 2021-12-09 at 11 08 52 AM](https://user-images.githubusercontent.com/8675043/145460043-f2cc5382-b168-4900-b114-cddb2c95bd79.png)

## To Reproduce

Send a request with a header w/ an object

## Environment

React Native, Flipper Version 0.123.0 (50.0.0), macOS

**Comment by mweststrate** [comment]
Is this about the network plugin? Network headers are afaik always strings, not sure how to get an object in there, unless the server itself puts the `[object Object]` string in there?

**Comment by mweststrate** [comment]
Lacking follow up info, so I assume the issue is solved.
