### ISSUE TITLE
Windows app blank screen

### ISSUE THREAD

**Issue by risingus** [facebook/flipper#3152]
## 🐛 Bug Report
When i open flipper app on windows, only shows a blank screen with the error: Failed to start Flipper desktop: Error: ENOENT: no such file or directory, open 'C:\Users\ADMINND\.config\flipper\settings.json'

## To Reproduce
Litterally just download windows app and open.

## Environment
Using windows 11, vs code with react native emulating android device with android studio

![Captura de tela 2021-12-10 152725](https://user-images.githubusercontent.com/42497575/145623647-a380dd04-233c-41c5-87ea-aa097061573e.png)

**Comment by mgithubmessier** [comment]
I'm running into the same issue on a mac

**Comment by mgithubmessier** [comment]
But I did downgrade to version 0.123.0 and this resolved it, must've been an issue with their newest release.

**Comment by jas777** [comment]
Present on Windows 10 too

**Comment by risingus** [comment]
Yep, 0.123.0 works fine, but 0.124.0 is broken

**Comment by mweststrate** [comment]
Seems a future change accidentally made it into a release, will cut a new
release.

**Comment by aigoncharov** [comment]
@risingus could you confirm the issue is fixed with [0.125.0](https://github.com/facebook/flipper/releases/tag/v0.125.0)?

**Comment by risingus** [comment]
0.125.0 still send erros, 0.123.0 is the one that open with no problems
![Captura de tela 2021-12-13 093823](https://user-images.githubusercontent.com/42497575/145814153-f9644a1e-128c-404f-91d8-c937fb657fe0.png)

**Comment by risingus** [comment]
0.125.0 still send erros, 0.123.0 is the one that open with no problems
![Captura de tela 2021-12-13 093823](https://user-images.githubusercontent.com/42497575/145814216-5c9ff44b-2bbb-4e4e-adc8-dcf5d5638352.png)

**Comment by mweststrate** [comment]
@risingus does installing openssl fix the problem? See https://fbflipper.com/docs/getting-started/index/#installation. Lack of openssl should clearly not result in a blank screen, but that will help us narrow down the problem

**Comment by risingus** [comment]
@mweststrate, i was installing using an .exe, but i tried again now with Chocolatey and after the installation Flipper was working fine. Thanks for the help.

**Comment by ZeeshanAhmadKhalil** [comment]
@risingus  can you tell the command to install flipper with Chocolatey ?

For me its giving the following issue:

![image](https://user-images.githubusercontent.com/41861952/147326794-790cb397-5833-4f93-83fd-194c2305853f.png)

**Comment by ZeeshanAhmadKhalil** [comment]
I was having the same issue my problem was solved by installing OpenSSL using following command:

`choco install openssl`

**Comment by adi1625** [comment]
我也是白屏，通过安装OpenSSL解决了。从这个地方下的。我win10 20H2。

my problem was solved by installing OpenSSL using the following site:

http://slproweb.com/products/Win32OpenSSL.html

**Comment by arjuntare** [comment]
> my problem was solved by installing OpenSSL using the following command:
> 
> `choco install openssl`

This is still needed. Thank you!

**Comment by HenryWu01** [comment]
> my problem was solved by installing OpenSSL using the following command:
> 
> `choco install openssl`

Thank you so much! You saved my day
