### ISSUE TITLE
"Failed to exchange certificate with APP_NAME" - Permission Denied

### ISSUE THREAD

**Issue by mgithubmessier** [facebook/flipper#3168]
## 🐛 Bug Report
I'm continually getting an error detailing that Flipper does not have the permission to open its own `server.srl` file.  
Would love if this is a problem on my end and I'm missing something vital here in my setup, but I'm not sure that's the situation.

<img width="863" alt="Screen Shot 2021-12-13 at 6 21 11 PM" src="https://user-images.githubusercontent.com/11222124/145904651-6b33f878-a41a-4af6-9248-f7fdff63b7a2.png">

## To Reproduce
Not sure about how to reliably reproduce, but I am actively attempting to get flipper working for the first time on my react native application and am encountering this error on both for ios and android.

## Environment
- `Flipper Desktop` Version is 0.125.0
- I am using `Flipper Version` 0.75.1 in my gradle.properties configuration
- My `target android API level` is 30
- My `OS` is macOS 11.6 Big Sur

- My `react-native` version is 0.64.2

**Comment by mweststrate** [comment]
Sounds like the Flipper Desktop app has no permissions to use your home directory, what output does `ll ~/.flipper/certs` yield?

**Comment by mgithubmessier** [comment]
yields this
<img width="396" alt="Screen Shot 2021-12-15 at 6 24 39 PM" src="https://user-images.githubusercontent.com/11222124/146280391-ad64ce2b-092f-4295-9720-96ef363ae085.png">

**Comment by mgithubmessier** [comment]
Solved this with a `chmod <USER>+r+w ~/.flipper/certs/*`, thanks for pointing me in the right direction there!
