### ISSUE TITLE
[Android] Flipper doesn't work when using ADB in wifi mode

### ISSUE THREAD

**Issue by rock-tran** [facebook/flipper#3169]
## 🐛 Bug Report
Flipper works well in USB mode, not wifi mode.
In wifi mode, I see "Logs" work, but the installed app is not detected.

## To Reproduce
1. Implement Flipper plugin in app
2. Enable wifi debug in Android. Here I'm using Galaxy S7 Edge running Android 8
3. Install then run app on phone

## Environment
Flipper Android : 0.122.0
Flipper Desktop : 0.125.0

ADB version : 
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133

OS : endeavourOS. Kernel : 5.15.7

![Screenshot from 2021-12-14 15-16-26](https://user-images.githubusercontent.com/43530559/145959988-b1423f56-8cf1-4f43-8c16-af145f746b94.png)

**Comment by rock-tran** [comment]
When I try with another phone, running Android 11, Flipper works on both USB and Wifi mode.
Where can I find the Android versions that Flipper work on Wifi mode ?

**Comment by mweststrate** [comment]
We don't officially support ADB over Wifi, but you might want to check the Flipper logs itself (exclamation mark icon) to see if there are any hints, or run the diagnostics activity: `adb shell am start -n <APP_PACKAGE>/com.facebook.flipper.android.diagnostics.FlipperDiagnosticActivity`

**Comment by rock-tran** [comment]
Thanks @mweststrate . I will try it.
