### ISSUE TITLE
[macOS]: Flipper hoists Cmd+K shortcut

### ISSUE THREAD

**Issue by robrechtme** [facebook/flipper#3170]
## 🐛 Bug Report

Anytime I have logs open in Flipper, the Cmd+K shortcut (which clears logs in Flipper) is completely hoisted. Even if the Flipper window is not focussed, I cannot use Cmd+K in other windows. This is quite annoying as I use this shortcut a lot in VSCode. 

## To Reproduce
- Open Flipper
- Open a tab with logs that can be cleared e.g. "Logs" or "Network"
- Open another program
- Cmd+K doesn't get triggered 

## Environment
- Flipper Desktop v0.125.0
- MacOS Monterey 12.0

**Comment by villesinisalo** [comment]
Same as #3090 - present in the MacOS client since 0.120.0. Can repro - annoying indeed. One option is downgrading to 0.119.0 if possible.

**Comment by robrechtme** [comment]
Duplicates #3090.
