### ISSUE TITLE
Discussion: Syntax Highligting for Logs Flipper Plugin

### ISSUE THREAD

**Issue by clytras** [facebook/flipper#3173]
Hello,

For productivity, I wanted syntax highligting for the console logs and this is/was something that kept me from using Flipper and relying to a browser debugger console for debugging.

I gave it a shot and I managed to make Flipper Logs plugin to have syntax highlighting (_with `TruncateHelper` even_) using [`react-syntax-highlighter`](https://www.npmjs.com/package/react-syntax-highlighter) which supports both [highlight.js](https://highlightjs.org/) and [Prism.js](https://prismjs.com/).

You can see the result using dark mode and _Night Owl_ [highlight.js theme](https://highlightjs.org/static/demo/):

![image](https://user-images.githubusercontent.com/6103077/146371127-e3ece4f7-f458-4699-8c05-b243073bf686.png)

It's not perfect as this method highlights everything, every message, but the majority of the massages (at least for me) are code references and simple strings are printed with single color except if they have some javascript keywords that get highlighted; even though, it's way better like this than not having syntax highlighting at all.

If you guys like it, I can provide a PR for Logs plugin as a starting point to make Flipper support syntax highlighting for _Logs_.

**Comment by efstathiosntonas** [comment]
For the name of God, please submit this PR! Thanks Chris!

**Comment by mweststrate** [comment]
Looks cool! My primary concern would be around performance, logs plugin can generated a few hundred K of lines and scroll very fast, so I'd check against a physical android device's logs to see if this doesn't slow down rendering a lot. If it does, maybe it could be made an option in the drop down menu?

**Comment by clytras** [comment]
@efstathiosntonas Hey Stathis! How nice to see you here! We need to get in touch!

I wanted to discuss this first before I procced submitting a PR.

@mweststrate I share the same concerns with you regarding performance, but remember, for each record, the highlighted text will be the truncated text, which currently has a length of 400:

https://github.com/facebook/flipper/blob/d48fbd8e50c8ae6203a8ce92aa5a98aa64160ca1/desktop/plugins/public/logs/index.tsx#L100-L104

so, even id there is a 5K string/object, the highlighter will always process the first 400 characters, it will only process the whole log entry when the user hits the *more* expand button.

It works pretty well so far on a big RN project with simple logs.

This definitely needs some options to the settings, not only for toggling its' state, but setting up the theme as well and I think it would be best to flag it (*and actually display it*) as experimental and even warn users that they may experience performance issues on big log loads/usage.

It's kind of hard to work on it right now in the middle of the holydays, but I'll do it soon and I'll provide a PR to see if this can fit to Flipper.

**Comment by mweststrate** [comment]
Looking forward to it! If not too complicated, it might be interesting to set it up as a shared DataFormatter as well in flipper-plugin, that makes the functionality easily shareable with other plugins

**Comment by clytras** [comment]
@mweststrate I have implemented it as a shared DataFormatter indeed, but the issue with this approach is that it can't work with the truncate formatter as it can't process JSX as a source to highlight, only strings.

Please have a look at my PR when you find some time as there are some issues that need to be discussed and ironed.

**Comment by vaughnkoch** [comment]
Related to this, it would be nice if Flipper logs could colorize output based on escape codes, such as:
```
09:05:14.358     0    client_log        [34m9:05:14 AM | INFO : SUPER INFO [0m
```
should ideally automatically colorize, like it does in Metro output. I know that Flipper already colors logs for error, warn etc, but packages like react-native-logs let you customize the colors internally as well. Maybe that should be in a separate github issue.
