### ISSUE TITLE
ssl3_get_record:wrong version number - No plugins showing up for my Mac

### ISSUE THREAD

**Issue by smilearchery** [facebook/flipper#318]
![image](https://user-images.githubusercontent.com/1215112/47979807-ddf67900-e0ff-11e8-9301-7dddfa65024b.png)
![image](https://user-images.githubusercontent.com/1215112/47977411-d2e91c00-e0f2-11e8-9ba9-509c7bb5e361.png)
![image](https://user-images.githubusercontent.com/1215112/47977480-3115ff00-e0f3-11e8-8f5d-c20ba1d5f66c.png)

flipper version: 0.10.0
adb version: 1.0.40-4986621
OSX version: macOS Mojave 10.14 (18A391)

**Comment by smilearchery** [comment]
![image](https://user-images.githubusercontent.com/1215112/47977604-fbbde100-e0f3-11e8-896e-7b2c915d13a1.png)

**Comment by jknoxville** [comment]
Hi @smilearchery 

I haven't seen this error before, but my first guess is that you might have a version of openssl installed that doesn't support the protocols used by the sdk.

Can you run the following, while flipper is running, and see what you get? This will attempt to connect to flipper using TLSv1.2: `openssl s_client -connect localhost:8088 -tls1_2`
Also, knowing what version of openssl you're running might be helpful too, which you can find out with `openssl version`

**Comment by smilearchery** [comment]
Hi @jknoxville 
Many thanks for the prompt reply. 

![image](https://user-images.githubusercontent.com/1215112/47999413-81b24a00-e13d-11e8-93c1-3374c97a467c.png)


% openssl version                                                     1 ↵ ✭
OpenSSL 1.0.2p  14 Aug 2018
% which -a openssl                                                        ✭
/usr/local/opt/openssl/bin/openssl
/usr/bin/openssl

I tried default openssl version, which is not work either.
% /usr/bin/openssl version                                                ✭
LibreSSL 2.6.4

**Comment by jknoxville** [comment]
Thats interesting that you get the same error here.
Could you try the same command with `-servername localhost` at the end?
And perhaps with -tls1 or -ssl3 instead of -tls1_2?

**Comment by smilearchery** [comment]
Hi @jknoxville

**Comment by smilearchery** [comment]
Hi @jknoxville 
![image](https://user-images.githubusercontent.com/1215112/48005987-c515b400-e14f-11e8-87db-5869bf9f405e.png)
![image](https://user-images.githubusercontent.com/1215112/48006026-dbbc0b00-e14f-11e8-932b-49565f146cd1.png)
![image](https://user-images.githubusercontent.com/1215112/48006072-f0000800-e14f-11e8-98ec-cf94a183fc64.png)

**Comment by smilearchery** [comment]
Finally I found the reason. A proxy server was running in background which listen and occupy the 8088 port.
Anyone who meet this problem may try `lsof -i:8088` to find which program is using your port.
Flipper may add a feature to handle the error case if the port is occupied
