### ISSUE TITLE
Flipper interrupting application

### ISSUE THREAD

**Issue by Victorcassiano** [facebook/flipper#3186]
## 🐛 Bug Report
The bug occurs when Flipper opens, node closes and stops the application

## To Reproduce
<img src="https://i.imgur.com/qWFDmG3.png" alt="drawing" width="300" />

## Environment
- Android 10
- Flipper 0.126.0
- React Native 0.64.2

**Comment by mweststrate** [comment]
@Victorcassiano could you try https://github.com/facebook/flipper/issues/3189#issuecomment-997191720?

**Comment by Victorcassiano** [comment]
> @Victorcassiano could you try [#3189 (comment)](https://github.com/facebook/flipper/issues/3189#issuecomment-997191720)?

yes

**Comment by mweststrate** [comment]
Duplicate of #3189, upgrading to Flipper 0.127 should fix the problem.
