### ISSUE TITLE
Publish on CococaPods

### ISSUE THREAD

**Issue by KrauseFx** [facebook/flipper#325]
Hey Flipper team,

This looks great, what is the current plan around a publicly available CocoaPod? I see the name isn't registered yet (https://cocoapods.org/pods/FlipperKit) and the [current docs](https://fbflipper.com/docs/getting-started.html#setup-your-ios-app) point to the GitHub repository directly. This would make sense if a developer wants to use the latest version from `master`, but in this case the guide tells developers to use the `flipperkit_version`, meaning we could make use of CocoaPods for actual releases.

**Comment by KrauseFx** [comment]
Registering & using the name would probably be a good idea, so that no one grabs it now

**Comment by pkrmf** [comment]
Hey @KrauseFx, there is an open issue for cocoapods https://github.com/facebook/flipper/issues/132 but we are hitting some roadblocks due to flipperkit’s dependencies 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KrauseFx** [comment]
Got it, thanks, closing in favor of #132
