### ISSUE TITLE
Searching Plugins throws error -  Unreachable hosts - your application id may be incorrect

### ISSUE THREAD

**Issue by JaxGit** [facebook/flipper#3265]
## 🐛 Bug Report

Searching in Plugin Manager > Install Plugins throws following error in Flipper Logs:

"unhandledrejection" event intercepted:
"Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com."
![Screen Shot 2022-01-11 at 11 23 49 am](https://user-images.githubusercontent.com/11201846/148861678-8df46232-f610-4437-8fca-115004873981.png)

## Environment

macOS Catalina version 10.15.7 (19H1519)
Flipper (0.127.0)

## Workaround
Am currently using the following:
- `npm pack [plugin-name]` to download tarball from npmjs to current folder
- Install plugin from file following https://fbflipper.com/docs/extending/plugin-distribution/

**Comment by olessavluk** [comment]
Hi 👋 
Happens for me when using corporate cloudflare warp with their certificate trickery.
Setting `NODE_TLS_REJECT_UNAUTHORIZED=0` and then running Flipper from command line resolved issue

**Comment by lblasa** [comment]
Hi @JaxGit I don't think this item is actionably by us. It does indeed look related to some network issue.

**Comment by growabeard** [comment]
I realize this is closed, but is there an available proxy setting for Flipper to search and add plugins when behind a proxy? I can't use Flipper on my work VPN.

**Comment by AndrewGable** [comment]
https://github.com/facebook/flipper/issues/3265#issuecomment-1020345731 Worked for me with Cloudflare WARP, thank you.
