### ISSUE TITLE
[Request] Provide binaries for v0.128.0

### ISSUE THREAD

**Issue by rafauke** [facebook/flipper#3281]
Hello,

Thanks for all the hard work :) It would be great if you could provide the binaries for recent release: https://github.com/facebook/flipper/releases/tag/v0.128.0

Thanks!

**Comment by passy** [comment]
Thanks for the request. Will restart the release jobs.

**Comment by passy** [comment]
It actually doesn't build on Windows right now. I'll need to land a fix for that first.

https://github.com/facebook/flipper/runs/4791210127?check_suite_focus=true

**Comment by passy** [comment]
We finally got a new release out now. Sorry for the delay!
