### ISSUE TITLE
Cannot create Flame Graph on Hermes

### ISSUE THREAD

**Issue by mrousavy** [facebook/flipper#3290]
## 🐛 Bug Report

Hi!

I'm trying to create a Flame Graph for my app which is running on Hermes to find out which functions are slow.

I can't seem to start the Performance Recording though, as the Hermes Debugger (RN) plugin is stuck at this screen forever and never actually starts:

![image](https://user-images.githubusercontent.com/15199031/149523900-4e85efd2-6ace-498b-92e7-4368d3cfdcb7.png)

These are the logs being printed in Flipper Logs:

![Screenshot 2022-01-14 at 14 52 19](https://user-images.githubusercontent.com/15199031/149526101-11c9d161-f59e-4a5f-9ac4-17dca9667b49.png)

## To Reproduce

* Open app (on Simulator) with Hermes
* Open Flipper
* Connect to App (select it in dropdown)
* Switch to Hermes Debugger (RN)
* Open Performance Tab
* Click "Record" button (circle)

### `package.json`

* react-native: ^0.67.0-rc.6
* react-native-flipper: ^0.128.0

### `Podfile.lock`

* Flipper: 0.128.0 (Pinned via `use_flipper(...)` arguments)

### Flipper Desktop App

Version 0.127.0

**Comment by passy** [comment]
I believe that's expected. See here: https://github.com/facebook/flipper/issues/1830
