### ISSUE TITLE
Said: "... you don't have OpenSSL installed...". But I manual run 'openssl version' is OK(add path correctly)!

### ISSUE THREAD

**Issue by huanguolin** [facebook/flipper#3294]
## 🐛 Bug Report
![image](https://user-images.githubusercontent.com/12430413/149616935-bff48b24-a669-437d-8474-7521f44ae2b7.png)
![image](https://user-images.githubusercontent.com/12430413/149617047-bc2d0211-3226-425b-8e6f-20b2b668b29c.png)

## To Reproduce
Just start flipper.

## Environment
Desktop version: 0.127.0
Android version: 0.125.0
OS: Windows 10 Enterprise 21H1 19043.1415

**Comment by huanguolin** [comment]
![image](https://user-images.githubusercontent.com/12430413/149617281-7f7b6f4a-531a-449f-b91b-82f0ce2d01c1.png)

**Comment by passy** [comment]
Sorry, I'm a Windows noob but this would indicate that `openssl` isn't available on the `$PATH` equivalent on there. Could you check if the article here is of any help? https://dev.to/danilovieira/installing-openssl-on-windows-and-adding-to-path-3mbf

**Comment by huanguolin** [comment]
> Sorry, I'm a Windows noob but this would indicate that `openssl` isn't available on the `$PATH` equivalent on there. Could you check if the article here is of any help? https://dev.to/danilovieira/installing-openssl-on-windows-and-adding-to-path-3mbf

Thanks! It's working! 

The key is: Must add path to the User Variables. Not System Variables.
If both places are added, it won't work either. 😂

**Comment by huanguolin** [comment]
I think this problem may be related to https://devblogs.microsoft.com/oldnewthing/20100203-00/?p=15083

**Comment by farmketprocess** [comment]
OpenSSL (https://wiki.openssl.org/index.php/Binaries) is not installed or not added to PATH. Command "openssl version" failed to execute with output: Command failed: openssl version 'openssl' is not recognized as an internal or external command, operable program or batch file
