### ISSUE TITLE
Flipper 0.128.4 - Android crash on startup

### ISSUE THREAD

**Issue by WenLonG12345** [facebook/flipper#3296]
Hi, I am recently update flipper from `0.127.0` to `0.128.4`. However, when I launch my Android app, the app crash during startup. Here is the crash log from flipper. 

```
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2022-01-17 14:47:51+0800
pid: 14211, tid: 14240, name: FlipperEventBas  >>> io.chativo.chat <<<
uid: 10239
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type folly::json::parse_error: json parse error on line 0: expected json value" failed'
    eax 00000000  ebx 00003783  ecx 000037a0  edx 00000006
    edi ed69d81e  esi c0676a10
    ebp f1bf8b90  esp c06769b8  eip f1bf8b99
```

It seems to be ndk version issues.. but I don't know? 

**Enviroment:** 
Flipper app: 0.128.4
gradle.properties: 0.128.4
react-native-flipper: 0.128.4

Anyone have idea why this error occurs? and also any solution for this?

**Comment by kevoroid** [comment]
Kinda same issue for me when I updated to 0.128.4 on Linux but no errors as it completely freezes!

**Comment by WenLonG12345** [comment]
Anyone upgrade to `0.129.0` ? is this fixed?

**Comment by Yrsafam** [comment]
@WenLonG12345

**Comment by ObidosDev** [comment]
same

**Comment by lblasa** [comment]
Hi, the issue is known and we are currently working on a solution.
