### ISSUE TITLE
Feature Request Adding Support for SqlLite DB browser and Shared Preference

### ISSUE THREAD

**Issue by pranayairan** [facebook/flipper#33]
As sonar on the path of replacing Stetho, there are some functionalities in Stetho that is currently not supported by Sonar. There are 2 main functionalities that would be awesome to add as a plugin. 

1. Support to browse SQLlite DB and run raw queries on it. 
2. Support to browse App's Shared Preference and option to edit them. 

This functionalities already exist in Stetho and super easy to use.

**Comment by xiphirx** [comment]
There is a shared preferences plugin available as of https://github.com/facebook/Sonar/commit/55930db6a6f9c50e8d548bdc6dad79313726769a 

Please try it out and let us know what you think.

There are plans to add a sqlite db plugin as well.

**Comment by guuilp** [comment]
Any news about this feature?

**Comment by BoD** [comment]
SQLite is really a must have feature.  Will not switch to Flipper until this is available.

**Comment by passy** [comment]
@BoD We're more than happy to look at any pull requests regarding this feature. :)

**Comment by xiphirx** [comment]
https://github.com/facebook/flipper/commit/a630b50a8f824928546a3d9d0c2d4949ca3d3afc

**Comment by soupormario77** [comment]
Quit sending me messages you fucking fat head!

Mario,
1-805-336-3069
