### ISSUE TITLE
[QUESTION] JS / Web Flipper connection

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#3317]
Recently added [js-flipper](https://github.com/facebook/flipper/tree/main/js/js-flipper) allows to use Flipper for `Node.js` or `Web` projects.

But I found the current Flipper desktop does not start the `ws` server on port `8333`, because of the `GK.get('comet_enable_flipper_connection')`.

I believe this `GK` util is only used internally in FB, but would it be possible to either allow by default, or move this from `GK` to be as settings option in Flipper?

Currently, need build Flipper Desktop locally and remove the GK condition.

**Comment by aigoncharov** [comment]
Hi @usrbowe! Thanks for spotting it, and for trying out `js-flipper`. The fix is on its way.

**Comment by aigoncharov** [comment]
Should be resolved by https://github.com/facebook/flipper/commit/3865a3d9a2e685fbfc6de5db589d9a136db79720
