### ISSUE TITLE
Discussion: 3rd party NPM registry, internal only plugins

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#3320]
I would like to open discussion on this topic. Most plugins will likely be open sourced and published to `npm`. But I believe lot of use cases will include internal plugins, which should only be available internally.

I guess this is also case in Facebook/Meta. So would like to know what approach you guys took, and maybe we could add some similar option for others as well?

One of the main issues, might be how to actually add 3rd party registry, since the searching through registry might be different and also parsing results will require lot of custom code.

So far there might be few options:

1. Add support for most common npm registry, like `Verdaccio` (with help from community). Could have folder with resolvers.
2. Add support for self hosted index of plugins with predefined format, so by adding `URL` into Flipper settings we would allow internal plugin discovery and also future auto updating. This will require hosting some simple web app, and flipper could even include some simple package to just run this.

Let me know if any other ideas or approaches we could take to allow publishing Flipper plugins internally.

**Comment by nikoant** [comment]
Hey @usrbowe! We have distribution mechanism for internal plugins which in addition to installation also supports auto-updates for plugins. I think it should be easy to adopt for option 2. I'll write up a doc this week on how the mechanism works and propose how we could extend it to support custom plugin indexes.

**Comment by usrbowe** [comment]
Hi @nikoant,
maybe we could start by just sharing some high level overview of the the mechanism, and I could try something out first. Wha you think?

**Comment by nikoant** [comment]
Hey @usrbowe, sorry for delay with that! Sounds good, yes. I opened a PR which moves rest of the internal plugin distribution code to open-source. Other code like UI for installing and updating plugins and dispatcher/reducer for firing downloads was already there.

**Comment by nikoant** [comment]
I added some explanation of the current design and comments here: https://github.com/facebook/flipper/pull/3473. I'm happy to hear any suggestions on how we can re-use it for different orgs. 

Eventually I would also like to better unify "internal" distribution and "public" distribution via npmjs.org. For now they are two totally different branches which isn't very convenient.

**Comment by usrbowe** [comment]
Nice, let me go through the PR first. Will try to came up with some proposal.

For the unification of public/internal plugins, you would like to use only npmjs.org? Because that would require to have a npmjs plan to publish private packages.

**Comment by nikoant** [comment]
> For the unification of public/internal plugins, you would like to use only npmjs.org?

I mean unification on UI side. Currently internal plugins can be installed from the app inspect panel, but to install those available on npm we need top open Plugin Manager. So I thought it would be nice to have a unified way of installation from different sources, probably something similar to VSCode extensions panel.

**Comment by usrbowe** [comment]
I see, yeah that make sense, to unify. Can be another phase once there is initial proposal of how to distribute "marketplace" plugins to Flipper.

**Comment by usrbowe** [comment]
Since the marketplace feature was released and is now available under settings: 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/5339061/158527508-f1c1093c-c7f7-4927-8c2b-674ecee0c45b.png">

I will close this issue. And we can continue this effort in new issue focused primarily on documentation: https://github.com/facebook/flipper/issues/3545

@nikoant 
We could probably also note down the UI modifications:
1. Internal and external plugin manager
2. Enhance settings modal (probably convert into full page and add tabs)
