### ISSUE TITLE
Question: Need to enable iOS diagnostics and the documentation is unclear

### ISSUE THREAD

**Issue by jwd-kalyber** [facebook/flipper#3322]
There is an existing issue #1757 that asks where you put the FlipperDiagnosticsViewController.m in react native, but it has not been answered.

I am able to connect to Flipper to Android without issue. With iOS I get an error:

Connection failed

Failed to find device ... while trying to connect app. 

I had hoped that the diagnostics controller view would shed more light on this issue, but the documentation in troubleshooting simply says add this file. Where should the file be added? Do I have to do anything else other than adding the file?

I've gone through the rest of the troubleshooting guide. I am using Flipper version 0.128.4 and react version 0.67.0. This is a clean install with no custom code at the moment. I hadn't used Flipper in the past but wanted to enable it for a new app.

**Comment by baveku** [comment]
Do you install fb-idb and watchman?

**Comment by lblasa** [comment]
Hi @jwd-kalyber sorry to hear you're having issues establishing a connection. 

For reference, FlipperDiagnosticsViewController is already part of FlipperKit so you just need to use it.

Example:
`#import <FlipperKit/FlipperDiagnosticsViewController.h>
FlipperDiagnosticsViewController* controller =
        [[FlipperDiagnosticsViewController alloc] init];
  self.window.rootViewController = controller;`

Could you please share logs from Flipper Desktop?

**Comment by jwd-kalyber** [comment]
Thanks @baveku and @lblasa! I have tracked this back to an issue with installing IDB. There is a problem installing IDB on my current version of Mac OS (11.6.2) through brew that is causing the real problem.

For any future reference the IDB issues are documented in the following:
- https://github.com/facebook/idb/issues/757
- https://github.com/facebook/idb/issues/751

I haven't tested this yet, but others are saying that the latest version of Mac OS works as expected for IDB.

**Comment by AlbertVilaCalvo** [comment]
Maybe it helps someone in the future.

I got the error "Failed to find device ... Timed out waiting for device" on a Mac with Brew. To fix it I had to link `idb-companion`: `brew link idb-companion`.

Use `brew doctor` to know if there is something unlinked.

**Comment by essana3** [comment]
idb-companion does not work on any M1 device
