### ISSUE TITLE
Gradle cannot resolve fbjni 0.12.0 for Android builds

### ISSUE THREAD

**Issue by bojankoma** [facebook/flipper#333]
I get this when I use 0.12.0 Flipper for Android on Gradle sync:
`ERROR: Failed to resolve: com.facebook.flipper:fbjni:0.12.0`

Desktop app is already at 0.12.0 and I checked [Bintray](https://bintray.com/facebook/maven/com.facebook.flipper:fbjni) and that version is really not pushed.

Is there a workaround or can it be pushed any time soon?

**Comment by passy** [comment]
Our publishing step must have failed. I'll look into it. Thanks for reporting!

**Comment by pavlospt** [comment]
@passy indeed https://circleci.com/gh/facebook/flipper/370

**Comment by passy** [comment]
```
* What went wrong:

Execution failed for task ':bintrayPublish'.

> java.lang.NullPointerException (no error message)
```

WHY THANKS GRADLE!

I manually published a new artifact. I hope that solves it for you, @bojankoma!

**Comment by bojankoma** [comment]
Indeed it does help, thanks for looking into it.
I can confirm it's resolved now.
