### ISSUE TITLE
Network Plugin can't copy headers or request body

### ISSUE THREAD

**Issue by callmepeanut** [facebook/flipper#334]
I want copy the  Request Body, but right click only get an empty prompt, as show below.

![_ _20181127151946](https://user-images.githubusercontent.com/5306883/49065141-1d743900-f258-11e8-8366-f781cd0f550f.png)

**Comment by passy** [comment]
Thanks for the report. We're looking into it.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by eygraber** [comment]
I still have this issue

**Comment by kaciula** [comment]
@passy I am also having this issue. I need to copy-paste the response body so I can build my models. I am using a Mac.

**Comment by varunest** [comment]
Having the same issue. Using Mac

**Comment by binaryfork** [comment]
Would be nice to copy all headers from a request. For example add a button that copies all headers to the menu when you right click the request.
