### ISSUE TITLE
Version 0.130.0 stopped showing app connected (Android only)

### ISSUE THREAD

**Issue by olessavluk** [facebook/flipper#3362]
## 🐛 Bug Report

| 0.130.0 (broken) | 0.129.0 (working) |
| ------------- | ------------- |
| ![broken](https://olessavluk.s3.eu-central-1.amazonaws.com/s/2022-01-27-11-49-40/Screenshot%202022-01-27%20at%2011.47.07.png)  | ![working](https://olessavluk.s3.eu-central-1.amazonaws.com/s/2022-01-27-11-50-07/Screenshot%202022-01-27%20at%2011.46.12.png)  |

If I click device selector on top left corner - there is no app either.

## To Reproduce

1. Run metro
2. start app on device
3. open Flipper

**Comment by cekkaewnumchai** [comment]
Version 0.130 is currently in broken state. We're working on releasing a new version with addressing this issue. Please downgrade to version 0.129 in a meantime, if possible. Sorry for the inconveniece

**Comment by radzio** [comment]
@cekkaewnumchai  did 0.131.0 fix this issue?

**Comment by cekkaewnumchai** [comment]
Yes 0.131 fix the connection problem we have in 0.130.

**Comment by Gnative** [comment]
I'm started having this issue with IOS as well - just updated. Downgrading to 129.

**Comment by passy** [comment]
If there are still problems with the connection, that's a separate issue. The one tracked here was fixed with 0.131.

**Comment by Gnative** [comment]
Fair call @passy, thank you..
