### ISSUE TITLE
Conflict with other jetified JNI libc++_shared.so

### ISSUE THREAD

**Issue by hbmartin** [facebook/flipper#3368]
## 🐛 Bug Report
When trying to build an app with another JNI library, encountering an error about duplicates:

```
> 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
   - .../.gradle/caches/transforms-3/.../transformed/jetified-common-17.1.0/jni/arm64-v8a/libc++_shared.so
   - .../.gradle/caches/transforms-3/.../transformed/jetified-fbjni-0.3.0/jni/arm64-v8a/libc++_shared.so
```

## To Reproduce
Unfortunately, the other library is internal and proprietary. If that's blocking this issue then I can try to create an external demo. 

## Environment
Kotlin 1.5.32, Gradle 7.3.3, Android Gradle plugin 7.0.4

**Comment by passy** [comment]
Sometimes the `pickFirst` options can help but if that doesn't work out, sadly, the only option left is building some custom repacking like they did here: https://stackoverflow.com/questions/24314983/how-to-exclude-duplicate-c-shared-libraries-so-in-a-multi-project-android-bui
