### ISSUE TITLE
adb logs should have the option to preserve leading whitespace

### ISSUE THREAD

**Issue by vlazzle** [facebook/flipper#337]
There are uses cases of adb that use leading whitespace in logs to convey a tree structure. One example is [node tree debugging](https://developer.android.com/guide/topics/ui/accessibility/node-tree-debugging).

I'd love to use Flipper's awesome Logs view for this, but right now I can't because it strips leading whitespace, which makes it very difficult to read the logs as a tree structure.

This issue can be addressed by preserving leading whitespace in the log message column.

**Comment by jknoxville** [comment]
That sounds like a good idea. Here is the relevant code: https://github.com/facebook/flipper/blob/master/src/plugins/logs/index.js#L316

I don't know the original reason for trimming these log lines, and whether we can get away with just removing that, or if we'll need to add a toggle to switch it on/off.

Definitely if we had a toggle, perhaps next to the "Clear Logs" button it would be an improvement.

**Comment by bizzguy** [comment]
The "trim" method is no longer part of "processEntry".  So it appears that the log entries are not being trimmed.  There is now white space at the beginning of log entries (as shown in this screenshot)

![image](https://user-images.githubusercontent.com/337874/67234226-6140d580-f40a-11e9-8779-6635737d4013.png)

So it seems like this issue could be closed.  Unless it is really necessary to be able to turn whitespace trimming on, but I don't see the use for that.
