### ISSUE TITLE
When plugin can't be compiled, previous version of the plugin would be still rendered.

### ISSUE THREAD

**Issue by OleksiyA** [facebook/flipper#345]
Steps to reproduce:

- create custom Flipper plugin;
- launch Flipper host App (using yarn start);
- connect mobile App that have corresponding custom Flipper plugin client side code;
- edit JS source code for custom plugin introducing JS syntax error;
<here plugin will be re-compiled and in console would be message "is ignored, because it could not be compiled">
- observe that your plugin is reloaded in Flipper host App using previous version of JS code (without syntax error).

It would be more logical to not show such plugin in host app.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
