### ISSUE TITLE
Android SDK v0.134.0 was not published

### ISSUE THREAD

**Issue by quiro91** [facebook/flipper#3455]
## 🐛 Bug Report
The build for v0.134.0 for Android failed to published. More details here: https://github.com/facebook/flipper/actions/runs/1842020347

**Comment by passy** [comment]
Thanks for the issue, this went unnoticed because the part of the pipeline that was supposed to report these issues was the reason why it failed. @lblasa restarted it and I just confirmed that it's now on Maven.
