### ISSUE TITLE
Failed to initialize ADB

### ISSUE THREAD

**Issue by DariaRyazhskikhVeriff** [facebook/flipper#3458]
## 🐛 Bug Report
Flipper is not able to connect to adb saying `Command ""path/to/adb" version" failed to execute with output: Command failed: "path/to/adb" version rosetta error: /var/db/oah/223263137464320_223263137464320/bb7ee3c0ae7358287c11465763d64aa5a7a6c14bf62ff5d5663269e86c844055/adb.aot: attachment of code signature supplement failed: 1`

Log:
![image](https://user-images.githubusercontent.com/96418366/154860405-c9583715-c20b-44c7-9537-e8e40c14aed1.png)

ADB is definitely installed, I can execute this command from zsh:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/96418366/154860436-cee45856-c990-4ef2-b441-682e6852f885.png">

## To Reproduce
Just open Flipper.
It used to work on this computer. I don't use Flipper every day, so cannot say when exactly it stopped working.

## Environment
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 90.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh

**Comment by karen-sch** [comment]
Having the same problem, Flipper used to work and now it doesn't. I tried different versions (0.137.0, 0.136.0, 0.135.0) to no avail.

**Comment by karen-sch** [comment]
A restart of my mac fixed this issue for me 😅
