### ISSUE TITLE
How to use css files for custom plugins

### ISSUE THREAD

**Issue by OleksiyA** [facebook/flipper#346]
It is explained how to apply style to own React components. 

Interesting to know how to handle case where some third party React component is being used in Flipper plugin JS code, and that third party code have styles in css file. For example https://react-table.js.org/#/story/readme or https://github.com/reactjs/react-tabs . I am using styled-components as a workaround, this require wrapping each component and generally seems quite a bit of work comparing to referencing css file  from html.

**Comment by danielbuechele** [comment]
We want to avoid the use of CSS for the risk of interfering with any of Flipper's UI. This is why we strongly recommend using our Styled Components: https://fbflipper.com/docs/styling-components.html

However, I agree that there might be some edge-cases, where it makes sense to use a CSS file. For example 3rd-party libraries bringing their own CSS. That being said, for tables and tabs, you can use the components provided by Flipper. Have a look at all available UI components: https://fbflipper.com/docs/ui-components.html

An easy solution for using CSS would be to add a `<style>`-tag somewhere in your component.
