### ISSUE TITLE
Not Able To Expand Large Array 

### ISSUE THREAD

**Issue by BhuwaneshSisodia** [facebook/flipper#3475]
![image](https://user-images.githubusercontent.com/19169880/155459298-929d83f0-3d68-48d7-b55c-0ea8101be183.png)

**Comment by BhuwaneshSisodia** [comment]
@passy @nikoant ?? When will this issue get fixed ??

**Comment by passy** [comment]
Sorry but this is not a Flipper issue. This is part of the Hermes debugger it seems based on the screenshot?
