### ISSUE TITLE
Applications with NSURLProtocols show duplicate data in the Network Inspector

### ISSUE THREAD

**Issue by pkrmf** [facebook/flipper#348]
Applications that take advantage of `NSURLProtocol` to intercept their outgoing requests will cause Network Inspector to show duplicate responses.

When an application using `NSURLProtocol` executes a request, before that request goes out the door, it will get intercepted by the `NSURLProtocol`. If the `NSURLProtocol` decides to execute that request on behalf of the client, the `NSURLProtocol` itself will be responsible for getting the delegate callbacks and pass the data back to the client.

Since `FLEXNetworkObserver` uses the objective-c runtime to swizzle all the `NSURLSession` and `NSURLConnection` delegate classes in the application, when we get a response for a particular request, we will be communicate back that response to the Plugin in the `NSURLProtocol` and then on its client (the true `NSURLSession/NSURLConnection` delegate), causing that information to be displayed twice in Network Inspector's UI.

Possible solutions:

- Not swizzling `NSURLProtocol`. The downside is that we could potentially miss on responses that the `NSURLProtocol` doesn't pass down to the client(true delegate).

- Marking the source of the requests in the Network Inspector UI. We could show in the Network Inspector layout that a request was triggered by an `NSURLProtocol`. This wouldn't fix the issue of showing duplicate responses in the Network Inspector but it would show the "why". The downside is that not everyone working on the same codebase might know what `NSURLProtocol` is or does. 

- Keeping a Hashmap of request/response based on the identifier  and not sending the request to the Network Inspector Plugin until we receive the response. This way, we can identify the response that maps a particular request and send the pair to the Network Inspector Plugin together. Once the data is sent, we delete the entry from the Hashmap to avoid another delegate being swizzled and resending the same exact information.

Any better ideas?

**Comment by priteshrnandgaonkar** [comment]
Sorry for the delayed response. Thanks for reporting the bug. I think we can go ahead with the last option with a slight variation. I would still send the request to the Network Plugin, still maintain it in a hashmap and clearing it once we receive the response. Would be happy to have a PR around this.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by bradjones1** [comment]
I think I've run into this in an Expo "bare workflow" development build. Intercepting the requests on my local web server I am only seeing the requests with responses in the screencap below, but there are duplicate entries (the duplicate being the one with no response metadata.)

![Screenshot from 2022-04-01 12-55-46](https://user-images.githubusercontent.com/981966/161324810-cd09dd0a-85ea-41c2-8f3f-07452d39baa4.png)

@passy would you want to reopen this or does this appear to be different?

Sorry I'm not super helpful on other initial debugging data, electron apps are a bit foreign to me. But I'm pretty sure this is related?
