### ISSUE TITLE
Failed to start flipper-server

### ISSUE THREAD

**Issue by CorradiSebastian** [facebook/flipper#3543]
I'm doing a fresh install on mi Mac M1 laptop and I get this error:
**### Error: ENOENT: no such file or directory, mkdir '/Users/sebastian.corradi/.flipper/certs'**

and, if I go to the plugin manager, the plugin **flipper-plugin-kaios-big-allocations** instalation is failed with this essage: **Cannot read properties of undefined (reading 'prototype')**

thanks a lot

**Comment by passy** [comment]
Please follow the issue template so we can support you. Thanks!
