### ISSUE TITLE
Android Could not find flipper 0.139.0

### ISSUE THREAD

**Issue by ChoiHyeongu** [facebook/flipper#3548]
## 🐛 Bug Report

could not find flipper 0.139.0

<img width="648" alt="스크린샷 2022-03-17 16 21 49" src="https://user-images.githubusercontent.com/35494666/158757368-ddde6839-39bc-43fc-bb05-a0bba2eb4c6c.png">

cannot found 0.139.0 in https://repo.maven.apache.org/maven2/com/facebook/flipper/flipper/
<img width="971" alt="스크린샷 2022-03-17 16 24 16" src="https://user-images.githubusercontent.com/35494666/158757742-7504ea42-8290-4e7c-8a13-4895507a7ab2.png">

## To Reproduce
Set `FLIPPER_VERSION = 0.139.0`  and `npm run android`

## Environment
OS: Android / react-native 0.67.3
Flipper Desktop version: 0.139.0

**Comment by AmorimRob** [comment]
same here
