### ISSUE TITLE
Docs: 0.139.0 release notes missing in CHANGELOG.md

### ISSUE THREAD

**Issue by Arron-Gill** [facebook/flipper#3550]
see: https://github.com/facebook/flipper/blob/main/desktop/static/CHANGELOG.md
![image](https://user-images.githubusercontent.com/87369513/158801890-e10c9896-6e10-43cc-83a2-a51b7d422699.png)

**Comment by prithivraj** [comment]
It's also missing from maven central https://repo1.maven.org/maven2/com/facebook/flipper/flipper/

**Comment by aigoncharov** [comment]
@Arron-Gill thanks for the ping. Nothing to worry about. It just means we did not link any commits to the release.

**Comment by aigoncharov** [comment]
> It's also missing from maven central https://repo1.maven.org/maven2/com/facebook/flipper/flipper/

Thanks for the report! Fixed.
