### ISSUE TITLE
Update Xcode 13.3 leads to RSockets deprecated warning

### ISSUE THREAD

**Issue by uloco** [facebook/flipper#3552]
## 🐛 Bug Report

After updating Xcode to 13.3 I started getting this warning:
`RSockets are being deprecated at Flipper. Please, use the latest Flipper client in your app to migrate to WebSockets`

## Environment

iOS Simulator v15.4
Flipper desktop:  0.139.0
react-native-flipper version: 0.138.0
macOS: 12.3
Xcode 13.3

**Comment by lblasa** [comment]
Hi @uloco , we are in the process of deprecating rsocket within Flipper.

For a while now, both Android and iOS SDKs have been using plain web-sockets. Flipper Desktop still supports both. For clients using rsocket, we are showing that deprecation notice.

As mentioned, if you use a recent version the Flipper iOS or Android SDK, it will use web-sockets.

I believe, this may be an issue with React Native only as it may be using an older version of Flipper. I will double check with our samples though.

**Comment by aigoncharov** [comment]
@uloco how do you enable Flipper in your app? Could you try following [this guide](https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk) to pin the latest version of Flipper?

**Comment by alfredarcifa** [comment]
> @uloco how do you enable Flipper in your app? Could you try following [this guide](https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk) to pin the latest version of Flipper?

If I follow the guide, for pods I have an error:

[!] CocoaPods could not find compatible versions for pod "FlipperKit/FBDefines":
  In Podfile:
    FlipperKit/FBDefines (= 0.139.0)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit/FBDefines (= 0.139.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

I use `source 'https://github.com/CocoaPods/Specs'` on top of Pod file

**Comment by alfredarcifa** [comment]
@uloco now, with 0.138.0 I have this error when I tr y to inspect with Hermes Debugger:

hermes-chrome-inspector-conn (20): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

And in flipper I see this error:
Debugging connection was closed. Reason: Websocket disconnected...

**Comment by uloco** [comment]
I didn't get any error. But I reinstalled all node and pod dependencies afterwards...

**Comment by uloco** [comment]
I am also not using any specific folly version etc. I am on React Native 0.66.3 and this is in my podfile

```use_flipper!({'Flipper' => '0.138.0'})```

**Comment by alfredarcifa** [comment]
Ok, I use "react-native": "0.64.1" and in Pod file I have to specify Flipper-Folly > 2.6.10, otherwise I get an error.

**Comment by mjstelly** [comment]
We're using RN 0.63.3. Flipper displays that deprecation warning. In my podfile, I have `'Flipper-RSocket' => '> 1.4'`. How do I update to `web-socket` to resolve this issue?

**Comment by OptimusZhang** [comment]
Same problem.

**Comment by rubanraj54** [comment]
Same issue here.

I'm using the latest Flipper desktop and client, but still, it shows the deprecation warning.

**Comment by vuptt** [comment]
I'm facing the same issue. Any solution?

**Comment by lblasa** [comment]
For a few releases now, iOS and Android clients already have web-socket-only support. If you see the deprecation warning, please update those apps. 

Bear in mind, even if there's a warning, a connection should be established and Flipper should be usable.
