### ISSUE TITLE
Question: Got notification like `RSockets are being deprecated at Flipper.`

### ISSUE THREAD

**Issue by xstable** [facebook/flipper#3554]
Even if I do use the very last Version of Flipper, I got this error: 
![image](https://user-images.githubusercontent.com/1778068/159166296-e611a65a-32ab-49e2-abab-cf1869013f4e.png)

At my package.json (react-native) I have :     "react-native-flipper": "^0.138.0", which also seems to be the newest version for it. 

So, any Idea, why this error occur?

**Comment by alfredarcifa** [comment]
Same error.

**Comment by xstable** [comment]
@alfredarcifa thanks, but I don't yet use xcode. Issue is on android for now.

**Comment by aigoncharov** [comment]
@xstable could you attach your Flipper logs and your device logs? 
@lblasa do RN users have to do anything specific to enable WebSockets?

**Comment by lblasa** [comment]
Hi all, we are in the process of deprecating rsocket within Flipper. 

For a while now, both Android and iOS SDKs have been using plain web-sockets. Flipper Desktop still supports both. For clients using rsocket, we are showing that deprecation notice.

As mentioned, if you use a recent version the Flipper iOS or Android SDK, it will use web-sockets.

I believe, this may be an issue with React Native only as it may be using an older version of Flipper.

**Comment by aigoncharov** [comment]
@xstable how do you enable Flipper in your RN app? Could you try pinning the latest version of Flipper following [this guide](https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk)?

**Comment by xstable** [comment]
@aigoncharov I have this in package.json:
```
  "devDependencies": {
    ...
    "react-native-flipper": "^0.138.0",
    ...
}
```
In `gradle.properties` I had:  `FLIPPER_VERSION=0.99.0` (I've changed it to 0.139.0, but then I got this while trying to run:

> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.flipper:flipper:0.139.0.
     Searched in the following locations:
     .... /node_modules/react-native/android/com/facebook/flipper/flipper/0.139.0/flipper-0.139.0.pom
     
 This is what I have in my `app/build.gradle`:
 ```
 dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

 ```

**Comment by aigoncharov** [comment]
>  I've changed the FLIPPER_VERSION in gradle.properties to 0.138.0 and error disappears for now.

I believe this is the solution then, isn't it? It seems FLIPPER_VERSION should not be higher that `react-native-flipper`.

**Comment by sregg** [comment]
For iOS, `use_flipper!({ 'Flipper' => '0.149.0' })` in `Podfile` does the trick.

**Comment by silsergey** [comment]
According [Flipper docs](https://fbflipper.com/docs/getting-started/react-native/) to For react-native version => 0.69.0
1. Call `FlipperConfiguration.enabled` with a specific version in `ios/Podfile`, for `example: :flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.174.0' }),`.
2. Run pod install --repo-update in the ios directory.
