### ISSUE TITLE
0.139.0 not published consistently to npm/cocoapods(/others?)

### ISSUE THREAD

**Issue by notjosh** [facebook/flipper#3568]
Hiya 👋 

I was looking at #3550 and noticed a small discussion about 0.139.0 not being published to Maven (which was resolved in the thread).

It looks like there's no release for `react-native-flipper` on NPM (current is 0.138.0 [here](https://www.npmjs.com/package/react-native-flipper)), or CocoaPods (current is 0.138.0 for `Flipper` [here](https://github.com/CocoaPods/Specs/tree/master/Specs/a/e/a/Flipper) and `FlipperKit` [here](https://github.com/CocoaPods/Specs/tree/master/Specs/3/2/5/FlipperKit)).

I'm not sure if anything else is missing, but it looks like the deployment was inconsistent. Can we get someone to look into getting 0.139.0 out everywhere it should be?

Thanks!

**Comment by nikoant** [comment]
Closing as 0.140 was released after this issue opened
