### ISSUE TITLE
0.14.2 artifacts are missing on jCenter

### ISSUE THREAD

**Issue by sockeqwe** [facebook/flipper#365]
Hi, 
the android artifacts for latest version 0.14.2 are missing on jcenter. Are they not published yet or is there another issue somewhere in the CI & CD pipeline.

Thanks

**Comment by passy** [comment]
Sorry, that's on me. We had some issues with the CircleCI task and I meant to rerun them manually. I'll try to do that now, but if I can't get this done in time I may have to do this tomorrow.

**Comment by sockeqwe** [comment]
Thanks for the heads up

Pascal Hartig <notifications@github.com> schrieb am Di., 29. Jan. 2019,
17:45:

**Comment by passy** [comment]
The artifacts should now be available on Jcenter.

**Comment by sockeqwe** [comment]
Thanks!
