### ISSUE TITLE
FlipperOkhttpInterceptor causes java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by G00fY2** [facebook/flipper#3663]
## 🐛 Bug Report
The `FlipperOkhttpInterceptor` tries to clone the body of the response but does not check if the response buffer is actually open.
https://github.com/facebook/flipper/blob/c8deef607b3b73be104e30912b4b50b237362fda/android/plugins/network/src/main/java/com/facebook/flipper/plugins/network/FlipperOkhttpInterceptor.java#L150

But doing so will lead OkHttp to throw a IllegalStateException because of this check:
https://github.com/square/okio/blob/b0f78aaa46f4a251928a62c9adb44d90d4c34001/okio/src/commonMain/kotlin/okio/internal/RealBufferedSource.kt#L58

## To Reproduce
Add an interceptor that closes the response before the FlipperOkhttpInterceptor.

## Solution
```diff
-if (response.body() != null
-    && response.body().source() != null
-    && response.body().source().buffer() != null) {
+if (response.body() != null
+    && response.body().source() != null
+    && response.body().source().buffer() != null
+    && response.body().source().isOpen()) {
```

## Environment
Flipper 0.143.0
OkHttp 4.9.3
Android emulator API 31

**Comment by passy** [comment]
Thanks for the report. Would you be interested in contributing this as a pull request?

**Comment by G00fY2** [comment]
We further investigated this issue on our side and we noticed that the FlipperOkhttpInterceptor was actually not set as the last interceptor (I believe this is suggested somewhere in your docs and also makes sense to log the requests after all other interceptors modified it). After fixing the Interceptor order, this crash went away. So I believe there is no need to change the logic here.
