### ISSUE TITLE
flipper: Desktop failed to provide certificates

### ISSUE THREAD

**Issue by maxim-pandra** [facebook/flipper#367]
Only CPU, logs and crashreporter seem to work. Desktop app and console says:

> flipper: Desktop failed to provide certificates. Error from flipper desktop:
>     Disallowed app name in CSR: com.my.application_alpha. Only alphanumeric characters and '.' allowed.

<img width="202" alt="screenshot 2019-02-07 at 16 00 15" src="https://user-images.githubusercontent.com/9080415/52413060-8813e180-2af1-11e9-86e7-d055a8a0d311.png">
This small icon changes periodically to a loading indicator.

Is the problem really in application name? Or something wrong with configuration?

In CustomApplication onCreate()
   ```
         final FlipperClient client = AndroidFlipperClient.getInstance(this);
            client.addPlugin(new InspectorFlipperPlugin(this, DescriptorMapping.withDefaults()));

            final DescriptorMapping descriptorMapping = DescriptorMapping.withDefaults();
            client.addPlugin(new InspectorFlipperPlugin(getApplicationContext(), descriptorMapping));

            client.addPlugin(
                    new SharedPreferencesFlipperPlugin(getApplicationContext()));

            client.start();
```

**Comment by jknoxville** [comment]
Thanks for the report! This should fix it: #368 
I'll get it merged asap.

**Comment by jknoxville** [comment]
This should now be fixed for you if you run flipper desktop from source: https://github.com/facebook/flipper#running-from-source

The fix will be in the website download in the next release, which we do roughly once a week.

**Comment by lucasluca** [comment]
I got it working by installing open SSL via Chocolately

**Comment by lucasluca** [comment]
GOt this certificates working installing openSSL via chocolately

**Comment by mbrehme** [comment]
I have the same issue on mac, the "Doctor" says open ssl is installed correctly

**Comment by svcat** [comment]
Same issue here

**Comment by mweststrate** [comment]
Comments on closed issues are rarely seen by anybody, and typically don't result in any help. Please open a new issue if you want to report an issue. Only comment on closed issues with comments that are somehow helpful to people that find them through search, such as an alternative solution.

**Comment by belics99** [comment]
same issue
