### ISSUE TITLE
Plugins based on createTablePlugin never load

### ISSUE THREAD

**Issue by mrmans0n** [facebook/flipper#375]
Hi!

The company I work for has a couple of custom Flipper plugins, and 3 of them are based on createTablePlugin. They were working alright, but they stopped working around the 0.13.0 version and never worked again - as it's still broken as of 0.16.2.

I have created a tiny project with two simple plugins to showcase this: https://github.com/mrmans0n/flipper-createTablePlugins-borked-sample

In the [flipper-plugins](https://github.com/mrmans0n/flipper-createTablePlugins-borked-sample/tree/master/flipper-plugins) directory in that repo there are two plugins: table-example (createTablePlugin based) and normal-example. Their codes are straight from the samples in [fbflipper.com](https://fbflipper.com). The table one doesn't show on the list of plugins for the app, and the normal one does.

When opening Flipper, on the bottom left plugin status button, we can see how the normal plugin loads (and resolves the name from its title), and how the table plugin doesn't even resolve its name: it just has the directory name for the plugin but not its title.

![screenshot 2019-02-21 at 12 47 58](https://user-images.githubusercontent.com/534307/53170045-f4eda800-35d6-11e9-9d1c-764305527945.png)

It also doesn't show any seemingly relevant error in Flipper's developer console. 

I have searched for related bug reports but I didn't see any. 

Thanks!

**Comment by danielbuechele** [comment]
As per our discussion on Twitter we found the problem. The name in the plugin's `package.json` needs to match the ID used in native side of the plugin.
On the JS side, we moved away from using a static class property for the plugin ID and use the package name instead. Clarification on the docs is landing soon.
