### ISSUE TITLE
Plugin manager: empty install plugin tab

### ISSUE THREAD

**Issue by kirill3333** [facebook/flipper#3752]
## 🐛 Bug Report

The install plugin tab is always empty on my version. I've tried to reinstall the flipper and even build it from sources.
In console I see it

<img width="1273" alt="Screenshot 2022-05-25 at 15 11 27" src="https://user-images.githubusercontent.com/1804678/170249306-833c9b36-a4c4-4bb7-ae3b-60b36d8f453b.png">

<img width="974" alt="Screenshot 2022-05-25 at 15 25 23" src="https://user-images.githubusercontent.com/1804678/170251426-be6e7bf1-a4de-42a5-a227-bd6162f92d64.png">

When I build from sources I found this issue (TypeError: fetch is not a function)

![telegram-cloud-photo-size-2-5220009836475956077-y](https://user-images.githubusercontent.com/1804678/170246800-aafec5ab-ba17-4881-8d6a-b1654324f864.jpg)

## To Reproduce

Just install a clear version

## Environment

Flipper version: 0.146.1
MacOS: 12.4 (21F79)
Installed with brew

**Comment by berdyshev** [comment]
same issue with 0.147.0 and with installed from source code.

**Comment by berdyshev** [comment]
isn't it because of the marketplace URL configured as `http://plugin-marketplace.local/get-plugins`?

**Comment by r3nya** [comment]
> isn't it because of the marketplace URL configured as `http://plugin-marketplace.local/get-plugins`?

@berdyshev it's disabled to me but I can confirm this issue on 0.147.0 version as well

**Comment by girish-syfe** [comment]
Same issue

**Comment by adityawarrier** [comment]
+1
Facing this on v0.147.0

![Screenshot 2022-05-27 at 7 27 34 PM](https://user-images.githubusercontent.com/31214818/170714099-b065e228-a797-4336-bbc0-9e1df5b75d89.jpg)

**Comment by noelsp** [comment]
+1

**Comment by SmolinPavel** [comment]
+1

**Comment by CHANDARA-code** [comment]
@kirill3333 
if you down grade Flipper, that's work as normal or not brother?

**Comment by SmolinPavel** [comment]
@CHANDARA-code downgrading to 0.140 has worked for me 👍

**Comment by CHANDARA-code** [comment]
@SmolinPavel could you share document how to downgrade Flipper version please?

**Comment by SmolinPavel** [comment]
@CHANDARA-code I've used this link https://github.com/facebook/flipper/releases/tag/v0.140.0

**Comment by CHANDARA-code** [comment]
> @CHANDARA-code I've used this link https://github.com/facebook/flipper/releases/tag/v0.140.0

It's work ! thanks !

**Comment by aigoncharov** [comment]
Should be resolved in [0.147.1](https://github.com/facebook/flipper/releases/tag/v0.147.1).

**Comment by ZeeshanAhmadKhalil** [comment]
There is no loader when its searching plugins, it should show a loader to let us know if its searching or not
