### ISSUE TITLE
cannot search plugin in flipper version 0.147.0 on Ubuntu 22.04 

### ISSUE THREAD

**Issue by CHANDARA-code** [facebook/flipper#3761]
## 🐛 Bug Report

I cannot search plugin in flipper -v 0.147.0.
example: I've search redux in search box but there are no result .

## bug

![image](https://user-images.githubusercontent.com/63392557/170809331-62651ed8-c37f-4307-acc9-f642355faded.png)

![image](https://user-images.githubusercontent.com/63392557/170809353-26bb69ac-1636-4c3e-a064-0a4958cc752f.png)

## Environment

 ubuntu 22.04
 flipper -v 0.147.0
 debug on react-native

**Comment by CHANDARA-code** [comment]
@wiryallcserviceseducative 
sorry I don't get what you mean !
could you write in English please!
Thanks!

**Comment by kirill3333** [comment]
@CHANDARA-code the same issue https://github.com/facebook/flipper/issues/3752

**Comment by CHANDARA-code** [comment]
@kirill3333
Thank you brother!

**Comment by aigoncharov** [comment]
Duplicate #3752
