### ISSUE TITLE
The Chinese characters are garbled

### ISSUE THREAD

**Issue by lijy91** [facebook/flipper#380]
`atob` does not support decoding of non-English characters, I modified `atob` to `decodeURIComponent(escape(atob(container.data)));`, This may not be a good solution, but he solved the problem.

My PR: #377

**Comment by lijy91** [comment]
@priteshrnandgaonkar @danielbuechele  any update on this

**Comment by danielbuechele** [comment]
Hey, sorry for the slow response and thanks for your PR. I am importing it now!

**Comment by danielbuechele** [comment]
Landed in #377 
Thanks @lijy91
