### ISSUE TITLE
Getting white background while hovering over an object (dark  mode)

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [facebook/flipper#3805]
## 🐛 Bug Report

When hovering over any object in the response to network request or in the redux state, got white background which hides out all keys in the object since keys and background have the same colour. Please take a look at the following screenshot for a better understanding.

![image](https://user-images.githubusercontent.com/41861952/173108647-fdfffd0a-000a-4f5c-ba04-443122f68a8b.png)

## To Reproduce

Download the latest version of the flipper `0.149.0` and switch to the dark mode.

## Environment

Windows 10 OS
flipper 0.149.0

**Comment by ZeeshanAhmadKhalil** [comment]
I should use the older version for now. Don't know what to do if this persists in the upcoming versions as well.

**Comment by dennisdeng2002** [comment]
Agreed, quite annoying as dark mode user

**Comment by ZeeshanAhmadKhalil** [comment]
Still not resolved in `0.150.0`

**Comment by plwai** [comment]
Seems like dark mode is not handled in the `v0.149.0` hover feature.

https://github.com/facebook/flipper/blob/40e65901bd6191603248a0ec2b3d31b13ed42e26/desktop/flipper-plugin/src/ui/data-inspector/DataInspectorNode.tsx#L53

**Comment by ZeeshanAhmadKhalil** [comment]
Resolved in `0.158.0`
