### ISSUE TITLE
No device selected

### ISSUE THREAD

**Issue by franticn** [facebook/flipper#381]
os: macOS 10.14.3
Flipper:0.16.2
adb: 1.0.40

when i launch Flipper in my mac,i cant find any devices,but i can find these by use `adb devices -l`
![image](https://user-images.githubusercontent.com/21286570/53317895-5f208880-3908-11e9-95d7-5e024828d4f8.png)

![image](https://user-images.githubusercontent.com/21286570/53316966-bc1a3f80-3904-11e9-8408-4275a0a5b222.png)

and i can find these error by open `Developer tools` 

![image](https://user-images.githubusercontent.com/21286570/53317007-f08dfb80-3904-11e9-8505-a6131d652d76.png)

and i already set `ANDROID_HOME` in `.bash_profile`

![image](https://user-images.githubusercontent.com/21286570/53317046-1a472280-3905-11e9-8b63-f8e61655912d.png)

so please help me,ty!

**Comment by franticn** [comment]
I have already do these from `Getting Started`docs,e.g.,
- Add  permissions and `FlipperDiagnosticActivity ` to my `AndroidManifest.xml`
- Add the dependencies to `build.gradle` file
- Initialize`Flipper` in my `Application`

**Comment by franticn** [comment]
look like this `process.env.ANDROID_HOME` don't equals my `ANDROID_HOME` in `.bash_profile`
![image](https://user-images.githubusercontent.com/21286570/53326990-d31b5a80-3921-11e9-86ba-77c57e3e90cb.png)

why is this?

**Comment by pavlospt** [comment]
@franticn Could you search who might be exporting a value equal to `/opt/android/sdk` in your shell?

**Comment by franticn** [comment]
> @franticn Could you search who might be exporting a value equal to `/opt/android/sdk` in your shell?

Sorry,I didn't search anything about `/opt/android/sdk` in my shell

**Comment by jknoxville** [comment]
Hey @franticn thanks for the detailed report.

I believe the problem here is that when you launch a GUI application from finder or some launcher, the bash profile isn't picked up like it would be if you ran it from the command line.

You can test this by launching flipper from the command line instead of by clicking on an icon. In that case it should pick up your config. Can you confirm this works?

The reason it is set to /opt/... in the debugger is because if it's not set for the given process when flipper starts, then flipper sets it itself to a reasonable default, but this only happens if it's not already set.

We'll need to come up with a better solution for configurable SDK locations, maybe an entry in config.json would be the simplest way forward. For now you could try adding a symlink in /opt.

**Comment by franticn** [comment]
> 嘿@franticn感谢您的详细报告。
> 
> 我相信这里的问题是，当您从finder或某个启动器启动GUI应用程序时，bash配置文件不会像从命令行运行它时那样被拾取。
> 
> 您可以通过从命令行启动flipper而不是单击图标来测试它。在这种情况下，它应该拿起你的配置。你能证实这个有效吗？
> 
> 在调试器中将其设置为/ opt / ...的原因是因为如果在脚蹼启动时没有为给定进程设置它，则鳍状板将其自身设置为合理的默认值，但只有在尚未设置的情况下才会发生这种情况。
> 
> 我们需要为可配置的SDK位置提供更好的解决方案，也许config.json中的条目将是最简单的方法。现在您可以尝试在/ opt中添加符号链接。

As you say, I launch flipper form the command line then I can see `Launch Android emulators` and some emulators I used to created. But I still can't see my physical devices.

**Comment by franticn** [comment]
> Hey @franticn thanks for the detailed report.
> 
> I believe the problem here is that when you launch a GUI application from finder or some launcher, the bash profile isn't picked up like it would be if you ran it from the command line.
> 
> You can test this by launching flipper from the command line instead of by clicking on an icon. In that case it should pick up your config. Can you confirm this works?
> 
> The reason it is set to /opt/... in the debugger is because if it's not set for the given process when flipper starts, then flipper sets it itself to a reasonable default, but this only happens if it's not already set.
> 
> We'll need to come up with a better solution for configurable SDK locations, maybe an entry in config.json would be the simplest way forward. For now you could try adding a symlink in /opt.

I launch flipper form command line as you say,and its work, no errors in developer tools.But I only see `Launch Android emulators` and some emulators I used to created,I still can't see my physical devices even if these list in `adb devices`

**Comment by jaripekkala** [comment]
@franticn Hello! Did you ever get this resolved?

I'm having the exact same issue using https://github.com/blankapp/flutter_flipperkit

**Comment by franticn** [comment]
> @franticn Hello! Did you ever get this resolved? I'm having the exact same issue using https://github.com/blankapp/flutter_flipperkit
> 
> After running the application via terminal the next console output is
> ![Screen Shot 2019-07-03 at 12 20 00 PM](https://user-images.githubusercontent.com/10659247/60579978-e71e0f80-9d8c-11e9-808c-c32037793e32.png)

No! I using `Stetho` now

**Comment by jaripekkala** [comment]
Hey @jknoxville is there anything I can do to get this issue resolved? 

I can now launch Android emulators from Flipper. However the device doesn't show up in the same devices menu after the mobile app is ran.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by jbruchanov** [comment]
@passy 
Seems to be still issue on mac.
I have to run it from terminal, otherwise getting that `/opt/android_sdk`value as `ANDROID_HOME`

**Comment by passy** [comment]
@jbruchanov That'll be taken care of soon with a settings panel that @jknoxville is working on.
