### ISSUE TITLE
NPM publishing failing in GitHub Actions

### ISSUE THREAD

**Issue by notjosh** [facebook/flipper#3816]
Hiya 👋 

I've noticed the NPM publish action has been failing for a couple of weeks now (starting [here](https://github.com/facebook/flipper/runs/6598456090?check_suite_focus=true#step:7:128)), so the `react-native-flipper` and `js-flipper` packages aren't up to date.

It looks like an expired/invalid token. Any chance someone can update the credentials and re-publish a recent version?

Thanks!

**Comment by aigoncharov** [comment]
https://github.com/facebook/flipper/commit/41d7b2a307ad6d3a5efa8b5369b4d3e6cbe6a49e should fix it. We will release 0.150 soon which should trigger the publishing job.
