### ISSUE TITLE
Android documentation missing critical init section

### ISSUE THREAD

**Issue by ColtonIdle** [facebook/flipper#382]
I setup flipper for the first time for my Android app with reading through the docs. They were really helpful except that I kept getting a crash. After I looked it up, it looked like https://github.com/facebook/flipper/issues/36 is related. `SoLoader.init` method needs to be called, but as far as I can tell, this isn't called out anywhere in the docs. Also, init can be called with different parameters and I don't know which one should be called. From a new developer trying to use flipper point of view, I think this is a piece of critical information that should be outlined.

**Comment by jknoxville** [comment]
Thanks for the feedback, it's definitely good to hear where people are having trouble.

It's not very prominent but it's included in the sample code here: https://fbflipper.com/docs/getting-started.html#setup-your-android-app

That said, documentation is useless if people can't find it / don't notice it, do you have any suggestions of how we could make it more noticeable? Perhaps just adding a note to explicitly call it out?

Also, feel free to send in a PR if you want to improve the docs yourself. For documentation like this, you can do it directly within github's markdown editor.

**Comment by ColtonIdle** [comment]
I would recommend putting it on this page: https://fbflipper.com/docs/getting-started.html under "Setup your Android app". Currently it includes everything you need to know for setup, except this `Soloader.init()` call. Not sure if it's omitted on purpose.
