### ISSUE TITLE
https://www.npmjs.com/package/js-flipper not pointing to the latest version 0.149

### ISSUE THREAD

**Issue by devhanos5** [facebook/flipper#3821]
## 🐛 Bug Report

![Screenshot 2022-06-15 at 1 31 45 PM](https://user-images.githubusercontent.com/99954079/173921626-0ec3444f-8533-42ca-a239-0fe5b9238f06.png)

https://www.npmjs.com/package/js-flipper is not pointing to the latest version. The latest version is 0.149.0 but its pointing to 0.146.1.
Seems like, the publish actions are failing.

**Comment by aigoncharov** [comment]
Duplicate of #3816
