### ISSUE TITLE
Exception while trying to reload after Electron upgrade

### ISSUE THREAD

**Issue by mhrheaume** [facebook/flipper#3839]
## 🐛 Bug Report
After the upgrade to Electron in `92cdb810969480c892b906724b7db495bd9b4d0a` (https://github.com/facebook/flipper/commit/92cdb810969480c892b906724b7db495bd9b4d0a), the reload functionality no longer works. Reloading the application results in the following exception:
<img width="372" alt="exception" src="https://user-images.githubusercontent.com/1011148/174672436-5babe19c-b72f-4ca5-a840-bc335b87d7b1.png">

## To Reproduce
1. Open Flipper.
2. From the Menu Bar: View -> Reload (or Cmd+R).

## Environment
Flipper Desktop v.0.150.0

**Comment by mweststrate** [comment]
Closing as https://github.com/facebook/flipper/pull/3840 will be part of next weeks release. Thanks for reporting and apologies for late follow up!
