### ISSUE TITLE
Network Plugin - Response Body section isn't easily copy-able

### ISSUE THREAD

**Issue by ColtonIdle** [facebook/flipper#384]
The response body section in the network plugin is really useful, but I can't easily copy it. If someone selects that field, it should entirely highlight so you can cmd + c to copy it. I have the body set to "formatted" not "parsed", so I'm just trying to copy the raw json.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by ColtonIdle** [comment]
I believe the "Copy entire tree" option was added when you right-click the response body field now, so I would say this issue is good to close.

**Comment by kaciula** [comment]
@ColtonIdle I am using version 0.26 on a Mac. Right clicking on any of the request/response headers/bodies does not open anything for me. 

Not being able to copy-paste the response body is a real issue for me.

**Comment by anudeep3998** [comment]
@passy Like @ColtonIdle mentioned, the latest version doesn't have any option to copy paste the response/request.

**Comment by ColtonIdle** [comment]
I wish flipper had an easy way to copy request+response in one action. Chucker for Android does this and it's pretty awesome to quickly share with a team member.

**Comment by kurtzur** [comment]
I need this functionality as well. This is a real usability problem for me and I'm going to switch to a different tool than Flipper because of this.
