### ISSUE TITLE
Discussion: auto update feature

### ISSUE THREAD

**Issue by damsonFilipson** [facebook/flipper#3858]
Hi guys,
i noticed that you're updating flipper very often (which is great, and i'm grateful for that). The problem is that after every update it's necessary to download app again and again. I was wondering if there is some possibility to build in-app updating system? 
Cheers, Damian

**Comment by rasaha91** [comment]
On a somewhat related note, is there an option to disable the notifications that an update is available? Without getting into the details of it, engineers on our team have flipper available through an automated process and we don't want them manually updating.

**Comment by kenyee** [comment]
we're going to be doing the same thing as @rasaha91 (also curious how folks do this install of a specific version of Flipper/plugins and any gotchas).

I filed a separate issue about the disable of the update notification FYI: https://github.com/facebook/flipper/issues/3947

**Comment by rasaha91** [comment]
@kenyee we have a pipeline that is used to download the latest flipper app release for windows, along with the dependencies (openssl, watchman), and create a NuGet package that automatically gets pulled for each developer. This NuGet package also contains a script (flipper.cmd) that adds the watchman install to PATH and sets the OPENSSL_CONF environment variable. developers can then just launch flipper.cmd without having to do any additional setup (ANDROID_SDK_ROOT is already set on dev environments for us).

Similarly, we have a pipeline which downloads flipper plugins, as well as the transitive dependencies (we build in offline mode). We control which version of the app and client is available for developer environments.

**Comment by aigoncharov** [comment]
@rasaha91 thanks for sharing your process!
Internally, we have flipper-launcher that handles auto-updates, but it is tied to Meta's infra. We might adjust it to work with open-source distribution at some point, but it is not on the current roadmap.
We would encourage the community to create a third-party launcher to handle it and distribute it separately.
