### ISSUE TITLE
dependency.platforms.ios.project is not allowed on react-native 0.69

### ISSUE THREAD

**Issue by maykonmichel** [facebook/flipper#3859]
## 🐛 Bug Report

With [react-native 0.69 update](https://reactnative.dev/blog/2022/06/21/version-069#breaking-changes), the [RN CLI was upgraded to v8](https://github.com/facebook/react-native/pull/33610/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R97) which [removed](https://github.com/react-native-community/cli/pull/1537/files#diff-867a86af070dcc54ad750ed04ce12a9eca45b7356e888d140d7ec8219bbe0d4dL64) `dependency.platforms.ios.project`. This causes the following error when running `react-native start` and flipper doesn't connect to the app.

```bash
warn Package react-native-flipper has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.project" is not allowed

// Followed by

WARN  The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed as yarn dependency to your project and, for iOS, that `pod install` is run in the `ios` directory.
```

## To Reproduce

We can reproduce this bug on any project with `react-native` 0.69:
```
npx react-native init flipperBug
```

Then install `react-native-flipper` package:
```
yarn add -D react-native-flipper
```

And start `react-native` metro:
```
react-native start
```

## Proposed fix
Removing `react-native.config.js` fixes the problem, but it's a *breaking change* as it won't work with react-native CLI 4.2.2 as it will search for an xcode project.

## Environment

```json
"dependencies": {
  "react-native": "0.69.0"
},
"devDependencies": {
  "react-native-flipper": "^0.151.1"
}
```

**Comment by lyqht** [comment]
Getting same error after upgrading react native from 0.66 to 0.69, and upgrading flipper from 0.75 to 0.151

```
> npx react-native android
warn Package react-native-flipper has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.project" is not allowed
error Unrecognized command "android". Did you mean "log-android"?
info Run "react-native --help" to see a list of all available commands.
```

**Comment by codedevstem** [comment]
Confirmed fix works. Using react-native-cli version 8.0.2 and it works as expected
Merge and version release would be awesome

**Comment by maykonmichel** [comment]
While we don't get this fixed, I managed to work around it with some resolutions in `package.json`:

```json
"resolutions": {
    "@types/react": "^18",
    "@react-native-community/cli": "^7.0.3",
    "@react-native-community/cli-platform-android": "^7.0.1",
    "@react-native-community/cli-platform-ios": "^7.0.1"
  },
```

**Comment by swrobel** [comment]
I don't understand how this isn't annoying to the maintainers. Please just merge @maykonmichel's PR!
