### ISSUE TITLE
react-native + flipper - Program type already present: com.facebook.jni.CppException

### ISSUE THREAD

**Issue by nihaux** [facebook/flipper#386]
Hello just starting with react-native and was trying to add flipper.
when i add 
```
    debugImplementation('com.facebook.flipper:flipper:0.16.2')
```
to my gradle.build
I get when running `react-native run-android`
```
Execution failed for task ':app:mergeExtDexDebug'.
[...]
 Program type already present: com.facebook.jni.CppException
```
I did some searching and tried to exclude fbjni from flipper
```
    debugImplementation('com.facebook.flipper:flipper:0.16.2') {
      exclude module: 'com.facebook.flipper:fbjni:0.16.2'
    }
```
tried different variant (not a java dev so kinda lost when it comes to building tools ^^)
```
      exclude group: 'com.facebook.flipper', module: 'fbjni:0.16.2'
      exclude group: 'com.facebook.flipper', module: 'fbjni'
```
In android studio, the only place I can found the CppException class is:
![capture d ecran 2019-03-02 a 19 58 47](https://user-images.githubusercontent.com/3429327/53686323-ccc41e80-3d25-11e9-806d-4517610aa693.jpg)

tried to debug with:
```
./gradlew :app:dependencies
```
It seems that the only deps it founds is from flipper.

Running out of ideas, any help is appreciated :)

**Comment by passy** [comment]
That's strange. You definitely tried the things I would have recommended.

Perhaps a silly thing to ask, but does this stop happening if you remove the Flipper dependency?
And assuming that it doesn't, would it be possible to share the `:app:dependencies` output?

**Comment by nihaux** [comment]
Hello, yes it stops when I remove the flipper dependency.  
I rerun the :app:dependencies, [here](https://pastebin.com/CHyVF7cR) is the pastbin to it.  
From what I see the task `debugAndroidTestRuntimeClasspath` contains 2 times the dependency to `com.facebook.flipper:fbjni:0.16.2`, one under `com.facebook.flipper:flipper:0.16.2` and one under directly attached to `debugAndroidTestRuntimeClasspath` but maybe that's normal ?

**Comment by nihaux** [comment]
So I made it work, don't really know what i did differently from the first time...
For those in the same case, final config is:
```
 debugImplementation ('com.facebook.flipper:flipper:0.16.2') {
        exclude group: 'com.facebook.flipper', module: 'fbjni'
        exclude group: 'com.facebook.yoga', module:'yoga'
    }
```
Had to exclude yoga too for the same reason.
Thx @passy for the help.
Edit: hum during the process of trying different things, I cleared the gradle cache with rm -rf ~/.gradle/caches/* maybe that did the trick...
