### ISSUE TITLE
Question: Connection to app on iPhone failed even if Doctor is all green

### ISSUE THREAD

**Issue by dani-z** [facebook/flipper#3931]
Hi everyone 👋 

I started having a weird issue that stops me from debugging on a real device. This happened right after I updated to the latest Flipper version but after spending some time debugging it and downgrading to a previous version I realised it is still happening :(
So not really sure what the issue is, Doctor setup is all green and all.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/394966/180482908-bd894ac0-053e-4414-b78c-b3f915ddaeec.png">

Any help is much appreciated.

Thanks

**Comment by LukeDefeo** [comment]
Hey which version of flipper are you running

**Comment by dani-z** [comment]
Hi @LukeDefeo 
Thanks for your response! I think the issue is being caused by a recent update on a 3rd party library. After downgrading that to the previous version it all works well. So not related to Flipper.
Thanks again.
