### ISSUE TITLE
Version 0.17.0 is crashing

### ISSUE THREAD

**Issue by vkalmath** [facebook/flipper#394]
Not able to see network logs on version 0.17.0 on Mac, in earlier version was able to see the complete logs for network.
<img width="1681" alt="screen shot 2019-03-06 at 11 24 08 am" src="https://user-images.githubusercontent.com/16566323/53907831-db028b00-4002-11e9-8adf-e79e312ef59b.png">

**Comment by jschear** [comment]
I'm also encountering this. Perhaps related to this recent change? https://github.com/facebook/flipper/pull/377

**Comment by passy** [comment]
https://github.com/facebook/flipper/commit/2c05fdf347e6e5e3571623fd456db531dd19feae fixes this. We're releasing a new version today that includes the commit. Thanks for the report!
