### ISSUE TITLE
Getting started page "Page not found!

### ISSUE THREAD

**Issue by andresarezo** [facebook/flipper#3946]
Hi,

Im triying to navigate from the app that is installed and running in a macbook pro SO Monterrey version 12.5 to this page 

https://fbflipper.com/docs/getting-started/index
<img width="1273" alt="Captura de Pantalla 2022-07-28 a la(s) 11 38 03" src="https://user-images.githubusercontent.com/9295656/181565749-d38c9d24-7963-4a2c-a5fe-6628f31418f8.png">

But is saying me that the page is not found.

Please see attached screenshoot about the issue.

Have a nice great day!

**Comment by LukeDefeo** [comment]
Thanks for pointing this out, I assume you got to this from the README.md? Fix will be out shortly, in the mean time you can use https://fbflipper.com/docs/getting-started
