### ISSUE TITLE
Discussion: Feature request - add a config flag to disable the "new update available" check

### ISSUE THREAD

**Issue by kenyee** [facebook/flipper#3947]
Use case: updates to Flipper sometimes break plugins.
We'd like to lock our devs' version of flipper and the plugins to a specific version.

Please add a configurable (via some text file in a known location) flag that would let us disable this update check.

**Comment by rasaha91** [comment]
For my organization's use case, it might be preferable to expose this as a command line flag (e.g. `--no-update-notifications`).

**Comment by kenyee** [comment]
Was looking at the .flipper/config.json file and noticed an "updaterEnabled" flag and got excited:
```
{"pluginPaths":[],"disabledPlugins":[],"darkMode":"light","updaterEnabled":true,"launcherEnabled":true,"lastWindowPosition":{"x":328,"y":38,"width":1400,"height":994}}
```

Only to find that nothing in the code does anything w/ this flag...searching github only shows this file using "updaterEnabled":
https://github.com/facebook/flipper/blob/b4fc108c2e303deb4488b07a4332fa916c85ddc4/desktop/static/setup.tsx

**Comment by kenyee** [comment]
Tried setting this updaterEnabled flag to false when starting Flipper 0.156.0 and it autoprompted anyways :-(

Seems like the updater plugin doesn't read this config flag like it should...

**Comment by kenyee** [comment]
was going to have a go at trying to fix this, but the Flipper desktop app doesn't seem to run when I check out this repo and follow the directions: https://github.com/facebook/flipper/issues/3988

**Comment by kenyee** [comment]
hmm...there's also a --no-updater flag, but it's probably for the Electron framework: https://www.electronjs.org/docs/latest/tutorial/updates

**Comment by kenyee** [comment]
Going to add a "notifyUpdateAvailable" flag for config.json.  The existing updaterEnabled flag might have been used for autoupdates?  No code seems to use it though.
When configuring the config.json, it's probably safer to set both these flags to false in case the updaterEnabled flag ever gets enabled.

**Comment by kenyee** [comment]
renamed flag to suppressPluginUpdateNotifications FYI

**Comment by aigoncharov** [comment]
Should be resolved by https://github.com/facebook/flipper/pull/3992
