### ISSUE TITLE
iOS sample has no workspace file and get an error while pod install

### ISSUE THREAD

**Issue by OuterCloud** [facebook/flipper#3949]
## 🐛 Bug Report

The picture below is the content in README
<img width="456" alt="image" src="https://user-images.githubusercontent.com/16227179/181781545-984d961b-3508-44a6-90a6-cecb051aa970.png">

But there is no workspace file under iOS/Sample directory
<img width="851" alt="image" src="https://user-images.githubusercontent.com/16227179/181781884-29177bc8-c393-4626-be4d-bd84042b9f57.png">

And when I execute the command "pod install" or "pod install --repo-update", it comes to be an error
<img width="742" alt="image" src="https://user-images.githubusercontent.com/16227179/181782368-748fee33-eb0e-46ff-ab23-7ac910e46d4a.png">

## To Reproduce

The info in Bug Report above is enough.

## Environment

MacBook Pro Apple M1
MacOS Monterey

**Comment by LukeDefeo** [comment]
The workspace file is generated by cocoapods after pod install. 

Looking at your output it is suggesting you add it. This should work

`pod repo add facebook-flipper https://github.com/facebook/flipper.git`

**Comment by OuterCloud** [comment]
Thank you very much, Luke, nice to meet you.

**Comment by LukeDefeo** [comment]
Im going to assume this means it has resolved your issue, good luck

**Comment by OuterCloud** [comment]
> Im going to assume this means it has resolved your issue, good luck

<img width="891" alt="image" src="https://user-images.githubusercontent.com/16227179/182568613-cff4f663-766d-4b47-b9de-3ae3f858ed90.png">
Execuse me, where is the file above? I didn't find the podspec files above with the path like "../../xxx.podspec"

**Comment by OuterCloud** [comment]
After I change the source to be
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
in Podfile
I can pod install the iOS/Sample successfully and I can build successfully
