### ISSUE TITLE
Flipper plugin hot reload when creating a new desktop plugin

### ISSUE THREAD

**Issue by khushal87** [facebook/flipper#3963]
Hello team,

I am creating a desktop plugin to debug my React Native application. Basically, when I change the code of the plugin locally, my plugin doesn’t hot reload in the Flipper desktop app(even if I am running `yarn watch`) and I have to close and reopen the app entirely to see the changes, is there a way I can hot reload the changes as they are done with the code?

PS: The changes done to HTML etc are only seen once I close and reload the Flipper application.

**Comment by LukeDefeo** [comment]
You should use `yarn start` to run run the development build of flipper, you can add --fast-refresh to avoid a full reload too.

Can you share a repo showing your plugin as it is and so can help some more

**Comment by khushal87** [comment]
Hey @LukeDefeo, I don't think there's a yarn start command in the scripts of the plugin:

```
"scripts": {
    "lint": "flipper-pkg lint",
    "prepack": "flipper-pkg lint && flipper-pkg bundle",
    "build": "flipper-pkg bundle",
    "watch": "flipper-pkg bundle --watch",
    "test": "jest --no-watchman"
  },
```

**Comment by khushal87** [comment]
Okay, this is only possible with flipper from the source and not from the application available as a download from the flipper website. Thanks.

**Comment by aeroxy** [comment]
Actually even with current main branch from source (commit a9fe38107670eded3d4f542c122a9346cb7a644a) I am not able to get HMR working...should I add addition flags besides using `yarn start` on my flipper source project?

**Comment by khushal87** [comment]
Try `yarn start --fast-refresh` and it should work @aeroxy
