### ISSUE TITLE
Dynamically loading plugin can't working on latest build?

### ISSUE THREAD

**Issue by lijy91** [facebook/flipper#398]
I can't use a custom plugin for latest build, I can only use the dynamic load plugin on the dev version.

My plugin: https://github.com/blankapp/flipper-plugin-reduxinspector

**Comment by passy** [comment]
Can you explain your steps and where things stopped working?

**Comment by lijy91** [comment]
Create a directory `~/flipper-plugins`

```
$ mkdir ~/flipper-plugins
$ cd ~/flipper-plugins
```

Clone the plugin to this directory

```
$ git clone --depth 1 --single-branch --branch master https://github.com/blankapp/flipper-plugin-reduxinspector.git
```

Remove all cached plugins

```
~/.flipper/plugins
```

Add the path to `~/.flipper/config.json`

```diff
{
    "pluginPaths": [
+      "~/flipper-plugins"
    ],
    "disabledPlugins": [],
    "lastWindowPosition": {
        "x": 0,
        "y": 23,
        "width": 1680,
        "height": 947
    },
    "updaterEnabled": true
}
```

Now Run Flipper(latest build), but can't build and load custom plugins.

**Comment by lijy91** [comment]
@passy any news?

**Comment by danielbuechele** [comment]
Hey @lijy91 I was able to see you plugin in the latest release of Flipper (0.19.0). You setup looks correct. 

Can you try launching Flipper from the command line like this `/Applications/Flipper.app/Contents/MacOS/Flipper` This should give us some logs on the command line that might be helpful. When removing `~/.flipper/plugins`. Is a new file for the plugin created once you start the app? When clicking on "Plugin not showing" on the bottom of the sidebar, is you plugin listed there?

**Comment by lijy91** [comment]
When I restart my computer, launching Flipper in the terminal, everything is ok. But when I launching Flipper at the launch pad, the plugin will not show up, launching again through the terminal, show compilation error

first launching on terminal,
```
➜  ~ rm -rf .flipper/plugins
➜  ~ /Applications/Flipper.app/Contents/MacOS/Flipper
🕵️‍  Watching for plugin changes
⚙️  Compiling flipper-plugin-dbbrowser...
Writing bundle output to: /Users/lijy91/.flipper/plugins/flipper-plugin-dbbrowser@1.0.0.js
Writing sourcemap output to: /Users/lijy91/.flipper/plugins/flipper-plugin-dbbrowser@1.0.0.map
Done writing bundle output
Done writing sourcemap output
⚙️  Compiling flipper-plugin-reduxinspector...
Writing bundle output to: /Users/lijy91/.flipper/plugins/flipper-plugin-reduxinspector@1.0.0.js
Writing sourcemap output to: /Users/lijy91/.flipper/plugins/flipper-plugin-reduxinspector@1.0.0.map
Done writing bundle output
Done writing sourcemap output
✅  Compiled all plugins.
2019-04-02 18:45:02.541 Flipper[705:8424] *** WARNING: Textured window <AtomNSWindow: 0x7f85f7493840> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

once again launching on terminal (Removed the custom plugin directory and launched it through the launchpad before)
```
➜  ~ rm -rf .flipper/plugins
➜  ~ /Applications/Flipper.app/Contents/MacOS/Flipper
🕵️‍  Watching for plugin changes
⚙️  Compiling flipper-plugin-dbbrowser...
❌  Plugin flipper-plugin-dbbrowser is ignored, because it could not be compiled.
ReferenceError: SHA-1 for file /Users/lijy91/Projects/flipper-plugins/flipper-plugin-dbbrowser/index.js is not computed
    at DependencyGraph.getSha1 (/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/node-haste/DependencyGraph.js:201:13)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:164:26
    at Generator.next (<anonymous>)
    at step (/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:31:30)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:50:14
    at new Promise (<anonymous>)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:28:12
    at Transformer.transformFile (/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:188:7)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/Bundler.js:78:34
    at Generator.next (<anonymous>)
⚙️  Compiling flipper-plugin-reduxinspector...
❌  Plugin flipper-plugin-reduxinspector is ignored, because it could not be compiled.
ReferenceError: SHA-1 for file /Users/lijy91/Projects/flipper-plugins/flipper-plugin-reduxinspector/index.js is not computed
    at DependencyGraph.getSha1 (/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/node-haste/DependencyGraph.js:201:13)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:164:26
    at Generator.next (<anonymous>)
    at step (/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:31:30)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:50:14
    at new Promise (<anonymous>)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:28:12
    at Transformer.transformFile (/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/DeltaBundler/Transformer.js:188:7)
    at /Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/Bundler.js:78:34
    at Generator.next (<anonymous>)
✅  Compiled all plugins.
2019-04-02 18:47:39.332 Flipper[1068:13904] *** WARNING: Textured window <AtomNSWindow: 0x7f89fff54590> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

```

**Comment by lijy91** [comment]
When I run watchman watch-del-all, the compilation error will disappear. But when I launching Flipper at the launch pad Error occurs again.

**Comment by danielbuechele** [comment]
I am able to reproduce the plugins not being loaded. I wasn't yet able to reproduce the `ReferenceError: SHA-1 for file` errors you are seeing.

What works:
- `open /Applications/Flipper.app/`
- `/Applications/Flipper.app/Contents/MacOS/Flipper`

What doesn't work:
- Double click in Finder
- Spotlight
- Launchpad

**Comment by lijy91** [comment]
My steps:

1. Delete the plugin directory after restarting the computer
2. Run flipper from the launch pad
3. Delete the plugin directory again
4. Run flipper from the terminal

**Comment by danielbuechele** [comment]
Can you edit this file: `/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/node-haste/DependencyGraph.js` in line 200 to manually calculate the SHA1, if we don't have one like this and then try to reopen Flipper and see if that fixes the problem:

```
    if (!sha1) {
      return getFileHash(resolvedPath)
      function getFileHash(file) {
        return require('crypto')
          .createHash('sha1')
          .update(fs.readFileSync(file))
          .digest('hex')
      }
    }
```

**Comment by danielbuechele** [comment]
This might be the underlaying issue: https://github.com/facebook/metro/issues/330

**Comment by lijy91** [comment]
> Can you edit this file: `/Applications/Flipper.app/Contents/Resources/app/node_modules/metro/src/node-haste/DependencyGraph.js` in line 200 to manually calculate the SHA1, if we don't have one like this and then try to reopen Flipper and see if that fixes the problem:

Compile error has been resolved, But launching Flipper from the launch pad still can't load the custome plugin.

**Comment by lijy91** [comment]
@danielbuechele any news?

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
