### ISSUE TITLE
Discussion: Update flipper within the app itself?

### ISSUE THREAD

**Issue by moulie415** [facebook/flipper#3986]
Its kind of annoying having to re-download the flipper every time there's an update would it not be possible just to have it update within itself? Its especially annoying on my windows machine less so on my mac

**Comment by aigoncharov** [comment]
Internally, we have `flipper-launcher` that handles auto-updates, but it is tied to Meta's infra. We might adjust it to work with open-source distribution at some point, but it is not on the current roadmap.
We would encourage the community to create a third-party launcher to handle it and distribute it separately.
