### ISSUE TITLE
Does flipper support Kotlin extensions?

### ISSUE THREAD

**Issue by ljfantin** [facebook/flipper#399]
I'm using kotlin extesions in my project to reemplace findViewById by import kotlinx.android.synthetic.

Then I've added flipper configuration and the the project is not compile with flipper, it has errors with kotlinx.android.synthetic

Error:
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:

**Comment by passy** [comment]
Hey @ljfantin, thanks for the bug report but that's not enough information for us to work with. Can you provide some more information and ideally a test project for this?

**Comment by ljfantin** [comment]
Hi @passy, thanks for reply soon.

Kotlin Android Extensions are another Kotlin plugin that is included in the regular one, and that will allow recovering views from Activities, Fragments, and Views in an amazing seamless way. The plugin will generate some extra code that will allow you to access views in the layout XML, just as if they were properties with the name of the id you used in the layout definition.

We've added:

```
apply plugin: 'kotlin-android-extensions'

androidExtensions {
    experimental = true
}

```
Then We try to access to the ids generated, we get the error message: **Unresolved reference. None of the following candidates** ...

This error appears since We've added flipper configuration

Official link documentation
https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding

**Comment by passy** [comment]
That sounds to me like a bug in the `kotlin-android-extensions` plugin. At the very least, the error message does not seem particularly helpful. At least just with this, I'm not quite sure what we could do on our end.

**Comment by pavlospt** [comment]
@ljfantin are you experiencing this issue only when you add Flipper's dependencies or without them as well?

**Comment by ljfantin** [comment]
Hi @pavlospt, this issue happens since I added Flipper to my project

**Comment by pavlospt** [comment]
@ljfantin could you share your `build.gradle` file or any relevant code? Even better would be a sample project if you have the time :)

**Comment by ljfantin** [comment]
@passy @pavlospt I created an hello world project with flipper configuration and Kotlin extensions and the project works.
My project still having the error :(  but probably is not by flipper
I close the issue. 
Thanks all

**Comment by passy** [comment]
Glad it worked out and thanks for chiming in, @pavlospt! :)

**Comment by alxrm** [comment]
Same problem

**Comment by alxrm** [comment]
@ljfantin the reason was because of androidx, if you try to use 0.16.2 version(the latest one without androidx) it'll work
