### ISSUE TITLE
No File menu for the Share Flipper Data feature

### ISSUE THREAD

**Issue by qichuan** [facebook/flipper#401]
I noticed that there is a new `Share Flipper Data` mentioned in doc [page](https://fbflipper.com/docs/share-flipper-data.html), and I am glad that Flipper team finally add it in. 

However, after upgrading Flipper to the latest 0.18.0, I do not see the File menu that suppose to contain the Share Flipper Data feature, and the shortcut ⌘E does not work as well.

![Screen Shot 2019-03-25 at 5 57 57 PM](https://user-images.githubusercontent.com/410850/54910852-20dab100-4f28-11e9-8d00-53406038f675.png)

**Comment by passy** [comment]
@priteshrnandgaonkar Should 0.18.0 include this?

**Comment by priteshrnandgaonkar** [comment]
No, its not released yet. I will make a new release.

**Comment by qichuan** [comment]
It is in 0.19.0, close issue.
