### ISSUE TITLE
Flipper support on iOS enterprise signed/deployment app

### ISSUE THREAD

**Issue by renchiyansc** [facebook/flipper#4012]
## 🐛 Bug Report
From local test, seems Flipper does not work out of the box for iOS enterprise signed/deployment app (and the idb that flipper use also claims the same thing on their readme). Flipper works perfectly with same app but with development signed/deployment.
<img width="1658" alt="Screen Shot 2022-08-18 at 5 06 03 PM" src="https://user-images.githubusercontent.com/13026619/185515514-6cd98209-6978-4135-9c69-40f6f61c2132.png">
<img width="344" alt="Screen Shot 2022-08-18 at 5 05 46 PM" src="https://user-images.githubusercontent.com/13026619/185515518-c8a677f7-86fc-4588-819a-19de3edf74c9.png">

## Past discussion
Checking past issues, I noticed this comment
https://github.com/facebook/flipper/issues/1942#issuecomment-785147105
around we need to implement our own FlipperKitCertificateProvider that is introduced by this commit https://github.com/facebook/flipper/commit/293de19c2bdf65e2489fec72144dd7beaef43203

## Question
I could not connect the dot on how to use FlipperKitCertificateProvider. Is it possible provide more instruction on how to implement the FlipperKitCertificateProvider, what cert do we need for flipper to work with iOS enterprise signed app?  Or if there is easy to to just use non secure connection (if we have other layer protections) https://github.sc-corp.net/Snapchat/flipper/blob/main/xplat/Flipper/FlipperConnectionManagerImpl.cpp#L236

Any comment and feedback are appreciated! Thanks

**Comment by renchiyansc** [comment]
For example, do we need to 
1. switch the CertificateExchangeMedium to www (since seems we cannot access files on enterprise signed app)
2. Load the csr into memory
3. ...

**Comment by renchiyansc** [comment]
cc @priteshrnandgaonkar @jknoxville @aigoncharov @passy

**Comment by zdl51go** [comment]
> cc @priteshrnandgaonkar @jknoxville @aigoncharov @passy Any comment and feedback is appreciated

So, what's the final solution ...
