### ISSUE TITLE
CMD + K - no longer clears logs

### ISSUE THREAD

**Issue by Gnative** [facebook/flipper#4027]
## 🐛 Bug Report
CMD + K - no longer clears logs, it use to previous to 0.160.0 versions

## To Reproduce
Pressing CMD + K when on a log screen

## Environment
Mac OSX 12.5
Macbook 16 Intel
Flipper 0.162.0

**Comment by aigoncharov** [comment]
it changed to `ctrl+l` in https://www.internalfb.com/phabricator/commit/FBS/0a85b930faaa0e9468d5391f15092aad7b6057ee
