### ISSUE TITLE
Hide plugin: Headless-demo

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#4045]
Currently the Flipper will show this plugin to all connected devices: 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/5339061/187824018-7ba6ecde-1769-4698-89b3-1449fe5355f8.png">

Would it be possible to scope this plugin, so it stays relevant for demo purposes, but doesn't show to any device?

https://github.com/facebook/flipper/blob/95af1428ce720101d76e33427608c449ff0846df/desktop/examples/headless-demo/package.json#L2

**Comment by aigoncharov** [comment]
The idea was to keep in Flipper all the time to spark curiosity about what it means to run Flipper in a headless mode. Could you elaborate on your concerns with keeping it there?

**Comment by usrbowe** [comment]
Oh, I thought it was there by accident. Then no concerns.

Which brings me to another idea. We could have some introduction screen for disabled/unavailable plugins.
Instead of showing: 
<img width="425" alt="image" src="https://user-images.githubusercontent.com/5339061/191523614-4cf5f29c-7e00-4533-b6f8-29d6a12ebb76.png">
or
<img width="296" alt="image" src="https://user-images.githubusercontent.com/5339061/191523657-85e12004-9ac6-4c8e-b5f9-4b56d917d5ad.png">

We could try load the `README.md` or any other details of plugin to provide more context. This could be also used for headless demo plugin, which could show its README and later some links to guide the users to explore what is the headless mode of Flipper.

**Comment by aigoncharov** [comment]
@usrbowe good idea! For unavailable plugins, we could potentially parse the list of supported devices/OSes and show it there
