### ISSUE TITLE
https://fbflipper.com/ can't download

### ISSUE THREAD

**Issue by yanqing1226** [facebook/flipper#405]

**Comment by yanqing1226** [comment]
https://fbflipper.com/docs/getting-started.html#desktop-app  also can't load

**Comment by jknoxville** [comment]
Are you accessing it from China by any chance? We got a similar report in the past ( #249 ) when we moved to GitHub pages, and we don't have any current plans to change this unfortunately.

Please reopen if that isn't the case.
