### ISSUE TITLE
Copy as cURL and other network options

### ISSUE THREAD

**Issue by martynhaigh** [facebook/flipper#406]
Would be great to implement stetho style 'Copy as cURL' and other options

<img width="251" alt="image" src="https://user-images.githubusercontent.com/155352/55504812-89710e80-5649-11e9-99d3-4f2360b4d69c.png">

**Comment by passy** [comment]
Yes, totally! We've heard that a few times and I agree that this would be handy. Thanks for raising this! By the way, if someone wants to look into this as a pull request, please let us know. :)
