### ISSUE TITLE
Flipper disconnection - reconnection loop 

### ISSUE THREAD

**Issue by PierroD** [facebook/flipper#4067]
## 🐛 Bug Report

  When I enable flipper on a physical android device, Flipper keep refreshing itself.
 While refreshing it errased all the Network requests, logs, and more... 
Under the device name there is a red message popping for few milliseconds `APPLICATION_DISCONNECTED`
In the Flipper's logs there is a message telling us that a connection loop is detected.
![image](https://user-images.githubusercontent.com/40763427/188836990-ba938bed-0c34-4388-9b47-a0fa01cb562b.png)

## To Reproduce
  - Get a react-native app
  - run metro with the following command : `yarn start --reset-cache`
  - open react-native, api's and flipper's ports : `adb reverse tcp:{port} tcp:{port}`
  - refresh the app once
  - and flipper might started to blink

## Environment

- OnePlus 7Pro under Android 11
-   React-native : 0.68.2
- Flipper : 0.162.0,
- OS : ZorinOs (ubuntu distro latest version)

**Comment by spectrl** [comment]
Was there a resolution to this? Same thing is happening on my OnePlus 5 with the latest versions of Flipper. It's currently running Android 13 on Lineage OS, but I also had the same issue when it was running Android 10 on the official Oxygen OS.

**Comment by praweshlamsal** [comment]
Has anyone found the fix i am also facing the similar issue.
