### ISSUE TITLE
Feature Request: Support easier installation of custom plugins

### ISSUE THREAD

**Issue by pwillmann** [facebook/flipper#407]
In order for custom plugins to work in Flipper on MacOS, `yarn` and `watchman` need to be installed on the machine. I think this is fine for development, but it is a bit of a hassle to share the finished plugin. 

Since the preloaded plugins also work without `yarn` and `watchman`, is there an easier way to distribute custom plugins? 

(Thanks for all the work on Flipper, it helps us a lot!)

**Comment by jknoxville** [comment]
That's a good point, @danielbuechele do you have any ideas about this? Maybe we could have an option for dynamically loading already-bundled plugins, instead of having to build them at runtime. Sounds like something that npm integration you worked on would solve.
