### ISSUE TITLE
New activities not automatically added to the Layout hierarchy tree

### ISSUE THREAD

**Issue by qichuan** [facebook/flipper#408]
![Capto_Capture 2019-04-05_03-20-55_PM](https://user-images.githubusercontent.com/410850/55611149-4634ae00-57b7-11e9-8cef-94af91a0af12.gif)

As shown in the video, the user needs to exit the Layout page and re-enter it in order to see the new Activity (`FlipperDiagnosticActivity` in this case) being added to the hierarchy tree

**Comment by jknoxville** [comment]
Thanks for the report, looks like a bug.

**Comment by qichuan** [comment]
I think I know how to fix it, will create a PR later.

**Comment by mgoyanes** [comment]
@qichuan What's that images plugin?
