### ISSUE TITLE
Can't connect Flipper with Emulators (Xcode and Android Studio)

### ISSUE THREAD

**Issue by Filipe-Faustino** [facebook/flipper#4090]
I can't connect the Flipper app with the Xcode emulator or Android Studio simulator.

![image](https://user-images.githubusercontent.com/94528461/190376744-5b5666da-6869-49e1-8c19-5293928df524.png)

XCode version: 13.4.1
XCode simulator: IPhone 13 iOS 15.5
Flipper version: 0.164.0  (but also tried with 163, 162 and 161)
React native in app version: 0.68.3
MacOS: Intel

My Flipper Doctor looks like this

![image](https://user-images.githubusercontent.com/94528461/190377394-79841e45-6039-4857-8424-fece5c1b622e.png)

 No error on the logs of Flipper

![image](https://user-images.githubusercontent.com/94528461/190377323-0a8e23c5-990a-44ce-970d-b69b3d501493.png)

I have tried:
  - Different Flipper versions
  - Using the exact flipper version on the use_flipper() in Podfile.

Any help is appreciated.

**Comment by khullar** [comment]
I am seeing the same issue on Flipper version: 0.164.0.

**Comment by Filipe-Faustino** [comment]
Update: In the last version of Flipper, it already works.
