### ISSUE TITLE
Unable to Integrate Flipper on Pre AndroidX projects

### ISSUE THREAD

**Issue by lokeshkalal** [facebook/flipper#410]
Getting Manifest merge Error.
Is there any way to fix this issue?

**Comment by passy** [comment]
Can you please post some more details of your project, ideally something for us to repro? Generally, by using jetifier, you should be able to use the library. Upgrading your gradle plugin may take care of it.

**Comment by pavlospt** [comment]
@passy I think they mean the opposite, which is true. There is no way of using an AndroidX library on apps that have not yet migrated to AndroidX IIRC!

**Comment by lokeshkalal** [comment]
getting this error :
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-8:39 to override.

**Comment by pavlospt** [comment]
@lokeshkalal Could you try the fix suggestion? `tools:replace="android:appComponentFactory"`

**Comment by qichuan** [comment]
@lokeshkalal Try downgrade the litho to 0.24.0

In gradle.properties

LITHO_VERSION=0.24.0
#ANDROIDX_VERSION=1.0.0

**Comment by kalallokesh** [comment]
@qichuan I am not using litho in my project

**Comment by passy** [comment]
Closing this one as it's not actionable for us right now, but please open a new one if you see something like this again.
