### ISSUE TITLE
Question: "The usage of flipperd (server) is currently disabled."

### ISSUE THREAD

**Issue by Slapbox** [facebook/flipper#4129]
Trying everything to remedy #3549, I wanted to try the experimental server, but in Flipper 0.166.0 it says: "The usage of flipperd (server) is currently disabled."

Why is that? We're on Ubuntu 22.04.

**Comment by aigoncharov** [comment]
We hid it behind a gatekeeper and forgot to roll it out to OSS. Should be resolved by https://github.com/facebook/flipper/commit/e8392bdcebc7ded9a66926e57a43467b500f214b. You should see it in the next release.
