### ISSUE TITLE
Recommend iOS Plugins

### ISSUE THREAD

**Issue by euanchan** [facebook/flipper#416]
Hi, we've open source our own iOS profiling / debugging assist tools `MTHawkeye`, and it seems that we could add the `MTHawkeye` plugins as part of flipper, do you have a plan on the iOS plugins yourselves?

For the detail of `MTHawkeye`, have a look at the readme and the plugins documentation. https://github.com/meitu/MTHawkeye

**Comment by passy** [comment]
Hi @euanchan! Congrats on open sourcing your project. I'm not entirely sure I understand your question. If you want to develop a Flipper plugin, that can happen entirely independent of us and you're definitely more than welcome to. :)

**Comment by euanchan** [comment]
Great, we'll try to develop Flipper plugins in the further. :D

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
