### ISSUE TITLE
flipper-plugin and flipper-plugin-lib stuck in 0.164.0

### ISSUE THREAD

**Issue by aeroxy** [facebook/flipper#4179]
Here:

https://www.npmjs.com/package/flipper-plugin
https://www.npmjs.com/package/flipper-plugin-lib

For some reason when using `yarn` to install the dependencies, it cannot find the newer versions even when the registry is set to https://registry.yarnpkg.com

**Comment by aeroxy** [comment]
Actually the registry.yarnpkg.com is pointing to the 0.164.0 as well https://registry.yarnpkg.com/flipper-plugin

**Comment by aigoncharov** [comment]
Duplicate of #4138
