### ISSUE TITLE
releases are missing binary DMG files for Flipper 0.167+

### ISSUE THREAD

**Issue by kenyee** [facebook/flipper#4189]
## 🐛 Bug Report
The https://github.com/facebook/flipper/releases/ page is missing binary DMG files for Flipper 0.167+

## To Reproduce
Look at release artifacts

## Environment
N.A.

**Comment by rafauke** [comment]
Also, assets for the other two recent versions (168 and 169) are also missing, it would be great to have those too :)

**Comment by rasaha91** [comment]
This is a duplicate of https://github.com/facebook/flipper/issues/4182
