### ISSUE TITLE
Consider implementing okhttp tracing as an EventListener

### ISSUE THREAD

**Issue by yschimke** [facebook/flipper#42]
It provides a cleaner API than using an Interceptor

https://github.com/square/okhttp/wiki/Events

**Comment by yschimke** [comment]
Implemented here https://github.com/yschimke/kona/blob/master/src/main/kotlin/com/baulsupp/sonar/okhttp/SonarOkhttpListener.kt

Without support for viewing body, but does not delay processing like the interceptor does.

**Comment by passy** [comment]
Marking this as help wanted. Happy to look at a PR for this if anybody fancies implementing this.
