### ISSUE TITLE
Connection on iPhone Simulator failed

### ISSUE THREAD

**Issue by colaquecez** [facebook/flipper#4202]
## 🐛 Bug Report

Whenever I open the flipper, that modal shows up, and I can't just close it because when I close it shows up again.

![Screen Shot 2022-10-10 at 11 10 23 PM](https://user-images.githubusercontent.com/38195454/194981420-1f495182-a2b4-4f0a-85d6-958a06c0d181.png)
![Screen Shot 2022-10-10 at 11 11 45 PM](https://user-images.githubusercontent.com/38195454/194981583-a0b663e9-0486-469b-b086-9e0f6420b5c3.png)

## Environment
Flipper Desktop, Version 0.166.0 (50.0.0)
I'm using Apple M1 Max

**Comment by thiavila-sigma** [comment]
Using M1 as well. I ran `yarn upgrade react-native-flipper` and it worked. Nevertheless, I'm still getting the deprecation error because even though there is already a release for 0.170, react-native-flipper is only at 0.164.

**Comment by colaquecez** [comment]
Hey, I needed to upgrade my Xcode and the flipper using `yarn upgrade react-native-flipper` and also the new update from the flipper website
