### ISSUE TITLE
The native module for Flipper seems unavailable. 

### ISSUE THREAD

**Issue by nicode-io** [facebook/flipper#4240]
## 🐛 Bug Report
After installing, v 0.171.1, got a warning message "The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed as yarn dependency to your project and, for iOS, that `pod install` is run in the `ios` directory." 
Flipper plugins are not working anymore, downgrade react-native-flipper version to 0.162.0 fix the issue but disabled updates for newest versions. 

## To Reproduce
1.  Create RN project
2. yarn add react-native-flipper
3. Install "redux-debugger" plugin for example
4. Launch app on iOS (simulator or device) and Flipper 0.171.1
5. Flipper plugins don't work

## Environment
 Flipper desktop: 0.171.1
 RN 0.68.2
 react-native-flipper 0.171.1
redux-flipper 2.0.1

**Comment by nicode-io** [comment]
Podfile content:
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '12.0'
install! 'cocoapods',
  :deterministic_uuids => false

target 'Pilot2' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  # Firebase
  pod 'Firebase/Analytics'

  # RN Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"


  if !ENV['CI']
     use_flipper!({ 'Flipper' => '0.162.0' })
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end

**Comment by zT0Tz** [comment]
I'm having the same error,
```Flipper desktop: 0.171.1
RN 0.68.2
react-native-flipper 0.171.1
redux-flipper 2.0.1

**Comment by vdanylov** [comment]
Same thing. Tried several redux-debugger plugins:

```
Flipper desktop: 0.171.1
RN: 0.66.4
react-native-flipper: 0.171.1
redux-flipper: 2.0.1
```

**Comment by djMax** [comment]
This is happening to me without any plugins:

```
RN: 0.67.4
react-native-flipper: 0.171.1
Flipper: 0.171.1
```

The error is "right" in that Flipper is NOT listed in the NativeModules. I'm digging further to see if I can see anything, but the Flipper initialization code seems to run fine, but NativeModules doesn't get modified.

**Comment by djMax** [comment]
More detail - after yarn-updating to 171, after running pod install, there is NO pod in Podfile.lock for react-native-flipper. 0.162.0 will add an entry. It's not clear to me exactly how this resolution happens

**Comment by aigoncharov** [comment]
Quoting #4265: Resolving https://github.com/facebook/flipper/issues/3859 led to breaking changes in react-native-flipper which made it incompatible with react-natvie < 0.69.

As a result, we had to make a hard decision of supporting future react-native-flipper updates only for react-native 0.69+. Please, upgrade your react-native to 0.69+. If you want to keep using react-native < 0.69, please, keep using react-native-flipper 0.162
I wan to highlight that you still can use new versions of Flipper itself! For instance, you should be able to run react-native-flipper@0.162 with Flipper@0.171.1.

**Comment by nicode-io** [comment]
Thanks for the answer, strange decision to make the official debugger incompatible for around 90% of your users...

**Comment by saikishore-232** [comment]
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. How to fix this compliation error.
