### ISSUE TITLE
unhandledrejection: Error: flipper-server: timeout for command 'client-request-response'

### ISSUE THREAD

**Issue by mohit23x** [facebook/flipper#4241]
## 🐛 Bug Report
"unhandledrejection" event intercepted: Error: Unable to send, connection error: Error: flipper-server: timeout for command 'client-request-response'

<img width="858" alt="image" src="https://user-images.githubusercontent.com/36567063/197127874-1f071317-42ab-4084-9b56-2ca9476ae3ee.png">

## To Reproduce
This issue randomly pops up while using react native app with `react-native-flipper` package installed.
versions - 
    "react-native-flipper": "^0.171.1",
    "react": "17.0.1",
    "react-native": "0.64.1",

	flipper desktop: "0.171.1"

**Comment by aigoncharov** [comment]
Could you try disabling "Flipper Server" in your settings?

**Comment by mohit23x** [comment]
@aigoncharov that works, thanks!

**Comment by sushrut-walmart** [comment]
> Could you try disabling "Flipper Server" in your settings?

How do you do that? I am running flipper 0.251.0 so I have to run flipper server in the background.
