### ISSUE TITLE
Discussion: Network Plugin could use an option to wrap long text in the response body section

### ISSUE THREAD

**Issue by mitchware-cfa** [facebook/flipper#431]
Given that an "Options" section exists with an option to switch between parsed and raw response body formats, I could see a similar option for wrapping long text in the response body to a new line.

Currently, if some JSON is returned that has a long string value (an API key/token, some kind of hash, etc), the network plugin renders it all in one line out of view.

Thoughts? Happy to help implement in a PR.

**Comment by passy** [comment]
Oh yes, definitely. If you're interested in contributing that, we'd be happy to take a look. :)

**Comment by mweststrate** [comment]
This should have been fixed with the latest release
