### ISSUE TITLE
Network Plugin - Response body format option isn't saved

### ISSUE THREAD

**Issue by mitchware-cfa** [facebook/flipper#432]
## 🐛 Bug Report
If you view the details of a particular network request and change to the "formatted" response body option, then swap to another request, the previous option isn't saved/respected. This might be intentional behavior, but it certainly is frustrating and seems like a bug...

## To Reproduce
* View details of a network request that returns a response
* Switch the response body option to "formatted"
* Back out and view a different request's details
_see that the response option is reset to the default "parsed" option_

## Expected Behavior
I would expect the plugin to save my choice, at least in memory, between viewing different network request details.

## Environment
Flipper version 0.20.0

**Comment by passy** [comment]
That's a good point. Thanks for the detailed report, @mitchware-cfa!
