### ISSUE TITLE
Documented disabling Flipper: https://fbflipper.com/docs/troubleshooting/#opting-out-from-flipper-ios.

### ISSUE THREAD

**Issue by error-try-again** [facebook/flipper#4496]
Documented disabling Flipper: https://fbflipper.com/docs/getting-started/troubleshooting/react-native/#opting-out-from-flipper-ios

Also locking the conversation know so that this remains the bottom comment :). Feel free to open new issues for follow up questions.

_Originally posted by @mweststrate in https://github.com/facebook/flipper/issues/1326#issuecomment-789804202_

Your documentation is a dead link.. Perhaps you could provide a mirror or an ia link instead. Please fix this as I found the previous conversation chain helpful and I'm sure others will also.

**Comment by luccasr73** [comment]
https://fbflipper.com/docs/getting-started/troubleshooting/react-native/#opting-out-from-flipper-ios to anyone that need this

**Comment by passy** [comment]
Sorry, I don't think I follow. What is the ask here?

**Comment by error-try-again** [comment]
> Sorry, I don't think I follow. What is the ask here?

https://fbflipper.com/docs/troubleshooting/#opting-out-from-flipper-ios is a dead link and cited as the reason for the conversation being locked. I was asking that the documentation link be updated so that others looking for a way to disable flipper can find it if they are looking for it.

**Comment by passy** [comment]
Oh, I see. @mweststrate could you maybe update the previous issue with the new link https://fbflipper.com/docs/getting-started/troubleshooting/react-native/#opting-out-from-flipper-ios?
