### ISSUE TITLE
Discussion: [Plugin][Android] An other constructor for SharedPreferencesFlipperPlugin 

### ISSUE THREAD

**Issue by s1rius** [facebook/flipper#450]
Hi, Can we create an other constructor for SharedPreferencesFlipperPlugin ?

Because I have a custom SharedPreferences implementation in a project. I cant just pass SharedPreferences's mode, name or a `SharedPreferencesDescriptor `.

Maybe we can add a constructor like below
```
  /**
   * Creates a {@link android.content.SharedPreferences} plugin for Flipper
   *
   * @param sharedPreferences The all SharedPreferences pair.
   */
  public SharedPreferencesFlipperPlugin (
      Map<SharedPreferences, SharedPreferencesDescriptor> sharedPreferences) {
    mSharedPreferences = sharedPreferences;
    ...
    registerOnSharedPreferenceChangeListener
    ...
  }

```
(And thanks build this tool)

**Comment by bizzguy** [comment]
How would you see the UI for the plugin changing (if at all)?  Would this just be an app "filter" on the shared preference files you would see in the plugin?

**Comment by passy** [comment]
I would think that should be compatible with what we currently have.

The `SharedPreferencesFlipperPlugin(Context context, List<SharedPreferencesDescriptor> descriptors)` effectively has the same result but you skip the resolution step. @s1rius if you want to put this up as a PR, I'm happy to take a look!

**Comment by s1rius** [comment]
Hi @passy ,I rethink it and find, we can simple add a function to create SharedPreferences, and no need to add an other constructor in the SharedPreferencesFlipperPlugin Class.
So, I create a pull request, hope you take a look.
