### ISSUE TITLE
Error: No iOS devices found, when i use react-native >= 0.70

### ISSUE THREAD

**Issue by deokyeong93** [facebook/flipper#4508]
## 🐛 Bug Report
![스크린샷 2023-02-09 오전 9 32 07](https://user-images.githubusercontent.com/66895208/217683568-7316d27b-8794-4c3c-ade6-cb43b660971d.png)

fliper is working well in simulator, but when i use real device it says it can't find the device.

At first, I thought the connection to the computer was not good, but the build worked well on the phone with Xcode, and when I checked the metro log, it came out well.

Has anyone had the same problem or knows how to solve it?

+) flipper is well in 0.69.7 (when i use real device and simulator)

## Environment
ios : 16.1.2
macos: 12.6.3
react-native : 0.71.2
react: 18.2.0

**Comment by deokyeong93** [comment]
Is the best approach to look at and update [flipper example](https://github.com/facebook/flipper/issues/3027)?😂

**Comment by deokyeong93** [comment]
I fixed this

**Comment by ovidb** [comment]
> I fixed this

How?

**Comment by jonno85** [comment]
I did reinstall the `idb` on my macOs Silicon

**Comment by deokyeong93** [comment]
Sorry🤣

It's a lot late, but I'll leave what I recorded at the time. (This may not be correct now.)
This problem is related to the idb setting issue.

First, you need to install idb.

```
brew install python3

brew tap facebook/fb

brew install idb-companion
pip3 install fb-idb

which idb // Just put this result in the path shown in the settings photo below.
```
<img width="736" alt="스크린샷 2023-02-10 오전 1 01 33" src="https://github.com/facebook/flipper/assets/66895208/d44f02c3-89e3-4837-bb78-57e082ff91bf">
<img width="347" alt="스크린샷 2023-02-10 오전 12 56 40" src="https://github.com/facebook/flipper/assets/66895208/df9362d5-6978-4e89-85a4-38df4a6a8635">
<img width="182" alt="스크린샷 2023-02-10 오전 1 01 23" src="https://github.com/facebook/flipper/assets/66895208/7640600d-da1b-41c3-a87d-586c7c01abb8">
