### ISSUE TITLE
Discussion: Add support for deleting a shared preference

### ISSUE THREAD

**Issue by paour** [facebook/flipper#451]
In Flipper 0.20, I can edit a shared preference item, but I can't delete one. If I delete the contents of a string preference, I end up with an empty string but I can't remove the preference item.

**Comment by danielbuechele** [comment]
I would love to merge a PR adding this feature!

**Comment by henryzx** [comment]
Really needed too!

**Comment by bizzguy** [comment]
@danielbuechele 
There are two SharedPreferences.Editor methods that could be used.

    - clear() ... remove all 
    - remove(String key) ... remove individual preference 

Would both be useful. What would the UI look like?

**Comment by umasankar-yedida** [comment]
@danielbuechele I'll take this up

**Comment by passy** [comment]
> @danielbuechele I'll take this up

Awesome! Do let us know if we can help you with anything. :)

**Comment by umasankar-yedida** [comment]
@passy @danielbuechele Currently the preferences values are being displayed in `DataInspector` component. In order to select and deselect a preference, would it be nice to have a checkbox beside every preference? or? do you suggest another approach for this?

**Comment by mzgreen** [comment]
Hey! @umasankar-yedida are you still working on this one? Because if not then I'll be happy to take it over.

**Comment by mzgreen** [comment]
@danielbuechele @passy 
I started looking around and seems like prefs are displayed in `ManagedDataInspector`. I don’t see any property that would allow me to add a button or other action there. So I see 2 options: 
1. Add a handler for deleting entries in `DataInspector` (similar to `setValue`)
2. Get rid of `ManagedDataInspector` and replace it with normal table with 3 columns: pref name, pref value (editable) and remove button.

I was thinking that this may be a good opportunity to add an option for creating a new preference key.

What do you think?

**Comment by passy** [comment]
@mzgreen Thanks for investigating this! Deleting seems like an action common enough that it would make sense to add support for this to the managed table itself.
