### ISSUE TITLE
Discussion: Execute SQL statements using databases plugin

### ISSUE THREAD

**Issue by abaker** [facebook/flipper#453]
It would be great if the databases plugin had support for executing SQL statements, similar to the [database inspection feature](https://facebook.github.io/stetho/#features) in Stetho

**Comment by AnkitPatanaik** [comment]
+1, would love to see this.

**Comment by jknoxville** [comment]
This has been added in recent commit https://github.com/facebook/flipper/commit/fe56c8471c29f7a0de6f831f0064019acc8226a5, and will become widely available in the next release.

If you build from source you can use the feature now. For arbitrary sql in particular, you'll only need to update the desktop version, but that change adds several features, some of which will require you to also update the in-app sdk.

I don't believe it has had much exposure yet so if you find bugs please let us know by way of github issues. In addition the UI could do with some TLC but the basic functionality is ready.
