### ISSUE TITLE
Discussion: Copy Response Body in Network Plugin 

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#456]
Hi.

I'm seeing some issues when trying to preview and copy the response body in the network plugin. 

If I have this API response:

```
{
  "id": "143123412",
  "salutation": null,
  "firstName": "Paul",
  "lastName": "Smith",
  "dateOfBirth": "1900-11-15",
  "mobilePhone": "+123456789",
  "email": null,
}
```
Response Body shows properlly formated and I can select the copy the entire tree or create paste option.

My API also returns this:

```
{
	"links": {
		"item": {
			"url": "https://some.url"
		}
	},
	"settings": {
		"offset": 0,
		"count": 6,
		"totalItems": 6,
		"items": [
			{
				"name": "VERSION",
				"value": "1"
			},
			{
				"name": "CURRENT_VERSION",
				"value": "1"
			},
			{
				"name": "TIMEOUT",
				"value": "rt1"
			},
			{
				"name": "API_BASE_URL",
				"value": "abu1"
			},
			{
				"name": "CACHING_TTL",
				"value": "cattl1"
			},
			{
				"name": "callbackUrl",
				"value": "https://callbackUrl"
			}
		]
	}
}
```
But this time, no matter if I select the boby parsed or formatted, the response Body section does not show this response propperly formatted. It also doesn't allow me to copy the contents.
I also verify this in other requests that return even responses with more data thus, making it extremely difficult to "see" my network responses. In comparison, Stetho shows all my responses properly formatted.

**Comment by mgoyanes** [comment]
Hello again.

I think I found the problem.

The header response contains `Content-Length: 339`. Since the response is pretty-printed (????), it's length is actually `606`.

With this response:

```
{
  "links": {
    "item": {
      "url": "https://some.url"
    }
  },
  "settings": {
    "offset": 0,
    "count": 6,
    "totalItems": 6,
    "items": [
      {
        "name": "VERSION",
        "value": "1"
      },
      {
        "name": "CURRENT_VERSION",
        "value": "1"
      },
      {
        "name": "TIMEOUT",
        "value": "rt1"
      },
      {
        "name": "API_BASE_URL",
        "value": "abu1"
      },
      {
        "name": "CACHING_TTL",
        "value": "cattl1"
      },
      {
        "name": "callbackUrl",
        "value": "https://callbackUrl"
      }
    ]
  }
}
```

These are my findings:

- Not sending `Content-Length`, Flipper displays the response properly formatted (regardless of sending the response pretty-printed or not).
- Sending `Content-Length`, Flipper only displays the response properly formatted if it actually matches the response length. In fact, what happens is that Flipper only shows in the response body the number of char that `Content-Length` enforces, thus cutting the response and this makes an invalid JSON thus not being correctly displayed.

Since this is a debug tool, I think we should not enforce the `Content-Lenght`.

Best regards,

Miguel.

P.S - I also think that, in Response Body, besides the Expand/Collapse button, there should be an option to Expand/Collapse ALL the tree.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by AndrewWestberg** [comment]
@passy Please re-open this issue. The very latest version for mac has no right-click options menu to copy anything from the response body field. For a very large graphql response, I need to put it into a tool so it's formatted better.
