### ISSUE TITLE
[maven] flipper-fresco-plugin not bumped to 0.183.0

### ISSUE THREAD

**Issue by RichardFevrier** [facebook/flipper#4565]
## 🐛 Bug Report

Hello, `flipper-fresco-plugin` has not been updated to `0.183.0` on maven resulting on `react-native` builds fail.
Would you mind bumping the version there? 🙂

Best regards

**Comment by passy** [comment]
The Fresco plugin is no longer published together with Flipper itself. Can you share where the build fails?

**Comment by RichardFevrier** [comment]
If you look into the latest `build.gradle` produced by `npx react-native init ProjectName`
You will find this:
```
dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}
```
So probably either `flipper-fresco-plugin` needs to be bumped or the latest `react-native-cli` needs to remove this depedency.

**Comment by cortinico** [comment]
> I see. We won't be bumping the dependency going forwards so the correct way for now would be to hard-code the Fresco plugin version to the last published release in the template.

Hey, Nicola from React Native here 👋 

@passy what's the reason why `flipper-fresco-plugin` won't be bumped anymore in the future?

How about just removing the `flipper-fresco-plugin` entirely from the template. and let to the user the possibility to eventually add it if they wish

**Comment by arnaudambro** [comment]
what is the solution then ?

**Comment by mark-zacharias** [comment]
This took a while to figure out for me. I've created a PR I think will help most folks figure this out sooner.
https://github.com/facebook/flipper/pull/4734

**Comment by tfreitas90** [comment]
Should we do what he says here:
https://github.com/facebook/flipper/pull/4734#issuecomment-1554292382

**Comment by cortinico** [comment]
React Native 0.73 will contain the bump of Flipper to the correct version + the bump of the Fresco plugin.

This issue can be closed as there are no actionables
