### ISSUE TITLE
Discussion: Host android sample APK within the repo?

### ISSUE THREAD

**Issue by erawhctim** [facebook/flipper#458]
It'd be convenient to just grab the APK and install it directly, since the first compile could be lengthy. Not sure if its easier to host in the official Github "releases" section, or just in a directory in the repo. 

Thoughts?

**Comment by passy** [comment]
I never considered that, but it's a pretty good idea! The rest of our release procedure is automated so we'd need to update that, but it should be possible. Thanks for the suggestion.

**Comment by mitchware-cfa** [comment]
Awesome! Yeah, that was my thought as well. Especially due to NDK variability (like mentioned in #461) and other things that might impact the android build in master.

**Comment by passy** [comment]
We have this now. :)
