### ISSUE TITLE
Flipper won't launch on Mac

### ISSUE THREAD

**Issue by joe-goodall-ticketmaster** [facebook/flipper#4585]
## 🐛 Bug Report

Cannot open the Flipper app on Mac

## To Reproduce

  Try and open the Flipper app

## Environment

 Have tried Flipper Desktop version 0.183.0 and other versions as well.

MacBook Pro (16-inch, 2021)

https://user-images.githubusercontent.com/65718433/223536328-7bff0b84-c61a-4c22-8700-a5d00dc38b08.mov

Tried everything here https://fbflipper.com/docs/getting-started/troubleshooting/general/#flipper-wont-launch-on-mac

Any other suggestions?

**Comment by joe-goodall-ticketmaster** [comment]
OK, eventually opened (despite seeing 'Application Not Responding' as seen in the video above) by just leaving the icon bouncing in the dock. Took about 2 minutes before it eventually opened. I guess that solves the problem but not sure why it took so long to open. Will close issue but leave comment in case anyone else has the same problem.

**Comment by silviodaminato** [comment]
Hello, I have the same issue, but in my case the icon eventually stops bouncing and nothing happens.
I have tried with versions 0.193.0, 0.192.0 and 0.191.0 getting the same result.

I am on a MacBook Pro (M1 mid 2020).

Any help is very appreciated!
Thanks!

**Comment by samueljim** [comment]
bump
![2023-07-10 at 18 38 15 - Brown Butterfly](https://github.com/facebook/flipper/assets/19277887/9dbc819b-d2d7-4001-8b2d-20efeaba7b8e)

**Comment by silviodaminato** [comment]
I noticed that I had many `ssh-agent` processes running on my mac, by killing them Flipper works like a charm.
After some days I was getting desperate and I tried everything came to my mind.
The multiple ssh-agents were created by eval `"$(ssh-agent -s)"` being put into my `.bash_profile` file so when starting the terminal with multiple tabs, each one created a process.
Hope it helps you!

**Comment by schaetz** [comment]
I have the same issue. After double-clicking the "Flipper" icon from the downloaded .dmg, the flipper icon in my app bar will bounce for a while, but the Flipper UI is never displayed. All I can do is kill the process from the activity monitor.

I am on a MacBook Pro from 2019 with Intel Core i9 processor.

I searched for `ssh-agent` in my list of processes, but that does not seem to be the issue for me...

**Comment by juspriet** [comment]
Same problem !
- Flipper v 0.252.0
- Macbook pro 2019 i9

**Comment by karel-suchomel-ed** [comment]
Same issue.

- Flipper v 0.252.0
- MacBook Air M1

In the console, it throws this error:
Failed to initialize ADB. Please disable Android support in settings, or configure a correct path. Error: spawn /opt/android_sdk ENOENT

However I cannot access settings of flipper, because it will not launch

**Comment by stanleyugwu** [comment]
Running `brew install --cask flipper` then relaunching Flipper after installation fixed it for me

**Comment by ARIPRASATH4664** [comment]
Same for me even tried installing older versions nothing works !!

**Comment by ARIPRASATH4664** [comment]
@akshay-mob123 @andriib-huma   Use this version https://github.com/facebook/flipper/releases/tag/v0.183.0 It works for me

**Comment by akshay-mob123** [comment]
Remove the flipper Downloaded from the fbFlipper.com and install it via ` brew install --cask flipper ` and then run it . This worked for me.

**Comment by ARIPRASATH4664** [comment]
> Remove the flipper Downloaded from the fbFlipper.com and install it via `brew install --cask flipper` and then run it . This worked for me.

Even this failed for me !  Anyhow we both are good to work for now : )

**Comment by Nazofer** [comment]
> https://github.com/facebook/flipper/releases/tag/v0.183.0

Same issue, did you manage to fix that?

**Comment by Nazofer** [comment]
> Same issue.
> 
> * Flipper v 0.252.0
> * MacBook Air M1
> 
> In the console, it throws this error: Failed to initialize ADB. Please disable Android support in settings, or configure a correct path. Error: spawn /opt/android_sdk ENOENT
> 
> However I cannot access settings of flipper, because it will not launch

Same issue, did you manage to fix that?

**Comment by sauravBalodi1** [comment]
@Nazofer @karel-suchomel-ed anything worked for u ?
for me flipper is launching but it is showing no application found

**Comment by LucasParra** [comment]
> @akshay-mob123 @andriib-huma Use this version https://github.com/facebook/flipper/releases/tag/v0.183.0 It works for me

This worked for me also, thank you so much!

**Comment by sarveshhh-m** [comment]
@ARIPRASATH4664 Thanks!

Installing this version helped for me as well.

**Comment by umair-khanzada** [comment]
> @akshay-mob123 @andriib-huma Use this version https://github.com/facebook/flipper/releases/tag/v0.183.0 It works for me

Worked for me..
Thanks Man!!

**Comment by Yangeok** [comment]
Worked for me. Awesome!

**Comment by UmarbekSaidov** [comment]
> @akshay-mob123 @andriib-huma Use this version https://github.com/facebook/flipper/releases/tag/v0.183.0 It works for me

This worked for me also, thank you so much!
