### ISSUE TITLE
Docs: Can't click on Features index page from inner pages

### ISSUE THREAD

**Issue by vkotovv** [facebook/flipper#460]
From inner pages (like https://fbflipper.com/docs/features/logs-plugin.html) I can't click on the Features title and get to the Features index page (https://fbflipper.com/docs/features/index.html).

This is true for every feature page.

![Screenshot](https://user-images.githubusercontent.com/1636249/59028027-37c04c80-8863-11e9-8ec5-25ee71dd013e.png)

**Comment by passy** [comment]
@vkotovv That's how our navigation is set up. I would say this works as intended.

**Comment by vkotovv** [comment]
@passy looks a bit confusing imo. I've missed the index page because of this. Although a minor issue.

**Comment by passy** [comment]
This is the default behaviour for Docusaurus. You can see that on the example pages here: https://docusaurus.io/en/users

It might be worth opening an issue there to check if others have found this to be counter-intuitive, too.
