### ISSUE TITLE
Question: How to connect enterprise app on a physical iOS device?

### ISSUE THREAD

**Issue by zdl51go** [facebook/flipper#4619]
I have been looking at the code for a long time, focusing on classes such as FlipperKitCertificateProvider, FlipperCertificateProvider on iOS, and MyWWWCertificateProvider on desktop. 

It seems need to find  a TLS certificate that is used on the client and desktop sides? 

There is little relevant information, can someone provide some experience ? It’s really bothering me.

**Comment by mweststrate** [comment]
We don't currently support using Flipper on physical iOS devices in the open source version, but the general idea is that we can't write the certificates using idb on a physical device, so they're uploaded by Flipper, and downloaded by the app itself through a third party service instead.
