### ISSUE TITLE
[js flipper] flipper not up to date on NPM

### ISSUE THREAD

**Issue by fathiasbiML** [facebook/flipper#4628]
## 🐛 Bug Report

Hi, the npm package stops at version 0.184.0. I saw that the GitHub action failed for version 0.185.0 and above. Would like to request to re-run the GitHub action or fixing it so that we have the latest version on npm

**Comment by aigoncharov** [comment]
Should be resolved by 905f5eea0f12938c730d5ceb73ea9766f09badf0. Next release should publish NPM

**Comment by owens-ben** [comment]
This is an issue again. Flipper has not been updated on NPM since August 19 (v0.212).
