### ISSUE TITLE
Flipper Mac OS v0.187.1 - “Flipper” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by sipamungkas** [facebook/flipper#4629]
## 🐛 Bug Report
“Flipper” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
Version v0.187.1

I already delete it, download again and reinstalled. But i keep getting the same error.

![Screenshot 2023-03-29 at 14 06 17](https://user-images.githubusercontent.com/43329321/228454418-57034fbc-5eed-4385-a290-fdb975e2997b.png)

Thanks

## To Reproduce
1. download flipper mac os from https://github.com/facebook/flipper/releases/tag/v0.187.1
2. open `flipper mac.dmg` and install it
3. open flipper from launchpad

## Environment

Flipper Desktop Version: V.0.187.1
MacOs Ventura Version 13.2
MacBook Pro Apple M1 Chip

**Comment by erikschul** [comment]
Why isn't the developer verified?

**Comment by YASH6004** [comment]
<img width="714" alt="Screenshot 2024-01-04 at 5 11 07 PM" src="https://github.com/facebook/flipper/assets/102504196/ea9713cc-67b3-42ca-9a71-bd45ef4bb4d8">

this works for me 

mac : M1 air 
mac OS: Version 14.2.1 (23C71)

**Comment by tuiza** [comment]
> <img alt="Screenshot 2024-01-04 at 5 11 07 PM" width="714" src="https://private-user-images.githubusercontent.com/102504196/294169779-ea9713cc-67b3-42ca-9a71-bd45ef4bb4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNjYwOTMsIm5iZiI6MTcxMTA2NTc5MywicGF0aCI6Ii8xMDI1MDQxOTYvMjk0MTY5Nzc5LWVhOTcxM2NjLTY3YjMtNDJjYS05YTcxLWJkNDVlZjRiYjRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMDAzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjJhMzI0OTJlOGNiZDQzZmI3ZTU4Y2E2YjBiMTBkOWYzMmMxMjdmMWJiZDEwNmIzYWRjZmZkZjY2OTdkNjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j6J8g6YahhwuI_gXZ8VCS1uCPVm-CDMZxkU6PSBPk8E">
> It works for me, thanks!
> 
> mac : M1 air mac OS: Version 14.2.1 (23C71)

This works for me,thanks

**Comment by tuiza** [comment]
> <img alt="Screenshot 2024-01-04 at 5 11 07 PM" width="714" src="https://private-user-images.githubusercontent.com/102504196/294169779-ea9713cc-67b3-42ca-9a71-bd45ef4bb4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNjgwMTQsIm5iZiI6MTcxMTA2NzcxNCwicGF0aCI6Ii8xMDI1MDQxOTYvMjk0MTY5Nzc5LWVhOTcxM2NjLTY3YjMtNDJjYS05YTcxLWJkNDVlZjRiYjRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMDM1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTU1MTVhMDZkMjQwYmVlMmZlMzc2YzFjNzg1ZGZhNTAwYmYxNzJmYzljOWNlYmZiYTcyN2M3MGY2MTI5NzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eMsuY9tnLgAbN1he6w7O6970pf6MyF9vUGi5QLLSHhE">
> this works for me
> 
> mac : M1 air mac OS: Version 14.2.1 (23C71)

It works for me, thanks!
