### ISSUE TITLE
Docs: README says this is OS X only, but it seems to work fine on Linux

### ISSUE THREAD

**Issue by mlc** [facebook/flipper#464]
The `README` for flipper suggests that the desktop app component of this only works on OS X. But if you clone the repo on Linux and do `yarn && yarn start`, it seems to work just fine. Even if the level of official support and packaging is likely to continue to stay lower on Linux than OS X, the `README` (and other relevant documentation) should be updated to at least hint that this is a possibility.

(I didn't try running this on Windows, but if it similarly works there, then similar concerns would apply.)

**Comment by passy** [comment]
I thought "(while Flipper is buildable using other systems as well, only macOS is officially supported)" would imply that. Any suggestions how we could make that more clear?
