### ISSUE TITLE
Discussion: SharedPreferences plugin default name

### ISSUE THREAD

**Issue by mitchware-cfa** [facebook/flipper#468]
The `SharedPreferencesFlipperPlugin(Context)` constructor uses `context.getPackageName()` as the name of the preference file to lookup. However, `PreferenceManager.getDefaultSharedPreferences(Context)` uses `context.getPackageName() + "_preferences"` as the default name, which I think could be misleading.

I'm not sure, however, if that implementation within `PreferenceManager` changes between OS versions, or if that has been stable since its inception.

**Comment by passy** [comment]
Sorry for never closing the loop on this one. This is a good point. Do you know if this causes any issues in the real world?

**Comment by mitchware-cfa** [comment]
I think its a pretty minor issue overall. It did throw me for a loop the first time, using the default constructor on the plugin, but it was an easy fix to debug and provide the right name manually.

**Comment by passy** [comment]
Thanks! I'll close this for now, but it's good to know. If this comes up again, we may want to change the default.
