### ISSUE TITLE
Shared Preferences: Changelog updates aren't reflected in the inspector

### ISSUE THREAD

**Issue by mitchware-cfa** [facebook/flipper#470]
## 🐛 Bug Report
When `SharedPreferences` updates are sent back to Flipper, the "current" values displayed in the inspector are not updated to reflect the changes in the changelog. 

## To Reproduce
- Setup Flipper with an Android sample app, a `SharedPreferences` reference, and the `SharedPreferences` flipper plugin installed.
- Set a value in the preferences
- Update that value at runtime and observe the changelog in flipper

## Expected Behavior
I expect the inspector values to update in real time in response to the changes sent back from the mobile plugin

## Environment
- Android OS version 9.0
- Flipper SDK version 0.15.0
- Flipper Desktop version 0.21.1
- Android gradle plugin version 3.4.1

**Comment by umasankar-yedida** [comment]
I'm working on it

**Comment by vkotovv** [comment]
Is this still not resolved?

**Comment by passy** [comment]
Thanks for noticing. That was addressed with #623.
