### ISSUE TITLE
[Android] Question: How to remove Flipper from React Native?

### ISSUE THREAD

**Issue by o-alexandrov** [facebook/flipper#4748]
The #1326 was closed w/o documenting the suggested way on how to remove the forcefully installed Flipper.

Commenting there is impossible, as the issue is locked, so let me please reopen the same issue here.
Is there any better way other than finding use of `ReactNativeFlipper`/`flipper` and removing it?

It'd be great to have a flag at the ReactNative CLI level, ex.:

`$ npx react-native init APP_NAME --no-flipper`

**Comment by passy** [comment]
Can you please ask this in the React Native community? We do not own or maintain the integration into RN. We just build Flipper itself.
