### ISSUE TITLE
couldn't find DSO to load: libflipperfb.so Not working in Emulator only

### ISSUE THREAD

**Issue by sajidjutt7** [facebook/flipper#477]
## 🐛 Bug Report

For earlier information: I was getting this error on build. it was not letting me build project. 

> Execution failed for task ':app:processDebugResources'. Android resource linking failed

which i resolved by Migration of support libraries to AndroidX. Doing that above issue resolved and my code start building.

Now after adding complete setup of flipper under build.gradle, AndroidManifest and MyApplication class. When i go to run project. my app is getting crash with logs i am posting below.

But the same code when i run on actual device. Mobile. Code is working which i can also verifry from logs that fbflipper is intiallized and etc.

But same code is not working on any Emulator. I have tried 4 different emulators from Android 22 to Android P.

Posting the Emulator crash logs below. Any help will be appreciated. Thanks

## To Reproduce

  To reproduce. Just use any emulator and run project. 

## Expected Behavior

App will crash on very start before opening application

## Environment

Flipper version : 

` debugImplementation 'com.facebook.flipper:flipper:0.22.0'`
 `debugImplementation 'com.facebook.soloader:soloader:0.6.0'`

Gradle Version: 5.0
compileSdkVersion 28
Android Plugin Version: 3.3.0

## Logs
07-04 16:34:03.043 5373-5373/? E/memtrack: Couldn't load memtrack module (No such file or directory)
07-04 16:34:03.043 5373-5373/? E/android.os.Debug: failed to load memtrack module: -2
07-04 16:34:03.854 5386-5386/? E/cutils-trace: Error opening trace file: Permission denied (13)
07-04 16:34:06.263 1976-2260/com.google.android.gms.persistent E/NetworkScheduler: Invalid component specified.
07-04 16:34:06.264 1976-2260/com.google.android.gms.persistent E/NetworkScheduler: Invalid component specified.
07-04 16:34:06.265 1976-2260/com.google.android.gms.persistent E/NetworkScheduler: Invalid component specified.
07-04 16:34:06.519 5425-5425/? E/memtrack: Couldn't load memtrack module (No such file or directory)
07-04 16:34:06.519 5425-5425/? E/android.os.Debug: failed to load memtrack module: -2
07-04 16:34:06.545 5437-5437/? E/libprocessgroup: failed to make and chown /acct/uid_10072: Read-only file system
07-04 16:34:06.560 5437-5446/? E/art: Failed sending reply to debugger: Broken pipe
07-04 16:34:06.605 5437-5470/? E/SoLoader: couldn't find DSO to load: libflipperfb.so
07-04 16:34:06.627 5472-5472/? E/libprocessgroup: failed to make and chown /acct/uid_10072: Read-only file system
07-04 16:34:06.669 5472-5505/? E/SoLoader: couldn't find DSO to load: libflipperfb.so
07-04 16:34:06.687 5507-5507/? E/libprocessgroup: failed to make and chown /acct/uid_10072: Read-only file system
07-04 16:34:06.731 5507-5540/? E/SoLoader: couldn't find DSO to load: libflipperfb.so
    
    --------- beginning of crash
07-04 16:34:06.732 5507-5540/? E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.my.app, PID: 5507
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipperfb.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:25)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:24)
07-04 16:34:12.015 5189-5546/com.android.providers.calendar E/SQLiteLog: (284) automatic index on view_events(_id)

**Comment by sajidjutt7** [comment]
I have just tried to downgrade the version from this

```
    debugImplementation 'com.facebook.flipper:flipper:0.22.0'
    debugImplementation 'com.facebook.soloader:soloader:0.6.0'
```
to this

```
    debugImplementation 'com.facebook.flipper:flipper:0.21.1'
    debugImplementation 'com.facebook.soloader:soloader:0.5.1'
```

It is now working on both Devices as well as emulators.

This issue is now closed. I am just telling that previous version is working. But getting error on 0.22.0

**Comment by kuhnroyal** [comment]
See https://github.com/facebook/flipper/issues/471

**Comment by sajidjutt7** [comment]
Thanks @kuhnroyal .  But in #471 no one tells. how can i delete x86 deps to test if 2.0.0 is working on emulator?

**Comment by kuhnroyal** [comment]
Try to use 0.23.0 and clear all cache, uninstall the old app etc. before rebuilding

**Comment by sajidjutt7** [comment]
Thanks @kuhnroyal updating library to 0.23.0 soloader to 0.6.0 is working. Thanks

**Comment by tsdmrfth** [comment]
Clean project > Rebuild project It worked for me.
