### ISSUE TITLE
Question: FlipperKit header files not found

### ISSUE THREAD

**Issue by kuhnroyal** [facebook/flipper#478]
Trying to follow the getting started for iOS from the website, I always end up with this error.
`'FBDefines/FBDefines.h' file not found` when trying to build my project in XCode.
The file is in this repository but not in my locally built pod.
I am using `use_frameworks!` and uncommented everything related.

I tried versions 0.22.0 and 0.21.1
Swift 5

Any ideas what I am doing wrong?

**Comment by kuhnroyal** [comment]
This might have to do something with header/framework search paths.
So if someone has a working Swift example with . `use_frameworks!`, that would probably help.

**Comment by kuhnroyal** [comment]
I have used the changes from this comment: https://github.com/facebook/flipper/issues/254#issuecomment-504405955 which fixed static linking for OpenSSL.

Looking at the headers generated by CocoaPods, `FBDefines/FBDefines.h` is actually in `FlipperKit/FBDefines.h` - if I change this, the error goes away but other missing headers appear.

I would really appreciate some input on how to get Flipper to work or if this is even supported.
The changes from https://github.com/facebook/flipper/issues/254#issuecomment-504405955 are also missing from the documentation.

**Comment by felislynx-silae** [comment]
For me more headers are not found, this is quite frustrating that flipper is not working with use_frameworks! :/

**Comment by priteshrnandgaonkar** [comment]
For CP 1.7+  with `use_framework!`, the following worked for me

```
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
    'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'openssl-ios-bitcode', 'boost-for-react-native']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::Target::BuildType.static_library
          end
        end
      end
  end
```

**Comment by priteshrnandgaonkar** [comment]
Will update the sample and docs soon.

**Comment by priteshrnandgaonkar** [comment]
@kuhnroyal  and @felislynx-silae can you try the above solution.

**Comment by felislynx-silae** [comment]
@priteshrnandgaonkar It looks it helped, but build time is very long. Maybe putting some things like boost for react as optional might help

**Comment by kuhnroyal** [comment]
I got further with this change but can't import `FlipperClient` and `FlipperKitLayoutPlugin` when following the setup.

```
        let client = FlipperClient.shared()
        let layoutDescriptorMapper = SKDescriptorMapper(defaults: ())
        FlipperKitLayoutComponentKitSupport.setUpWith(layoutDescriptorMapper)
        client?.add(FlipperKitLayoutPlugin(rootNode: application, with: layoutDescriptorMapper!))
        client?.start()
```

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!

**Comment by hannojg** [comment]
Hey, the @priteshrnandgaonkar didn't worked, please reopen

**Comment by Appkidd** [comment]
For anyone finding this in the future... Flipper does now document how to define Pods whilst using `use_frameworks`: https://fbflipper.com/docs/getting-started/ios-native/

```
project 'MyApp.xcodeproj'
flipperkit_version = '0.49.0'

target 'MyApp' do
  platform :ios, '9.0'

  # .......

  # If you use `use_frameworks!` in your Podfile,
  # uncomment the below $static_framework array and also
  # the pre_install section.  This will cause Flipper and
  # it's dependencies to be built as a static library and all other pods to
  # be dynamic.
  #
  # NOTE Doing this may lead to a broken build if any of these are also
  #      transitive dependencies of other dependencies and are expected
  #      to be built as frameworks.
  #
  # $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
  #   'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
  #   'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
  #   'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  #
  # pre_install do |installer|
  #   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  #   installer.pod_targets.each do |pod|
  #       if $static_framework.include?(pod.name)
  #         def pod.build_type;
  #           Pod::BuildType.static_library
  #         end
  #       end
  #     end
  # end
end
```

**Comment by ghasemikasra39** [comment]
> For anyone finding this in the future... Flipper does now document how to define Pods whilst using `use_frameworks`: https://fbflipper.com/docs/getting-started/ios-native/
> 
> ```
> project 'MyApp.xcodeproj'
> flipperkit_version = '0.49.0'
> 
> target 'MyApp' do
>   platform :ios, '9.0'
> 
>   # .......
> 
>   # If you use `use_frameworks!` in your Podfile,
>   # uncomment the below $static_framework array and also
>   # the pre_install section.  This will cause Flipper and
>   # it's dependencies to be built as a static library and all other pods to
>   # be dynamic.
>   #
>   # NOTE Doing this may lead to a broken build if any of these are also
>   #      transitive dependencies of other dependencies and are expected
>   #      to be built as frameworks.
>   #
>   # $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
>   #   'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
>   #   'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
>   #   'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
>   #
>   # pre_install do |installer|
>   #   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>   #   installer.pod_targets.each do |pod|
>   #       if $static_framework.include?(pod.name)
>   #         def pod.build_type;
>   #           Pod::BuildType.static_library
>   #         end
>   #       end
>   #     end
>   # end
> end
> ```

What about react native?

**Comment by zhuzhiyongai** [comment]
> static_library

$static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
     'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
     'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
     'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
   pre_install do |installer|
     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
     installer.pod_targets.each do |pod|
         if $static_framework.include?(pod.name)
           def Pod::**BuildType**;
             Pod::Target::BuildType.static_library
           end
         end
       end
  end

**Comment by thliu21** [comment]
Hello folks. I am encountering this issue again as I am getting 
`'FBDefines/FBDefines.h' file not found`
while using `use_frameworks!`. 
I tried what @kuhnroyal mentioned by changing the path to `FlipperKit/FBDefines.h` but it revealed more issues like this. I think there is something definitely wrong with my podfile but I cannot find out where. Could anyone help me out?

**Comment by karthik-balasubramanyam15** [comment]
I'm using Flipper 0.152.0, both manual & automatic config, yields iOS build failure - 'FBDefines/FBDefines.h' file not found. Is there anything specific I can do to resolve the issue? I have tried all the above solutions but no dice. Any help is much appreciated.

**Comment by billnbell** [comment]
usually you can add it to podspec the include.

**Comment by Muhammad-Sufian** [comment]
https://stackoverflow.com/questions/73894220/flipperkit-flipperclient-h-file-not-found
this resolved issue for me

**Comment by kdpadhiyar** [comment]
But what steps solved?
@Muhammad-Sufian 

I am facing same issue as @kuhnroyal  is asked to resolve.
@kuhnroyal Are you able to solve that issue?

**Comment by kuhnroyal** [comment]
Yes, I moved to Flutter a long time ago.
