### ISSUE TITLE
Discussion: network plugin should support full body filter to support graphql

### ISSUE THREAD

**Issue by henryzx** [facebook/flipper#487]
The problem is:

when it comes to **graphql** network requests, the domain are all the same...
It is basically impossible to find the request we want through filter.

So, 
1. Is there any plugin under development intended to support graphql?
2. Is there any hidden trick for this?
3. or we may include request header/request body/response header/response body into filter text.

looking forward any feedback~

**Comment by marshallcool** [comment]
will there be graphql support?
