### ISSUE TITLE
What about Cordova?

### ISSUE THREAD

**Issue by Baadier-Sydow** [facebook/flipper#49]
Are there any plans to add support for Cordova in the future?

**Comment by danielbuechele** [comment]
This is not on our internal roadmap, because it is not a use-case for us. But, if there is a community driven effort, I would be happy to support this.

**Comment by chawax** [comment]
Can't you already use Chrome or Safari dev tools with Cordova ?

**Comment by passy** [comment]
Hey everyone, I'm currently cleaning up some longstanding issues and enhancement proposals that have not seen any traction. Please feel free to comment if you still thing there is value in keeping this one on the backlog. :)
