### ISSUE TITLE
Issue: After upgrading React Native to 0.71.11, the Network plugin only shows requests to the localhost.

### ISSUE THREAD

**Issue by adenyx** [facebook/flipper#4916]
After updating React Native from 0.70.6 to 0.71.11, there seems to be an issue with the Network plugin. 
It is only showing requests to localhost from the beginning of the React Native app.
![image](https://github.com/facebook/flipper/assets/59793388/7ecea1e3-11de-45f8-9916-b91fbb425573)

Could someone help me with this issue? 
I followed the instructions on this page for the update:
https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.11

**Comment by v-tonguyen** [comment]
@adenyx 

Call FlipperConfiguration.enabled with a specific version in ios/Podfile, for example: :flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.190.0' })

NOTE: 0.190.0 -> current version react-native-flipper

Run pod install --repo-update in the ios directory.
