### ISSUE TITLE
Question: Android Handling Build Variants

### ISSUE THREAD

**Issue by mo-vericatch** [facebook/flipper#494]
Hi!
In the official documentation, we add a `debugImplementation` and `releaseImplementation`.

> ```
> repositories {
>   jcenter()
> }
> 
> dependencies {
>   debugImplementation 'com.facebook.flipper:flipper:0.23.1'
>   debugImplementation 'com.facebook.soloader:soloader:0.5.1'
> 
>   releaseImplementation 'com.facebook.flipper:flipper-noop:0.23.1'
> }
> ```

Then in the our Application class we initialize. 
This works perfectly ok until its ready to produce a `release` variant, which obviously means different dependencies. 

This creates an issue as the expected behaviour is to have `SoLoader` (and others) in the `no-op` dependency to make it work

This is from my base application class, not resolved when switching from `debug` to `release`

![image](https://user-images.githubusercontent.com/44822381/61496982-e1225400-a972-11e9-854d-e688ddf266db.png)

Is this not supported yet?
Am I missing something?

Thank you!

**Comment by tommytcchan** [comment]
I'm getting this as well -- the no-op library doesn't have any of the plugin class shells, leading to the issue you mentioned. There are no docs on handling this so I'm wondering if it's the developers that should be doing this -- or should I write these noop shells in that noop library and submit a pull request?

**Comment by franticn** [comment]
Because [no-op](https://github.com/facebook/flipper/tree/master/android/no-op/src/main/java/com/facebook/flipper) doesn't have package path `com.facebook.flipper.plugins.*`

**Comment by tommytcchan** [comment]
correct but that means that the no-op package is definitely missing some support for the regular lib, which has all of the plugin extension classes

**Comment by franticn** [comment]
> correct but that means that the no-op package is definitely missing some support for the regular lib, which has all of the plugin extension classes
Maybe @jknoxville can help us.

**Comment by jknoxville** [comment]
Hey guys, take a look at our [sample app](https://github.com/facebook/flipper/tree/7dae5771d96ea76b75796d3b3a2c78746e581e3f/android/sample) for reference. It initializes the client and plugins in a `FlipperInitializer` class, which there is a [debug](https://github.com/facebook/flipper/blob/7dae5771d96ea76b75796d3b3a2c78746e581e3f/android/sample/src/debug/java/com/facebook/flipper/sample/FlipperInitializer.java) and a [release](https://github.com/facebook/flipper/blob/7dae5771d96ea76b75796d3b3a2c78746e581e3f/android/sample/src/release/java/com/facebook/flipper/sample/FlipperInitializer.java) variant of.

The release variant doesn't do anything with flipper clients or plugins, so you don't get any build errors.

Does that answer your question?

**Comment by mo-vericatch** [comment]
@jknoxville Unfortunately its not that, the dependency is not imported at all because of the scope of the build variant. You can get away with it by using `implementation ... ` configuration scope, but then you will be including the flipper code with release version.

As a workaround until a lib support is available, I added the missing classes and did the no-op manually. Inside src, created packages per build variant as following:
![image](https://user-images.githubusercontent.com/44822381/63449180-6ecee480-c3f4-11e9-81cb-7f406fafa1f1.png)

Sample implementation for example `FlipperUtils`
```java
package com.facebook.flipper.android.utils;

import android.app.Application;

/**
 * No operation class to replace the original implementation that is mainly used for debugging.
 * Usually this is done by the library provider, but by this time, we have to make it manually.
 */
public class FlipperUtils {

    private FlipperUtils() {}

    public static boolean shouldEnableFlipper(Application application) {
        // No-op
        return false;
    }
}

```

**Comment by passy** [comment]
Hi folks, we have no plans on extending the `no-op` package to include any plugin code. This would run counter to how we advise the library to be used. As @jknoxville described, we recommend you centralise all your Flipper code in a `release` and a `debug` variant, so you don't have to rely on any plugin-specific imports in the release version of your app.

That way we can ensure that the footprint that the Flipper integration adds to your production build is a minimal as possible.
