### ISSUE TITLE
java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer

### ISSUE THREAD

**Issue by moulie415** [facebook/flipper#4957]
Android seems to crash whenever I try and debug, I'll go to select my device from the top left and it will just crash the app with this error in the reporter ```java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer```

**Comment by moulie415** [comment]
Never mind this was unrelated to flipper and was in fact related to react native sentry which needed an update

**Comment by CyxouD** [comment]
@moulie415 thank you for pointing to Sentry. Here is the [issue](https://github.com/getsentry/sentry-java/issues/2675), If someone also looks for it

**Comment by abdumutalSharp** [comment]
> Never mind this was unrelated to flipper and was in fact related to react native sentry which needed an update

Hi, how I do

**Comment by spyshower** [comment]
@abdumutalSharp https://learnenglishkids.britishcouncil.org/
