### ISSUE TITLE
Discussion: LeakCanary v2

### ISSUE THREAD

**Issue by justintuchek** [facebook/flipper#497]
Hi 👋 

I was just wondering if support for LeakCanary v2 was on anybody's written or mental roadmap?

If not, open to a PR? Not sure on the scope of work but would be willing to at least check it out!

Thanks 🙇

**Comment by passy** [comment]
Not on the roadmap at the moment, but *definitely* open for PRs. :)

**Comment by bizzguy** [comment]
According to the doc, Leak Canary 2 is still in beta.

`'com.squareup.leakcanary:leakcanary-android:2.0-beta-3'`

Moving to the new version would be good once it is stable.

**Comment by justintuchek** [comment]
Going to close out this issue since LeakCanary is no longer part of mainline since 0.25.0

Still an appetite but don't believe this needs to be on the Flipper repo
