### ISSUE TITLE
Question: How to programmatically highlight a row.

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#508]
I have created a plugin based on the "logs" plugin.  When the plugin starts, it shows some rows from the log file.  I would like to have the first row highlighted (and to run any code that runs when the row is highlighted by user interaction).  

The rows are displayed in a <SearchableTable> component.

Any ideas?  Thanks.

**Comment by jknoxville** [comment]
In general, a good way to find out how to do things like this is read the available props on the components to see if any does what you want.

You can see [here](https://github.com/facebook/flipper/blob/master/src/ui/components/table/ManagedTable.js#L115) in ManagedTable.js that there's a `highlightedRows` prop where you can specify this.

`onRowHighlighted` lets you specify a callback to run when a row is highlighted.

I'm not sure if that callback will be fired for initially selected rows, but if not you can just call that directly instead.
