### ISSUE TITLE
App name string overriden and set to "Yoga"

### ISSUE THREAD

**Issue by spectrl** [facebook/flipper#509]
## 🐛 Bug Report
I have a string named `app_name` which is used to set the `android:label` of my application in the AndroidManifest.xml file, which is then displayed as the app's name underneath its icon in the launcher. However since adding the Flipper dependency and setting it up, my app name is now showing up as "Yoga" (see screenshot).
This seems to be happening whenever I use `@string/app_name` to set some text. e.g. In the toolbar of an activity.

<img width="225" alt="Screenshot 2019-08-05 at 23 24 49" src="https://user-images.githubusercontent.com/5111666/62498765-403bf180-b7d8-11e9-9263-a2ec2ab170f2.png">

## To Reproduce
Set the `android:label` for your application or an activity in the AndroidManifest.xml file using the string resource `@string/app_name`.

## Expected Behavior
I would expect Flipper to not override my `app_name` string with its own, or wherever the "Yoga" string is coming from.

## Environment
Android 9 (Pie)
Flipper 0.23.4

**Comment by passy** [comment]
Oh wow, I had not seen/heard this before. I reckon this must come from a https://github.com/facebook/yoga/blob/e224a29d1cbfd4d662392a7c69e0939d9278c3cf/java/res/values/strings.xml. Would you mind opening an issue over there? I'm not sure why that's part of the top-level Java code. Could there for a good reason or an oversight.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
