### ISSUE TITLE
Flipper UI Issue Unable to see plugin list

### ISSUE THREAD

**Issue by MultidimensionalLife** [facebook/flipper#5200]
## 🐛 Bug Report

Issue regarding flipper UI. Please see the screenshot below.

<img width="933" alt="image" src="https://github.com/facebook/flipper/assets/38305614/dc906ffd-257c-4058-8397-451a8fe1a1cf">

## To Reproduce
1. Open Flipper Client
2. Click Add plugin

## Environment
Flipper Desktop Version 0.225.0
OS: Apple m2 (Ventura 13.5.1)

**Comment by gongshoudao** [comment]
+1

**Comment by gongshoudao** [comment]
![image](https://github.com/facebook/flipper/assets/4568329/5005d2d8-1f26-45ed-ba88-7dede23858f0)

**Comment by DarkShtir** [comment]
Same issue
Flipper Desktop Version 0.228.0
OS: Apple m1 (Ventura 13.5.2)

![Screenshot 2023-10-19 at 09 28 57](https://github.com/facebook/flipper/assets/31916981/3fd4e2dc-4c88-4d37-beb0-04fcd5c79705)

**Comment by devphilipcesar** [comment]
Any update on this issue?

**Comment by gianlucalippolis** [comment]
Hi all, @MultidimensionalLife i fixed this bug in this PR https://github.com/facebook/flipper/pull/5161 that has been merged today.
