### ISSUE TITLE
Flipper not being published on NPM

### ISSUE THREAD

**Issue by owens-ben** [facebook/flipper#5223]
NPM.js has not been updated since Aug 19

It seems like this was a problem in the past https://github.com/facebook/flipper/issues/4628

**Comment by owens-ben** [comment]
https://github.com/facebook/flipper/actions/workflows/publish-npm.yml

**Comment by eduardoborges** [comment]
+1

**Comment by 1nspir3d** [comment]
+1

**Comment by aliwatters** [comment]
https://github.com/facebook/flipper/releases/tag/v0.236.0 
https://www.npmjs.com/package/react-native-flipper -- 0.212

```
    TypeError: command.args.filter is not a function
```
https://github.com/facebook/flipper/actions/runs/6751037696/job/18354472378#step:7:47

@passy @mweststrate @lblasa  -- not sure who are the maintainers here (so sorry to ping if you're not)

**Comment by mweststrate** [comment]
Sorry this took so terribly long, but it seems the pipeline finished successfully again :) https://www.npmjs.com/package/flipper-pkg?activeTab=versions
