### ISSUE TITLE
Failed to start Flipper. Error: FlipperServerConfig has not been set for version `0.229.0`

### ISSUE THREAD

**Issue by hpelitebook745G2** [facebook/flipper#5228]
## 🐛 Bug Report
Open Flipper and I got this error message:
<img width="1338" alt="Screenshot 2023-10-19 at 7 03 12 PM" src="https://github.com/facebook/flipper/assets/27658429/f0a9415a-a7c0-4e97-bccc-575ab6aace56">

## To Reproduce
1. I was using version `0.228.0` and it was working. A bit buggy, when I switched theme without restarting, there's popup glitch.
2. Flipper couldn't connect to my device anymore.
3. Restarted and I got the notification that there's new version `0.229.0`.
4. Downloaded and installed in macOS Sonoma and I got the error above.

## Environment
Flipper Desktop version: v0.228.0 to v0.229.0
macOS: Sonoma 14.0
Android and iOS are irrelevant as they were working on my v0.228.0

**Comment by fmording** [comment]
Same issue here after installing new version. Although i was first asked to run this command: `sudo kill -9 $(lsof -t -i :52342)`. After running it and then reopening Flipper i get this exact message.

MacOS Sonoma 14.0
Flipper v0.229.0

**Comment by eirnym** [comment]
Same here

**Comment by d-p-2023** [comment]
same issue

**Comment by mtebele** [comment]
Same here

**Comment by caiodeambrosio** [comment]
Same here

**Comment by devethan** [comment]
Same here, macos sonoma 14.0

**Comment by redefinered** [comment]
same

**Comment by redefinered** [comment]
> > Same here, downgrade to v0.228.0 worked to me
> > https://github.com/facebook/flipper/releases/tag/v0.228.0
> 
> Same here, macos sonoma 14.0 Downgrade to `v0.228.0` is worked

worked for me too. who release 0.229.0? XD

**Comment by Kreshnik** [comment]
Same

**Comment by GeuntaBuwono** [comment]
this issue has been fixed at `0.230.0`

**Comment by hpelitebook745G2** [comment]
closing this ticket as it's been fixed with v[0.231.0](https://github.com/facebook/flipper/releases)

**Comment by vision72** [comment]
> Same...reverted to 0.228 with: brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/f4f2b75c75f0df059f224caaa486012baa740d51/Casks/f/flipper.rb

worked, thanks.
