### ISSUE TITLE
Unable to build in Android Studio

### ISSUE THREAD

**Issue by IgorGanapolsky** [facebook/flipper#523]
## 🐛 Bug Report

Cannot build my project after following Flipper directions.  Get this build error:
> Program type already present: androidx.mediarouter.R
java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
com.android.tools.r8.utils.AbortException: Error: Program type already present: androidx.mediarouter.R
Error: Program type already present: androidx.mediarouter.R

## To Reproduce

Follow gradle instructions here: https://fbflipper.com/docs/getting-started.html

## Expected Behavior

Everything should build, and I should be able to launch my project.

## Environment

A.S. 3.6 Canary 6

**Comment by passy** [comment]
Trying to repro this right now but everything I've tried so far seems to work, even with 3.6 Canary 6. Can you post the exact gradle command that's failing?

**Comment by IgorGanapolsky** [comment]
Just trying to run the project from Android Studio.  I gather that there
must be conflicting Gradle dependencies in my proj, as my company has
dozens of them.....

**Comment by passy** [comment]
@IgorGanapolsky I would still need the full log from it, because I've not been able to reproduce this.

**Comment by IgorGanapolsky** [comment]
It's the MediaRouter api from Tealium SDK.  That is the conflict.  Know
what I'm sayin?

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
