### ISSUE TITLE
Plugin install modal seem to be broken

### ISSUE THREAD

**Issue by hixus** [facebook/flipper#5262]
## 🐛 Bug Report
Plugin name and install button seem to have very narrow area. Also noticed Flipper title says unsupported.

Pretty sure I saw the fields correctly once but not anymore. Have tried to remove flipper and install again.

![CleanShot 2023-11-01 at 09 57 17](https://github.com/facebook/flipper/assets/1814734/612b1f64-bece-4aa2-9e2e-62f7c737a889)

## To Reproduce
Install latest version from https://fbflipper.com/ 
Open install plugins modal

## Environment
Flipper 0.233.0, OSX Sonoma

**Comment by heath-clink** [comment]
duplicate of https://github.com/facebook/flipper/issues/5124
See also https://github.com/facebook/flipper/pull/5161

**Comment by hixus** [comment]
Thanks @heath-clink, suggested workaround helped.
