### ISSUE TITLE
Flipper not starting, showing Blank screen in Windows 10

### ISSUE THREAD

**Issue by deepakumar8** [facebook/flipper#5292]
## 🐛 Bug Report

Flipper not starting, showing Blank screen in Windows 10

## To Reproduce
Run the flipper exe file in the Windows 

<img width="943" alt="Screenshot_6" src="https://github.com/facebook/flipper/assets/110049543/5f4c545f-8a71-43a6-93d4-8c8d767fcd72">
<img width="411" alt="Screenshot_7" src="https://github.com/facebook/flipper/assets/110049543/8ea75a44-ef01-40ee-9b68-6bf58d80e8bf">

**Comment by rafaelfndev** [comment]
I had the same problem, so I downloaded a few older versions, and one of them showed the message telling me to "install OpenSSL" (maybe this warning was removed from this version, but it's probably necessary too).

After I installed OpenSSL, I added the OpenSSL /bin folder to the environment variable and restarted the system. So I opened the old version and it worked, then I redownloaded the latest version and it also worked. Maybe it could be your problem too.

I downloaded OpenSSL here:
https://slproweb.com/products/Win32OpenSSL.html

**Comment by sibeduli** [comment]
@rafaelfndev i don't think i want to change my OpenSSL as a quick hack here, i have the newest one already, don't want to downgrade or anything

**Comment by deepakumar8** [comment]
@rafaelfndev  Yes you are right. I have also done the same steps. Previously in my system I don't have OpenSSL. After installing older version I got to know OpenSSL is necessary in flipper. I have installed the OpenSSL then run the newest version it works. 

 Basically in newer version there was no error/warning in flipper if OpenSSL was not there

**Comment by blamay** [comment]
Using chocolatey to install OpenSSL fixed the problem for me. `choco install openssl`. 
I think chocolatey resolves some PATH issues that the download mentioned above sometimes does not handle.
