### ISSUE TITLE
Docs translation

### ISSUE THREAD

**Issue by romainwn** [facebook/flipper#53]
Is there any plans for internationalisation ?
I would love to help translate the docs

**Comment by danielbuechele** [comment]
We can not provide this internally. Community translations are definitely appreciated. We are using Docusaurus to generate our website, which supports [translations](https://docusaurus.io/docs/en/translation).
One thing I want to make sure when adding translations is that the translations are well maintained and correct. It could become super confusing, when we changing APIs and change the English docs, but other languages still refer to older versions.

Which language would you be able to provide?

**Comment by romainwn** [comment]
I definitely take a look at Docusaurus in the next few days :) 

I know that Electron uses [Crowdin](https://crowdin.com/project/electron) but I didn't get a chance to take a good look at it yet.

I would be able to provide the French part !

**Comment by passy** [comment]
Closing this as we've decided against hosting/supporting multiple languages for now.
