### ISSUE TITLE
Discussion: speeding up iOS build

### ISSUE THREAD

**Issue by jamesdixon** [facebook/flipper#531]
Hi, Flipper seems like a really great tool but the friction caused by the setup process and the build time when launching my app makes it tough to continue to use.

I had to apply one of the workarounds in #254 and while it worked, the build time for iOS is insane and really brings my system a crawl (MBPro 2015 Quad-Core). I'm running Flipper for a Flutter app and while Flutter's hot reload is awesome, if I have to stop the app and restart it, it goes through the entire Pod Install and XCode Build process again, which takes over 10 minutes.

I'm no expert on this subject and have no suggestions other than maybe reducing the number of dependencies needed at a build time.

All that said, is anyone else experiencing this issue? Are there solutions?

Thanks!

**Comment by priteshrnandgaonkar** [comment]
So for the first install, we download and build openssl which takes a lot of time. But the subsequent pod install's should not take that long. While running `pod install`, run it in a verbose mode to get the logs, to understand at what step it is taking a long time. 

Stopping the app and restarting it shouldn't rebuild the openssl as it should be cached.

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
