### ISSUE TITLE
Question: network plugin is not showing 

### ISSUE THREAD

**Issue by Gauravpatki** [facebook/flipper#532]
Getting following error 
<img width="361" alt="Screenshot 2019-09-01 at 11 30 11 AM" src="https://user-images.githubusercontent.com/13919994/64072437-e54ccb80-ccab-11e9-8058-82bec82e668c.png">

Code 
 ` OkHttpClient.Builder builder1 = new OkHttpClient.Builder();
  builder1.addNetworkInterceptor(new FlipperOkhttpInterceptor( new 
     NetworkFlipperPlugin()));`

 Application code 
   ` SoLoader.init(this, false);
         if (BuildConfig.DEBUG && FlipperUtils.shouldEnableFlipper(this)) {
            final FlipperClient client = AndroidFlipperClient.getInstance(this);
            client.addPlugin(new InspectorFlipperPlugin(this, DescriptorMapping.withDefaults()));
            client.addPlugin((new NetworkFlipperPlugin()));
            client.start();
        }`

on desktop app its just showing crash and log plugin 
<img width="540" alt="Screenshot 2019-09-01 at 11 37 19 AM" src="https://user-images.githubusercontent.com/13919994/64072510-4a54f100-ccad-11e9-9cc9-7303e2c18659.png">

**Comment by passy** [comment]
@Gauravpatki Could you please check if `/opt/android_sdk` is the correct path to your Android SDK or otherwise set the `ANDROID_HOME` environment variable to the correct one?

**Comment by burntcookie90** [comment]
I ran into this. 

Initialized your network plugin and interceptor ahead of time and then attach the same instances to okhttp as you do flipper.

**Comment by passy** [comment]
@burntcookie90 That's likely a separate issue. Based on the bug description by OP, there is no connection to between Flipper and the SDK at all. If that's still an issue for you, can you open a separate issue? I'll close this one here for staleness.
