### ISSUE TITLE
Docs: Poor documentation over Sandbox feature

### ISSUE THREAD

**Issue by haroldolivieri** [facebook/flipper#535]
First of all, great tool.
The potential here is amazing.

Secondly, it can be totally my lack of attention but it is not clear at all how to set up a `SandboxFlipperPluginStrategy`.

What is expected to be the keys and values in `getKnownSandboxes()`'s map and what does the method `setSandbox()`?

**Comment by kxfang** [comment]
Also it looks like the Sandbox plugin is disabled by GK. Is that intentional?

![image](https://user-images.githubusercontent.com/2383950/64200368-5f22b780-ce5a-11e9-845b-3b40e714f069.png)

**Comment by jknoxville** [comment]
From looking at the code, I believe you just need to implement a `SandboxFlipperPluginStrategy`, and pass it in, when constructing the plugin.

`setSandbox` should override the sandbox within your app. It will be called on your strategy when the user enters a string as their sandbox. What this does is technically up to the implementation, but it could for example, set the base url for outgoing requests from the app to `staging.myapp.com` for example. How this is done will depends on your app.

`getKnownSandboxes` should return a map of predefined options, keyed by name. For example, you could provide this as a map:
```
{
test: test.myapp.com,
staging: staging.myapp.com,
production: prod.myapp.com
}
```
to let the user select from a list without typing.

Feel free to update the docs:
https://github.com/facebook/flipper/blob/master/docs/setup/sandbox-plugin.md

**Comment by jbfitb** [comment]
I came here to ask what the Sandbox plugin does. Docs are pretty sparse. Happy to update the docs if you tell me what to say 😄 

https://fbflipper.com/docs/setup/sandbox-plugin.html
