### ISSUE TITLE
v0.23.6 isn't available on jcenter

### ISSUE THREAD

**Issue by saket** [facebook/flipper#542]
## 🐛 Bug Report
Hey folks, it looks like artifacts for the latest version `0.23.6` are missing from jcenter. The latest version visible is `0.23.5`:
https://bintray.com/facebook/maven/com.facebook.flipper%3Aflipper

## To Reproduce
Add `v0.23.6` to gradle:

```gradle
com.facebook.flipper:flipper:0.23.6
```

**Comment by passy** [comment]
Thanks for the report. There's been an issue with the release job, but we should fix that within the next day.

**Comment by passy** [comment]
Apologies for the delay. There were a bunch of nested issues on Circle CI with the build. Snapshots are back running and a new release is currently landing, which should hopefully fix this within the next hour or so.

**Comment by passy** [comment]
v0.23.7 is now available.

**Comment by passy** [comment]
v0.23.7 is now available. Thanks for your patience!

**Comment by b95505017** [comment]
It says `Could not find com.facebook.fbjni:fbjni:0.0.1` after upgraded to v0.23.7

**Comment by technoir42** [comment]
Same here, can't use 0.23.7 because of `fbjni`.
