### ISSUE TITLE
Question: I accidentally deleted the Network plug-in, how to restore it

### ISSUE THREAD

**Issue by proc07** [facebook/flipper#5457]
<img width="244" alt="截屏2024-01-31 11 43 07" src="https://github.com/facebook/flipper/assets/16809535/83022404-85ae-45c9-9bf4-78d930cb32a7">

**Comment by yunyami0605** [comment]
i faced to this problem. So, I solved below
go to setting > Reset all local storage based state > 'Reset all state' button click and restart the flipper app

**Comment by proc07** [comment]
> i faced to this problem. So, I solved below go to setting > Reset all local storage based state > 'Reset all state' button click and restart the flipper app

very thanks
