### ISSUE TITLE
403 for fbjni-0.0.1

### ISSUE THREAD

**Issue by casolorz** [facebook/flipper#546]
Since this morning I've had an issue compiling, the error is strange because it mentions moat, I have no idea why. 

```
> Could not resolve all task dependencies for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.facebook.fbjni:fbjni:0.0.1.
     Required by:
         project :app > project :androidutils > com.facebook.flipper:flipper:0.23.7
      > Could not resolve com.facebook.fbjni:fbjni:0.0.1.
         > Could not get resource 'https://s3.amazonaws.com/moat-sdk-builds/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom'.
            > Could not GET 'https://s3.amazonaws.com/moat-sdk-builds/com/facebook/fbjni/fbjni/0.0.1/fbjni-0.0.1.pom'. Received status code 403 from server: Forbidden
```

These are my gradle lines:
```
debugApi 'com.facebook.flipper:flipper:0+'
debugApi 'com.facebook.soloader:soloader:0+'
releaseApi 'com.facebook.flipper:flipper-noop:0+'
```

If I change to `0.23.6` that I'm guessing is what I what I was using yesterday, when it worked fine, then it gives me the same error but with `0.23.6`. 

Any idea what could be wrong? literally went from compiling fine last night to not compiling this morning.

**Comment by b95505017** [comment]
I think that is causing by `fbjni` not synced to jCenter yet, so you have to add [facebook bintray repository manually currently](https://github.com/facebook/flipper/blob/master/build.gradle#L34-L37).

**Comment by casolorz** [comment]
That appears to fix it, thanks. 
Is there a downside to having that repository there?

**Comment by passy** [comment]
Sorry for the late response. Yes, adding that repository to your list will fix the resolution and doesn't come with any downsides. I'm working on getting it published through the proper channels.

**Comment by casolorz** [comment]
Thanks, marking this as closed.

**Comment by ZacSweers** [comment]
It does come with a downside though - now every user that has this issue
has to come dig through the issue tracker to find this issue. A dependency
on mavencentral should almost never have transitive dependencies on things
not in also mavencentral. The only real exemptions to this are Android
libraries depending on things in Google's maven repo and Kotlin libraries
depending on things in kotlinx

**Comment by passy** [comment]
Yes, let's keep this open until it's actually fixed.

**Comment by pakerfeldt** [comment]
Is there an ETA on this? Because adding a new repository might be trickier than you think in a large org :)

**Comment by passy** [comment]
@pakerfeldt I should have a fix ready for this by the end of the day. Fingers crossed!

**Comment by passy** [comment]
Published this, which should hopefully take care of this. https://github.com/facebook/flipper/releases/tag/v0.23.8

One quick note: v0.24.0 is already soft-published and does *not* contain this version bump. I'll publish v0.24.1 later today or tomorrow which will include the same change. Please let me know if this works for you. :)

**Comment by guilherme-pereira-ifood** [comment]
`0.23.8` worked for me! Thanks @passy

**Comment by pakerfeldt** [comment]
Indeed it works, thanks!

**Comment by Ghedeon** [comment]
@passy so, what exactly stops us from using `0.24.0` fully? Somebody wrote that fbjni is not synced to jCenter yet. Is that the cause? But that was like 10 days ago. Just to make it clear, there is nothing to fix and we're waiting for the sync to happen?

**Comment by casolorz** [comment]
Not sure what happened but this was working fine yesterday and today when I went to compile I got this error, no changes on my end. I do see that I now have 0.24.1. 

> FATAL EXCEPTION: FlipperEventBaseThread
> Process: myprocess, PID: 29877
> java.lang.ExceptionInInitializerError
> at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:24)
> Caused by: java.lang.IllegalStateException: NativeLoader has not been initialized. To use standard native library loading, call NativeLoader.init(new SystemDelegate()).
> at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:36)
> at com.facebook.jni.HybridData.<clinit>(HybridData.java:31)
> ... 1 more
> FATAL EXCEPTION: FlipperConnectionThread
> Process: myprocess, PID: 29877
> java.lang.NoClassDefFoundError: com.facebook.flipper.android.EventBase
> at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:24)
> Caused by: java.lang.ExceptionInInitializerError
> ... 1 more
> Caused by: java.lang.IllegalStateException: NativeLoader has not been initialized. To use standard native library loading, call NativeLoader.init(new SystemDelegate()).
> at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:36)
> at com.facebook.jni.HybridData.<clinit>(HybridData.java:31)
> ... 1 more

**Comment by casolorz** [comment]
I should mention `com.facebook.flipper.android.EventBase` is there, I can see it on Android Studio.

**Comment by passy** [comment]
@casolorz That's an error in SoLoader. If you pin it to `0.8.0`, that should fix it. I'll put out another patch release today that does that directly in the Flipper dependency.

**Comment by passy** [comment]
https://github.com/facebook/flipper/releases/tag/v0.24.2 is out now. The original issue should definitely be addressed now, but please feel free to open a new issue if there's still something not working correctly with the release. Thanks for all the reports and feedback!
