### ISSUE TITLE
Question: Support for React Native 0.73

### ISSUE THREAD

**Issue by rachitdua** [facebook/flipper#5482]
Hey,

I am working on upgrading react native to v0.73.x and they [seemed to have dropped](https://react-native-community.github.io/upgrade-helper/?from=0.72.10&to=0.73.4#RnDiffApp-android-gradle.properties) `FLIPPER_VERSION` variable from `gradle.properties`.

This results in Android Studio sync failing because `FLIPPER_VERSION` is not defined.

Any help on upgrading flipper to support react native v0.73.x is appreciated.

**Comment by anujsachan1990** [comment]
@rachitdua read this:

https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0641-decoupling-flipper-from-react-native-core.md

https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#deprecated-debugging-features
