### ISSUE TITLE
Electron support is removed. How to use it now? 

### ISSUE THREAD

**Issue by diskree** [facebook/flipper#5510]
> Important Announcement
> Flipper is moving away from its Electron distribution to an in-Browser experience.
> 
> How does this affect me?
> 
> Functionality hasn't changed. The UI remains unchanged. Flipper will run in your default browser instead of a standalone application. If you build from source, Flipper will open in the browser instead of a standalone app. We also provide a MacOS app for the Flipper runtime which can be run and will also open Flipper in the browser.
> 
> The last Electron release is [v0.239.0](https://github.com/facebook/flipper/releases/tag/v0.239.0). As such, future releases will not include Electron artifacts.

How to use it now? I launched an android application that has a flipper support and nothing opened in my browser. What should I do with the dmg file?

**Comment by diskree** [comment]
Why didn't you warn about this change in advance? What do you recommend doing now to make it look like before? Do I need to install another browser? I don't want to use it like that, it's very inconvenient

**Comment by camilossantos2809** [comment]
I have to download Chrome, but actually it simply opens a web page in http://localhost:52342/ with the same UI.

**Comment by diskree** [comment]
I still don't understand how to run this damn new flipper. I need to download tgz, but what should I do with it next? I'm not a flipper developer to understand how to use it. your wiki page doesn't explain anything

**Comment by diskree** [comment]
Does anyone know if it is possible to bring back support for electron, maybe someone is developing a fork?

**Comment by diskree** [comment]
the answer was found here https://github.com/facebook/flipper/issues/5619
