### ISSUE TITLE
Discussion: Dark theme

### ISSUE THREAD

**Issue by troy-lamerton** [facebook/flipper#552]
## Steps to reproduce

1. Use mac with dark theme
2. Open flipper.app
3. Flipper's white UI burns your eyes

## Question

Which files/modules would need changing to add dark mode?

**Comment by danielbuechele** [comment]
Hey Tory,
that's something that is on my list as well. Unfortunately, we didn't have the time to implement this, yet. But I'm fully supportive of adding dark mode support!

To check if the system is in dark mode, electron provides an API: `require('electron').remote.systemPreferences.isDarkMode()`. All colors that we are using are defined in this file: https://github.com/facebook/flipper/blob/master/src/ui/components/colors.tsx
So a first step could be simply returning a different set of colors from this file, while dark mode is active.

**Comment by troy-lamerton** [comment]
Looking like I won't get to this as my priorities have changed. Would be glad for someone else to take the lead.

**Comment by troy-lamerton** [comment]
![AF90B3C1-3953-4CB1-B44A-2AF7750AA848_1_105_c](https://user-images.githubusercontent.com/13446008/72658906-bcf20f00-39b7-11ea-81aa-bc3935eb215c.jpeg)

I inverted all colors.

**Comment by lucasbento** [comment]
@danielbuechele @passy: where did those colours come from? any chance that someone could provide their _matches_ for dark mode?

The easiest part is to identify if the OS is running on dark mode, deciding which hex to use for specific parts is the tricky one.

**Comment by osamaaamer95** [comment]
As someone who works with dark mode on, I would love to work on this if someone else isn't already.

**Comment by lucasbento** [comment]
You are more than welcome to work on it @osamaaamer95 😄

**Comment by zhigang1992** [comment]
Would it be possible to integrate something like https://chrome.google.com/webstore/detail/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by lukebars** [comment]
@osamaaamer95 are you currently working on it? I could spare some time and do it / help with something

**Comment by osamaaamer95** [comment]
@lukebars yes, I started going through the codebase and am familiarizing myself. I have full time work though, so anyone is welcome to collaborate!

**Comment by osamaaamer95** [comment]
![image](https://user-images.githubusercontent.com/12623498/79547903-0c76d280-80ae-11ea-9b88-041f0f4b23b5.png)

Main UI elements are done, but I am not fully comfortable with the approach @danielbuechele suggested. Most colors are named `light<variation>` and returning a different set would mean I have to do something like this:

```javascript
const baseColors = {
  // existing color palette
}

export const colors = {
  ...baseColors,
  ...(SHOULD_USE_DARK && {
    // return overrides for dark mode
    light50: baseColors.dark50, 
    macOSTitleBarBackgroundTop: '#434444'
}
```

When a developer wants an element to have the color `light50`, but dark mode overrides it, I think it is semantically incorrect. UI elements should use a key which describes the **element** instead of it's **color** when the color is mutable. Overriding `macOSTitleBarBackgroundTop` instead of `light50` just makes more sense.

**Comment by ezranbayantemur** [comment]
@osamaaamer95  Looks amazing! I hope it will be implement the app.

**Comment by whenmoon** [comment]
Guys I have just started using Flipper and it is amazing but my eyes are buuuuuurning!  :)

**Comment by lukebars** [comment]
@danielbuechele @nikoant got few minutes for this ? https://github.com/facebook/flipper/issues/552#issuecomment-615117097

**Comment by mweststrate** [comment]
As a short update on this, we are looking into standardizing on a well established publicly available component library, probably ant.design. With that we will also start to support dark mode.

**Comment by mweststrate** [comment]
This is planned, so closing the issue for now.

**Comment by troy-lamerton** [comment]
What's the status of this?

Does the label `fix-in-sandy` mean it is being worked on?

**Comment by mweststrate** [comment]
Dark mode is available in the Flipper settings. Some plugins and core components don't respect it yet though, that is WIP.

**Comment by rikur** [comment]
I can't seem to disable dark mode.. and some of the non-conforming plugins(?) are nearly unusable. I have to CMD+A select all to be able to read the text of a diff view.

**Comment by mweststrate** [comment]
You might need to do apply instead of apply + restart

**Comment by rikur** [comment]
@mweststrate thanks, but didn't seem to work. It's ok, I'll manage until the dark theme support is better. Flipper is awesome 👍 

![Screen Shot 2021-08-13 at 9 20 11 PM](https://user-images.githubusercontent.com/4004/129074487-957adbb4-afd7-4179-b333-23f95ffaf3b9.png)

**Comment by mweststrate** [comment]
Strange! You can try that "reset all state" button as alternative, that
should work :)

**Comment by rikur** [comment]
Didn't help, but like I said, it's not that important :)

**Comment by ManuViola77** [comment]
I came here to comment on that issue that disabling the dark mode didn't work, but with tapping only apply and not apply and restart worked great, thanks! 

Also actually came to say that navigation plugin with dark mode had invisible things, but is already reported so all good, will use white mode til that is fixed.

Love flipper, thanks!
