### ISSUE TITLE
How to install flipper server on linux?

### ISSUE THREAD

**Issue by kuchaguangjie** [facebook/flipper#5523]
Using react-native to develop android app.
When click `Open Debugger` from android phone, the dev server on my linux shows:
> info Launching JS debugger...
>warn Attempting to debug JS in Flipper (deprecated). This requires Flipper to be installed on your system to handle the 'flipper://' URL scheme.

So, I tried to install flipper on my linux laptop, but didn't figure out how:
- The download link from https://fbflipper.com/docs/getting-started/ is broken: https://www.facebook.com/fbflipper/public/linux
- I tried to download from github release, but after uncompress got a `package/` dir, which:
  - can't failed to installl via `pnpm i`
  - failed to run via `node server.js`

So, how to get a flipper executable for linux that can be run directly ?

**Comment by kuchaguangjie** [comment]
Ok, I've install & started flipper via `yarn`, but still got:
> warn Attempting to debug JS in Flipper (deprecated). This requires Flipper to be installed on your system to handle the 'flipper://' URL scheme.

**Comment by kuchaguangjie** [comment]
Just switched to `expo`, which is easier to use I think.

**Comment by yogirajc** [comment]
> Just switched to `expo`, which is easier to use I think.

Doesn't seem as a solution to the original issue

It is still not working -
`╰─ ./server.js     
[flipper-server] Starting flipper server with pre-bundled UI
2024-03-31T10:10:47.433Z [FileStreamRotator] Logging to:  /home/abc/Downloads/package/static/flipper-server-log.out
2024-03-31T10:10:47.434Z [FileStreamRotator] Rotating file:   size: 1048576
Server startup error:  TypeError: (0 , flipper_common_1.addLogTailer) is not a function
    at initializeLogger (/home/yogirajc/Downloads/package/lib/logger.js:47:39)
    at async start (/home/yogirajc/Downloads/package/lib/startServer.js:109:5)`

**Comment by ckyleda** [comment]
The flipper documentation for Linux installs is extremely poor. From the readme:

```
yarn install
yarn flipper-server
```

The install command works with some finagling, but `yarn flipper-server` reports `error Command "flipper-server" not found.` - the install instructions packaged with the linux distribution are essentially non-functional.

**Comment by xilin** [comment]
`yarn start` also work for pre-package linux distribution.
