### ISSUE TITLE
Security:Insecure Transport

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/flipper#553]
http protocol is not authenticated and encrypted, please use https protocol
https://github.com/facebook/flipper/blob/master/scripts/start-dev-server.js#L107

**Comment by jknoxville** [comment]
I've changed this to only listen in localhost, but as it's just the development server, I don't think there's any need for this to be encrypted. More detail in the referenced commit.
Please let me know if there was some other reason I missed.
