### ISSUE TITLE
Android Gradle || Failed to resolve: com.facebook.flipper:flipper:0.252.0

### ISSUE THREAD

**Issue by sumit-jha-Pw** [facebook/flipper#5578]
In the Current version `v0.252.0` Gradle Build is failing.
While it's getting compiled with `v0.250.0`.

**Comment by sarvarrose** [comment]
Latest version available on [MVN Repository](https://mvnrepository.com/artifact/com.facebook.flipper/flipper) is `v0.250.0`.
