### ISSUE TITLE
[Windows][v0.24] Cannot find module 'p-map'

### ISSUE THREAD

**Issue by Strime** [facebook/flipper#558]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/8624527/65436830-088a1700-de23-11e9-92ab-3244f756f5ba.png)

## To Reproduce
Unzip [v0.24](https://github.com/facebook/flipper/releases/tag/v0.24.0).
Launch it

## Environment
Windows 10

**Comment by jknoxville** [comment]
Thanks for letting us know, I can confirm it's impacting mac as well.
Looking into it now.

**Comment by Strime** [comment]
v0.24.1 fixed it ! 
Well done.
