### ISSUE TITLE
"Could not find com.facebook.react:flipper-integration" error with new Android Studio and react native 0.73.7

### ISSUE THREAD

**Issue by amir-ibrahim** [facebook/flipper#5586]
Could not find com.facebook.react:flipper-integration:.

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:flipper-integration:.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at

<img width="1510" alt="Screenshot 2024-04-24 at 12 41 49 PM" src="https://github.com/facebook/flipper/assets/41516271/97687d93-3ba9-4197-b06d-aa075b22f7ad">

## To Reproduce

  new Android Studio and react native 0.73.7

## Environment

   React native 0.73.7 + Android Studio latest version ( Android Studio Iguana | 2023.2.1 Patch 2 )

**Comment by amir-ibrahim** [comment]
thank God, so the issue was in the Flipper integration because they removed it from the  React Native as the new version of RN  0.74.0 is launched for more info: 
https://github.com/react-native-community/discussions-and-proposals/pull/641

**Comment by SanaButt01** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:flipper-integration:.
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 17s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'. > Could not find com.facebook.react:flipper-integration:. Required by: project :app * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 17s.
info Run CLI with --verbose flag for more details.

**Comment by SanaButt01** [comment]
what can i do ? i cannot understand it

**Comment by SanaButt01** [comment]
i have this error in react native latest version

**Comment by ashishAmz** [comment]
how to resolve this issue?

**Comment by SanaButt01** [comment]
> how to resolve this issue?

i also dont know

**Comment by amir-ibrahim** [comment]
@SanaButt01, @ashishAmz  They removed the flipper from the new React Native 0.74, now you have to specify the flipper version when using it

android sample:
old:
implementation("com.facebook.react:flipper-integration")
new:
implementation("com.facebook.react:flipper-integration:0.73.7")

**Comment by ashishAmz** [comment]
Thanks @amir-ibrahim, that issue got resolved but now getting below issue,
Duplicate class com.facebook.react.flipper.ReactNativeFlipper found in modules jetified-flipper-integration-0.73-debug.7-debug-runtime (com.facebook.react:flipper-integration:0.73.7) and jetified-react-android-0.74-debug.1-debug-runtime (com.facebook.react:react-android:0.74.1)

**Comment by amir-ibrahim** [comment]
@ashishAmz are you using RN 0.74 or 0.73.7?
if you are using 0.74 remove flipper (deprecated)
if you are using 0.73.7 it should work also try to update to 0.73.8
+ Clean your build files

**Comment by khanhvohoangvib** [comment]
for me it's caused by @types/react-native-htmlview, I removed this one and then I can build normally

**Comment by Maksim-creator** [comment]
If you are just bumped your expo version to 51. 

Do: `npx expo prebuild --clean` before building Android build
