### ISSUE TITLE
Custom plugin issue when start Flipper.exe

### ISSUE THREAD

**Issue by Strime** [facebook/flipper#560]
## 🐛 Bug Report
I'm trying to write my first flipper plugin.
Obviously I know that _'C:\Users\gsancassani\flipper-plugins\FileReader\D:\flipper\resources\app\package.json'_ is not a correct path, but I didn't find how to fix it by reading your documentation.

## To Reproduce
Content of my ~/.flipper/config.json:
![image](https://user-images.githubusercontent.com/8624527/65513894-75adb300-dedc-11e9-96a4-3777686bc0ae.png)

## Expected Behavior
Plugin not found (even if application is sending data)
![Capture](https://user-images.githubusercontent.com/8624527/65513824-4f881300-dedc-11e9-8159-f9acf4b61cff.PNG)

Issue when start Flipper.exe
```
Watching for plugin changes
Compiling FileReader...
Failed to construct transformer:  { Error: Cannot parse C:\Users\gsancassani\flipper-plugins\FileReader\D:\flipper\resources\app\package.json as JSON: ENOENT: no such file or directory, open 'C:\Users\gsancassani\flipper-plugins\FileReader\D:\flipper\resources\app\package.json'
    at Object.<anonymous> (D:\flipper\resources\app\node_modules\jest-haste-map\build\worker.js:167:15)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\flipper\resources\app\node_modules\jest-haste-map\build\worker.js:78:24)
    at _next (D:\flipper\resources\app\node_modules\jest-haste-map\build\worker.js:98:9)
    at D:\flipper\resources\app\node_modules\jest-haste-map\build\worker.js:103:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\flipper\resources\app\node_modules\jest-haste-map\build\worker.js:95:12)
    at Object.worker (D:\flipper\resources\app\node_modules\jest-haste-map\build\worker.js:120:18)
    at execFunction (D:\flipper\resources\app\node_modules\jest-worker\build\workers\processChild.js:155:17)
    at execHelper (D:\flipper\resources\app\node_modules\jest-worker\build\workers\processChild.js:139:5) type: 'Error' }
Plugin FileReader is ignored, because it could not be compiled.
```

## Environment
Windows 10
Flipper v0.24.1
Plugin code:
index.tsx:
```
import {FlipperPlugin} from 'flipper';

export default class extends FlipperPlugin {
  render() {
    return 'hello world';
  }
}

```

package.json
```
{
  "name": "FileReader",
  "version": "1.0.0",
  "main": "index.tsx",
  "license": "MIT",
  "keywords": ["flipper-plugin"],
  "icon": "apps",
  "title": "File reader",
  "dependencies": {}
}
```

Thanks for your help :)

edit: simple workaround is to clone flipper repo and add custom plugin into _src\plugins_

**Comment by passy** [comment]
Thanks for the report, @Strime! That looks like an issue with our path resolution on Windows. Sorry about that. I don't have a good testing environment for this right now, but I'm taking a look.

**Comment by passy** [comment]
@Strime  Sorry, took me a while to get my windows setup going. I couldn't reproduce this directly but I noticed that you were using unescaped backslashes. You will want to change that to `C:\\Users\\gsancassani\\flipper-plugins`.

For me, plugin loading worked once I had the correct path formatting figured out.

**Comment by Strime** [comment]
I did a try with ` "pluginPaths":["~//.flipper//flipper-plugins//"]`, but I got same issue. 

Fun fact is when I remove index.tsx from my plugin folder, path resolution is correct on first error 

![image](https://user-images.githubusercontent.com/8624527/65878245-dd0cac80-e38d-11e9-9c7a-4b830158ec8a.png)

**Comment by passy** [comment]
@Strime The double forward slashes will probably be ignored; this will only be relevant if you use backslashes. I don't think we currently support loading `.tsx` directly. For now, you'll probably need to set up a build pipeline for your plugin so you can import a compiled `.js` file instead.

**Comment by Strime** [comment]
I actually moved Flipper.exe from `D:/Flipper` to `~/Flipper` and it works :)
