### ISSUE TITLE
Android app release build failed becouse of unresolved references

### ISSUE THREAD

**Issue by Nikron9** [facebook/flipper#561]
## 🐛 Bug Report
On debug build variant everything works ok, but release is not possible to build due to lack of references. 

![image](https://user-images.githubusercontent.com/26006585/65602829-d6082780-dfa4-11e9-9c1d-4313bf367cfe.png)

## To Reproduce
Add dependencies 
```
    debugImplementation 'com.facebook.flipper:flipper:0.24.2'
    debugImplementation 'com.facebook.soloader:soloader:0.8.0'
    debugImplementation 'com.facebook.flipper:flipper-network-plugin:0.24.2'

    releaseImplementation 'com.facebook.flipper:flipper-noop:0.24.2'
```

Add network interceptor to your OkHttpClient

```        
client = OkHttpClient.Builder()
                .addNetworkInterceptor(FlipperOkhttpInterceptor(ServiceResolver.get()))
                .build()
```
Build release.

**Probably we need noop version for network-plugin.**

## Expected Behavior

Build success as on debug build variant.

## Environment
Android App

**Comment by passy** [comment]
Thanks for the report, @Nikron9.

We will not include empty interfaces for plugins as this would promote bad practices. We instead recommend to separate the debug and release setup code of your app itself as discussed here: https://github.com/facebook/flipper/issues/158#issuecomment-502031144

**Comment by e16din** [comment]
I try to use Flipper 0.126.0 and have the same problem. 

How to fix it?
