### ISSUE TITLE
Is my flipper hopelessly bricked/broken?

### ISSUE THREAD

**Issue by Todder82** [facebook/flipper#5664]
So a friend sold me his flipper before moving out of state. He gave me very vague directions on how to set it up and update the firmware. I was attempting to do just that but while the firmware was being installed I got a message that said the firmware was not installed properly due to an error. The main issueis that the flipper itself will not power on. I have tried to do the hard reset using the left arrow and back button and holding down the center button along with the back button for 30 seconds and nothing. Did I break it somehow? Is it fixable? Someone please help....

**Comment by passy** [comment]
I think you're talking about a different Flipper? This isn't Flipper Zero.
