### ISSUE TITLE
Getting "target has transitive dependencies that include statically linked binaries" error

### ISSUE THREAD

**Issue by keshavamurthy1** [facebook/flipper#606]
Hi team, im getting below error at the end of "pod install" 
I have followed instructions from : https://fbflipper.com/docs/getting-started.html#cocoapods

Kindly help me to solve it.

[!] The 'Pods-App-target' target has transitive dependencies that include statically linked binaries: (/Users/keshavgn/Desktop/Projects/halodoc-ios/Pods/CocoaLibEvent/lib/libevent.a, /Users/keshavgn/Desktop/Projects/halodoc-ios/Pods/CocoaLibEvent/lib/libevent_core.a, /Users/keshavgn/Desktop/Projects/halodoc-ios/Pods/CocoaLibEvent/lib/libevent_extra.a, /Users/keshavgn/Desktop/Projects/halodoc-ios/Pods/CocoaLibEvent/lib/libevent_pthreads.a, /Users/keshavgn/Desktop/Projects/halodoc-ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a, and /Users/keshavgn/Desktop/Projects/halodoc-ios/Pods/OpenSSL-Universal/ios/lib/libssl.a)

**Comment by priteshrnandgaonkar** [comment]
Which cocoapods version are you using ?

**Comment by priteshrnandgaonkar** [comment]
If you are using `use_framework!`. Make sure you add the following

```
   $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
     'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
     'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
     'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
   pre_install do |installer|
     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
     installer.pod_targets.each do |pod|
         if $static_framework.include?(pod.name)
           def pod.build_type;
             Pod::Target::BuildType.static_library
           end
         end
       end
  end
```

**Comment by keshavamurthy1** [comment]
Hi thank you for your response
It works.

Thank you

**Comment by teo029** [comment]
> If you are using `use_framework!`. Make sure you add the following
> 
> ```
>    $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
>      'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
>      'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
>      'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
>   
>    pre_install do |installer|
>      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>      installer.pod_targets.each do |pod|
>          if $static_framework.include?(pod.name)
>            def pod.build_type;
>              Pod::Target::BuildType.static_library
>            end
>          end
>        end
>   end
> ```

Had to `Pod::BuildType.static_library` instead of `Pod::Target::BuildType.static_library`

**Comment by sohayb** [comment]
Apparently this is closed but when I did the exact same thing with the suggested solution I had a different error:
```
'fmt/compile.h' file not found
```
This in `RCT-Folly` target, `FmtCompile.h`. I wonder if anyone had the same issue. React native version `0.65.1`


```ruby
    $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
        'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
        'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
        'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
     
    pre_install do |installer|
        Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
        installer.pod_targets.each do |pod|
            if $static_framework.include?(pod.name)
              def pod.build_type;
                Pod::BuildType.static_library
              end
            end
          end
    end

    # Enables Flipper.
    use_flipper!({ 'Flipper' => '0.102.0', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-Glog' => '0.3.9', 'Flipper-PeerTalk' => '0.0.4' })
```

**Comment by sumitbalyan** [comment]
> Apparently this is closed but when I did the exact same thing with the suggested solution I had a different error:
> 
> ```
> 'fmt/compile.h' file not found
> ```
> 
> This in `RCT-Folly` target, `FmtCompile.h`. I wonder if anyone had the same issue. React native version `0.65.1`
> 
> ```ruby
>     $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
>         'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
>         'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
>         'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
>      
>     pre_install do |installer|
>         Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>         installer.pod_targets.each do |pod|
>             if $static_framework.include?(pod.name)
>               def pod.build_type;
>                 Pod::BuildType.static_library
>               end
>             end
>           end
>     end
> 
>     # Enables Flipper.
>     use_flipper!({ 'Flipper' => '0.102.0', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-Glog' => '0.3.9', 'Flipper-PeerTalk' => '0.0.4' })
> ```

Same for me

**Comment by batcodegen** [comment]
any solution to 'fmt/compile.h' file not found ?

**Comment by moriyuu** [comment]
> 'fmt/compile.h' file not found

same problem.

**Comment by Yamingue** [comment]
tanks @tonyvx  it's work for me

**Comment by hasnainbaloch** [comment]
> in Podfile - commenting filpper resolved it for me.
> 
> ```shell
>   # Enables Flipper.
>   #
>   # Note that if you have use_frameworks! enabled, Flipper will not work and
>   # you should disable the next line.
>   use_flipper!()
> ```

Thank you

**Comment by partriv** [comment]
> Which cocoapods version are you using ?

i was using a very old version and this fixed it for me

**Comment by FredSoares** [comment]
In my case adding `use_frameworks! :linkage => :static` in Podfile resolved it for me.

**Comment by chu3kit0** [comment]
> In my case adding `use_frameworks! :linkage => :static` in Podfile resolved it for me.

Work for me! thx
