### ISSUE TITLE
Discussion: Consider moving stetho support to a separate artifact

### ISSUE THREAD

**Issue by ZacSweers** [facebook/flipper#607]
Stetho was never updated to androidx. This means that flipper and any consumers of it have to use jetifier still because of it _even if_ they don't use stetho and _even though_ flipper itself has moved to androidx.

```
* com.facebook.flipper:flipper:0.26.0
  \-- com.facebook.stetho:stetho:1.5.1
   \-- com.android.support:support-annotations:28.0.0

* com.facebook.flipper:flipper-network-plugin:0.26.0
  \-- com.facebook.flipper:flipper:0.26.0
   \-- com.facebook.stetho:stetho:1.5.1
    \-- com.android.support:support-annotations:28.0.0
```

**Comment by passy** [comment]
Yes, that would be great. I just checked what we actually depend on `stetho` for and it comes down to four utilities (https://gist.github.com/passy/27c274b5b9e447678d0bf0ed7363c179)

```
com.facebook.stetho.common.android.ResourcesUtil;
com.facebook.stetho.common.android.FragmentActivityAccessor;
com.facebook.stetho.common.android.FragmentCompat;
com.facebook.stetho.common.android.FragmentManagerAccessor;
``````

I don't think we've got the bandwidth for this right now, but if someone would like to pick this up as a PR, please feel free to get in touch or just submit it!

**Comment by ZacSweers** [comment]
Should we just copy those in?

**Comment by passy** [comment]
@ZacSweers I think that would be fine. I haven't checked if we use all the methods defined, but if not I'd just limit it to the ones actually being used by Flipper.

**Comment by ZacSweers** [comment]
@passy took awhile but I've circled back to this and opened #762
