### ISSUE TITLE
Question: How can I reset selection of a ManagedTable?

### ISSUE THREAD

**Issue by kingori** [facebook/flipper#620]
How can I reset selection of a ManagedTable?

In my plugin, I used two ManagedTable and I want to reset selection of each table when
1. I clicked 'reset' button in plugin or
2. select a row in another table

I've tried to set `highlightableRows` property, but it does not work well and sometimes desktop application freezed. ( In Calculate scroll position, offset was NaN, so loop not terminzated.)

So, is there any good way to reset selection of ManagedTable?
![스크린샷 2019-10-31 오후 1 08 07](https://user-images.githubusercontent.com/520510/67918420-935af000-fbdf-11e9-942c-e414febaad43.png)

**Comment by jknoxville** [comment]
Good question @kingori , the prop you're looking for is [`highlightedRows`](https://github.com/facebook/flipper/blob/master/src/ui/components/table/ManagedTable.tsx#L116).

This specifies the **initial** starting selection but will be overridden by any state changes occurring by user clicking.
However, whenever it changes, it will reset the selection to that new set.

So just pass in a new `Set()` to reset to zero again.

**Comment by jknoxville** [comment]
Feel free to reopen if you are still having trouble.

**Comment by kingori** [comment]
@jknoxville Thank you for your comment.

I've tried `highlightedRows` properties, but it makes Flipper desktop client freeze. I've paused client, and checked stack trace.

```
findNearestItemBinarySearch (index.cjs.js:1576)
findNearestItemExponentialSearch (index.cjs.js:1605)
findNearestItem (index.cjs.js:1571)
getStartIndexForOffset (index.cjs.js:1686)
_getRangeToRender (index.cjs.js:1443)
render (index.cjs.js:1356)
```

In findNearestItemBinarySearch(), Nan is passed as offset. So, while loop in `findNearestItemBinarySearch$1` function does not finish.

Reproduce step is like this.

1. start render with empty highlightedRows attribute.
2. select a row in ManagedTable
3. set highlightedRows with new Set() with selected item id.
4. desktop freezes.

Here is my sample plugin code.

```
import {
    Button,
    FlipperPlugin,
    ManagedTable,
    TableRows,
    FlexBox,
    FlexRow,
    FlexColumn,
    TableBodyRow,
    Text,
    styled,
} from 'flipper';
import React from 'react';

type Item = {
    key: string,
    name: String
}

type State = {
    selectedItem: string
};


const ruleColumns = {
    key: {
      value: 'Key',
    },
    name: {
      value: 'Name',
    }
};

const ruleColumnSizes = {
    key: 120,
    name: 'flex'
}

export default class Actions extends FlipperPlugin<State, any, any> {

    state =  {
        selectedItem: null as string
    }

    render() {
        const { selectedItem} = this.state;
        
        let highlightedRows  = ( selectedItem == null ) ? new Set() : new Set(selectedItem);

        return (
                <ManagedTable
                    columns={ruleColumns}
                    columnSizes={ruleColumnSizes}
                    highlightableRows={true}
                    multiline={false}
                    multiHighlight={false}
                    rowLineHeight="40px"
                    onRowHighlighted={this.onRowSelected}
                    highlightedRows={highlightedRows}
                    rows={this.buildRuleRows()}
                    tableKey="rules"
                    />
        );
    }

    buildRuleRows() : TableRows {
        const rules = [ {key : "1", name: "1"},{key : "2", name: "2"}];

        return rules.map( (item) => (
            this.buildSingleRow(item)
        ));
    }

    buildSingleRow(item: Item ) : TableBodyRow {
        const row: TableBodyRow = {
            columns:  {
                key: {  value: <Text>{item.key }</Text> },
                name: { value: <Text>{item.name}</Text> }
            },
            key: item.key
        };
        return row;
    }
    
   
    onRowSelected = (rows: Array<string>) => {
            let targetKey = rows.length === 1 ? rows[0] : null;
            this.setState({
               selectedItem: targetKey
            });
      };
}
```

I've test it on OSX client version 0.24.1.
