### ISSUE TITLE
No Icons on Windows

### ISSUE THREAD

**Issue by sebhell** [facebook/flipper#641]
## 🐛 Bug Report
When downloading the Flipper Desktop Release for Windows and starting it via Flipper.exe most of the icons are not shown. It seems that something is wrong with the path delimiter for the icons folder.

![no_icons_windows](https://user-images.githubusercontent.com/5691866/68935237-95ed4600-0798-11ea-87b3-bf408550fc7e.png)
![no_icons_windows_errors](https://user-images.githubusercontent.com/5691866/68935252-9d145400-0798-11ea-8673-aec99d5c403b.png)

When checking out the Repo and running the application with yarn, the icons are shown.

## To Reproduce
In Windows download flipper-win.zip from latest release, unzip it and start Flipper.exe.

## Expected Behavior
The Icons should be shown.

## Environment
Flipper Desktop version 0.28.

Issue exists since Version 0.26.

OpenSSL is installed and in path, sdk path is also set.

**Comment by passy** [comment]
Thanks for the report. Will try to repro that today.

**Comment by passy** [comment]
<img width="950" alt="Capture" src="https://user-images.githubusercontent.com/9906/69170302-ca8f3380-0af1-11ea-8435-8b0c5d0db92d.PNG">

I finally managed to get my Windows laptop to boot up again but I can't repro this, unfortunately. It looks like the images that can't be loaded in your screenshot are bundled with Flipper and shouldn't require downloading. Can you confirm that you unzipped the entire folder before running Flipper as opposed to using the Explorer feature of directly starting from the ZIP? The latter doesn't work with how we access local files.

**Comment by sebhell** [comment]
Ok, that is odd. Yes, I started the application after fully extracting the whole zip. Doesn't work with Windows internal zip-extractor as well as 7zip.

But I think I found one part of the problem: I tried Flipper on 4 different machines and it worked on the one with Windows set to English language. On the other three machines set to German it showed no icons.

But I can confirm, that the icons are available:
![Anmerkung 2019-11-20 153607](https://user-images.githubusercontent.com/5691866/69248438-962c7d80-0bac-11ea-96ac-17e544a3c6cd.png)

Thank you for your effort, I hope this helps.

**Comment by Nekromancer** [comment]
I have the issue with polish windows locale

**Comment by adrinieto** [comment]
I have the same problem with spanish locale

**Comment by passy** [comment]
Thanks for confirming this. It's very useful to know that this affects other locales as well. To be transparent here, we currently don't have the bandwidth to investigate this. If someone would want to dig into this deeper and potentially come up with a fix, we'd be super grateful. Otherwise it may take a bit until someone from our team can look into a fix.
