### ISSUE TITLE
Unable to get certificates from desktop

### ISSUE THREAD

**Issue by hexlay** [facebook/flipper#644]
## 🐛 Bug Report
![Screenshot_1](https://user-images.githubusercontent.com/16070367/69007132-3edfa080-0953-11ea-8126-ad9947d7f68d.png)
Flipper shows that no clients are connected, however every log and crash report does work. .flipper/certs are empty.
I have tried to delete .flipper folder.

![Screenshot_2](https://user-images.githubusercontent.com/16070367/69007173-c1686000-0953-11ea-9f54-034a026ab2d2.png)
Here's image from desktop client's console. I have tried to manually create D:/tmp/flipper.

## Expected Behavior
Flipper to show plugins

## Environment
Android 10 on Android Emulator
Flipper 0.28.0 on Windows (Pre-built, non yarn version)

**Comment by cekkaewnumchai** [comment]
Thanks for the report, I will to repro this.

**Comment by cekkaewnumchai** [comment]
@hexlay Do you have OpenSsl on your Windows?

**Comment by hexlay** [comment]
> @hexlay Do you have OpenSsl on your Windows?

Sorry for late reply, after installing and properly configuring OpenSSL it started working, thanks ! I'm closing this issue.

**Comment by chetnashah** [comment]
@hexlay how did you configure openssl ? I have put openssl on the PATH. What else needs to be done?
I am facing the same issue on windows.

**Comment by danilo-vieira** [comment]
I need to know how do this too.
How to add openssl to PATH on Windows?

**Comment by passy** [comment]
> I need to know how do this too.
> How to add openssl to PATH on Windows?

https://answers.unity.com/questions/616484/open-ssl-not-found.html

Not a Windows user but Google has a bunch of answers for this.

**Comment by danilo-vieira** [comment]
> > I need to know how do this too.
> > How to add openssl to PATH on Windows?
> 
> https://answers.unity.com/questions/616484/open-ssl-not-found.html
> 
> Not a Windows user but Google has a bunch of answers for this.

Thank you. I found the solution and wrote a guide about it: https://dev.to/danilovieira/installing-openssl-on-windows-and-adding-to-path-3mbf

**Comment by AlcantaraRW** [comment]
Having the same issue here with Flipper 0.45.0.
I have OpenSSL installed and added to PATH (Windows 10) and I'm still facing those certificate issues.

**Comment by Kianoni** [comment]
I had the same issue on Windows 10. Fixed by running Flipper as administrator once, seems openssl needs some extra permissions to generate the certificate.

**Comment by danilo-vieira** [comment]
> I had the same issue on Windows 10. Fixed by running Flipper as administrator once, seems openssl needs some extra permissions to generate the certificate.

Yeah! anyway, if you get this error again, you can read my guide on dev.to. I teach how install openssl on Windows. 😊
