### ISSUE TITLE
Unable to edit a string shared preference whose contents is a URL

### ISSUE THREAD

**Issue by angusholder** [facebook/flipper#647]
## 🐛 Bug Report
An Android shared preference whose value is a string URL cannot be edited. It looks like
![image](https://user-images.githubusercontent.com/7407345/69243438-fadedc80-0b9a-11ea-8833-2f0df2cd7d9e.png)

## To Reproduce
When clicking the field, it momentarily turns into a text input, but then opens the URL in my default browser, and when I navigate back to Flipper the text input has turned back into the clickable span again, so I'm unable to edit the field.

## Expected Behavior
It would probably be best to make URLs not links in this case, so clicking it does the normal action of turning it into a text input, rather than opening the URL.

## Environment
Flipper 0.28.0
Windows 10

**Comment by mweststrate** [comment]
The next release will include a small edit button after the URL to resolve the issue.

![Screen Shot 2020-01-16 at 13 55 49](https://user-images.githubusercontent.com/1820292/72532722-cff7c880-386b-11ea-95fc-b7f86264672e.png)

**Comment by angusholder** [comment]
Thanks for fixing that!
