### ISSUE TITLE
can't build flipper project in release (debug works)

### ISSUE THREAD

**Issue by frannois** [facebook/flipper#648]
## 🐛 Bug Report
`./gradlew assembleDebug` works
`/gradlew assembleRelease` does not work

stack trace 
{path}/flipper/sample/FlipperSampleApplication.java:16: error: package com.facebook.flipper.plugins.navigation does not exist
import com.facebook.flipper.plugins.navigation.NavigationFlipperPlugin;
                                              ^
{path}/flipper/android/sample/src/main/java/com/facebook/flipper/sample/MainActivity.java:15: error: package com.facebook.flipper.plugins.navigation does not exist
import com.facebook.flipper.plugins.navigation.NavigationFlipperPlugin;
                                              ^
{path}/flipper/android/sample/src/main/java/com/facebook/flipper/sample/DeepLinkActivity.java:12: error: package com.facebook.flipper.plugins.navigation does not exist
import com.facebook.flipper.plugins.navigation.NavigationFlipperPlugin;
                                              ^
3 errors
2 warnings

## To Reproduce
Run `./gradlew assembleRelease`

## Expected Behavior
build is successful
## Environment
Macbook : I tried building master, tag v0.28.0 and tag v0.27.0

**Comment by cekkaewnumchai** [comment]
Hello @frannois, thank you for reporting bug. I will try to reproduce and get back to you

**Comment by passy** [comment]
@frannois It sounds like you've declared Flipper as a `debugImplementation` dependency. If you do this, you cannot reference any Flipper code in your release builds. This is by design as Flipper code should never be bundled into your production builds.

**Comment by frannois** [comment]
@passy I am not talking about building my application with Flipper.
I am talking about building the flipper github project.

**Comment by frannois** [comment]
Last night master github project was failing for another reason.

**Comment by passy** [comment]
Thanks for the clarification! Will give that a try.

**Comment by passy** [comment]
Now I feel really stupid. Sorry, you're completely right. We must have broken this quite a while ago. Fix for it is coming and I'll make sure to add a CI job for preventing this from happening again. Thanks for the report!

**Comment by agungsb** [comment]
I get this error when building my application using the following command:
`react-native run-android --variant=release`

In my `/android/app.build.gradle`:
```
...
debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
...
```

Any thoughts on how to solve this?

**Comment by vaibsshukla** [comment]
Hi, @passy  and @frannois  I am facing the same issue after upgrading it to "react-native": "^0.62.2" It works in debug but in a release, it shows same as mentioned by @frannois. After Commenting on a flipper class while creating a build but when I use debug I have to uncomment to use a flipper. It is a wrong practice to comment and uncomment code. Kindly Suggest any solution for this.

**Comment by ahanusek** [comment]
I have the same problem. After upgrade to RN 0.62.2 I cannot build the app in release mode.

`
ReactNativeFlipper.java:10: error: package com.facebook.flipper.android does not exist
import com.facebook.flipper.android.AndroidFlipperClient;
`

**Comment by ahanusek** [comment]
Ah, I had to move ReactNativeFlipper file to debug folder from main.
