### ISSUE TITLE
Question: I can't use react devtools

### ISSUE THREAD

**Issue by jb9229** [facebook/flipper#653]
hello

i want to use react devtools plugin, but it is not working

Env:
  1. react: 16.12.0, 16.9.0(this version is same issue)
  2. FLIPPER_VERSION=0.23.4

Issue Image:
<img width="1198" alt="스크린샷 2019-11-22 오후 2 49 01" src="https://user-images.githubusercontent.com/3200647/69401279-ff8cc780-0d37-11ea-8cf4-026ce0f5b77a.png">

I tried
  1. yarn add --dev react-devtools@^3
  2. npm install -g react-devtools@^3

 But i got same problem.

how can i solve the issue?

**Comment by mweststrate** [comment]
Can you give a bit more context? The plugin can at the moment (afaik) only connect to DevTools v4 based applications. What are you connecting to? React Native? You might need to be on a newer version to get support from this plugin.

**Comment by jb9229** [comment]
@mweststrate 

Yes I connected to react-native on flipper.

I tried it on two projects, but both didn't work.(android flipper)
  * [I was following along that guide](https://github.com/facebook/flipper/blob/da25241f7fbb06dffd913958559044d758c54fb8/docs/getting-started.md#android)

# First Project:
   - "react-native": "0.61.2"
# Second Project
   - expo eject project
   -

**Comment by sanohin** [comment]
@mweststrate the same for my project. React devtools are not working, the error message is the same as on screenshot, I tried installing `react-devtools@^3` in the project and globally but it didn't help. I guess, react-devtools is bundled with flipper.
It would be nice to find some workaround for that.

**Comment by mweststrate** [comment]
Our next weeks release will contain a bunch of improvements in the react-devtools setup. But if you have a small test repo I can test it against, I can check if it solves your specific case.

**Comment by sanohin** [comment]
Unfortunately, my current project is not open source. Package versions:
react-native: 0.60.4
react: 16.8.6 
I also tried updating to react 16.12.0 and it didn't make any change.

**Comment by sanohin** [comment]
@mweststrate I've just set up a project with `create-react-native-app` and configured flipper according to flipper documentation. I've set up Android only as I had some issues with setting up iOS (build errors). So anyways, the Android version doesn't work with react-devtools right now.

Test repo:
https://github.com/sanohin/flipper-demo

**Comment by mweststrate** [comment]
We just released Flipper 0.31.2, this should have the React devtools working more stable against RN 0.61

**Comment by mweststrate** [comment]
Apologies, missed this one! So far thought the issue was the React version, but it is about the React Native version: https://reactjs.org/blog/2019/08/15/new-react-devtools.html#which-versions-of-react-are-supported. React Native 0.62 is around the corner though, so hopefully this will be fixed soon! (currently we cannot ship a separate version of the plugin for older versions, we are decoupling that as well atm, so that that will be possible in the future)

**Comment by sanohin** [comment]
oh. ok, so hopefully the fix will be in React Native 0.62?

**Comment by sanohin** [comment]
@mweststrate  ls that possible to define a custom version of react-devtools? For some projects, it may be not so quick and easy to migrate React Native version

**Comment by mweststrate** [comment]
@sanohin just tried, and that is quite easy to achieve if you change `"react-devtools-core"` to version `"3.6.3"` in `src/plugins/reactdevtools`, and then run `yarn` once inside that directory. After that they worked OOTB for me:

![Screen Shot 2020-02-17 at 15 31 29](https://user-images.githubusercontent.com/1820292/74667194-c7601e00-519a-11ea-84ef-447072b2ac20.png)

**Comment by mweststrate** [comment]
Closing as a workaround is available and a fix is in the release pipeline. Let us know if the work around doesn't suffice

**Comment by jb9229** [comment]
@mweststrate 

Thank you for your help.

Where does 'src/plugins/reactdevtools' mean?
Is it in 'react-devtools npm global package directory'??

**Comment by mweststrate** [comment]
Apologies, that was assuming you run Flipper from source (clone this repo, `yarn && yarn start`). For the pre-built package we don't have a work around at this moment

**Comment by usrbowe** [comment]
Published plugin for those on older version of React Native -> https://github.com/facebook/flipper/issues/945
