### ISSUE TITLE
Plugins make crash

### ISSUE THREAD

**Issue by ScreamZ** [facebook/flipper#662]
## 🐛 Bug Report

After installation all available plugin and restart flipper, it keep crashing

```
Uncaught Exception:
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
```

## Environment
Flipper desktop MACOS 0.28

**Comment by passy** [comment]
Hey @ScreamZ, thanks for the report. Your ulimits are probably too low. You can check https://wilsonmar.github.io/maximum-limits/ for how to increase them.

Do you have watchman installed on your system?

**Comment by mtzfactory** [comment]
Same here... It was working and I just installed some plugins to test and... it stop working and reported that error...

**Comment by ScreamZ** [comment]
I have watchman yes, what's the impact on augment ulimit ? Can this impact the system stability ? Thanks

**Comment by Hackergeek** [comment]
![image](https://user-images.githubusercontent.com/9377994/69968210-e31d3600-1554-11ea-8a03-63889e24543e.png)
Same here...

**Comment by reevesnick** [comment]
On Mac, You can navigate to`/Users/<USERNAME>/.flipper/. Delete the folder. Then open the application again

**Comment by ScreamZ** [comment]
@reevesnick I guess for linux it's same than macOS `~/.flipper`

**Comment by reevesnick** [comment]
Really? Judging on the file directory structure, I thought Linux will be in the `usr` directory. Usually its a user based preference from the OS

**Comment by reevesnick** [comment]
Even trying it on Watchman, with MacOS Catalina 10.15.1 does not work. Did an automatic install via Homebrew and did not effect. The only way is to delete the corresponding directories. It will reset Flipper when launch the next time.
