### ISSUE TITLE
Extract UI components to separate module

### ISSUE THREAD

**Issue by yatsyk** [facebook/flipper#67]
It would be nice to have UI components usable outside Sonar or Sonar plugins particularly in web apps. 

I've created web app with create-react-app and moved ui, utils, fb-stubs folders to this application.

To use few components in this application I made following changes:

- add flow support to my react app
- add import React from "react" to some of the components
- move imports to start of the file
- comment out functionality related to electron (clipboard)

**Comment by danielbuechele** [comment]
Agreed! This would be a great usecase for yarn workspaces. We should create a sub-package called `sonar-ui` which only contains the UI components. I feel this could be valuable for other projects (especially electron apps).

We could also think about making the calls to electron optional to be able to use them in the browser.

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!
