### ISSUE TITLE
Question: How can I copy log rows with priority (Type) column?

### ISSUE THREAD

**Issue by vkotovv** [facebook/flipper#673]
I'd like to copy Android logs with Type = All, but in the copied lines there is no Type column present (only Time, Tag and Message).

How can I do that?

Use case: I'd like to send recorded logs to another person, so I just copied all the logs, but type column is not present. I know I can filter logs by type, but I'd like to copy all types, not just a single one.

I'm using Flipper 0.28.0 on Linux.

**Comment by mweststrate** [comment]
If you don't mind a little scripting, you can do File > Export > As file... and export your device data. This produces a json file in which you should be able to find the device logs as structured data and freely query on it. (on linux you can nicely use the `jq` command for that)

**Comment by vkotovv** [comment]
@mweststrate Yeah, go it. It would be great to have some way of doing this via UI.
