### ISSUE TITLE
Flipper doctor wrong warning

### ISSUE THREAD

**Issue by dphans** [facebook/flipper#687]
## 🐛 Bug Report
Flipper display wrong message that Android SDK is not found.

## To Reproduce
- Open Flipper, warning message display on the top.

## Expected Behavior
- Android SDK already installed (with Android Studio) at /Users/<user_name>/Library/Android/sdk. And it should be not display warning message.

## Environment
Flipper version: 0.30.0.

<img width="1127" alt="Screen Shot 2019-12-11 at 14 02 52" src="https://user-images.githubusercontent.com/12996976/70599269-54c54600-1c1f-11ea-8264-4de96e127d0e.png">
<img width="804" alt="Screen Shot 2019-12-11 at 14 08 30" src="https://user-images.githubusercontent.com/12996976/70599492-d5844200-1c1f-11ea-9822-b025c6d00c20.png">
<img width="1028" alt="Screen Shot 2019-12-11 at 14 06 37" src="https://user-images.githubusercontent.com/12996976/70599350-8c33f280-1c1f-11ea-9219-8a555b5bcddf.png">

**Comment by passy** [comment]
cc @nikoant

**Comment by nikoant** [comment]
@dphans thanks for reporting! This issue looks similar to another one reported earlier - https://github.com/facebook/flipper/issues/667. What do you get if you run the commands suggested by John in this comment - https://github.com/facebook/flipper/issues/667#issuecomment-560470909?

**Comment by nikoant** [comment]
The workaround implemented in this commit: 5d17eed
