### ISSUE TITLE
Screen recording failure leads to 0b file being pulled

### ISSUE THREAD

**Issue by hacker1024** [facebook/flipper#688]
## 🐛 Bug Report
When taking a screen recording of a WearOS device, the outputted file is empty. Tested over USB & Bluetooth.

## To Reproduce
1. Connect to your smartwatch with ADB over USB or Bluetooth (I suspect Wi-FI won't work either, but I haven't tried it)
2. Start a screen recording
3. Examine the recording file when complete. It will be empty.

## Expected Behavior
The screen recording file should contain video data, rather than be 0 bytes.

## Environment
- [WearOS H](https://support.google.com/wearos/thread/563800) (Based on [Android 9.0 Pie](https://www.android.com/versions/pie-9-0/)) with [Linux](https://www.kernel.org/) [3.18.120](https://cdn.kernel.org/pub/linux/kernel/v3.x/ChangeLog-3.18.120) on a [Mobvoi TicWatch Pro](https://www.mobvoi.com/ticwatchpro/) ([Snapdragon Wear 2100](https://www.qualcomm.com/products/snapdragon-processors-wear-2100))
- [macOS 10.15 Catalina](https://www.apple.com/macos/catalina/)
- [Flipper](https://fbflipper.com/) [0.30.0](https://github.com/facebook/flipper/releases/tag/v0.30.0)

**Comment by passy** [comment]
Hey @hacker1024! Thanks for the report. There's probably not much we can do about this. We use the [`screenrecord`](https://developer.android.com/studio/command-line/adb#screenrecord) command on Android and pull the resulting file to your desktop. We probably should do a better job at checking if there's a valid video before pulling, but the underlying problem here will be with WatchOS or the particular ROM.

**Comment by hacker1024** [comment]
> Hey @hacker1024! Thanks for the report. There's probably not much we can do about this. We use the [`screenrecord`](https://developer.android.com/studio/command-line/adb#screenrecord) command on Android and pull the resulting file to your desktop. We probably should do a better job at checking if there's a valid video before pulling, but the underlying problem here will be with WatchOS or the particular ROM.

Thanks for the info.
When manually running `screenrecord`, I get the error described [here](https://stackoverflow.com/questions/25491528/screen-record-android-wear/25496528).

**Comment by passy** [comment]
Ah, I see. I'll rephrase the title here a little so we can add this to our backlog. Thanks for the report!

**Comment by passy** [comment]
We fixed a bunch of issues around this. Hopefully this should no longer be a thing.
