### ISSUE TITLE
Question: We are getting error: cannot access BufferingFlipperPlugin

### ISSUE THREAD

**Issue by shriharshs** [facebook/flipper#698]
We have Release and the Debug builds, it works well with the Debug build, but when changed to release build, it would throw this error. Would there be any help or workaround to fix it?

**Comment by mweststrate** [comment]
Would you mind providing a lot more detail? Flipper versions, relevant build configuration, the target you are developing on (iOS / Android / React Native). Include stacktraces etc. Without tangible information we can't help out.

**Comment by passy** [comment]
We do not support running Flipper in release builds. As Michel said, without more information we can only make guesses, but there are various checks depending on the platform that disable Flipper unless it's a debug build.
