### ISSUE TITLE
Uncaught exception: Too many open files

### ISSUE THREAD

**Issue by Ehesp** [facebook/flipper#699]
Hi All,

I've been creating my own Flipper plugin, which seemed to be going well. At one point, I had 2 dependencies `flipper: latest` & `react: ^16.12.0` and everything seemed to be going ok. 

Once I started to build out my project, adding some dev dependencies, sub-components etc, things worked and all of a sudden I started to get the following error when starting Flipper:

![image](https://user-images.githubusercontent.com/842078/70820548-d9a39180-1dd0-11ea-8cf0-199544ffde0c.png)

I've tried the answers in https://github.com/facebook/flipper/issues/662 with no luck. I also ran Flipper from source & had the same issue. 

After spending far too long trying to get it to work, something in the following process seems to have solved the problem:

- Upped the Mac OS File Descriptor Limits, as mentioned [here](https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits).
- Restarted my Mac.
- Ran `watchman watch-del-all` & `watchman shutdown-server`.
- Started Flipper from the command line.

It's probably also worth mentioning that on another Mac which encounters the same issue:

- A fresh clone of the repo, adding it to the plugins paths caused the issue straight away.
- Following the steps above, Flipper can be opened from the command line but **not** by opening the app directly from Applictions UI.

For now it seems nuking watchman "fixes" the issue, but something internally seems to cause the open files to keep stacking.

Flipper Version: 0.30.0
Node Version: 12.4.0
Watchman Version: 4.9.0

**Comment by mweststrate** [comment]
In what directory are you developing your plugin? I had the same issue when developing inside `~/.flipper` directory, but if you set up your own, as explained here, I think the issue is less likely to occur: https://fbflipper.com/docs/tutorial/js-setup.html#dynamic-plugin-loading

**Comment by Ehesp** [comment]
In my own, inside of `~/Documents/flipper-plugins/`, which only has the one. I can seem to get around the problem by running the app from the command line + clearing watchman. Not ideal, but it seems to work for now.

**Comment by mweststrate** [comment]
For background, I suspect the cause of this issue might be here: https://github.com/facebook/flipper/blob/09184a999f4ed81914618dd576c0b5a0099dfd66/static/compilePlugins.js#L68, where we set up watching too naive, as it is recursive, meaning the `node_modules` will be watched as well, which should ideally be blacklisted from watching. However, node does not provide an API for that afaik, so probably we should use a different package there, like watchman indeed, or something else.

**Comment by mweststrate** [comment]
In our latest release last week we improved the file watching system. If this problem still occurs after updating please open a fresh issue with some more details. 

Note that on iOS the amount of watchable files always has to be increased as it is insanely low by default. For example by following these instructions: https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits
