### ISSUE TITLE
Discussion: add support for import/export custom plugin data.

### ISSUE THREAD

**Issue by jaychang0917** [facebook/flipper#701]
Currently only build-in plugins data can be import/export, it would be great to support custom plugin too.

**Comment by mweststrate** [comment]
@jaychang0917 does your plugin have a `persistedStateReducer`, as in that case it should be picked up automatically.

**Comment by ggv-jaychang** [comment]
@mweststrate yes, the plugin having `defaultPersistedState` will be picked, but how about plugin that doesn't run in the background?

**Comment by jaychang0917** [comment]
@mweststrate yes, the plugin having defaultPersistedState will be picked, but how about plugin that doesn't run in the background?

**Comment by mweststrate** [comment]
It seems that the mechanism hasn't been documented yet, but you should be able to use the following methods for this, note that the export is `async`, so you and use that make calls to the app using `callClient`. 

```typescript
static deserializePersistedState: (
    serializedString: string,
  ) => PersistedState = (serializedString: string) => {
    return JSON.parse(serializedString);
  };

  static exportPersistedState = async (
    callClient: (method: string, params?: any) => Promise<any>,
    persistedState: PersistedState | undefined,
    _irelevantargument,
    idler?: Idler,
    statusUpdate = (_msg: string) => {},
  ): Promise<PersistedState | undefined> => {
    // fetch some data and serialize it
  };
```

**Comment by jaychang0917** [comment]
Sorry for my late reply, so you mean for plugin running in background, flipper is able to export its data, but for plugin that doesn't run in background we need to write the serialization logic? Is it possible flipper handle the serialization logic for both cases?

**Comment by mweststrate** [comment]
To be able to export a plugin, it has to have persistedState, as local plugin state isn't known in the global registery of Flipper. If you want to be able to export the state, I recommend to move the state into the peristedState functionality (see https://fbflipper.com/docs/extending/js-plugin-api.html#background-plugins). You are not required to further leverage the background functionality. 

https://github.com/facebook/flipper/blob/901817040c17909388120f57b988dccd05a624f8/src/utils/exportData.tsx#L206-L212

**Comment by jaychang0917** [comment]
Got it, thanks @mweststrate
