### ISSUE TITLE
Cannot install on macOS(catalina). 

### ISSUE THREAD

**Issue by RajeshBatth** [facebook/flipper#716]
## 🐛 Bug Report

“Flipper” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

## To Reproduce

Happening all the time
## Expected Behavior

App to open
## Environment

macOS: Catalina 10.15.1 (19B88)

**Comment by RajeshBatth** [comment]
This can be fixed by changing macOS's privacy settings.

**Comment by florian-milky** [comment]
Go into Security&Privacy then General and you should see Allow Flipper

**Comment by jrz** [comment]
Reopening, as the binary is not signed.

**Comment by leonaburime** [comment]
> Reopening, as the binary is not signed.

Is Facebook even trying to fix this? Seems like it's pretty important and wouldnt
be that hard to correct..

**Comment by n0f3** [comment]
still broken on latest version, not signed

**Comment by nnaren1902** [comment]
Still broken and can't be used

**Comment by kvaghas** [comment]
Still broken

**Comment by jonlambert** [comment]
Still very much broken. Think it's unlikely this will be fixed.

**Comment by azzhexperiment** [comment]
Still no fix 🙄
