### ISSUE TITLE
createTablePlugin column values don't render

### ISSUE THREAD

**Issue by snepalnetflix** [facebook/flipper#717]
## 🐛 Bug Report

When using the createTablePlugin sample, nothing is rendered inside each column.

## To Reproduce
Create a flipper plugin using the code from the following documentation:
https://fbflipper.com/docs/extending/create-table-plugin.html

Create an app to send "newRow" events. For example:
```
        val params = FlipperObject.Builder()
            .put("id", "id-1")
            .put("column1", "column1-value")
            .put("column2", "column2-value")
            .put("column3", "column3-value")
            //.put("extras", "extras-value")
            .build()
        connection.send("newRow", params)
```

Right click on a row and click copy row, the following is copied:
`{"column3":"column3-value","column1":"column1-value","column2":"column2-value","id":"1"}`

Unfortunately, nothing is actually displayed. See screenshot.

## Expected Behavior
The column values sent by the client should be shown.

## Environment
Flipper Desktop version: 0.30.1
Android: Pixel 3 emulator
<img width="1545" alt="Screen Shot 2019-12-21 at 3 42 08 PM" src="https://user-images.githubusercontent.com/51517611/71315581-bc487600-2415-11ea-9215-78a39b41e4aa.png">

**Comment by mweststrate** [comment]
Could you share the source code of the flipper plugin as well? At least the relevant parts with the datashape and table setup?

**Comment by passy** [comment]
Closing for staleness. Please reopen if this is still an issue.
