### ISSUE TITLE
Question: React Native (Android) can't use plugins

### ISSUE THREAD

**Issue by CarlosUvaSilva** [facebook/flipper#725]
I've followed the RN documentation and I'm building Flipper-v.0.23.4 from source as per the documentation.

I have the crash report and logs tabs but I can't use any of the other plugins (network etc).
I've checked and openssl is in my PATH but it seems flipper can't connect with the app, tried with Emulator and a physical device

**Comment by mateosilguero** [comment]
Could you share a bit of your code ?
