### ISSUE TITLE
Feature request: create no-ops for default plugins

### ISSUE THREAD

**Issue by donaldchen** [facebook/flipper#736]
I'm working on integrating Flipper with an Android app. It's hard to set up the default plugins for network inspection, layout inspection, and shared preferences inspection when there isn't a default no-op implementation for those plugins. Without those no-op implementations, release builds cannot compile successfully.

**Feature Request**
Add the plugin no-ops from https://github.com/theGlenn/flipper-android-no-op (mentioned in https://github.com/facebook/flipper/issues/180) into `com.facebook.flipper:flipper-noop`.

**Comment by passy** [comment]
Thanks for flagging @theGlenn's repo. I wasn't aware of this. Unfortunately we won't be able to include this directly into our repo. The reasons for that are that a) we don't have a good process at the moment when working on plugins to ensure that the no-op implementations stay in sync and b) that we recommend against this approach as it still has some app weight overhead (with a default Android build setup) and we instead suggest people compartmentalise their code strictly into debug and release setup procedures so this is not necessary.

I'll make sure to add a link to @theGlenn's packages directly to the docs so this is more obvious to people who would like to follow this approach.

**Comment by donaldchen** [comment]
@passy , makes sense. Thanks!
