### ISSUE TITLE
Annotate the code with @Nonnull / @Nullable 

### ISSUE THREAD

**Issue by eboudrant** [facebook/flipper#75]
For better interopt with Kollin. At least the public api code should be annotated.

**Comment by passy** [comment]
We generally don't use `@NotNull` internally. Unless something is marked as `@Nullable`, it should be considered to never be null.

**Comment by Takhion** [comment]
@passy indeed there is since [Kotlin 1.1.4](https://blog.jetbrains.com/kotlin/2017/08/kotlin-1-1-4-is-out):  [`@ParametersAreNonnullByDefault`](https://static.javadoc.io/com.google.code.findbugs/jsr305/3.0.1/javax/annotation/ParametersAreNonnullByDefault.html)

**Comment by passy** [comment]
@Takhion Nice! We should annotate the package with that.

**Comment by justintuchek** [comment]
Is anyone actively working on this issue?

Don't want to step on anyones toes but looking at a good first issue to pickup

**Comment by recheej** [comment]
@passy can you close this? Looks like it's already done by you :)

https://github.com/facebook/flipper/commit/0daa5de428eedd79dd23c695c861d5ae77fda011

**Comment by passy** [comment]
@recheej Thanks for noting!
