### ISSUE TITLE
Discussion: React Native Realm database plugin

### ISSUE THREAD

**Issue by GabeConsalter** [facebook/flipper#750]
I think we need to talk about a database inspector plugin to realm in a react native app.

**Comment by mweststrate** [comment]
Would you mind formulating a bit more actionable issue? Not sure if this is a question, proposal or offer :)

**Comment by ptupi** [comment]
> I think we need to talk about a database inspector plugin to realm in a react native app.

Definitely! How can we start this?

**Comment by mweststrate** [comment]
Quickest way to start extending flipper is https://fbflipper.com/docs/extending/index.html
