### ISSUE TITLE
Flipper does not reload plugin when plugin source code is modified

### ISSUE THREAD

**Issue by oliviernotteghem** [facebook/flipper#756]
## 🐛 Bug Report
Flipper does not reload plugin when plugin source code is modified

## To Reproduce
Launch flipper from command line with a custom plugin folder specified in flipper config.
Verify custom plugin is loaded and run. 
Modify plugin index.js and save changes. Plugin does not refresh. If Flipper is killed/restarted, changes are visible.

output from flipper :
🕵️‍  Watching for plugin changes
🥫  Using cached version of analytics_flipper...
🥫  Using cached version of ribtree...
✅  Compiled all plugins.

## Expected Behavior
Flipper reloads plugin and changes are visible

## Environment
Mac desktop 0.30.2

**Comment by nikoant** [comment]
Hi @oliviernotteghem, could you check if the same works on your machine for built-in plugins? E.g. try to start Flipper dev mode (yarn && yarn start) and change some built-in plugin e.g. https://github.com/facebook/flipper/tree/master/src/plugins/network.

Also, do you have [watchman](https://facebook.github.io/watchman/) in PATH?

**Comment by oliviernotteghem** [comment]
Thanks @nikoant for your reply. I notice the same issue with Flipper in dev mode built from repo locally. I do have watchman in PATH. When I modify a plugin file, I don't see any activity in Flipper log at all.

watchman watch-list
{
    "version": "4.9.0",
    "roots": [
        "/Users/oliviern/Uber/flipper",
        "/Users/oliviern/Desktop/flipper-plugins/analytics",
        "/Users/oliviern/Uber/android",
        "/Applications/Flipper.app/Contents/Resources"
    ]
}

**Comment by nikoant** [comment]
@oliviernotteghem, thanks for checking this. This is actually expected that release version doesn't rebuild plugins on the fly. I have changed this recently as a part of file watching optimizations. It seems I missed there are cases when release build is used for plugin development. But that's strange that with "yarn start" it also doesn't work. I tried to reproduce this, but without any luck for now.

**Comment by oliviernotteghem** [comment]
@nikoant : thanks for clarifying hot reload was disabled on release builds. It doesn't sound unreasonable to use release build for plugin development, maybe whether watchman is used or not should be exposed in app settings / UI?

I just retested with yarn start and see only my update if I restart the app :(

**Comment by nikoant** [comment]
@oliviernotteghem could you also try to change some code inside Flipper itself, e.g. PluginContainer.tsx when "yarn start" is running. Will such change be detected and Flipper window reloaded?

**Comment by oliviernotteghem** [comment]
@nikoant: interesting, I can't repro issue if I modify PluginContainer.tsx or the network plugin tsx files. Issue happens only for my own plugins (whose folder path is specified in ~/.flipper/config.json)

**Comment by nikoant** [comment]
@oliviernotteghem could you try to add file with name ".watchmanconfig" containing just one empty json object "{}" to the folder where you keep your custom plugins (I guess "/Users/oliviern/Uber/android/tooling/flipper-plugins/")?

**Comment by nikoant** [comment]
@oliviernotteghem, this issue should be fixed in master now. Please verify it on your machine and feel free to re-open the issue if the issue still exists.

**Comment by oliviernotteghem** [comment]
@nikoant : confirmed my issue is fixed on master. Thanks a lot!
