### ISSUE TITLE
Question: Debugging network request made by exoplayer(native module)

### ISSUE THREAD

**Issue by s4kh** [facebook/flipper#775]
I am using `react-native-video` to stream HLS playlist, is there a way to inspect network requests sent from native module like AVPlayer or ExoPlayer?

**Comment by passy** [comment]
That depends on what they use for making their network connections. If they're setup to reuse the OkHttp client setup by the main app, you should be able to inspect them. However, it's possible that they communicate from a different process in which case they won't be able to communicate with Flipper by default.
