### ISSUE TITLE
Feature request: Network Response/Request modification

### ISSUE THREAD

**Issue by vkalmath** [facebook/flipper#777]
Thank you for the amazing tool. Gr8 work.
Is it possible enhance the network plugin so that we can set breakpoint in flipper on nw requests and modify the request and response params, similar to what we do on Charles Proxy.

**Comment by bizzguy** [comment]
How would this functionality overlap with the open Pull Request that would allow mock data in the Network calls? 

    https://github.com/facebook/flipper/pull/488

The PR has been open for some time now.

**Comment by vkalmath** [comment]
Will it be merged ever?

**Comment by passy** [comment]
Yes, hopefully. 🤞 We've been embarrassingly slow but someone internally is assigned in getting this to a merge-able state soon.

**Comment by passy** [comment]
Closing this in favour of the open PR.
