### ISSUE TITLE
Network plugin + OkHttp interceptor does not decompressed gzipped responses

### ISSUE THREAD

**Issue by damianw** [facebook/flipper#79]
Responses with `Content-Type: gzip` are not unzipped, and render garbage as plaintext in the Sonar network view.

**Comment by danielbuechele** [comment]
There is some logic in place to unzip requests, however for some reasons it is failing: https://github.com/facebook/Sonar/blob/master/src/plugins/network/RequestDetails.js#L64

@damianw Can you see why this is happening?

**Comment by damianw** [comment]
I'm not exactly sure as I haven't had time to investigate it. In the meantime, I've added a custom interceptor to perform the unzipping on the Android side.

**Comment by amenon** [comment]
@damianw typically, gzipped responses have the `Content-Encoding` set to `gzip` rather than the `Content-Type`.

I noticed that the plugin was not decompressing my OkHttp interceptor responses because my responses used a lower-case header name `content-encoding`. I have a PR (#143) to address that.

**Comment by damianw** [comment]
My mistake, I meant `Content-Encoding`

**Comment by passy** [comment]
I believe that this was fixed quite a while ago in the referenced commit.
