### ISSUE TITLE
Discussion: add deploy preview for PRs

### ISSUE THREAD

**Issue by lucasbento** [facebook/flipper#796]
Hello 👋 

I would like to suggest adding deploy previews for each PR, this helps a ton when reviewing them, both for the contributor and for the maintainer.

We got it set-up at [@react-native-community/upgrade-helper](https://github.com/react-native-community/upgrade-helper) and [@facebook/react-native-website](https://github.com/facebook/react-native-website) using [Netlify](https://www.netlify.com/), you can see an example [at the bottom of this PR](https://github.com/react-native-community/upgrade-helper/pull/140).

Configuration is fairly simple and can be done pretty quickly.

**Comment by passy** [comment]
Hey @lucasbento! I'm sorry, I may just be a bit tired today, but what exactly should I be looking for in the PR that you've linked there? What exactly is the preview part?

**Comment by lucasbento** [comment]
@passy: sorry, forgot the UI of the checks changes when the PR is closed, this one can illustrate this better: https://github.com/react-native-community/upgrade-helper/pull/159.

At the bottom you can see:

![image](https://user-images.githubusercontent.com/6207220/74462977-60d4ba80-4e91-11ea-9a8b-f30358d5e16d.png)

The `netlify/upgrade-helper/deploy-preview` runs on every PR creation and creates a live build for previewing the changes of the PR: https://deploy-preview-159--upgrade-helper.netlify.com/.

**Comment by passy** [comment]
Ah, gotcha. This shouldn't be much work. We already build the full app as part of our build pipelines. We'd just have to store the artifacts somewhere. I don't think GitHub Actions support this yet, though, and we're trying to get off of Circle CI in the medium term.

**Comment by lucasbento** [comment]
I think it would take some time to do with GitHub Actions, apparently [you can save the artifact](https://github.com/actions/upload-artifact) but not sure how to make it publicly available.

If you go forward with Netlify (you can also use [ZEIT Now](https://zeit.co/home)) then it's just a matter of putting in the script for building the `website` and it shouldn't take such a big decision as you can use it only for PRs and deploy previews.

**Comment by passy** [comment]
Our website changes are quite rare so I'm not sure how much value there is. I did set up artifact saving for the actions though, which is actually quite neat. It's on a branch right now, but that should be ready today. :)

**Comment by lucasbento** [comment]
Makes sense!
