### ISSUE TITLE
Discussion: add hotkeys to trigger Metro commands

### ISSUE THREAD

**Issue by lucasbento** [facebook/flipper#798]
It would be nice to add hotkeys to trigger the functionalities added in [`3dcfe9f`](https://github.com/facebook/flipper/commit/3dcfe9f3aef2b02ec8f520c0d331a962c1a1e197) for reloading and opening the developer menu.

It would also be great if those hotkeys were global and could, perhaps, be configured in the preferences screen, I would definitely be in for working on that.

**Comment by passy** [comment]
Agreed, this would be great to have! If you want to give it a shot, @lucasbento, please do. :)

**Comment by lucasbento** [comment]
@passy great! just to make sure that we are aligned, I'll start working on global hotkeys with a couple of configuration inputs in the preferences screen 🙂
