### ISSUE TITLE
Getting byteCount() does not exists for request.headers() okhttp3

### ISSUE THREAD

**Issue by nilesh1433** [facebook/flipper#80]
I have flavoured app and this is what I added in the gradle 
_devImplementation 'com.facebook.sonar:sonar:0.0.1'_.

However, after adding this I am getting error as _error: cannot find symbol method byteCount()_ .

I am using OkHttp3.

**Comment by yschimke** [comment]
This is same root cause as https://github.com/facebook/Sonar/issues/24

**Comment by yschimke** [comment]
Think this can be closed
