### ISSUE TITLE
Flipper’s dependencies throw build warnings

### ISSUE THREAD

**Issue by alloy** [facebook/flipper#803]
## 🐛 Bug Report

Adding Flipper integration to one’s iOS project adds a whole bunch of build warnings.

## To Reproduce

1. Create a new app:

   ```bash
   react-native init TestFlipper --version 0.62.0-rc.2
   open TestFlipper/iOS/TestFlipper.xcworkspace
   ```

1. Build (command-b)

1. See:
   <img width="272" alt="Screenshot 2020-02-14 at 17 00 15" src="https://user-images.githubusercontent.com/2320/74559518-e37a7a00-4f64-11ea-8dd7-f57f6bd996d6.png">

## Expected Behavior

No new warnings being added to the build.

## Environment

Xcode 11.3.1

**Comment by priteshrnandgaonkar** [comment]
There are few warnings from FlipperKit network plugin which I will fix it. Majority of the warnings are coming from FlipperKit's dependencies like Flipper-Folly, Flipper-PeerTalk, Flipper-RSocket, ComponentKit etc. I will fix the once coming from FlipperKit. I will fix the once coming from the dependencies later.

**Comment by alloy** [comment]
Perhaps some can be temporarily disabled with compiler flags, until you get to them? Although I believe one of them (Folly?) is mostly a header and thus warnings would have to be disabled on the targets that include it, which is going to be tougher.

**Comment by alloy** [comment]
@priteshrnandgaonkar Great stuff on getting rid of those fro FlipperKit 👌 Did you mean for this issue to be closed yet, though?

**Comment by maestor** [comment]
Is there any schedule when will dependencies warning fixed? After upgrading RN 0.62 which have Flipper support, I have massive amount of warning outputs. And my CI have 4MB of log restriction (Travis in use), so I didn't even get build finished. Reason is thousands of unnecessary warning output rows which goes over 35k lines (approximately row limit when 4MB exceed and task will terminated).

As a workaround to get builds finished, have to currently run xcodebuild with some ignore flags (CLANG_WARN_COMMA='NO' CLANG_WARN_DOCUMENTATION_COMMENTS='NO' CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF='NO').

**Comment by priteshrnandgaonkar** [comment]
Unfortunately we don't have plans yet. As most of the warnings are coming from Flipper's dependencies and not Flipper itself.  If someone is willing to take it up and fix the warnings in the dependencies then that would be awesome.

**Comment by vicary** [comment]
We are piping our CI/CD logs into AWS CloudWatch for internal team notifications and these warnings increase quite a bit of expenses for log ingestion traffic, we have no choice but the ignore everything with build flags at the moment.

**Comment by caiobiodere** [comment]
having the same issue here, looking forward to have them fixed soon!
