### ISSUE TITLE
Layout plugin regression.

### ISSUE THREAD

**Issue by mgoyanes** [facebook/flipper#805]
Changing view visibility from VISIBLE to GONE with the layout plugin does not work. After pressing enter the view visibility changes to VISIBLE.

This is reproducible in the most recent release. I hadn't tried this recently so do not know when it stopped working.

**Comment by cekkaewnumchai** [comment]
Hello @modocache, thank you for reporting the issue. I can reproduce this. Will look into this

**Comment by modocache** [comment]
(Heh @cekkaewnumchai I think you meant to mention @mgoyanes, not me 😅)
