### ISSUE TITLE
Discussion: distribute macOS application with DMG

### ISSUE THREAD

**Issue by lucasbento** [facebook/flipper#807]
The main point for this is to make it easier (and prettier) to install the application under the `Applications` folder, right now you just unzip it and it's left wherever the `.zip` was stored.

With `electron-builder` this should be pretty straightforward: https://www.electron.build/configuration/dmg.

**Comment by passy** [comment]
I've never quite understood the benefit of having a `dmg` over a normal `zip`, could you maybe explain how it's more convenient?

I generally wouldn't be opposed to having another option to our build script (e.g. `yarn build --mac-dmg`). We use the default behaviour in some other contexts, so I'd quite like to preserve this but adding an alternative option should be fine!

**Comment by lucasbento** [comment]
I got [this](https://stackoverflow.com/a/41400244/4252781) and [this](https://stackoverflow.com/a/3954517/4252781) which I think that are good points.

Also, I believe that it looks more _presentable_ with a DMG, with a zip I just forget about where the app is, but that's just me 😅

**Comment by passy** [comment]
Those are good points! Internally we build a `.pkg` for distribution, but it's all just lipstick on a pig. Package management on MacOS is a disaster.

Would you be interested in working on this? Otherwise I may open another issue with some instructions because this seems like it could be a nice starter issue. :)

**Comment by lucasbento** [comment]
> but it's all just lipstick on a pig

TIL `lipstick on a pig` 😄

> Package management on MacOS is a disaster.

Completely agree with this.

I can make some time to work on this, probably starting next week though as I'm working on #798. It's definitely fine to open another issue If you feel like there's another person available to work on this sooner 🙂

**Comment by passy** [comment]
Amazing! :)
