### ISSUE TITLE
Unable to integrate SDKs into React Native 0.61.5 - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by SvetlinStaevNewsUK** [facebook/flipper#816]
## 🐛 Bug Report
We have a standard React Native 0.61.5. When we try to integrate Flipper into the iOS part of the app with the guide provided here - https://fbflipper.com/docs/getting-started.html#setup-your-react-native-app we get the following error:

```
undef: _OBJC_CLASS_$_FlipperKitNetworkPlugin
undef: _OBJC_CLASS_$_SKIOSNetworkAdapter
undef: _OBJC_CLASS_$_FlipperKitReactPlugin
undef: _OBJC_CLASS_$_FKUserDefaultsPlugin
undef: _OBJC_CLASS_$_FlipperKitLayoutPlugin
undef: _OBJC_CLASS_$_SKDescriptorMapper
undef: _OBJC_CLASS_$_FlipperClient
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlipperKitNetworkPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKIOSNetworkAdapter", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperKitReactPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FKUserDefaultsPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperKitLayoutPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKDescriptorMapper", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in AppDelegate.o
```

We use the Objective-C integration in AppDelegate.m.

Any idea why that would be happening?

## Environment
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 412.38 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 22, 23, 25, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native: 0.61.5
```

**Comment by priteshrnandgaonkar** [comment]
Let me try to reproduce it. I will try making a new app and integrate it with the instructions mentioned in our docs.

If you have particular repro steps, do let me know.

**Comment by SvetlinStaevNewsUK** [comment]
Nothing specific added, just the init call and the `initializeFlipper` method in the AppDelegate.m plus the installation of the pods according to the docs. I also added an empty swift file in the project as it was failing because of Swift before that.

**Comment by priteshrnandgaonkar** [comment]
I did the following additional steps which is not listed in that doc which made the RN integration work.

Rather than adding empty swift file I added the following
- `/usr/lib/swift` as the first entry of the` LD_RUNPATH_SEARCH_PATHS`
- Added the following entries in LIBRARY_SEARCH_PATHS

```
 "$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"
 "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"
```
- set `DEAD_CODE_STRIPPING` to `Yes`

I will update the docs with this information. Having said that, I was not able to repro the errors which you have posted above.

![Screen Shot 2020-02-20 at 5 02 39 PM](https://user-images.githubusercontent.com/3865908/74960034-828af000-5403-11ea-96fd-504b9cbe8e3a.png)

**Comment by SvetlinStaevNewsUK** [comment]
Tried this but doesn't quite work unfortunately. I will await the next version of Flipper or RN, might be related to something within our current setup of these two.

**Comment by pix2D** [comment]
Having the same (similar?) issue:

```
Undefined symbols for architecture x86_64:
  "_swift_getFunctionReplacement", referenced from:
      _swift_getFunctionReplacement50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getFunctionReplacement50)
  "_swift_getOrigOfReplaceable", referenced from:
      _swift_getOrigOfReplaceable50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getOrigOfReplaceable50)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've set `LD_RUNPATH_SEARCH_PATHS` and `LIBRARY_SEARCH_PATHS` per the docs, as well as `DEAD_CODE_STRIPPING` to YES.

**Comment by pix2D** [comment]
I was able to get it working by following https://github.com/react-native-community/upgrade-helper/issues/191. The thing that fixed it for me was adding a empty swift file to the project through Xcode which created some kind of bridging header.

**Comment by priteshrnandgaonkar** [comment]
Closing this issue as it is solved in recent versions of 0.62

**Comment by matinzd** [comment]
Build succeeds but app crashes after a while!    
https://pastebin.com/uwHgZJQj

**Comment by maxckelly** [comment]
I'm also getting this issue, has anyone found a solution?

**Comment by Murtaza-arif** [comment]
> I did the following additional steps which is not listed in that doc which made the RN integration work.
> 
> Rather than adding empty swift file I added the following
> 
> * `/usr/lib/swift` as the first entry of the `LD_RUNPATH_SEARCH_PATHS`
> * Added the following entries in LIBRARY_SEARCH_PATHS
> 
> ```
>  "$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"
>  "$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"
> ```
> 
> * set `DEAD_CODE_STRIPPING` to `Yes`
> 
> I will update the docs with this information. These are some of the steps which are written in [objc integration](https://fbflipper.com/docs/getting-started.html#for-pure-objective-c-projects) too. Having said that, I was not able to repro the errors which you have posted above.
> 
> ![Screen Shot 2020-02-20 at 5 02 39 PM](https://user-images.githubusercontent.com/3865908/74960034-828af000-5403-11ea-96fd-504b9cbe8e3a.png)

How to the first step
