### ISSUE TITLE
couldn't find DSO to load: libflipper.so caused by: dlopen failed: library "libevent_extra-2.1.so" not found result: 0

### ISSUE THREAD

**Issue by ZacSweers** [facebook/flipper#824]
## 🐛 Bug Report
After upgrading to Flipper 0.31.2 and SoLoader 0.8.2, we had a runtime crash like below

```
2020-02-20 15:53:56.168 25246-25324/com.Slack.internal.debug E/SoLoader: couldn't find DSO to load: libflipper.so caused by: dlopen failed: library "libevent_extra-2.1.so" not found result: 0
2020-02-20 15:53:56.169 25246-25324/com.Slack.internal.debug E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.Slack.internal.debug, PID: 25246
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: library "libevent_extra-2.1.so" not found result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

## To Reproduce
Unfortunately happens in our internal project

## Expected Behavior
Doesn't crash

## Environment
Android 10, target/compile SDK 29

**Comment by passy** [comment]
@ZacSweers Sorry for the inconvenience! Can you share what architecture your emulator has?

**Comment by smithc42** [comment]
Same issue here. 
## 🐛 Bug Report
App crashing on start with below error:
```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: library "libevent_extra-2.1.so" not found result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

## To Reproduce
Internal project also but I can reproduce with the following dependencies:

Crashing:
Flipper : `0.31.0`
SoLoader: `0.8.1`
Fragment: `androidx.fragment:fragment-ktx:1.2.2` 

Working:
Flipper : `0.31.0`
SoLoader: `0.8.1`
Fragment: `androidx.fragment:fragment-ktx:1.2.1` 

Changing the fragment dependency seems to make it crash every time.

## Expected Behaviour
 No crash

## Environment
- Flipper : 0.31.0
- Soloader : 0.8.1
- Pixel 3A - Android 10

**Comment by michaelworth** [comment]
Re: @ZacSweers post above, the device we saw the issue on was a Pixel 3A.

**Comment by passy** [comment]
I've got a 2XL. Will try it out on that one today. Should be close enough.

**Comment by passy** [comment]
I've installed the sample app on my 2XL where it worked fine.

Additionally, I tried to add `fragment-ktx` in both versions which also didn't seem to make a difference and set the Flipper version to the published `0.31.0` artifacts. 

Could you try to install our sample app and see if that causes the same issue on the phones / emulators you have? Annoyingly, we don't have it on the most recent releases here but it should show up soon on the one that's landing right now: https://github.com/facebook/flipper/releases (give it ~1h from now)

**Comment by jaychang0917** [comment]
same issue here. 

@passy But works when I install the latest android sample apk.

##Environment
Flipper : 0.35.0
Soloader : 0.8.2
XiaoMi A1 - Android 9

**Comment by jaychang0917** [comment]
delete the `app/build` folder solve my problem.

**Comment by yueban** [comment]
Still occur on 0.49.0.

delete `app/build` or `rebuild` not solve it.

Solve it by changing `implementation "com.facebook.flipper:flipper:0.49.0"`
to `implementation "com.facebook.flipper:flipper:0.49.0@aar"`

add a `@aar` suffix.

**Comment by mweststrate** [comment]
Closing as the issue seems solved with two possible solutions

**Comment by rezareact** [comment]
> delete the `app/build` folder solve my problem, now it works.

`./gradlew clean` worked for me.

**Comment by Isaacmeedinaa** [comment]
This does not work with flipper version 0.54.0

**Comment by stopachka** [comment]
@Isaacmeedinaa if you found this through a react-native bug, I set the flipper version to 0.105.0, and it went this past this bug.

**Comment by demondayza** [comment]
@stopachka that worked great to fix my issue above everything else. I had to find mine through logcat as it was a hard crash.

**Comment by willstepp** [comment]
> @Isaacmeedinaa if you found this through a react-native error, I set the flipper version to 0.105.0, and it went this past this bug.

Lifesaver! Thank you, have a 🍺 on me. May I ask how you figured that out?

**Comment by stopachka** [comment]
Cheers :) — let me know if ever in NYC!

Based on the logcat, started looking deeper into flipper. Ended up
discovering this in their docs:

https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk

**Comment by mweststrate** [comment]
Locking the issue as above link with: "how to update to latest first" is a great conclusion :)
