### ISSUE TITLE
Discussion: do we have plan to upgrade LeakCanary to 2.0?

### ISSUE THREAD

**Issue by 060601199** [facebook/flipper#832]
LeakCanary2 uses 10x less memory and some other benefits: https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/. Do we have a plan to upgrade it in near future? Thanks.

I saw there was a discussion before but got closed: https://github.com/facebook/flipper/issues/497. LeakCanary2 is released with stable version now, maybe it's time to upgrade it?

**Comment by passy** [comment]
We don't have any plans on the team, but would definitely be more than happy to review a PR if somebody wants to take a stab at it!

**Comment by pyricau** [comment]
👋🏻LeakCanary author here. I don't really have time to figure out how to create a Flipper plugin (especially the desktop / JS part) but I'm more than happy to help with reviews and guidance as well. Also happy to create new APIs if necessary. The LeakCanary 1 integration is passing a giant string and parsing it. We can do better :)
