### ISSUE TITLE
No route to flipper found when wifi debugging 

### ISSUE THREAD

**Issue by farsheel** [facebook/flipper#880]
## 🐛 Bug Report

Getting " no route to flipper found" when connected using wifi debugging. can't connect db plugin 

## To Reproduce

1. Use any android device.
2. Add flipper db plugin
` client.addPlugin(new DatabasesFlipperPlugin(this));`
3. connect the device using `adb connect IP:PORT`
4. install the app

![image](https://user-images.githubusercontent.com/9196332/76284816-450fd900-62c4-11ea-9b22-ce6c4c6d07ad.png)

## Environment
**Devices**
1. Android 7.1.1 (Samsung Galaxy TAB A)
2. Android 7.1.2 (ELO TAB)

**Implementations**
```
  debugImplementation 'com.facebook.flipper:flipper:0.31.2'
  debugImplementation 'com.facebook.soloader:soloader:0.8.2'
```

Flipper desktop version : 0.31.2 (Ubuntu 18.4)

**Comment by mweststrate** [comment]
I am not familiar with wifi debugging, does it work correctly if you debug using an USB connection?

**Comment by farsheel** [comment]
Yes, USB debugging works perfectly.

i also tried with XIOMI Redmi 5

**Comment by mweststrate** [comment]
I just tried it locally, and it seems to works fine for me if I:

1. connect with USB
2. check `adb devices` shows devices
3. run `adb tcpip 5555`
4. disconnect
5. make sure pc and mobile are on the same wifi
6. run `adb connect <phone ip>:5555`
7. start flipper

Please do make sure the ports 5555, 5037, 8088, 8089 are open and no other process is running on them (especially the last two are quite common)

**Comment by barriosnahuel** [comment]
Hi!
Same issue here if I start Flipper **after** starting Android Studio.

By running: `sudo lsof -i -P -n` I get:
```
adb       22465       nbarrios    6u  IPv4 0x540e0965290da6cf      0t0  TCP 127.0.0.1:5037->127.0.0.1:53182 (ESTABLISHED)
adb       22465       nbarrios    9u  IPv4 0x540e09652f2a69df      0t0  TCP 127.0.0.1:5037->127.0.0.1:53184 (ESTABLISHED)
adb       22465       nbarrios   16u  IPv4 0x540e09652fb1a057      0t0  TCP 127.0.0.1:5037 (LISTEN)
adb       22465       nbarrios   17u  IPv4 0x540e09652d2ec9df      0t0  TCP 127.0.0.1:5037->127.0.0.1:53327 (ESTABLISHED)
adb       22465       nbarrios   18u  IPv4 0x540e09652ed94057      0t0  TCP 127.0.0.1:5037->127.0.0.1:53328 (ESTABLISHED)
adb       22465       nbarrios   19u  IPv4 0x540e09652eda26cf      0t0  TCP 192.168.0.12:53167->192.168.0.13:5555 (ESTABLISHED)
adb       22465       nbarrios   21u  IPv4 0x540e09650ca21057      0t0  TCP 127.0.0.1:5037->127.0.0.1:53330 (ESTABLISHED)
Flipper   23054       nbarrios   25u  IPv4 0x540e0964fd8106cf      0t0  TCP 127.0.0.1:53184->127.0.0.1:5037 (ESTABLISHED)
Flipper   23054       nbarrios   27u  IPv4 0x540e09652fb26d47      0t0  TCP 127.0.0.1:53182->127.0.0.1:5037 (ESTABLISHED)
Flipper   23054       nbarrios   29u  IPv6 0x540e096524bee4ff      0t0  TCP *:8088 (LISTEN)
Flipper   23054       nbarrios   30u  IPv6 0x540e096524bf0d3f      0t0  TCP *:8089 (LISTEN)
studio    23468       nbarrios  273u  IPv4 0x540e09652f2a6057      0t0  TCP 127.0.0.1:6942 (LISTEN)
studio    23468       nbarrios  540u  IPv4 0x540e09652165cd47      0t0  TCP 127.0.0.1:63342 (LISTEN)
studio    23468       nbarrios  605u  IPv4 0x540e096527afa9df      0t0  TCP 127.0.0.1:8700 (LISTEN)
studio    23468       nbarrios  607u  IPv4 0x540e09652d2ec057      0t0  TCP 127.0.0.1:53327->127.0.0.1:5037 (ESTABLISHED)
studio    23468       nbarrios  608u  IPv4 0x540e09652d2ead47      0t0  TCP 127.0.0.1:53328->127.0.0.1:5037 (ESTABLISHED)
studio    23468       nbarrios  613u  IPv4 0x540e09652ed936cf      0t0  TCP 127.0.0.1:53330->127.0.0.1:5037 (ESTABLISHED)
studio    23468       nbarrios  614u  IPv4 0x540e09650ca1fd47      0t0  TCP 127.0.0.1:8600 (LISTEN)
```

As you can see Android Studio is also using port `5037`. Closing and opening Android Studio again it uses the same port.

I if keep Android Studio closed and then I start Flipper, then I get a different error:
![image](https://user-images.githubusercontent.com/196234/76589475-f8e1b600-64c8-11ea-803a-0275a82301e0.png)

Here are port' status:
```
adb       22465       nbarrios    6u  IPv4 0x540e0965290da6cf      0t0  TCP 127.0.0.1:5037->127.0.0.1:53182 (ESTABLISHED)
adb       22465       nbarrios    9u  IPv4 0x540e09652f2a69df      0t0  TCP 127.0.0.1:5037->127.0.0.1:53184 (ESTABLISHED)
adb       22465       nbarrios   16u  IPv4 0x540e09652fb1a057      0t0  TCP 127.0.0.1:5037 (LISTEN)
adb       22465       nbarrios   19u  IPv4 0x540e09652eda26cf      0t0  TCP 192.168.0.12:53167->192.168.0.13:5555 (ESTABLISHED)
Flipper   23054       nbarrios   25u  IPv4 0x540e0964fd8106cf      0t0  TCP 127.0.0.1:53184->127.0.0.1:5037 (ESTABLISHED)
Flipper   23054       nbarrios   27u  IPv4 0x540e09652fb26d47      0t0  TCP 127.0.0.1:53182->127.0.0.1:5037 (ESTABLISHED)
Flipper   23054       nbarrios   29u  IPv6 0x540e096524bee4ff      0t0  TCP *:8088 (LISTEN)
Flipper   23054       nbarrios   30u  IPv6 0x540e096524bf0d3f      0t0  TCP *:8089 (LISTEN)
```

Any suggestion? Should I create a different issue?

## Context
- Home's wifi network;
- Moto G5 Plus;
- OS Android `v8.1.0`;

**Comment by barriosnahuel** [comment]
Working on v0.136.0 and the new wireless debugging feature by Android Studio Bumblebee
