### ISSUE TITLE
Docs: Link to download for Mac standalone is broken

### ISSUE THREAD

**Issue by FRizzonelli** [facebook/flipper#882]
Hello guys!

Unfortunately link to download for [Mac](https://www.facebook.com/fbflipper/public/mac) is broken (returns 404). Can you upload again the installer or provide a new link? Thank you for your awesome work :)

**Comment by rizwanatta** [comment]
after 19 hours still the same! it's not being downloaded! and for out of the blue no reason old install said sorry we cannot verify you and move to bin please.  Waiting for it hard FB Pros.

**Comment by passy** [comment]
Sorry, this got fixed yesterday.
