### ISSUE TITLE
Desktop app window is not displayed in WIn10

### ISSUE THREAD

**Issue by AngelinaBallerina11** [facebook/flipper#885]
## 🐛 Bug Report
 I have installed the latest version of Flipper for Windows and incorporated the latest dependency to the android app. The desktop app works on background, is displayed in the taskbar but the window cannot be maximized.

## To Reproduce
Open Flipper desktop app. Try to maximize the window.

## Environment
Windows 10 with all the latest updates

**Comment by mweststrate** [comment]
@nikoant  does this ring a bell to you?

**Comment by nikoant** [comment]
@AngelinaBallerina11, are you using Dark Mode on Windows 10? If yes, then this is caused by Electron issue https://github.com/electron/electron/issues/19468. Please try switching from dark mode to standard one.

**Comment by AngelinaBallerina11** [comment]
> @AngelinaBallerina11, are you using Dark Mode on Windows 10? If yes, then this is caused by Electron issue [electron/electron#19468](https://github.com/electron/electron/issues/19468). Please try switching from dark mode to standard one.

Yes, I was using Dark mode, but after switching the app is still not displayed. It is interesting that when I put a cursor on the Taskbar icon mini-version of the window is displayed, but it is not possible to maximize it.

**Comment by nikoant** [comment]
@AngelinaBallerina11, that's strange, the latest version works fine on my Windows 10 machine. Just to check - have you disabled Dark Mode for both Windows and apps? There are two different settings. And have you restarted Windows after that change?

**Comment by hanhmh1203** [comment]
I think because in the path of sdk, there was the space. somethings like "C:\Users\Huu Hanh" and Flipper can not read " ", too stupid :(

**Comment by nikoant** [comment]
@hanhmh1203, do you mean path to Android SDK?

**Comment by AngelinaBallerina11** [comment]
Closing, the issue was with the display, the flipper window was going beyond the screen dimentions. I could put it in place by using MOVE + arrows
