### ISSUE TITLE
Scrolling doesn't stick to bottom after filtering Logs

### ISSUE THREAD

**Issue by lucasr** [facebook/flipper#90]

**Comment by danielbuechele** [comment]
It only seems to work when there is no selection made. Removing this line should fix it:
https://github.com/facebook/Sonar/blob/master/src/device-plugins/logs/LogTable.js#L551

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!

**Comment by tdubourg** [comment]
@passy it certainly still is an issue. It's actually really bad, it makes flipper almost unusable. You have to keep pressy "clear", if your logs are scrolling fast, then it's simply useless.

**Comment by jknoxville** [comment]
Fixed in 6bdaa6aff1aaba62768d61495debdd7dc8f75391

Will be included in the next release (v0.21.2)
