### ISSUE TITLE
Discussion: Log filtering

### ISSUE THREAD

**Issue by DomiR** [facebook/flipper#920]
I'd like to see more options for the log filtering.

Currently we can search for logs via the search field, but as soon as one presses enter, it turns the search query into a filter which does not behave as one might expect and there is no documentation about this behavior.

A filter works on table columns and is either in 'enum', 'include' or 'exclude' mode. Include and exclude are misleading here as well, as they check for equal and not equal respectively. The enum filter is not creatable by search input, but is there as a default filter (the one dropdown Type=All).

To create a filter one needs to input `Key=Value` or `Key:Value`, where `=` is preferred over `:` so one could theoretically input `Key=x:y` I think. To negate the filter (and toggle 'exclude' mode) one needs to input `Key!=Value` or `Key=!Value', so there are two ways to do this. 

I needed to look at the source code to understand this behavior and I don't think it is very intuitive. (This can be found in Searchable.tsx)

As it is not possible to add Tags to logs via react-native (or at least I don't know how), a common way is to scope the logs similar to how the popular debug package does it. 
The output my look like: 
```
[Mon Mar 23 2020 12:31:13.408]  LOG      myApp:debug:connectionStore       ble adapter status: true +0ms
[Mon Mar 23 2020 12:31:13.409]  LOG      myApp:debug:connectionStore       location status: true +4ms
[Mon Mar 23 2020 12:31:13.409]  LOG      myApp:debug:networkStore          loaded networks +0ms 1
[Mon Mar 23 2020 12:31:13.409]  LOG      myApp:debug:deviceManagerStore    with box config [] +1s
[Mon Mar 23 2020 12:31:13.410]  LOG      myApp:debug:deviceManagerStore    loading model value null +1ms
[Mon Mar 23 2020 12:31:13.410]  LOG      myApp:debug:roomStore             loaded rooms: [{"id":"default","name":"New room","icon":{"type":"icon","source":"rooms/defaultroom","name":"rooms/defaultroom"},"iconUri":null}] +0ms
[Mon Mar 23 2020 12:31:13.410]  LOG      myApp:debug:networkStore          activate network: "261D072D-0661-4C68-8B7D-3FC3ABF0A30B" +255ms
[Mon Mar 23 2020 12:31:13.411]  LOG      myApp:debug:networkStore          saving network +5ms
[Mon Mar 23 2020 12:31:13.411]  LOG      myApp:debug:networkStore          activated network with netKey "726F4FEE256245AD33423B6B39F47D85" +19ms
[Mon Mar 23 2020 12:31:13.411]  LOG      myApp:debug:connectionStore       connect +302ms
[Mon Mar 23 2020 12:31:13.412]  LOG      myApp:debug:connectionStore       connecting with real devices:  +15ms 1
[Mon Mar 23 2020 12:31:13.412]  LOG      myApp:debug:connectionStore       connect to nearest proxy node +4ms
[Mon Mar 23 2020 12:31:13.412]  LOG      myApp:debug:networkStore          launched without url +34ms
```

I would love to be able to filter like chrome does it where I can add filters `myApp:debug:connectionStore` and `myApp:debug:deviceManagerStore` so I can dynamically turn on and off log scopes I'm interested in.

At least the current behavior should be documented somewhere but I think it is not very intuitive right now. Searches should not be turned into filters, that suddenly exclude all results and should also not be transformed via seemingly arbitrary query-rules. If you type in `myApp:debug:connectionStore` into the search field it works as expected but as soon as you press the enter button it turns into `myApp=debug=connectionStore` and the table is empty.

I tried to add a pull request to at least change the current `include` and `exclude` behaviour into what they say, but the community build step is broken, as we don't have the `fb` folder in plugins dir.
`compileRenderer` in `build-utils.ts` should use `pathExistsSync`. Also the icons get downloaded every time, which sometimes takes ages (I should have gigabit here, but maybe external downloaders get a limit). They should probably be cached in the static folder as well.

**Comment by jknoxville** [comment]
Thanks for your feedback @DomiR 
I think you're right that the search / filter UI lacks discoverability, consistency, and functionality. I think this is due to it growing dynamically over time without an over arching vision.

It would be great to improve it. If you publish your PR, we can import it and fix up any fb-related breakages, sorry about that, but it's the best system we've been able to come up with.
