### ISSUE TITLE
Releases are missing changelogs

### ISSUE THREAD

**Issue by ZacSweers** [facebook/flipper#934]
The past few releases are no longer including release notes. Are these listed somewhere else?

**Comment by passy** [comment]
We switched to a new "automated" way and then forgot to actually leave notes that could be extracted. I'll manually backfill this today. :)

**Comment by passy** [comment]
Backfilled some notes.

**Comment by ZacSweers** [comment]
Thanks 👍

**Comment by ZacSweers** [comment]
Looks like it's broken again :/
