### ISSUE TITLE
Build error on manually linked libraries

### ISSUE THREAD

**Issue by sburaksak** [facebook/flipper#938]
## 🐛 Bug Report
I am getting build error on manually linked libraries, like code-push, react native unity view etc.
There is no error if try without flipper pods
like below: 
<img width="259" alt="Screen Shot 2020-03-28 at 00 08 13" src="https://user-images.githubusercontent.com/56319708/77800635-45f88700-7088-11ea-81cf-99fb23db707f.png">
<img width="272" alt="Screen Shot 2020-03-28 at 00 08 21" src="https://user-images.githubusercontent.com/56319708/77800641-4b55d180-7088-11ea-8350-adbf0f1e0c46.png">

## To Reproduce
install this pods and try build

 ```
def flipper_pods()
    flipperkit_version = '0.34.0'
    pod 'FlipperKit', '~>' + flipperkit_version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitLayoutPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
    pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitReactPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
  end

  # Post Install processing for Flipper
  def flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == 'YogaKit'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.1'
        end
      end
    end
    file_name = Dir.glob("*.xcodeproj")[0]
    app_project = Xcodeproj::Project.open(file_name)
    app_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
        unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
          puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
          cflags << '-DFB_SONARKIT_ENABLED=1'
        end
        config.build_settings['OTHER_CFLAGS'] = cflags
      end
      app_project.save
    end
    installer.pods_project.save
  end 
```

## Environment
react native 0.62
latest flipper

**Comment by priteshrnandgaonkar** [comment]
Can you share the exact repro steps, so that we I can try reproducing it on my end ?

**Comment by K-Leon** [comment]
I'm seeing the same issues (upgrading RN from a previous version) I'm using a default setup without many package.

**Comment by K-Leon** [comment]
@sburaksak Did you have any success solving this?

**Comment by alexlevy0** [comment]
same issue with react-native-onesignal

**Comment by MayoudP** [comment]
@alexlevy0 Same here, did you find a fixe ?
