### ISSUE TITLE
Discussion: React Devtools v3

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#945]
Will there be any plans to also include react devtools v3 for those using Flipper with RN0.61 or lower?
It's fairly simple to add support. Tried to change version for built in plugin:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/5339061/77930008-e3e48f80-72dc-11ea-857e-004c07de992a.png">

---

Ideally would love to create and 3rd party plugin, but somehow Flipper ignores my local package...

**Comment by passy** [comment]
Hey @usrbowe, we don't have any plans to support older versions, but if you want to publish it as a standalone plugin on npm, that sounds like a great idea. Can you share what's not working with your local setup?

**Comment by usrbowe** [comment]
So basically I added this path to `~/.flipper/config.json`
```json
"pluginPaths": ["~/Git/flipper-plugins/flipper-plugin-test-info/"],
```
I restart Flipper and my expectation is to see it in this list of plugins:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/5339061/77992496-be956700-7358-11ea-9201-270e818637ca.png">

**Comment by mweststrate** [comment]
I think your path should be `["~/Git/flipper-plugins"]`

**Comment by usrbowe** [comment]
Thanks a lot, somehow I thought need to specify path for each plugin. The documentation says this correctly :).

So two findings to add. Related to Flipper class for plugins.
1. `FlipperDevicePlugin` - the plugin will show automatically under `React Native` (section will appear once we have running metro packager) 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/5339061/78097134-075b2780-740e-11ea-849d-c68a0a8535dd.png">
2. `FlipperPlugin` - the plugin will be hidden, and we need to expand the list and enable from app: 
<img width="242" alt="image" src="https://user-images.githubusercontent.com/5339061/78097184-2b1e6d80-740e-11ea-8712-0a7c699bf1ae.png"> 

Enabling plugin should be done by each plugin, so this is only needed during development:
```js
import { addPlugin } from 'react-native-flipper';

addPlugin({
  getId() {
    return 'flipper-plugin-info-2';
  },
  onConnect() {},
  onDisconnect() {},
});
```

**Comment by usrbowe** [comment]
For those interested, here is the published plugin for React Devtools v3: https://www.npmjs.com/package/flipper-plugin-react-devtools-v3
Works with React Native bellow `0.62`.

**Comment by passy** [comment]
Amazing! Thank you. I'll close the issue here then. :)
