### ISSUE TITLE
Arrays and objects are shown as string

### ISSUE THREAD

**Issue by acerbastimur** [facebook/flipper#950]
## 🐛 Bug Report

Hi, I'm starting to use Flipper in my React Native project. When I log an object like:
```
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
````

It's shown as a string. 
<img width="852" alt="Screen Shot 2020-03-31 at 11 51 08" src="https://user-images.githubusercontent.com/33218120/78006629-ea5b2180-7345-11ea-9861-4917f0a09a0e.png">

I don't want to use debugger in my browser but browser shows it as 
<img width="282" alt="Screen Shot 2020-03-31 at 11 54 52" src="https://user-images.githubusercontent.com/33218120/78007065-70776800-7346-11ea-86a2-9b340b8e2218.png">
which is very usefull for nested objects. Will you planning this feature ?

**Comment by mweststrate** [comment]
Yes, we intend to support better object representations like that partially in the future, although it will probably not give the same experience, because the browser connects to the living objects, and can evaluate them lazily when they are being expanded and show the underlying part, while the Flipper integration has to serialize them (the log connection is unidirectional at this moment), but an serialized can grow unbounded large.

A simple solution might be to use `console.log(JSON.stringify(object, null, 2))`. Whether that works depends on the serializability of your object.

**Comment by antonigiske** [comment]
Is there any updates on this issue?

**Comment by mweststrate** [comment]
JSON is now formatted in the logs plugin, but beyond that no improvements like lazily expanding objects and such are planned.

**Comment by mrusmanali** [comment]
why on earth FB removed a working chrome debuger to replace it with this flipper piece of shit....

**Comment by mrusmanali** [comment]
on top of that now its default.... always shoving their own stupid ideas up other people butts... so typical of FAcebook

**Comment by atropos0902** [comment]
any updates on this?

**Comment by atropos0902** [comment]
I am having a really hard time debugging my react native app since the json data is not being displayed in json format. Just in messy string :(

**Comment by robbie-c** [comment]
Is there a way of overriding the default string formatter? It's very common to do something like `console.log({ payload })` and writing `console.log({payload: JSON.stringify(payload, null, 2)})` is quite a lot worse.

**Comment by minhchienwikipedia** [comment]
Any update? why did this issue close? Please open it!

**Comment by WarrenBuffering** [comment]
Agreed, this is a significant portion of how I want to debug. Please open

**Comment by WarrenBuffering** [comment]
Agreed, this is a significant portion of what I want to debug. Please reopen

**Comment by israromar** [comment]
> Agreed, this is a significant portion of what I want to debug. Please reopen

+1

**Comment by AndriyZahura** [comment]
Really miss this feature since I moved from React Native Debugger to the flipper due to the use of reanimated

**Comment by Ryabchikus** [comment]
any news?
I really need lazily expanding because I still use react-native-debugger with crutches due to the lack of friendly logging
maybe someone knows a plugin for this?
