### ISSUE TITLE
Question: How to install plugin via zip/tar.gz?

### ISSUE THREAD

**Issue by usrbowe** [facebook/flipper#955]
I wanted to use drag&drop installation of plugins (without need to publish on NPM), to distribute internal plugins. But somehow I'm hitting some issue.

The first was, that it was not very clear what is the format of plugin. Later I found out this is correct shape of archive we need to provide:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/5339061/78129376-18c22500-744a-11ea-997c-e2fc4707e10a.png">
After restarting Flipper I check `~/.flipper/thirdparty/` and can see my newly added plugin, but it doesn't show in the list `Plugin Status`, even if I invoke the `addPlugin` in my app.

---

 **Edit**
So actually those plugins (as compared to locally linked) will show under `Install plugins`. Still can't the plugin though.

---

**Update 2**
So found out when reset local dev, it will throw this error:
```
❌  Plugin flipper-plugin-test-feature is ignored, because it could not be compiled.
ReferenceError: SHA-1 for file /Users/anonymous/Git/flipper/desktop/node_modules/metro/src/lib/polyfills/require.js (/Users/anonymous/Git/flipper/desktop/node_modules/metro/src/lib/polyfills/require.js) is not computed

**Comment by passy** [comment]
@nikoant Can you shed some light here? :)

**Comment by nikoant** [comment]
Sorry, this was broken for Flipper running in dev mode (yarn start). I fixed this just recently in this commit https://github.com/facebook/flipper/commit/0711617c63efe15e4a4078e6ee13693899dadf87.

**Comment by nikoant** [comment]
Also I'm going to update docs on plugin format soon. Installation from files is kinda "early access" feature for now :)
