### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FlipperClient

### ISSUE THREAD

**Issue by TimBroddin** [facebook/flipper#975]
Hi all,

I'm getting `Undefined symbol: _OBJC_CLASS_$_FlipperClient`when trying to build a release build. Everything works great with debug builds.

Dead code stripping is on and the Swift bridging header is present.

My Podfile includes this:

```
def add_flipper_pods!
  version = '~> 0.33.1'
  pod 'FlipperKit', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
end
```

Does anyone have any clues?

**Comment by TimBroddin** [comment]
Nevermind, I think I found it.

I was using react-native-flipper, which includes some Objective C code that tries to include FlipperClient. Since FlipperKit is only included with de Debug configuration you get that error.

I'll be filing a bug report towards `react-native-flipper`.

**Comment by justinairbase** [comment]
@TimBroddin Can you please link the issue you filed against `react-native-flipper` here? 
I'm facing this same issue after trying to use `react-native-flipper`.
