### ISSUE TITLE
Desktop app Error: Feature not implemented

### ISSUE THREAD

**Issue by wael-Fadlallah** [facebook/flipper#979]
## 🐛 Bug Report

  I followed the install guide in the https://github.com/facebook/flipper but I have empty debugging log and the fallowing error in the console  

`
src/init.bundle:248971 Error: Feature not implemented
    at getUser (src/init.bundle:81058)
    at _default (src/init.bundle:248967)
    at src/init.bundle:237901
    at Array.map (<anonymous>)
    at _default (src/init.bundle:237901)
    at src/init.bundle:811
    at Object.rehydrate (src/init.bundle:97207)
    at _rehydrate (src/init.bundle:96541)
    at src/init.bundle:96566
(anonymous) @ src/init.bundle:248971
index.dev.html:1 Uncaught (in promise) Error: ENOENT: no such file or directory, mkdir 'C:\tmp\flipper'
src/init.bundle:238072 Uncaught (in promise) FailError
src/init.bundle:237996 Error: Command failed: C:\Users\Revo\AppData\Local\android\sdk/tools/emulator -list-avds
The system cannot find the path specified.

    at ChildProcess.exithandler (child_process.js:308)
    at ChildProcess.emit (events.js:210)
    at maybeClose (internal/child_process.js:1021)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283)
`
## Environment
windows 10

**Comment by cekkaewnumchai** [comment]
Please provide repro step for this. Did you run from source or use the one in the website?

**Comment by wael-Fadlallah** [comment]
I tried both , same error

**Comment by cekkaewnumchai** [comment]
Did it happen when you just open Flipper?

**Comment by wael-Fadlallah** [comment]
yes , here what is looks like 
![Capture](https://user-images.githubusercontent.com/19624163/78509380-6d171e80-7742-11ea-933e-562491a32c9f.PNG)

**Comment by passy** [comment]
The "Feature not implemented" error is misleading here. It should probably be a warning instead.

**Comment by wael-Fadlallah** [comment]
any idea how to it work !?

**Comment by cekkaewnumchai** [comment]
You can ignore "Feature not implemented" errors as @passy mentioned. Seems the error might come from the last error shown in the picture. 

Did you encounter Android emulator not found? I think Flipper doctor should have caught it. Can you try click on the icon beside the setting icon to see if all are checked? Otherwise, you need to make sure that the SDK path is correctly set.

**Comment by wael-Fadlallah** [comment]
No I didn't encounter any android emulator error , and of as flipper doctor I had watchman and openssl error because they wasn't in my system so I install them and now the doctor check is all good and the SDK path is correctly set 
![Capture](https://user-images.githubusercontent.com/19624163/78585643-0bf95480-77ef-11ea-85c0-03ab2914d9cc.PNG)

**Comment by wael-Fadlallah** [comment]
No I didn't encounter any android emulator error because I don't have any am using my phone to run apps  , and as for flipper doctor I had watchman and openssl error because they wasn't in my system so I install them and now the doctor check is all good and the SDK path is correctly set
![Capture](https://user-images.githubusercontent.com/19624163/78586343-2849c100-77f0-11ea-98ec-73a35af4538d.PNG)

**Comment by whenmoon** [comment]
I am getting this error with React Native v0.62.2 and Flipper v0.46.0, mac ,physical Pixel 2XL:

```
bundle.js:2281 Error: Feature not implemented
    at getUser (bundle.js:597)
    at e.default (bundle.js:2281)
    at bundle.js:1577
    at Array.map (<anonymous>)
    at _default (bundle.js:1577)
    at bundle.js:3
    at Object.rehydrate (bundle.js:707)
    at _rehydrate (bundle.js:699)
    at bundle.js:699
```

**Comment by mweststrate** [comment]
This issue will be fixed in the next release, thanks for reporting!
