### ISSUE TITLE
Add quotes to doctor command

### ISSUE THREAD

**Issue by krisidmisso** [facebook/flipper#980]
## 🐛 Bug Report

 If the username in Windows contains a space the following error is shown:
![image](https://user-images.githubusercontent.com/9657055/78509069-a9bb3800-778b-11ea-9c15-8b336dd12050.png)

## To Reproduce

Add a user with space in windows and check Flipper doctor

## Environment

  Windows 10
  Latest Android Studio

**Comment by nikoant** [comment]
Thanks for reporting, @krisidmisso!
