### ISSUE TITLE
Question:  how execute on linux

### ISSUE THREAD

**Issue by cavator** [facebook/flipper#985]
i download a zip file, have no ideia what is the MTF file to execute, have no fucking tutorial on the site, have no one single explanation of nothing

**Comment by cekkaewnumchai** [comment]
Sorry for the sparse instruction for setting up the desktop app.

For Linux, you can unzip the file downloaded from the website. Then, you can open `flipper-project` and Flipper will be opened. After that, you can follow Flipper doctor instruction to install missing software.

**Comment by zTaaso** [comment]
@cekkaewnumchai There's no `flipper-project` file.

**Comment by nikoant** [comment]
@zTaaso `flipper-project` was renamed back to `flipper` in the latest release 0.37.0.

**Comment by passy** [comment]
This was renamed again.

**Comment by Maskedman99** [comment]
Ubuntu 18.04, clicking the flipper file results in error. Please distribute the app in .deb or .rpm formats
![Screenshot-20200422201222-918x607](https://user-images.githubusercontent.com/31368194/79996105-ac30c800-84d5-11ea-8681-a9300603c4af.png)
