### ISSUE TITLE
Question: Connect application failed

### ISSUE THREAD

**Issue by zgxbliss** [facebook/flipper#991]
I am using Flipper 0.36.0 and Android Studio 3.6.2 on Mac machine. I can see the android device but can't connect to application running on android device with the following error. What's the reason and how can I solve it?
===
flipper: Desktop failed to provide certificates. Error from flipper desktop:
    Premature end of stream, needed 4 more bytes
===

**Comment by cekkaewnumchai** [comment]
Thank you for reporting this. I'm looking into it.

**Comment by zgxbliss** [comment]
Is there any information or suggestion for solving this error?

**Comment by cekkaewnumchai** [comment]
Do you mind trying to upgrade Flipper to latest version both on Android and Mac sides?

**Comment by zgxbliss** [comment]
I think Flipper 0.36.0 which I am using is already the latest version. And the configuration in AndroidStudio is following.Is there any missing?

    debugImplementation 'com.facebook.flipper:flipper:0.36.0'
    debugImplementation 'com.facebook.soloader:soloader:0.8.2'
    releaseImplementation 'com.facebook.flipper:flipper-noop:0.36.0'

**Comment by romreed** [comment]
I have the same issue for 
"react-native": "0.62.2",
"react-native-flipper": "^0.39.0",
flipper 0.39.0 (50.0.0)
