### ISSUE TITLE
Network plugin displays wrong time for request time on iOS devices

### ISSUE THREAD

**Issue by Johan-dutoit** [facebook/flipper#997]
## 🐛 Bug Report
When my app makes a request at 09:57 it displays the request time as 03:15.
Could possibly be a timezone issue or parsing the date incorrectly.

## To Reproduce
Make a request outside of the timezone the plugin was made in  👀. 

## Environment
MacOS: 10.15.4 (19E287)
Flipper: 0.35.0 (0.35.0)
Flipper Pods: 0.33.1
React Native: 0.62.1
iOS simulator: 13.4

**Comment by cekkaewnumchai** [comment]
Thank you for reporting this! I will take a look into it

**Comment by merovingienne** [comment]
Seeing the same issue on Flipper version 0.49.

### Environment
MacOS: 10.15.3 (19D76)
Flipper: 0.49.0
Flipper Pods: 0.33.1
React Native: 0.62.2
iOS simulator: 13.3

**Comment by swrobel** [comment]
I'm still seeing this on flipper 0.92.0.

Actual time: 11:24am Pacific
Request time: 20:06

**Comment by mweststrate** [comment]
We don't report the actual time, we report the device time. Does the time line up with the time as reported on the device / emulator?

**Comment by swrobel** [comment]
@mweststrate it does not match the device time (assuming by that, you mean the time shown in the status bar at the top of the device). I have no idea what time it could possibly be reflecting.

**Comment by mweststrate** [comment]
Interesting, what kind of device / application stack does the issue occur with?

**Comment by swrobel** [comment]
I just did some additional testing and the time seems to be correct with an Android Virtual device (have not tried an actual Android device).

I have noticed it's incorrect on both iPhone simulators and actual iPhone devices.

**Comment by mweststrate** [comment]
A fix is currently landing. It will be released next week Wednesday. Bumping Flipper to 0.94 should then solve the issue. See https://fbflipper.com/docs/getting-started/react-native#using-the-latest-flipper-sdk for how to do that.

**Comment by swrobel** [comment]
https://github.com/facebook/flipper/commit/1cf745613390e5ce87b72e09016c42784cb0566a

**Comment by joshbuchea** [comment]
Apologies for asking if the answer is obvious, but has 1cf7456 landed in public builds of Flipper yet?

I'm still experiencing incorrect network request times for iOS devices in Flipper `0.96.1`

- React Native `0.63.2`
- Xcode `12.5`
- Flipper `0.96.1`
- iPhone 12 (iOS `14.6`)

**Comment by swrobel** [comment]
@joshbuchea the fix is actually in the Flipper pod, not the app itself. Here's an example from my `Podfile`:

```ruby
use_flipper!({ 'Flipper' => '~> 0.94.1', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
```

**Comment by joshbuchea** [comment]
I did miss that it's in the pod rather than the app 😅 Thanks for the response and clarification @swrobel 🙌 

Looking forward to seeing those sweet accurate timestamps again!
